import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://pacnegivzgxpanphrnwp.supabase.co','sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id),money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'});let ctx=null,batches=[],warranties=[],paidOrders=[],deliveredOrders=[],currentOrderDetail=null,currentFinance=null,currentSheet=null,commerceRead=false,canWrite=false,accountingRead=false,accountingWrite=false;
const batchStatus={submitted:'Enviado',received:'Recibido',closed:'Cerrado',cancelled:'Cancelado'},warrantyStatus={opened:'Abierta',in_replacement:'En reposición',ready:'Lista',delivered:'Entregada',cancelled:'Cancelada'},payerLabel={guardian:'Familia',sponsor:'Sponsor',player:'Jugador',organization:'Club',other:'Otro'};
function show(id){['loadingView','deniedView','view'].forEach(v=>$(v)?.classList.toggle('hidden',v!==id));}function message(id,text='',type='error'){const e=$(id);if(!e)return;e.textContent=text;e.dataset.type=type;e.classList.toggle('hidden',!text);}async function rpc(name,params={}){const {data,error}=await supabase.rpc(name,params);if(error)throw error;return data;}function safe(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}function dateFmt(v){if(!v)return '—';const raw=String(v),d=raw.length<=10?new Date(`${raw}T12:00:00`):new Date(raw);return new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',...(raw.length>10?{timeStyle:'short'}:{})}).format(d);}function selectedValues(selector){return [...document.querySelectorAll(selector)].filter(x=>x.checked).map(x=>x.value);}function idem(prefix){return globalThis.crypto?.randomUUID?`${prefix}:${ctx.organization_id}:${crypto.randomUUID()}`:`${prefix}:${ctx.organization_id}:${Date.now()}:${Math.random()}`;}
async function boot(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/v2';return;}const rows=await rpc('v2_my_context');if(!rows?.length){$('deniedText').textContent='Tu cuenta no está vinculada a una organización.';show('deniedView');return;}ctx=rows[0];const modules=await rpc('v2_my_modules',{organization_id:ctx.organization_id}),commerce=modules.find(m=>m.module_code==='commerce'),accounting=modules.find(m=>m.module_code==='accounting');commerceRead=Boolean(commerce?.enabled&&commerce?.can_read);canWrite=Boolean(commerce?.enabled&&commerce?.can_write);accountingRead=Boolean(accounting?.enabled&&accounting?.can_read);accountingWrite=Boolean(accounting?.enabled&&accounting?.can_write);if(!commerceRead&&!accountingRead){$('deniedText').textContent='Tu rol no tiene acceso a Producción ni a Contabilidad.';show('deniedView');return;}$('orgName').textContent=ctx.organization_name||'Tannery City FC';$('roleBadge').textContent=ctx.is_owner?'Propietario':(ctx.role||'Miembro');['newBatch','newWarranty','newReplacement'].forEach(id=>$(id)?.classList.toggle('hidden',!canWrite));$('tabWarranties')?.classList.toggle('hidden',!commerceRead);$('accountingLink')?.classList.toggle('hidden',!accountingRead);await load();show('view');}
async function load(){if(commerceRead){const [b,w,p,pp,d]=await Promise.all([rpc('v2_production_batches',{organization_id:ctx.organization_id}),rpc('v2_warranties',{organization_id:ctx.organization_id,status_filter:null}),rpc('v2_orders',{organization_id:ctx.organization_id,status_filter:'paid'}),rpc('v2_orders',{organization_id:ctx.organization_id,status_filter:'partial_payment'}),rpc('v2_orders',{organization_id:ctx.organization_id,status_filter:'delivered'})]);batches=Array.isArray(b)?b:[];warranties=Array.isArray(w)?w:[];paidOrders=[...(Array.isArray(p)?p:[]),...(Array.isArray(pp)?pp:[])];deliveredOrders=Array.isArray(d)?d:[];}else{batches=await rpc('v2_production_batches',{organization_id:ctx.organization_id})||[];warranties=[];paidOrders=[];deliveredOrders=[];}renderKpis();renderBatches();renderWarranties();}
function renderKpis(){$('kpiSubmitted').textContent=batches.filter(b=>b.status==='submitted').length;$('kpiReceived').textContent=batches.filter(b=>b.status==='received').length;$('kpiWarrantyOpen').textContent=warranties.filter(w=>['opened','in_replacement'].includes(w.status)).length;$('kpiWarrantyReady').textContent=warranties.filter(w=>w.status==='ready').length;}
function renderBatches(){const box=$('batchList');box.innerHTML='';$('batchEmpty').classList.toggle('hidden',batches.length>0);batches.forEach(b=>{const row=document.createElement('article');row.className='batch-row';const qty=b.batch_type==='orders'?`${b.order_count} pedido${Number(b.order_count)===1?'':'s'}`:`${b.warranty_count} garantía${Number(b.warranty_count)===1?'':'s'}`;row.innerHTML=`<div class="batch-main"><div class="title-line"><strong>${safe(b.folio)}</strong><span class="kind ${safe(b.batch_type)}">${b.batch_type==='orders'?'Corte':'Reposición'}</span></div><span>${safe([b.supplier_name,qty].filter(Boolean).join(' · '))}</span><small>Venta ${money.format(Number(b.sales_total||0))} · costo ${money.format(Number(b.cost_total||0))} · utilidad esperada ${money.format(Number(b.sales_total||0)-Number(b.cost_total||0))}</small><small>Enviado ${safe(dateFmt(b.submitted_on))}${b.received_at?` · Recibido ${safe(dateFmt(b.received_at))}`:''}</small></div><div class="batch-money"><b>${money.format(Number(b.cost_total||0))}</b><small>por pagar / costo</small><span class="status ${safe(b.status)}">${safe(batchStatus[b.status]||b.status)}</span></div><div class="batch-actions"></div>`;const actions=row.querySelector('.batch-actions');if(b.batch_type==='orders'){const finance=document.createElement('button');finance.type='button';finance.className='secondary mini';finance.textContent='Finanzas';finance.addEventListener('click',()=>openFinance(b.id));actions.appendChild(finance);const sheet=document.createElement('button');sheet.type='button';sheet.className='secondary mini';sheet.textContent='Hoja de producción';sheet.addEventListener('click',()=>openSheet(b.id));actions.appendChild(sheet);}if(canWrite&&b.status==='submitted'){const btn=document.createElement('button');btn.type='button';btn.className='secondary mini';btn.textContent='Recibir lote';btn.addEventListener('click',()=>receiveBatch(b.id,b.folio));actions.appendChild(btn);}box.appendChild(row);});}
function renderWarranties(){const box=$('warrantyList');box.innerHTML='';$('warrantyEmpty').classList.toggle('hidden',warranties.length>0);warranties.forEach(w=>{const order=deliveredOrders.find(o=>o.id===w.order_id),row=document.createElement('article');row.className='warranty-row';row.innerHTML=`<div><div class="title-line"><strong>${safe(w.folio)}</strong><span class="status ${safe(w.status)}">${safe(warrantyStatus[w.status]||w.status)}</span></div><span>${safe(w.reason)}</span><small>${safe(order?.folio?`Pedido ${order.folio}`:`Pedido ${String(w.order_id).slice(0,8)}`)} · ${Number(w.item_count||0)} pieza${Number(w.item_count)===1?'':'s'} · ${safe(dateFmt(w.opened_at))}</small></div><div class="warranty-actions"></div>`;const actions=row.querySelector('.warranty-actions');if(canWrite&&w.status==='ready'){const btn=document.createElement('button');btn.type='button';btn.className='primary mini';btn.textContent='Entregar';btn.addEventListener('click',()=>deliverWarranty(w.id,w.folio));actions.appendChild(btn);}box.appendChild(row);});}
function tab(which){if(!commerceRead)which='batches';const isB=which==='batches';$('tabBatches').classList.toggle('active',isB);$('tabWarranties').classList.toggle('active',!isB);$('batchesPanel').classList.toggle('hidden',!isB);$('warrantiesPanel').classList.toggle('hidden',isB);}
function closeModals(){['batchModal','warrantyModal','replacementModal','financeModal','sheetModal'].forEach(id=>{$(id)?.classList.add('hidden');$(id)?.setAttribute('aria-hidden','true');});$('backdrop').classList.add('hidden');currentOrderDetail=null;currentFinance=null;currentSheet=null;['batchMessage','warrantyMessage','replacementMessage','supplierPaymentMessage'].forEach(id=>message(id));}function openModal(id){closeModals();$('backdrop').classList.remove('hidden');$(id).classList.remove('hidden');$(id).setAttribute('aria-hidden','false');}
async function openFinance(batchId){openModal('financeModal');$('financeBody').innerHTML='<div class="loading-mini">Calculando venta, cobros, costo y pagos al proveedor…</div>';try{currentFinance=await rpc('v2_production_batch_finance',{organization_id:ctx.organization_id,batch_id:batchId});renderFinance();}catch(e){$('financeBody').innerHTML=`<div class="mini-empty">${safe(e.message||'No se pudo cargar el control financiero.')}</div>`;}}
function renderFinance(){const f=currentFinance,b=f.batch;$('financeFolio').textContent=b.folio;$('financeSupplier').textContent=b.supplier_name||'Proveedor sin nombre';$('financeSale').textContent=money.format(Number(b.sales_total||0));$('financeCollected').textContent=money.format(Number(f.customerCollected||0));$('financeCost').textContent=money.format(Number(b.cost_total||0));$('financeSupplierPaid').textContent=money.format(Number(f.supplierPaid||0));$('financePayable').textContent=money.format(Number(f.supplierPayable||0));$('financeProfit').textContent=money.format(Number(f.grossProfitExpected||0));$('financeCash').textContent=money.format(Number(f.cashNetCurrent||0));const body=$('financeBody');body.innerHTML='';(f.orders||[]).forEach(o=>{const card=document.createElement('article');card.className='finance-order';const pays=(o.payments||[]).map(p=>`<small>${dateFmt(p.date)} · ${money.format(Number(p.amount||0))} · ${safe(payerLabel[p.payerType]||p.payerType||'Pagador')} ${safe(p.payerName||'')}</small>`).join('');card.innerHTML=`<div><strong>${safe(o.folio)} · ${safe(o.customer||'')}</strong><span>Venta ${money.format(Number(o.sale||0))} · costo ${money.format(Number(o.cost||0))} · utilidad ${money.format(Number(o.grossProfitExpected||0))}</span><span>Cobrado ${money.format(Number(o.collected||0))} · saldo cliente ${money.format(Number(o.customerBalance||0))}</span>${pays||'<small>Sin cobros ligados.</small>'}</div>`;body.appendChild(card);});const sp=$('supplierPaymentList');sp.innerHTML='';(f.supplierPayments||[]).forEach(p=>{const row=document.createElement('article');row.className='supplier-payment-row';row.innerHTML=`<div><strong>${money.format(Number(p.amount||0))}</strong><span>${dateFmt(p.date)} · ${safe(p.method||'otro')}${p.reference?` · ${safe(p.reference)}`:''}</span></div>`;sp.appendChild(row);});$('supplierPaymentEmpty').classList.toggle('hidden',(f.supplierPayments||[]).length>0);const canPay=accountingWrite&&Number(f.supplierPayable||0)>0;$('supplierPaymentForm').classList.toggle('hidden',!canPay);if(canPay){$('supplierAmount').value=Number(f.supplierPayable).toFixed(2);$('supplierAmount').max=Number(f.supplierPayable).toFixed(2);$('supplierDate').value=new Date().toISOString().slice(0,10);$('supplierReference').value='';$('supplierNotes').value='';}message('supplierPaymentMessage');}
async function saveSupplierPayment(){if(!currentFinance||!accountingWrite)return;const amount=Number($('supplierAmount').value||0),payable=Number(currentFinance.supplierPayable||0);if(!Number.isFinite(amount)||amount<=0){message('supplierPaymentMessage','Captura un monto mayor a cero.');return;}if(amount>payable+0.005){message('supplierPaymentMessage',`No puedes pagar más de ${money.format(payable)}.`);return;}const btn=$('saveSupplierPayment');btn.disabled=true;try{await rpc('v2_post_batch_supplier_payment',{organization_id:ctx.organization_id,batch_id:currentFinance.batch.id,amount,expense_date:$('supplierDate').value,method:$('supplierMethod').value,reference:$('supplierReference').value.trim()||null,notes:$('supplierNotes').value.trim()||null,idempotency_key:idem('supplier')});const id=currentFinance.batch.id;currentFinance=await rpc('v2_production_batch_finance',{organization_id:ctx.organization_id,batch_id:id});renderFinance();await load();message('supplierPaymentMessage','Pago al proveedor registrado y ligado al corte.','success');}catch(e){message('supplierPaymentMessage',e.message||'No se pudo registrar el pago.');}finally{btn.disabled=!accountingWrite;}}
/* Hoja de producción: documento para el proveedor, separado del control financiero.
   Dos tablas con propósitos distintos (así trabaja cualquier maquilador):
   - Corte: cuántas piezas cortar por prenda+talla (agregado, sin importar de quién es cada una).
   - Personalización: qué nombre/número lleva cada jersey — no se puede agregar, cada pieza es única.
   Se agrupa por pedido y, dentro de cada pedido, por kit (si la pieza pertenece a uno),
   para que el proveedor entregue las piezas de un mismo kit juntas. */
function cutMatrix(items){
  const map=new Map();
  items.forEach(i=>{
    const key=`${i.description}|${i.talla||'—'}|${i.tipo||''}`;
    if(!map.has(key))map.set(key,{description:i.description,talla:i.talla||'—',tipo:i.tipo||'',qty:0});
    map.get(key).qty+=Number(i.quantity||0);
  });
  return [...map.values()].sort((a,b)=>a.description.localeCompare(b.description,'es')||String(a.talla).localeCompare(String(b.talla),'es'));
}
function personalizationOrders(items){
  const personal=items.filter(i=>i.nombrePers||i.numero);
  const byOrder=new Map();
  personal.forEach(i=>{
    if(!byOrder.has(i.orderId))byOrder.set(i.orderId,{folio:i.orderFolio,customerName:i.customerName,items:[]});
    byOrder.get(i.orderId).items.push(i);
  });
  return [...byOrder.values()].sort((a,b)=>safe(a.folio).localeCompare(safe(b.folio),'es'));
}
function personRow(i){return `<tr><td>${safe(i.description)}</td><td>${safe(i.talla||'—')}</td><td>${safe(i.nombrePers||'—')}</td><td>${i.numero?'#'+safe(i.numero):'—'}</td><td>${Number(i.quantity||1)}</td></tr>`;}
function personOrderTable(o){
  const kits=new Map(),standalone=[];
  o.items.forEach(i=>{if(i.kitKey){if(!kits.has(i.kitKey))kits.set(i.kitKey,{name:i.kitName||'Kit',items:[]});kits.get(i.kitKey).items.push(i);}else standalone.push(i);});
  const kitRows=[...kits.values()].map(k=>`<tr class="sheet-kit-row"><td colspan="5">${safe(k.name)}</td></tr>${k.items.map(personRow).join('')}`).join('');
  return `<table class="sheet-table sheet-person-table"><caption>${safe(o.folio)} · ${safe(o.customerName||'Cliente sin nombre')}</caption><thead><tr><th>Prenda</th><th>Talla</th><th>Nombre</th><th>Número</th><th>Cant.</th></tr></thead><tbody>${kitRows}${standalone.map(personRow).join('')}</tbody></table>`;
}
async function openSheet(batchId){
  openModal('sheetModal');
  $('sheetBody').innerHTML='<div class="loading-mini">Armando hoja de corte y personalización…</div>';
  try{currentSheet=await rpc('v2_production_batch_sheet',{organization_id:ctx.organization_id,batch_id:batchId});renderSheet();}
  catch(e){$('sheetBody').innerHTML=`<div class="mini-empty">${safe(e.message||'No se pudo generar la hoja.')}</div>`;}
}
function renderSheet(){
  const b=currentSheet.batch,items=currentSheet.items||[];
  $('sheetFolio').textContent=`Hoja de producción · ${b.folio}`;
  const cuts=cutMatrix(items),totalQty=cuts.reduce((s,c)=>s+c.qty,0);
  const persons=personalizationOrders(items),personCount=items.filter(i=>i.nombrePers||i.numero).length;
  $('sheetBody').innerHTML=`
    <div class="sheet-header">
      <div class="sheet-brand"><strong>${safe(ctx.organization_name||'Tannery City FC')}</strong><span>Hoja de producción</span></div>
      <div class="sheet-meta">
        <div><span>Corte</span><strong>${safe(b.folio)}</strong></div>
        <div><span>Proveedor</span><strong>${safe(b.supplierName||'Sin asignar')}</strong></div>
        <div><span>Fecha de envío</span><strong>${safe(dateFmt(b.submittedOn))}</strong></div>
      </div>
    </div>
    ${b.notes?`<p class="sheet-notes"><strong>Notas:</strong> ${safe(b.notes)}</p>`:''}
    <div class="sheet-section">
      <div class="sheet-section-title">Hoja de corte <small>${totalQty} pieza${totalQty===1?'':'s'} en total</small></div>
      <table class="sheet-table">
        <thead><tr><th>Prenda</th><th>Talla</th><th>Tipo</th><th>Cantidad</th></tr></thead>
        <tbody>${cuts.map(c=>`<tr><td>${safe(c.description)}</td><td>${safe(c.talla)}</td><td>${safe(c.tipo||'—')}</td><td>${c.qty}</td></tr>`).join('')||'<tr><td colspan="4" class="mini-empty">Sin piezas.</td></tr>'}</tbody>
        <tfoot><tr><td colspan="3">Total</td><td>${totalQty}</td></tr></tfoot>
      </table>
    </div>
    <div class="sheet-section sheet-break">
      <div class="sheet-section-title">Lista de personalización <small>${personCount} pieza${personCount===1?'':'s'} con nombre/número</small></div>
      ${persons.length?persons.map(personOrderTable).join(''):'<p class="mini-empty">Ninguna pieza de este corte lleva nombre o número — no hace falta lista de personalización.</p>'}
    </div>`;
}
async function openBatch(){openModal('batchModal');$('batchSupplier').value='';$('batchNotes').value='';const box=$('batchCandidates');box.innerHTML='<div class="loading-mini">Validando pedidos pagados y con anticipo…</div>';if(!paidOrders.length){box.innerHTML='<div class="mini-empty">No hay pedidos pagados o con anticipo suficiente disponibles para corte.</div>';return;}const readiness=await Promise.all(paidOrders.map(async o=>{try{return [o.id,await rpc('v2_order_readiness',{organization_id:ctx.organization_id,order_id:o.id})]}catch(e){return [o.id,{ok:false,missing:[e.message]}]}})),byId=new Map(readiness);box.innerHTML='';paidOrders.forEach(o=>{const r=byId.get(o.id)||{},label=document.createElement('label');label.className=`candidate ${r.ok?'ready':'blocked'}`;const paidTag=o.status==='partial_payment'?`<span class="candidate-payment">Anticipo ${Number(r.paidPercent??0).toFixed(0)}% de ${money.format(Number(o.total||0))}</span>`:'';label.innerHTML=`<input type="checkbox" class="batch-check" value="${safe(o.id)}" ${r.ok?'':'disabled'}><div><strong>${safe(o.folio)} · ${safe(o.customer_name)}</strong><span>${money.format(Number(o.total||0))}</span>${paidTag}<small>${r.ok?'Listo para producción':safe((r.missing||['No disponible']).join(' · '))}</small></div>`;box.appendChild(label);});}
async function saveBatch(){const ids=selectedValues('.batch-check');if(!ids.length){message('batchMessage','Selecciona al menos un pedido listo.');return;}const btn=$('saveBatch');btn.disabled=true;try{await rpc('v2_create_production_batch',{organization_id:ctx.organization_id,order_ids:ids,supplier_name:$('batchSupplier').value.trim()||null,notes:$('batchNotes').value.trim()||null});closeModals();await load();tab('batches');}catch(e){message('batchMessage',e.message||'No se pudo crear el corte.');}finally{btn.disabled=!canWrite;}}
async function receiveBatch(id,folio){if(!confirm(`¿Confirmar que recibiste el lote ${folio}? Los pedidos/garantías pasarán a Listo.`))return;try{await rpc('v2_receive_production_batch',{organization_id:ctx.organization_id,batch_id:id});await load();}catch(e){alert(e.message||'No se pudo recibir el lote.');}}
function openWarranty(){openModal('warrantyModal');$('warrantyReason').value='';$('warrantyNotes').value='';$('warrantyItems').innerHTML='<div class="mini-empty">Selecciona primero un pedido entregado.</div>';const s=$('warrantyOrder');s.innerHTML='<option value="">Selecciona pedido</option>';deliveredOrders.forEach(o=>{const op=document.createElement('option');op.value=o.id;op.textContent=`${o.folio} · ${o.customer_name} · ${money.format(Number(o.total||0))}`;s.appendChild(op);});if(!deliveredOrders.length)message('warrantyMessage','No hay pedidos entregados disponibles.');}
async function loadWarrantyItems(){const id=$('warrantyOrder').value,box=$('warrantyItems');currentOrderDetail=null;if(!id){box.innerHTML='<div class="mini-empty">Selecciona primero un pedido entregado.</div>';return;}box.innerHTML='<div class="loading-mini">Cargando piezas…</div>';try{currentOrderDetail=await rpc('v2_order_detail',{organization_id:ctx.organization_id,order_id:id});const items=currentOrderDetail?.items||[];box.innerHTML='';if(!items.length){box.innerHTML='<div class="mini-empty">Este pedido no tiene piezas disponibles.</div>';return;}items.forEach(i=>{const label=document.createElement('label');label.className='candidate warranty-item';label.innerHTML=`<input type="checkbox" class="warranty-check" value="${safe(i.id)}"><div><strong>${safe(i.description)}</strong><span>${safe([i.attributes?.talla||i.attributes?.size,i.attributes?.nombrePers||i.attributes?.personalizationName,i.attributes?.numero||i.attributes?.number].filter(Boolean).join(' · ')||'Sin detalle')}</span><small>Cantidad original: ${Number(i.quantity||1)} · costo congelado ${i.unitCost==null?'no disponible':money.format(Number(i.unitCost))}</small></div><input class="warranty-qty" data-item="${safe(i.id)}" type="number" min="1" max="${Number(i.quantity||1)}" value="1" inputmode="numeric">`;box.appendChild(label);});}catch(e){box.innerHTML=`<div class="mini-empty">${safe(e.message||'No se pudo cargar el pedido.')}</div>`;}}
async function saveWarranty(){const orderId=$('warrantyOrder').value,reason=$('warrantyReason').value.trim();if(!orderId){message('warrantyMessage','Selecciona un pedido entregado.');return;}if(!reason){message('warrantyMessage','Escribe el motivo de la garantía.');return;}const chosen=selectedValues('.warranty-check');if(!chosen.length){message('warrantyMessage','Selecciona al menos una pieza.');return;}const items=chosen.map(id=>({order_item_id:id,quantity:Number(document.querySelector(`.warranty-qty[data-item="${CSS.escape(id)}"]`)?.value||1)})),btn=$('saveWarranty');btn.disabled=true;try{await rpc('v2_open_warranty',{organization_id:ctx.organization_id,order_id:orderId,reason,items,notes:$('warrantyNotes').value.trim()||null});closeModals();await load();tab('warranties');}catch(e){message('warrantyMessage',e.message||'No se pudo abrir la garantía.');}finally{btn.disabled=!canWrite;}}
function openReplacement(){openModal('replacementModal');$('replacementSupplier').value='';$('replacementNotes').value='';const rows=warranties.filter(w=>w.status==='opened'),box=$('replacementCandidates');box.innerHTML='';if(!rows.length){box.innerHTML='<div class="mini-empty">No hay garantías abiertas pendientes de reposición.</div>';return;}rows.forEach(w=>{const label=document.createElement('label');label.className='candidate';label.innerHTML=`<input type="checkbox" class="replacement-check" value="${safe(w.id)}"><div><strong>${safe(w.folio)}</strong><span>${safe(w.reason)}</span><small>${Number(w.item_count||0)} pieza${Number(w.item_count)===1?'':'s'}</small></div>`;box.appendChild(label);});}
async function saveReplacement(){const ids=selectedValues('.replacement-check');if(!ids.length){message('replacementMessage','Selecciona al menos una garantía.');return;}const btn=$('saveReplacement');btn.disabled=true;try{await rpc('v2_create_warranty_replacement_batch',{organization_id:ctx.organization_id,warranty_ids:ids,supplier_name:$('replacementSupplier').value.trim()||null,notes:$('replacementNotes').value.trim()||null});closeModals();await load();tab('batches');}catch(e){message('replacementMessage',e.message||'No se pudo crear el lote de reposición.');}finally{btn.disabled=!canWrite;}}
async function deliverWarranty(id,folio){if(!confirm(`¿Confirmar entrega de la garantía ${folio}?`))return;try{await rpc('v2_deliver_warranty',{organization_id:ctx.organization_id,warranty_id:id,notes:null});await load();}catch(e){alert(e.message||'No se pudo entregar la garantía.');}}
$('tabBatches').addEventListener('click',()=>tab('batches'));$('tabWarranties').addEventListener('click',()=>tab('warranties'));$('newBatch').addEventListener('click',openBatch);$('newWarranty').addEventListener('click',openWarranty);$('newReplacement').addEventListener('click',openReplacement);$('warrantyOrder').addEventListener('change',loadWarrantyItems);$('saveBatch').addEventListener('click',saveBatch);$('saveWarranty').addEventListener('click',saveWarranty);$('saveReplacement').addEventListener('click',saveReplacement);$('saveSupplierPayment').addEventListener('click',saveSupplierPayment);$('printSheet')?.addEventListener('click',()=>window.print());$('backdrop').addEventListener('click',closeModals);document.querySelectorAll('.close-modal').forEach(b=>b.addEventListener('click',closeModals));boot().catch(e=>{$('deniedText').textContent=e.message||'No fue posible abrir Producción.';show('deniedView');});