import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const supabase=createClient('https://pacnegivzgxpanphrnwp.supabase.co','sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'});
let ctx=null,batches=[],warranties=[],paidOrders=[],deliveredOrders=[],currentOrderDetail=null,canWrite=false;
const batchStatus={submitted:'Enviado',received:'Recibido',closed:'Cerrado',cancelled:'Cancelado'};
const warrantyStatus={opened:'Abierta',in_replacement:'En reposición',ready:'Lista',delivered:'Entregada',cancelled:'Cancelada'};
function show(id){['loadingView','deniedView','view'].forEach(v=>$(v)?.classList.toggle('hidden',v!==id));}
function message(id,text='',type='error'){const e=$(id);if(!e)return;e.textContent=text;e.dataset.type=type;e.classList.toggle('hidden',!text);}
async function rpc(name,params={}){const {data,error}=await supabase.rpc(name,params);if(error)throw error;return data;}
function safe(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function dateFmt(v){if(!v)return '—';const raw=String(v),d=raw.length<=10?new Date(`${raw}T12:00:00`):new Date(raw);return new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',...(raw.length>10?{timeStyle:'short'}:{})}).format(d);}
function selectedValues(selector){return [...document.querySelectorAll(selector)].filter(x=>x.checked).map(x=>x.value);}

async function boot(){
  const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/v2';return;}
  const rows=await rpc('v2_my_context');if(!rows?.length){$('deniedText').textContent='Tu cuenta no está vinculada a una organización.';show('deniedView');return;}
  ctx=rows[0];const modules=await rpc('v2_my_modules',{organization_id:ctx.organization_id});const mod=modules.find(m=>m.module_code==='commerce');
  if(!mod?.enabled||!mod?.can_read){$('deniedText').textContent='Tu rol no tiene acceso a Tienda/Producción.';show('deniedView');return;}
  canWrite=Boolean(mod.can_write);$('orgName').textContent=ctx.organization_name||'Tannery City FC';$('roleBadge').textContent=ctx.is_owner?'Propietario':(ctx.role||'Miembro');['newBatch','newWarranty','newReplacement'].forEach(id=>$(id).classList.toggle('hidden',!canWrite));await load();show('view');
}

async function load(){
  const [b,w,p,d]=await Promise.all([
    rpc('v2_production_batches',{organization_id:ctx.organization_id}),
    rpc('v2_warranties',{organization_id:ctx.organization_id,status_filter:null}),
    rpc('v2_orders',{organization_id:ctx.organization_id,status_filter:'paid'}),
    rpc('v2_orders',{organization_id:ctx.organization_id,status_filter:'delivered'})
  ]);
  batches=Array.isArray(b)?b:[];warranties=Array.isArray(w)?w:[];paidOrders=Array.isArray(p)?p:[];deliveredOrders=Array.isArray(d)?d:[];renderKpis();renderBatches();renderWarranties();
}
function renderKpis(){$('kpiSubmitted').textContent=batches.filter(b=>b.status==='submitted').length;$('kpiReceived').textContent=batches.filter(b=>b.status==='received').length;$('kpiWarrantyOpen').textContent=warranties.filter(w=>['opened','in_replacement'].includes(w.status)).length;$('kpiWarrantyReady').textContent=warranties.filter(w=>w.status==='ready').length;}
function renderBatches(){const box=$('batchList');box.innerHTML='';$('batchEmpty').classList.toggle('hidden',batches.length>0);batches.forEach(b=>{const row=document.createElement('article');row.className='batch-row';const qty=b.batch_type==='orders'?`${b.order_count} pedido${Number(b.order_count)===1?'':'s'}`:`${b.warranty_count} garantía${Number(b.warranty_count)===1?'':'s'}`;row.innerHTML=`<div class="batch-main"><div class="title-line"><strong>${safe(b.folio)}</strong><span class="kind ${safe(b.batch_type)}">${b.batch_type==='orders'?'Corte':'Reposición'}</span></div><span>${safe([b.supplier_name,qty].filter(Boolean).join(' · '))}</span><small>Enviado ${safe(dateFmt(b.submitted_on))}${b.received_at?` · Recibido ${safe(dateFmt(b.received_at))}`:''}</small></div><div class="batch-money"><b>${money.format(Number(b.cost_total||0))}</b><small>costo congelado</small><span class="status ${safe(b.status)}">${safe(batchStatus[b.status]||b.status)}</span></div><div class="batch-actions"></div>`;const actions=row.querySelector('.batch-actions');if(canWrite&&b.status==='submitted'){const btn=document.createElement('button');btn.type='button';btn.className='secondary mini';btn.textContent='Recibir lote';btn.addEventListener('click',()=>receiveBatch(b.id,b.folio));actions.appendChild(btn);}box.appendChild(row);});}
function renderWarranties(){const box=$('warrantyList');box.innerHTML='';$('warrantyEmpty').classList.toggle('hidden',warranties.length>0);warranties.forEach(w=>{const order=deliveredOrders.find(o=>o.id===w.order_id);const row=document.createElement('article');row.className='warranty-row';row.innerHTML=`<div><div class="title-line"><strong>${safe(w.folio)}</strong><span class="status ${safe(w.status)}">${safe(warrantyStatus[w.status]||w.status)}</span></div><span>${safe(w.reason)}</span><small>${safe(order?.folio?`Pedido ${order.folio}`:`Pedido ${String(w.order_id).slice(0,8)}`)} · ${Number(w.item_count||0)} pieza${Number(w.item_count)===1?'':'s'} · ${safe(dateFmt(w.opened_at))}</small></div><div class="warranty-actions"></div>`;const actions=row.querySelector('.warranty-actions');if(canWrite&&w.status==='ready'){const btn=document.createElement('button');btn.type='button';btn.className='primary mini';btn.textContent='Entregar';btn.addEventListener('click',()=>deliverWarranty(w.id,w.folio));actions.appendChild(btn);}box.appendChild(row);});}

function tab(which){const isB=which==='batches';$('tabBatches').classList.toggle('active',isB);$('tabWarranties').classList.toggle('active',!isB);$('batchesPanel').classList.toggle('hidden',!isB);$('warrantiesPanel').classList.toggle('hidden',isB);}
function closeModals(){['batchModal','warrantyModal','replacementModal'].forEach(id=>{$(id).classList.add('hidden');$(id).setAttribute('aria-hidden','true');});$('backdrop').classList.add('hidden');currentOrderDetail=null;['batchMessage','warrantyMessage','replacementMessage'].forEach(id=>message(id));}
function openModal(id){closeModals();$('backdrop').classList.remove('hidden');$(id).classList.remove('hidden');$(id).setAttribute('aria-hidden','false');}

async function openBatch(){openModal('batchModal');$('batchSupplier').value='';$('batchNotes').value='';const box=$('batchCandidates');box.innerHTML='<div class="loading-mini">Validando pedidos pagados…</div>';if(!paidOrders.length){box.innerHTML='<div class="mini-empty">No hay pedidos pagados disponibles para corte.</div>';return;}const readiness=await Promise.all(paidOrders.map(async o=>{try{return [o.id,await rpc('v2_order_readiness',{organization_id:ctx.organization_id,order_id:o.id})]}catch(e){return [o.id,{ok:false,missing:[e.message]}]}}));const byId=new Map(readiness);box.innerHTML='';paidOrders.forEach(o=>{const r=byId.get(o.id)||{};const label=document.createElement('label');label.className=`candidate ${r.ok?'ready':'blocked'}`;label.innerHTML=`<input type="checkbox" class="batch-check" value="${safe(o.id)}" ${r.ok?'':'disabled'}><div><strong>${safe(o.folio)} · ${safe(o.customer_name)}</strong><span>${money.format(Number(o.total||0))}</span><small>${r.ok?'Listo para producción':safe((r.missing||['No disponible']).join(' · '))}</small></div>`;box.appendChild(label);});}
async function saveBatch(){const ids=selectedValues('.batch-check');if(!ids.length){message('batchMessage','Selecciona al menos un pedido listo.');return;}const btn=$('saveBatch');btn.disabled=true;message('batchMessage');try{await rpc('v2_create_production_batch',{organization_id:ctx.organization_id,order_ids:ids,supplier_name:$('batchSupplier').value.trim()||null,notes:$('batchNotes').value.trim()||null});closeModals();await load();tab('batches');}catch(e){message('batchMessage',e.message||'No se pudo crear el corte.');}finally{btn.disabled=!canWrite;}}
async function receiveBatch(id,folio){if(!confirm(`¿Confirmar que recibiste el lote ${folio}? Los pedidos/garantías pasarán a Listo.`))return;try{await rpc('v2_receive_production_batch',{organization_id:ctx.organization_id,batch_id:id});await load();}catch(e){alert(e.message||'No se pudo recibir el lote.');}}

function openWarranty(){openModal('warrantyModal');$('warrantyReason').value='';$('warrantyNotes').value='';$('warrantyItems').innerHTML='<div class="mini-empty">Selecciona primero un pedido entregado.</div>';const s=$('warrantyOrder');s.innerHTML='<option value="">Selecciona pedido</option>';deliveredOrders.forEach(o=>{const op=document.createElement('option');op.value=o.id;op.textContent=`${o.folio} · ${o.customer_name} · ${money.format(Number(o.total||0))}`;s.appendChild(op);});if(!deliveredOrders.length)message('warrantyMessage','No hay pedidos entregados disponibles.');}
async function loadWarrantyItems(){const id=$('warrantyOrder').value,box=$('warrantyItems');currentOrderDetail=null;if(!id){box.innerHTML='<div class="mini-empty">Selecciona primero un pedido entregado.</div>';return;}box.innerHTML='<div class="loading-mini">Cargando piezas…</div>';try{currentOrderDetail=await rpc('v2_order_detail',{organization_id:ctx.organization_id,order_id:id});const items=currentOrderDetail?.items||[];box.innerHTML='';if(!items.length){box.innerHTML='<div class="mini-empty">Este pedido no tiene piezas disponibles.</div>';return;}items.forEach(i=>{const label=document.createElement('label');label.className='candidate warranty-item';label.innerHTML=`<input type="checkbox" class="warranty-check" value="${safe(i.id)}"><div><strong>${safe(i.description)}</strong><span>${safe([i.attributes?.talla||i.attributes?.size,i.attributes?.nombrePers||i.attributes?.personalizationName,i.attributes?.numero||i.attributes?.number].filter(Boolean).join(' · ')||'Sin detalle')}</span><small>Cantidad original: ${Number(i.quantity||1)} · costo congelado ${i.unitCost==null?'no disponible':money.format(Number(i.unitCost))}</small></div><input class="warranty-qty" data-item="${safe(i.id)}" type="number" min="1" max="${Number(i.quantity||1)}" value="1" inputmode="numeric">`;box.appendChild(label);});}catch(e){box.innerHTML=`<div class="mini-empty">${safe(e.message||'No se pudo cargar el pedido.')}</div>`;}}
async function saveWarranty(){const orderId=$('warrantyOrder').value,reason=$('warrantyReason').value.trim();if(!orderId){message('warrantyMessage','Selecciona un pedido entregado.');return;}if(!reason){message('warrantyMessage','Escribe el motivo de la garantía.');return;}const chosen=selectedValues('.warranty-check');if(!chosen.length){message('warrantyMessage','Selecciona al menos una pieza.');return;}const items=chosen.map(id=>({order_item_id:id,quantity:Number(document.querySelector(`.warranty-qty[data-item="${CSS.escape(id)}"]`)?.value||1)}));const btn=$('saveWarranty');btn.disabled=true;message('warrantyMessage');try{await rpc('v2_open_warranty',{organization_id:ctx.organization_id,order_id:orderId,reason,items,notes:$('warrantyNotes').value.trim()||null});closeModals();await load();tab('warranties');}catch(e){message('warrantyMessage',e.message||'No se pudo abrir la garantía.');}finally{btn.disabled=!canWrite;}}

function openReplacement(){openModal('replacementModal');$('replacementSupplier').value='';$('replacementNotes').value='';const rows=warranties.filter(w=>w.status==='opened'),box=$('replacementCandidates');box.innerHTML='';if(!rows.length){box.innerHTML='<div class="mini-empty">No hay garantías abiertas pendientes de reposición.</div>';return;}rows.forEach(w=>{const label=document.createElement('label');label.className='candidate';label.innerHTML=`<input type="checkbox" class="replacement-check" value="${safe(w.id)}"><div><strong>${safe(w.folio)}</strong><span>${safe(w.reason)}</span><small>${Number(w.item_count||0)} pieza${Number(w.item_count)===1?'':'s'}</small></div>`;box.appendChild(label);});}
async function saveReplacement(){const ids=selectedValues('.replacement-check');if(!ids.length){message('replacementMessage','Selecciona al menos una garantía.');return;}const btn=$('saveReplacement');btn.disabled=true;message('replacementMessage');try{await rpc('v2_create_warranty_replacement_batch',{organization_id:ctx.organization_id,warranty_ids:ids,supplier_name:$('replacementSupplier').value.trim()||null,notes:$('replacementNotes').value.trim()||null});closeModals();await load();tab('batches');}catch(e){message('replacementMessage',e.message||'No se pudo crear el lote de reposición.');}finally{btn.disabled=!canWrite;}}
async function deliverWarranty(id,folio){if(!confirm(`¿Confirmar entrega de la garantía ${folio}?`))return;try{await rpc('v2_deliver_warranty',{organization_id:ctx.organization_id,warranty_id:id,notes:null});await load();}catch(e){alert(e.message||'No se pudo entregar la garantía.');}}

$('tabBatches').addEventListener('click',()=>tab('batches'));$('tabWarranties').addEventListener('click',()=>tab('warranties'));$('newBatch').addEventListener('click',openBatch);$('newWarranty').addEventListener('click',openWarranty);$('newReplacement').addEventListener('click',openReplacement);$('warrantyOrder').addEventListener('change',loadWarrantyItems);$('saveBatch').addEventListener('click',saveBatch);$('saveWarranty').addEventListener('click',saveWarranty);$('saveReplacement').addEventListener('click',saveReplacement);$('backdrop').addEventListener('click',closeModals);document.querySelectorAll('.close-modal').forEach(b=>b.addEventListener('click',closeModals));
boot().catch(e=>{$('deniedText').textContent=e.message||'No fue posible abrir Producción.';show('deniedView');});