import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
import {bootstrapProtectedShell,$,setShellHealth} from '/v2/shell.js';
const supabase=createClient('https://pacnegivzgxpanphrnwp.supabase.co','sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',{auth:{persistSession:true,autoRefreshToken:true}});
const boot=await bootstrapProtectedShell({active:'admin',title:'Cutover V1 → V2'});if(!boot)throw new Error('No access');const org=boot.ctx.organization_id;let latest=null;
const domainLabels={players:'Jugadores',payments:'Movimientos financieros',prospects:'Prospectos',orders:'Pedidos'};
const fmt=v=>v?new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function msg(text=''){const el=$('cutoverMessage');el.textContent=text;el.classList.toggle('hidden',!text);}
function renderDomain(domain,data){const article=document.createElement('article'),missing=Number(data?.missingCount||0),without=Number(data?.rowsWithoutId||0),state=missing?'danger':without?'warning':'ready';article.className=`cutover-domain ${state}`;article.innerHTML=`<div class="domain-top"><span>${domainLabels[domain]||domain}</span><b>${state==='ready'?'✓':state==='danger'?'!':'•'}</b></div><strong>${missing}</strong><p>faltante${missing===1?'':'s'} · ${Number(data?.legacyCount||0)} en V1 · ${Number(data?.canonicalLegacyIdCount||0)} IDs migrados</p>${without?`<small>${without} fila(s) V1 sin ID estable; requieren revisión.</small>`:''}`;$('domainGrid').appendChild(article);}
function sampleLabel(domain,row){if(domain==='payments')return [row.date,row.amount!=null?`$${row.amount}`:null,row.category,row.concept].filter(Boolean).join(' · ')||row.id;if(domain==='orders')return [row.label,row.date,row.total!=null?`$${row.total}`:null].filter(Boolean).join(' · ')||row.id;return [row.label,row.status].filter(Boolean).join(' · ')||row.id;}
function renderDelta(data){const panel=$('deltaPanel'),wrap=$('deltaTables');wrap.innerHTML='';const domains=Object.entries(data?.comparison||{}).filter(([,v])=>Number(v?.missingCount||0)>0||Number(v?.rowsWithoutId||0)>0);panel.classList.toggle('hidden',!domains.length);domains.forEach(([domain,v])=>{const section=document.createElement('section');section.className='delta-domain';const sample=Array.isArray(v.missingSample)?v.missingSample:[];section.innerHTML=`<div class="delta-title"><strong>${esc(domainLabels[domain]||domain)}</strong><span>${Number(v.missingCount||0)} faltantes</span></div>${sample.length?`<div class="delta-list">${sample.map(r=>`<div><code>${esc(r.id||'sin-id')}</code><span>${esc(sampleLabel(domain,r))}</span></div>`).join('')}</div>`:'<p class="delta-empty">Sin muestra disponible.</p>'}${Number(v.rowsWithoutId||0)?`<p class="delta-warning">${Number(v.rowsWithoutId)} fila(s) no tienen ID estable y no se pueden reconciliar automáticamente.</p>`:''}`;wrap.appendChild(section);});}
function render(data){latest=data;$('domainGrid').innerHTML='';Object.entries(data.comparison||{}).forEach(([d,v])=>renderDomain(d,v));const total=Number(data.totalMissing||0),banner=$('cutoverBanner');banner.className=`cutover-banner ${total?'danger':'ready'}`;$('bannerTitle').textContent=total?'V1 todavía tiene delta pendiente':'Dominios cubiertos reconciliados';$('bannerText').textContent=total?'No retires V1 todavía. Revisa/importa los registros faltantes y vuelve a comparar.':'No hay IDs nuevos pendientes en los dominios cubiertos. Aún falta hacer freeze y comparación final antes del retiro.';$('missingTotal').textContent=total;$('checkedAt').textContent=fmt(data.checkedAt);$('legacyTime').textContent=fmt(data.legacyServerTime);renderDelta(data);setShellHealth({state:total?'danger':'attention',label:total?`${total} faltante(s) V1`:'Freeze final pendiente'});}
async function run(){const btn=$('runCheck');btn.disabled=true;btn.textContent='Comparando…';msg();setShellHealth({state:'attention',label:'Consultando V1'});try{const {data,error}=await supabase.functions.invoke('legacy-cutover-check',{body:{organizationId:org}});if(error)throw error;if(!data?.ok)throw new Error(data?.message||'No se pudo comparar.');render(data);}catch(e){msg(e.message||'No se pudo comparar V1.');setShellHealth({state:'danger',label:'Comparación falló'});}finally{btn.disabled=false;btn.textContent='Comparar V1 ahora';}}
function exportDelta(){if(!latest)return;const safe={checkedAt:latest.checkedAt,legacyServerTime:latest.legacyServerTime,totalMissing:latest.totalMissing,status:latest.status,comparison:latest.comparison},blob=new Blob([JSON.stringify(safe,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`tanneros-cutover-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
$('runCheck').addEventListener('click',run);$('exportDelta').addEventListener('click',exportDelta);