import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://pacnegivzgxpanphrnwp.supabase.co','sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);let ctx=null,prospects=[],filtered=[],current=null,moduleRows=[];
function show(id){['loadingView','deniedView','prospectsView'].forEach(v=>$(v)?.classList.toggle('hidden',v!==id));}
function msg(id,text='',type='error'){const el=$(id);if(!el)return;el.textContent=text;el.dataset.type=type;el.classList.toggle('hidden',!text);}
async function rpc(name,params={}){const {data,error}=await supabase.rpc(name,params);if(error)throw error;return data;}
function fmtDate(v){if(!v)return '—';return new Intl.DateTimeFormat('es-MX',{dateStyle:'medium'}).format(new Date(v));}
function fmtDateTime(v){if(!v)return '—';return new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));}
function localDateTimeValue(v){const d=v?new Date(v):new Date();const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`;}
function nameOf(p){return [p.first_name,p.last_name].filter(Boolean).join(' ').trim();}
async function boot(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/v2';return;}const rows=await rpc('v2_my_context');if(!rows?.length){$('deniedText').textContent='Tu cuenta no está vinculada a un club.';show('deniedView');return;}ctx=rows[0];moduleRows=await rpc('v2_my_modules',{organization_id:ctx.organization_id});const prospectsMod=moduleRows.find(m=>m.module_code==='prospects');const scoutingMod=moduleRows.find(m=>m.module_code==='scouting');if(!(prospectsMod?.enabled&&prospectsMod?.can_read)&&!(scoutingMod?.enabled&&scoutingMod?.can_read)){$('deniedText').textContent='Tu rol no tiene acceso a Prospectos ni Scouting.';show('deniedView');return;}ctx.canProspectsWrite=Boolean(prospectsMod?.enabled&&prospectsMod?.can_write);ctx.canScoutingRead=Boolean(scoutingMod?.enabled&&scoutingMod?.can_read);ctx.canScoutingWrite=Boolean(scoutingMod?.enabled&&scoutingMod?.can_write);$('orgName').textContent=ctx.organization_name||'Tannery City FC';$('roleBadge').textContent=ctx.is_owner?'Propietario':ctx.role;await loadProspects();show('prospectsView');}
async function loadProspects(){prospects=await rpc('v2_prospects',{organization_id:ctx.organization_id,status_filter:null});applyFilters();renderKpis();}
function renderKpis(){const open=prospects.filter(p=>!['converted','lost'].includes(p.status)).length;$('kpiOpen').textContent=open;$('kpiNew').textContent=prospects.filter(p=>p.status==='new').length;$('kpiTrial').textContent=prospects.filter(p=>p.status==='trial').length;$('kpiScouting').textContent=prospects.filter(p=>Number(p.scouting_count||0)>0).length;}
function applyFilters(){const status=$('statusFilter').value,q=$('searchProspect').value.trim().toLocaleLowerCase('es-MX');filtered=prospects.filter(p=>(!status||p.status===status)&&(!q||`${nameOf(p)} ${p.phone||''} ${p.email||''} ${p.guardian_name||''} ${p.category_interest||''}`.toLocaleLowerCase('es-MX').includes(q)));renderList();}
const statusLabel={new:'Nuevo',contacted:'Contactado',trial:'Prueba',qualified:'Calificado',converted:'Convertido',lost:'Perdido'};
function renderList(){const list=$('prospectList');list.innerHTML='';$('prospectEmpty').classList.toggle('hidden',filtered.length>0);for(const p of filtered){const row=document.createElement('button');row.type='button';row.className='prospect-row';row.innerHTML=`<div class="prospect-main"><strong>${nameOf(p)||'Sin nombre'}</strong><span>${p.category_interest||'Sin categoría'} · ${p.phone||p.email||'Sin contacto'}</span></div><div class="prospect-meta"><span class="pipeline ${p.status}">${statusLabel[p.status]||p.status}</span><small>${p.scouting_count||0} visorías</small></div>`;row.addEventListener('click',()=>openProspect(p));list.appendChild(row);}}
async function openProspect(p){current=p;$('prospectName').textContent=nameOf(p)||'Prospecto';$('prospectMeta').textContent=`${p.category_interest||'Sin categoría'} · alta ${fmtDate(p.created_at)}`;$('prospectStatus').value=p.status||'new';$('nextAction').value=p.next_action_at?localDateTimeValue(p.next_action_at):'';$('prospectNotes').value=p.notes||'';$('saveFollowup').disabled=!ctx.canProspectsWrite;$('saveScout').disabled=!ctx.canScoutingWrite;$('scoutCategory').value=p.category_interest||'';$('scoutDate').value=localDateTimeValue();msg('followupMessage');msg('scoutMessage');await loadScoutingHistory();$('prospectBackdrop').classList.remove('hidden');$('prospectDrawer').classList.remove('hidden');$('prospectDrawer').setAttribute('aria-hidden','false');}
function closeProspect(){current=null;$('prospectBackdrop').classList.add('hidden');$('prospectDrawer').classList.add('hidden');$('prospectDrawer').setAttribute('aria-hidden','true');}
async function saveFollowup(){if(!current||!ctx.canProspectsWrite)return;msg('followupMessage');const btn=$('saveFollowup');btn.disabled=true;try{await rpc('v2_update_prospect_followup',{organization_id:ctx.organization_id,prospect_id:current.id,status:$('prospectStatus').value,next_action_at:$('nextAction').value?new Date($('nextAction').value).toISOString():null,notes:$('prospectNotes').value.trim()||null});msg('followupMessage','Seguimiento guardado.','success');await loadProspects();current=prospects.find(p=>p.id===current.id)||current;}catch(e){msg('followupMessage',e.message||'No se pudo guardar.');}finally{btn.disabled=!ctx.canProspectsWrite;}}
function num(id){const v=$(id).value;return v===''?null:Number(v);}
async function saveScout(){if(!current||!ctx.canScoutingWrite)return;msg('scoutMessage');const btn=$('saveScout');btn.disabled=true;try{await rpc('v2_create_scouting_report',{organization_id:ctx.organization_id,prospect_id:current.id,observed_name:null,observed_at:$('scoutDate').value?new Date($('scoutDate').value).toISOString():new Date().toISOString(),observed_location:$('scoutLocation').value.trim()||null,player_position:$('scoutPosition').value.trim()||null,category:$('scoutCategory').value.trim()||null,technical_score:num('scoreTechnical'),physical_score:num('scorePhysical'),tactical_score:num('scoreTactical'),mental_score:num('scoreMental'),star_quality:$('starQuality').value.trim()||null,verdict:$('scoutVerdict').value.trim()||null,notes:$('scoutNotes').value.trim()||null});msg('scoutMessage','Visoría guardada.','success');['scoutPosition','scoutLocation','scoreTechnical','scorePhysical','scoreTactical','scoreMental','starQuality','scoutVerdict','scoutNotes'].forEach(id=>$(id).value='');await Promise.all([loadScoutingHistory(),loadProspects()]);}catch(e){msg('scoutMessage',e.message||'No se pudo guardar la visoría.');}finally{btn.disabled=!ctx.canScoutingWrite;}}
async function loadScoutingHistory(){const box=$('scoutingHistory');box.innerHTML='';if(!ctx.canScoutingRead){box.innerHTML='<div class="empty">Sin acceso a Scouting.</div>';return;}const rows=await rpc('v2_scouting_reports',{organization_id:ctx.organization_id,prospect_id:current.id});if(!rows?.length){box.innerHTML='<div class="empty">Sin visorías todavía.</div>';return;}for(const r of rows){const avg=[r.technical_score,r.physical_score,r.tactical_score,r.mental_score].filter(v=>v!=null).reduce((a,b,_,arr)=>a+Number(b)/arr.length,0);const card=document.createElement('article');card.className='scout-card';card.innerHTML=`<div><strong>${fmtDateTime(r.observed_at)}</strong><span>${r.observed_location||'Sin lugar'} · ${r.player_position||'Sin posición'}</span></div><div><b>${avg?avg.toFixed(1):'—'}</b><span>${r.verdict||'Sin veredicto'}</span></div>`;box.appendChild(card);}}
$('statusFilter').addEventListener('change',applyFilters);$('searchProspect').addEventListener('input',applyFilters);$('closeProspect').addEventListener('click',closeProspect);$('prospectBackdrop').addEventListener('click',closeProspect);$('saveFollowup').addEventListener('click',saveFollowup);$('saveScout').addEventListener('click',saveScout);$('signOut').addEventListener('click',async()=>{await supabase.auth.signOut();location.href='/v2';});boot().catch(e=>{$('deniedText').textContent=e.message||'No pudimos abrir Prospectos.';show('deniedView');});