import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://pacnegivzgxpanphrnwp.supabase.co','sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);let ctx=null,canWrite=false,members=[],invites=[];
const roleLabels={president:'Presidencia',operations:'Operaciones',coach:'Formadores',academy:'Academia',cashier:'Taquilla',accounting:'Contabilidad',commercial:'La Quinta Fuerza',scouting:'Scouting',player:'Tanner'};
function show(id){['loadingView','deniedView','view'].forEach(v=>$(v)?.classList.toggle('hidden',v!==id));}
function msg(id,t='',type='error'){const e=$(id);if(!e)return;e.textContent=t;e.dataset.type=type;e.classList.toggle('hidden',!t);}
async function rpc(n,p={}){const {data,error}=await supabase.rpc(n,p);if(error)throw error;return data;}
function friendly(e){const t=String(e?.message||e||'Error');const map={'Not authorized':'No tienes permiso para administrar usuarios.','Valid email required':'Escribe un correo válido.','Invalid role':'Rol inválido.','Owner membership is protected':'La membresía owner está protegida y no puede modificarse desde esta pantalla.','Pending invitation not found':'La invitación ya no está pendiente.'};return map[t]||t;}
async function boot(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/v2';return;}const rows=await rpc('v2_my_context');if(!rows?.length){$('deniedText').textContent='Sin organización.';show('deniedView');return;}ctx=rows[0];const mods=await rpc('v2_my_modules',{organization_id:ctx.organization_id});const mod=mods.find(m=>m.module_code==='users');if(!mod?.enabled||!mod?.can_read){$('deniedText').textContent='Tu rol no tiene acceso a Usuarios.';show('deniedView');return;}canWrite=!!mod.can_write;$('orgName').textContent=ctx.organization_name||'Tannery City FC';$('roleBadge').textContent=ctx.is_owner?'Propietario':ctx.role;$('sendInvite').disabled=!canWrite;await load();show('view');}
async function load(){const data=await rpc('v2_users_admin',{organization_id:ctx.organization_id});members=Array.isArray(data?.members)?data.members:[];invites=Array.isArray(data?.invitations)?data.invitations:[];render();}
function render(){const pending=invites.filter(i=>i.status==='pending'&&new Date(i.expiresAt)>new Date());$('kpiActive').textContent=members.filter(m=>m.active).length;$('kpiInactive').textContent=members.filter(m=>!m.active).length;$('kpiPending').textContent=pending.length;$('kpiOwners').textContent=members.filter(m=>m.isOwner).length;renderMembers();renderInvites(pending);}
function roleOptions(current){return Object.entries(roleLabels).map(([v,l])=>`<option value="${v}" ${v===current?'selected':''}>${l}</option>`).join('');}
function renderMembers(){const box=$('memberList');box.innerHTML='';$('memberEmpty').classList.toggle('hidden',members.length>0);members.forEach(m=>{const row=document.createElement('article');row.className=`member-card ${m.active?'':'inactive'}`;const locked=m.isOwner||!canWrite;row.innerHTML=`<div class="member-main"><div class="member-title"><strong>${m.displayName||m.email||'Usuario'}</strong>${m.isOwner?'<span class="owner-chip">Owner</span>':''}</div><span>${m.email||'Sin correo visible'}</span><small>${m.active?'Acceso activo':'Acceso inactivo'}</small></div><div class="member-actions"><select class="role-select" data-id="${m.membershipId}" ${locked?'disabled':''}>${roleOptions(m.roleCode||'player')}</select>${m.isOwner?'':`<button class="secondary mini toggle-member" data-id="${m.membershipId}" data-active="${m.active}" type="button" ${!canWrite?'disabled':''}>${m.active?'Desactivar':'Reactivar'}</button>`}</div>`;box.appendChild(row);});box.querySelectorAll('.role-select').forEach(s=>s.addEventListener('change',()=>updateMember(s.dataset.id,s.value,null)));box.querySelectorAll('.toggle-member').forEach(b=>b.addEventListener('click',()=>updateMember(b.dataset.id,null,b.dataset.active!=='true')));}
function renderInvites(rows){const box=$('inviteList');box.innerHTML='';$('inviteEmpty').classList.toggle('hidden',rows.length>0);rows.forEach(i=>{const exp=new Date(i.expiresAt).toLocaleDateString('es-MX');const row=document.createElement('article');row.className='invite-card';row.innerHTML=`<div><strong>${i.email}</strong><span>${roleLabels[i.roleCode]||i.roleCode} · vence ${exp}</span></div>${canWrite?`<button class="secondary mini revoke-invite" data-id="${i.id}" type="button">Revocar</button>`:''}`;box.appendChild(row);});box.querySelectorAll('.revoke-invite').forEach(b=>b.addEventListener('click',()=>revokeInvite(b.dataset.id)));}
async function createInvite(e){e.preventDefault();msg('inviteMessage');const btn=$('sendInvite');btn.disabled=true;try{await rpc('v2_create_invitation',{organization_id:ctx.organization_id,email:$('inviteEmail').value.trim(),role_code:$('inviteRole').value});e.target.reset();$('inviteRole').value='president';await load();msg('inviteMessage','Invitación creada. Debe registrarse con ese mismo correo dentro de 7 días.','success');}catch(err){msg('inviteMessage',friendly(err));}finally{btn.disabled=!canWrite;}}
async function updateMember(id,roleCode,active){const m=members.find(x=>x.membershipId===id);if(!m)return;try{await rpc('v2_update_membership',{organization_id:ctx.organization_id,membership_id:id,role_code:roleCode||m.roleCode,active:active===null?m.active:active});await load();}catch(err){alert(friendly(err));await load();}}
async function revokeInvite(id){if(!confirm('¿Revocar esta invitación?'))return;try{await rpc('v2_revoke_invitation',{organization_id:ctx.organization_id,invitation_id:id});await load();}catch(err){alert(friendly(err));}}
$('inviteForm').addEventListener('submit',createInvite);$('refresh').addEventListener('click',load);boot().catch(e=>{$('deniedText').textContent=friendly(e);show('deniedView');});