import {supabase,rpc,$,bootstrapProtectedShell,moduleAccess,setShellHealth} from '/v2/shell.js';
import {BRANDING_BUCKET,normalizeBranding,brandingAssetUrl,applyBranding} from '/v2/branding.js';
const defaults={primary:'#012A3A',secondary:'#087D8E',accent:'#C6AC5C',background:'#F5F3EB'};
let ctx=null,navigation=[],branding=null,dirty=false;const pending={logo:null,logoDark:null,mark:null,appIcon:null,splash:null};const removed=new Set();const objectUrls=new Map();
function show(id){['loadingView','deniedView','view'].forEach(v=>$(v)?.classList.toggle('hidden',v!==id));}
function message(text='',ok=false){$('saveMessage').textContent=text;$('saveState').textContent=ok?'Identidad guardada':(dirty?'Cambios pendientes':'Sin cambios pendientes');}
function setDirty(value=true){dirty=value;$('saveState').textContent=dirty?'Cambios pendientes':'Sin cambios pendientes';}
function validHex(v){return /^#[0-9A-Fa-f]{6}$/.test(String(v||''));}
function extFor(file){return file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg';}
function safeFile(file){if(!file)return false;if(file.size>5*1024*1024)throw new Error('La imagen supera 5 MB.');if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('Usa PNG, JPG o WebP.');return true;}
function localUrl(slot,file){if(objectUrls.has(slot))URL.revokeObjectURL(objectUrls.get(slot));const url=URL.createObjectURL(file);objectUrls.set(slot,url);return url;}
function previewEl(slot){return {logo:$('previewLogo'),logoDark:$('previewLogoDark'),mark:$('previewMark'),appIcon:$('previewAppIcon'),splash:$('previewSplash')}[slot];}
function setPreview(slot,url){const box=previewEl(slot);if(!box)return;box.innerHTML='';if(url){const img=document.createElement('img');img.src=url;img.alt='Vista previa';box.appendChild(img);}else box.innerHTML=`<span>${slot==='mark'?'T':slot==='appIcon'?'APP':slot==='splash'?'SPLASH':'LOGO'}</span>`;}
function currentAsset(slot){if(removed.has(slot))return null;if(pending[slot])return objectUrls.get(slot)||localUrl(slot,pending[slot]);if(slot==='appIcon')return brandingAssetUrl(branding.assets.appIcon180);return brandingAssetUrl(branding.assets[slot]);}
function fillForm(){$('brandName').value=branding.brand||'';$('productName').value=branding.product||'';$('appName').value=branding.appName||'';$('tagline').value=branding.tagline||'';for(const key of ['primary','secondary','accent','background']){$(key).value=branding.colors[key];$(`${key}Picker`).value=branding.colors[key];}['logo','logoDark','mark','appIcon','splash'].forEach(slot=>setPreview(slot,currentAsset(slot)));renderPreview();setDirty(false);message();}
function fieldBranding(){return normalizeBranding({...branding,brand:$('brandName').value.trim(),product:$('productName').value.trim(),appName:$('appName').value.trim(),tagline:$('tagline').value.trim(),colors:{primary:$('primary').value.toUpperCase(),secondary:$('secondary').value.toUpperCase(),accent:$('accent').value.toUpperCase(),background:$('background').value.toUpperCase()},assets:{...branding.assets}});}
function setMockImage(id,url,fallback='T'){const el=$(id);el.innerHTML='';if(url){const img=document.createElement('img');img.src=url;img.alt='';el.appendChild(img);}else el.textContent=fallback;}
function renderPreview(){const b=fieldBranding(),c=b.colors,box=$('brandPreview');box.querySelector('aside').style.background=c.primary;box.querySelector('main').style.background=c.background;box.querySelector('.mock-nav.active').style.background=c.secondary;box.querySelector('.mock-mark').style.background=c.accent;box.querySelector('.mock-welcome').style.background=`linear-gradient(120deg,${c.primary},${c.secondary})`;$('mockProduct').textContent=b.product;$('mockBrand').textContent=b.brand;$('mockAppName').textContent=b.appName;$('mockTagline').textContent=b.tagline||b.brand;setMockImage('mockMark',currentAsset('mark')||currentAsset('appIcon'),(b.brand||'T').charAt(0));setMockImage('phoneIcon',currentAsset('appIcon')||currentAsset('mark'),(b.brand||'T').charAt(0));$('phoneIcon').style.background=c.primary;$('phoneName').textContent=b.appName;}
function bindColor(key){const text=$(key),picker=$(`${key}Picker`);picker.addEventListener('input',()=>{text.value=picker.value.toUpperCase();setDirty();renderPreview();});text.addEventListener('input',()=>{if(validHex(text.value))picker.value=text.value;setDirty();renderPreview();});}
function bindFile(id,slot){$(id).addEventListener('change',e=>{try{const file=e.target.files?.[0];if(!file)return;safeFile(file);pending[slot]=file;removed.delete(slot);setPreview(slot,localUrl(slot,file));setDirty();renderPreview();message('Imagen lista para subir al guardar.');}catch(err){e.target.value='';message(err.message);}});}
async function uploadFile(slot,file){safeFile(file);const path=`organizations/${ctx.organization_id}/branding/${slot}-${Date.now()}-${crypto.randomUUID()}.${extFor(file)}`;const {error}=await supabase.storage.from(BRANDING_BUCKET).upload(path,file,{cacheControl:'31536000',upsert:false,contentType:file.type});if(error)throw error;return path;}
async function iconBlob(file,size,color){safeFile(file);const bmp=await createImageBitmap(file),ratio=bmp.width/bmp.height;if(ratio<.75||ratio>1.33){bmp.close();throw new Error('Para el icono de app usa una imagen aproximadamente cuadrada.');}const canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;const g=canvas.getContext('2d');g.fillStyle=color;g.fillRect(0,0,size,size);const max=size*.84,scale=Math.min(max/bmp.width,max/bmp.height),w=bmp.width*scale,h=bmp.height*scale;g.drawImage(bmp,(size-w)/2,(size-h)/2,w,h);bmp.close();return await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('No se pudo generar el icono.')),'image/png',.95));}
async function uploadIconSet(file,color){const result={};for(const size of [180,192,512]){const blob=await iconBlob(file,size,color),path=`organizations/${ctx.organization_id}/branding/app-icon-${size}-${Date.now()}-${crypto.randomUUID()}.png`;const {error}=await supabase.storage.from(BRANDING_BUCKET).upload(path,blob,{cacheControl:'31536000',upsert:false,contentType:'image/png'});if(error)throw error;result[`appIcon${size}`]=path;}return result;}
async function save(ev){ev.preventDefault();message();const b=fieldBranding();if(!b.brand||!b.product||!b.appName){message('Completa marca, producto y nombre de app.');return;}for(const v of Object.values(b.colors))if(!validHex(v)){message('Revisa los colores HEX.');return;}const btn=$('saveBranding');btn.disabled=true;btn.textContent='Guardando…';try{const assets={...branding.assets};for(const slot of ['logo','logoDark','mark','splash']){if(removed.has(slot))assets[slot]=null;else if(pending[slot])assets[slot]=await uploadFile(slot,pending[slot]);}if(removed.has('appIcon')){assets.appIcon180=null;assets.appIcon192=null;assets.appIcon512=null;}else if(pending.appIcon)Object.assign(assets,await uploadIconSet(pending.appIcon,b.colors.primary));const payload={brand:b.brand,product:b.product,appName:b.appName,tagline:b.tagline,colors:b.colors,assets};const saved=await rpc('v2_update_branding',{organization_id:ctx.organization_id,branding:payload});branding=normalizeBranding(saved||payload);Object.keys(pending).forEach(k=>pending[k]=null);removed.clear();fillForm();applyBranding(branding,{organizationId:ctx.organization_id});setShellHealth({state:'ok',label:'Branding guardado'});message('Se aplicó a TannerOS y al manifest de instalación.',true);}catch(err){message(err.message||'No se pudo guardar.');}finally{btn.disabled=false;btn.textContent='Guardar identidad';}}
async function boot(){const shell=await bootstrapProtectedShell({active:'admin',title:'Marca y apariencia'});if(!shell){show('deniedView');return;}ctx=shell.ctx;navigation=shell.navigation;if(!moduleAccess(navigation,'admin',true)){$('deniedText').textContent='Puedes ver Administración, pero no editar la identidad.';show('deniedView');return;}branding=normalizeBranding(await rpc('v2_branding',{organization_id:ctx.organization_id}));applyBranding(branding,{organizationId:ctx.organization_id});fillForm();show('view');['brandName','productName','appName','tagline'].forEach(id=>$(id).addEventListener('input',()=>{setDirty();renderPreview();}));['primary','secondary','accent','background'].forEach(bindColor);bindFile('fileLogo','logo');bindFile('fileLogoDark','logoDark');bindFile('fileMark','mark');bindFile('fileAppIcon','appIcon');bindFile('fileSplash','splash');document.querySelectorAll('.clear-asset').forEach(btn=>btn.addEventListener('click',()=>{const slot=btn.dataset.clear;pending[slot]=null;removed.add(slot);setPreview(slot,null);setDirty();renderPreview();}));$('resetDefaults').addEventListener('click',()=>{Object.entries(defaults).forEach(([k,v])=>{$(k).value=v;$(`${k}Picker`).value=v;});setDirty();renderPreview();message('Paleta TannerOS restaurada en la vista previa. Guarda para aplicarla.');});$('brandingForm').addEventListener('submit',save);}
boot().catch(e=>{$('deniedText').textContent=e.message||'No pudimos abrir Marca y apariencia.';show('deniedView');});
