import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://pacnegivzgxpanphrnwp.supabase.co','sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);let ctx=null,academies=[],players=[],canWrite=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function show(id){['loadingView','deniedView','view'].forEach(v=>$(v)?.classList.toggle('hidden',v!==id));}
function msg(id,t='',type='error'){const e=$(id);if(!e)return;e.textContent=t;e.dataset.type=type;e.classList.toggle('hidden',!t);}
async function rpc(n,p={}){const {data,error}=await supabase.rpc(n,p);if(error)throw error;return data;}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function pname(p){return [p.first_name,p.last_name].filter(Boolean).join(' ');}
async function boot(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/';return;}const rows=await rpc('v2_my_context');if(!rows?.length){$('deniedText').textContent='Sin organización.';show('deniedView');return;}ctx=rows[0];const mods=await rpc('v2_my_modules',{organization_id:ctx.organization_id});const mod=mods.find(m=>m.module_code==='academies');if(!mod?.enabled||!mod?.can_read){$('deniedText').textContent='Tu rol no tiene acceso a Academias.';show('deniedView');return;}canWrite=!!mod.can_write;$('orgName').textContent=ctx.organization_name||'Tannery City';$('roleBadge').textContent=ctx.is_owner?'Presidencia':ctx.role;$('saveAcademy').disabled=!canWrite;$('saveEnrollment').disabled=!canWrite;$('enrollDate').value=today();players=await rpc('v2_players',{organization_id:ctx.organization_id,status_filter:'active'});await load();renderPlayers();show('view');}
async function load(){academies=await rpc('v2_academies',{organization_id:ctx.organization_id})||[];renderAcademies();}
function renderPlayers(){const s=$('enrollPlayer');s.innerHTML='<option value="">Selecciona</option>';[...players].sort((a,b)=>pname(a).localeCompare(pname(b),'es-MX')).forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=`${pname(p)} · ${p.code||''}`;s.appendChild(o);});}
function renderAcademies(){const list=$('academyList'),sel=$('enrollAcademy');list.innerHTML='';sel.innerHTML='<option value="">Selecciona</option>';$('empty').classList.toggle('hidden',academies.length>0);academies.forEach(a=>{const unlimited=Number(a.capacity||0)<=0,full=!unlimited&&Number(a.active_enrollments||0)>=Number(a.capacity||0);const o=document.createElement('option');o.value=a.id;o.disabled=full;o.textContent=`${a.name||'Academia'}${unlimited?' · sin límite':` · ${a.active_enrollments||0}/${a.capacity}${full?' · LLENA':''}`}`;sel.appendChild(o);const c=document.createElement('article');c.className='academy-card';c.innerHTML=`<div><strong>${esc(a.name||'Academia')}</strong><span>${esc(a.location||'Sin ubicación')} · ${esc(a.status||'active')}</span></div><div><b>${Number(a.active_enrollments||0)}${unlimited?'':` / ${Number(a.capacity||0)}`}</b><span>${full?'llena':unlimited?'inscritos · sin límite':`${Number(a.available_spots||0)} lugares libres`}</span></div>`;list.appendChild(c);});}
async function createAcademy(e){e.preventDefault();msg('academyMessage');const btn=$('saveAcademy');btn.disabled=true;try{await rpc('v2_upsert_academy_enhanced',{organization_id:ctx.organization_id,academy_id:null,slug:$('academySlug').value.trim(),name:$('academyName').value.trim(),academy_type:$('academyType').value.trim()||'general',description:$('academyDescription').value.trim()||null,status:'active',monthly_fee:$('academyFee').value===''?null:Number($('academyFee').value),hourly_rate:null,schedule:[],location:$('academyLocation').value.trim()||null,capacity:Number($('academyCapacity').value||0)});msg('academyMessage','Academia creada.','success');e.target.reset();$('academyType').value='general';$('academyCapacity').value='0';await load();}catch(err){msg('academyMessage',err.message||'No se pudo crear.');}finally{btn.disabled=!canWrite;}}
async function enroll(e){e.preventDefault();msg('enrollMessage');const btn=$('saveEnrollment');btn.disabled=true;try{await rpc('v2_enroll_academy',{organization_id:ctx.organization_id,academy_id:$('enrollAcademy').value,player_id:$('enrollPlayer').value,starts_on:$('enrollDate').value,agreed_fee:$('enrollFee').value===''?null:Number($('enrollFee').value),notes:$('enrollNotes').value.trim()||null});msg('enrollMessage','Tanner inscrito. La cuota de Academia se administra como cargo separado en su cuenta.','success');$('enrollPlayer').value='';$('enrollFee').value='';$('enrollNotes').value='';await load();}catch(err){const map={'Academy is full':'La academia ya llegó a su cupo.','Player already enrolled':'Ese Tanner ya está inscrito en esta academia.'};msg('enrollMessage',map[err.message]||err.message||'No se pudo inscribir.');}finally{btn.disabled=!canWrite;}}
$('academyForm')?.addEventListener('submit',createAcademy);$('enrollForm')?.addEventListener('submit',enroll);$('refresh')?.addEventListener('click',load);boot().catch(e=>{$('deniedText').textContent=e.message||'No pudimos abrir Academias.';show('deniedView');});
