import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://pacnegivzgxpanphrnwp.supabase.co','sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',{auth:{persistSession:true,autoRefreshToken:true}});const $=id=>document.getElementById(id);let ctx=null,players=[],packages=[],sessions=[],canWrite=false;const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'});
function show(id){['loadingView','deniedView','view'].forEach(v=>$(v)?.classList.toggle('hidden',v!==id));}function msg(id,t='',type='error'){const e=$(id);if(!e)return;e.textContent=t;e.dataset.type=type;e.classList.toggle('hidden',!t);}async function rpc(n,p={}){const {data,error}=await supabase.rpc(n,p);if(error)throw error;return data;}function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}function pname(p){return [p.first_name,p.last_name].filter(Boolean).join(' ');}function fmtDate(v){return v?new Intl.DateTimeFormat('es-MX',{dateStyle:'medium'}).format(new Date(`${v}T12:00:00`)):'—';}
async function boot(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/v2';return;}const rows=await rpc('v2_my_context');if(!rows?.length){$('deniedText').textContent='Sin organización.';show('deniedView');return;}ctx=rows[0];const mods=await rpc('v2_my_modules',{organization_id:ctx.organization_id});const mod=mods.find(m=>m.module_code==='academies');if(!mod?.enabled||!mod?.can_read){$('deniedText').textContent='Tu rol no tiene acceso a Academias.';show('deniedView');return;}canWrite=!!mod.can_write;$('orgName').textContent=ctx.organization_name;$('roleBadge').textContent=ctx.is_owner?'Propietario':ctx.role;$('savePackage').disabled=!canWrite;$('saveSession').disabled=!canWrite;$('packageDate').value=today();$('sessionDate').value=today();players=await rpc('v2_players',{organization_id:ctx.organization_id,status_filter:'active'});renderPlayers();await load();wire();show('view');}
function renderPlayers(){for(const id of ['packagePlayer','sessionPlayer']){const s=$(id);s.innerHTML='<option value="">Selecciona</option>';[...players].sort((a,b)=>pname(a).localeCompare(pname(b),'es-MX')).forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=`${pname(p)} · ${p.category||'Sin categoría'}`;s.appendChild(o);});}}
async function load(){[packages,sessions]=await Promise.all([rpc('v2_goalkeeper_packages',{organization_id:ctx.organization_id,player_id:null}),rpc('v2_goalkeeper_sessions',{organization_id:ctx.organization_id,player_id:null})]);renderKpis();renderPackages();renderSessions();}
function renderKpis(){$('kpiPackages').textContent=packages.filter(p=>p.is_active).length;$('kpiRemaining').textContent=packages.filter(p=>p.is_active).reduce((s,p)=>s+Number(p.classes_remaining||0),0);$('kpiSessions').textContent=sessions.filter(s=>s.status!=='cancelled').length;$('kpiLoose').textContent=sessions.filter(s=>!s.package_id&&s.status!=='cancelled'&&Number(s.amount||0)>0).length;}
function renderPackages(){const box=$('packageList');box.innerHTML='';$('packagesEmpty').classList.toggle('hidden',packages.length>0);packages.forEach(p=>{const card=document.createElement('article');card.className=`package-card ${p.is_active?'active':p.is_expired?'expired':'done'}`;card.innerHTML=`<div><strong>${p.player_name}</strong><span>${p.classes_used}/${p.classes_total} usadas · ${p.classes_remaining} restantes</span></div><div><b>${money.format(Number(p.price))}</b><span>${p.expires_on?`vence ${fmtDate(p.expires_on)}`:'sin vencimiento'}</span><small>${p.is_active?'Activo':p.is_expired?'Vencido':'Sin clases'}</small></div>`;box.appendChild(card);});}
function renderSessions(){const box=$('sessionList');box.innerHTML='';$('sessionsEmpty').classList.toggle('hidden',sessions.length>0);sessions.slice(0,50).forEach(s=>{const card=document.createElement('article');card.className=`session-card ${s.status==='cancelled'?'cancelled':''}`;card.innerHTML=`<div><strong>${s.player_name}</strong><span>${fmtDate(s.session_date)} · ${s.hours} h · ${s.package_id?'Paquete':'Suelta'}</span></div><div><b>${s.package_id?'Incluida':money.format(Number(s.amount||0))}</b>${s.status==='completed'&&canWrite?'<button class="secondary mini" type="button">Cancelar</button>':'<span>Cancelada</span>'}</div>`;card.querySelector('button')?.addEventListener('click',()=>cancelSession(s));box.appendChild(card);});}
async function savePackage(e){e.preventDefault();msg('packageMessage');const btn=$('savePackage');btn.disabled=true;try{await rpc('v2_purchase_goalkeeper_package',{organization_id:ctx.organization_id,academy_id:null,player_id:$('packagePlayer').value,classes:Number($('packageClasses').value),price:Number($('packagePrice').value),purchased_on:$('packageDate').value,expires_on:$('packageExpires').value||null,method:$('packageMethod').value,reference:$('packageReference').value.trim()||null,notes:$('packageNotes').value.trim()||null});msg('packageMessage','Paquete y cobro registrados.','success');e.target.reset();$('packageClasses').value='4';$('packageDate').value=today();await load();}catch(err){msg('packageMessage',err.message||'No se pudo registrar.');}finally{btn.disabled=!canWrite;}}
async function saveSession(e){e.preventDefault();msg('sessionMessage');const btn=$('saveSession');btn.disabled=true;try{const loose=$('sessionMode').value==='loose';await rpc('v2_add_goalkeeper_session',{organization_id:ctx.organization_id,academy_id:null,player_id:$('sessionPlayer').value,session_date:$('sessionDate').value,start_time:null,hours:Number($('sessionHours').value),rate:loose?Number($('sessionRate').value):null,package_id:null,force_loose:loose,method:$('sessionMethod').value,reference:$('sessionReference').value.trim()||null,notes:$('sessionNotes').value.trim()||null});msg('sessionMessage',loose?'Clase suelta y cobro registrados.':'Clase registrada; si había paquete se descontó automáticamente.','success');e.target.reset();$('sessionDate').value=today();$('sessionHours').value='1';$('sessionMode').value='auto';toggleRate();await load();}catch(err){const map={'Rate required for loose session':'Escribe la tarifa por hora para la clase suelta.','Package has no remaining classes':'Ese paquete ya no tiene clases disponibles.','Package expired':'El paquete ya venció.'};msg('sessionMessage',map[err.message]||err.message||'No se pudo registrar.');}finally{btn.disabled=!canWrite;}}
async function cancelSession(s){if(!confirm(`¿Cancelar la clase de ${s.player_name}? ${s.package_id?'La clase regresará al paquete.':'El ingreso ligado a la clase será anulado.'}`))return;try{await rpc('v2_cancel_goalkeeper_session',{organization_id:ctx.organization_id,session_id:s.id,reason:'Cancelada desde TannerOS v2'});await load();}catch(err){alert(err.message||'No se pudo cancelar.');}}
function toggleRate(){const loose=$('sessionMode').value==='loose';$('rateWrap').classList.toggle('hidden',!loose);$('sessionRate').required=loose;if(!loose)$('sessionRate').value='';}
function wire(){$('packageForm').addEventListener('submit',savePackage);$('sessionForm').addEventListener('submit',saveSession);$('sessionMode').addEventListener('change',toggleRate);$('refresh').addEventListener('click',load);toggleRate();}
boot().catch(e=>{$('deniedText').textContent=e.message||'No pudimos abrir Porteros.';show('deniedView');});