import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const supabase = createClient(
  'https://pacnegivzgxpanphrnwp.supabase.co',
  'sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',
  { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true } }
);

const $ = id => document.getElementById(id);
const views = ['authView','pendingView','appView'];
let authMode = 'signin';
let ctx = null;
let players = [];
let lastSignupEmail = '';
let moduleRows = [];
let pendingPaymentKey = null;
let drawerPlayer = null;
const money = new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:2});

function showView(id){ views.forEach(v => $(v)?.classList.toggle('hidden',v!==id)); }
function setMessage(text='',type='error'){ const b=$('authMessage'); if(!b)return; b.textContent=text; b.dataset.type=type; b.classList.toggle('hidden',!text); }
function setPaymentMessage(text='',type='error'){ const b=$('paymentMessage'); if(!b)return; b.textContent=text; b.dataset.type=type; b.classList.toggle('hidden',!text); }
function setLifecycleMessage(text='',type='error'){ const b=$('lifecycleMessage'); if(!b)return; b.textContent=text; b.dataset.type=type; b.classList.toggle('hidden',!text); }
function showResend(show=true){ $('resendConfirmation')?.classList.toggle('hidden',!show); }
function friendlyError(e){ const r=String(e?.message||e||'Ocurrió un error.'); if(/invalid login credentials/i.test(r))return 'Correo o contraseña incorrectos.'; if(/email not confirmed/i.test(r))return 'Confirma tu correo antes de entrar.'; if(/user already registered/i.test(r))return 'Ese correo ya tiene una cuenta. Usa “Entrar”.'; if(/rate limit/i.test(r))return 'Demasiados intentos. Intenta de nuevo en unos minutos.'; if(/not authorized/i.test(r))return 'No tienes permiso para realizar esta operación.'; if(/player not found/i.test(r))return 'No encontramos ese jugador dentro de tu club.'; if(/amount must be greater than zero/i.test(r))return 'El monto debe ser mayor a cero.'; if(/withdrawal reason required/i.test(r))return 'Escribe el motivo de la baja.'; if(/only active players can be withdrawn/i.test(r))return 'Solo un Tanner activo puede darse de baja.'; if(/only withdrawn players can be reactivated/i.test(r))return 'Solo un Tanner dado de baja puede reactivarse.'; return r; }
function switchAuthMode(mode){ authMode=mode; const up=mode==='signup'; $('signInTab')?.classList.toggle('active',!up); $('signUpTab')?.classList.toggle('active',up); $('nameField')?.classList.toggle('hidden',!up); $('authSubmit').textContent=up?'Crear cuenta':'Entrar'; $('password')?.setAttribute('autocomplete',up?'new-password':'current-password'); setMessage(); showResend(false); }
async function rpc(name,params={}){ const {data,error}=await supabase.rpc(name,params); if(error)throw error; return data; }

async function handleAuthSubmit(ev){ ev.preventDefault(); setMessage(); showResend(false); const email=$('email').value.trim(), password=$('password').value, displayName=$('displayName')?.value.trim(); const btn=$('authSubmit'); btn.disabled=true; try{ if(authMode==='signup'){ lastSignupEmail=email; const {data,error}=await supabase.auth.signUp({email,password,options:{data:{display_name:displayName||email.split('@')[0]},emailRedirectTo:`${location.origin}/v2`}}); if(error)throw error; if(!data.session){ setMessage('Cuenta creada. Revisa tu correo y confirma el acceso. Si el enlace expira, puedes reenviarlo aquí.','success'); showResend(true); return; } }else{ const {error}=await supabase.auth.signInWithPassword({email,password}); if(error)throw error; } await loadAuthenticatedApp(); }catch(e){ const msg=friendlyError(e); setMessage(msg); if(/confirma tu correo/i.test(msg)){ lastSignupEmail=email; showResend(true); } }finally{ btn.disabled=false; btn.textContent=authMode==='signup'?'Crear cuenta':'Entrar'; } }

async function resendConfirmation(){ const email=lastSignupEmail||$('email')?.value.trim(); if(!email){ setMessage('Escribe primero el correo que quieres confirmar.'); return; } const btn=$('resendConfirmation'); btn.disabled=true; try{ const {error}=await supabase.auth.resend({type:'signup',email,options:{emailRedirectTo:`${location.origin}/v2`}}); if(error)throw error; setMessage(`Listo. Enviamos un nuevo correo de confirmación a ${email}. Usa el más reciente.`,'success'); }catch(e){ setMessage(friendlyError(e)); }finally{ btn.disabled=false; } }

async function loadAuthenticatedApp(){ const {data:userData}=await supabase.auth.getUser(); if(!userData?.user){ showView('authView'); return; } const rows=await rpc('v2_my_context'); if(!Array.isArray(rows)||!rows.length){ $('pendingText').textContent=`La cuenta ${userData.user.email||'actual'} ya existe en Supabase Auth. Falta vincularla a Tannery City.`; showView('pendingView'); return; } ctx=rows[0]; await loadDashboard(userData.user); showView('appView'); }

function monthStart(){ const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`; }
function todayLocal(){ const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
async function loadDashboard(user){ const org=ctx.organization_id; const [snap,playerRows,modules]=await Promise.all([ rpc('v2_collection_snapshot',{organization_id:org,billing_period:monthStart()}), rpc('v2_players',{organization_id:org,status_filter:'active'}), rpc('v2_my_modules',{organization_id:org}) ]); players=Array.isArray(playerRows)?playerRows:[]; moduleRows=Array.isArray(modules)?modules:[]; $('orgName').textContent=ctx.organization_name||'Tannery City FC'; $('roleBadge').textContent=ctx.is_owner?'Propietario':(ctx.role||'Miembro'); $('welcome').textContent=`Sesión segura de ${ctx.display_name||user.email||'Tanner'}`; $('kpiPlayers').textContent=snap?.active_players??players.length; $('kpiCollection').textContent=snap?.collection_rate==null?'—':`${snap.collection_rate}%`; $('kpiCovered').textContent=snap?.covered==null?'':`${snap.covered}/${snap.collection_population} cubiertos`; $('kpiCurrentDebt').textContent=money.format(Number(snap?.current_period_receivable||0)); $('kpiTotalDebt').textContent=money.format(Number(snap?.total_receivable||0)); renderModules(moduleRows.filter(m=>m.enabled&&m.can_read)); renderPlayers(players); configurePaymentPanel(); }

function configurePaymentPanel(){ const billing=moduleRows.find(m=>m.module_code==='billing'); const canWrite=Boolean(billing?.enabled&&billing?.can_write); $('paymentPanel')?.classList.toggle('hidden',!canWrite); if(!canWrite)return; const select=$('paymentPlayer'); const current=select.value; select.innerHTML='<option value="">Selecciona un Tanner</option>'; [...players].sort((a,b)=>playerName(a).localeCompare(playerName(b),'es-MX')).forEach(p=>{ const opt=document.createElement('option'); opt.value=p.id; opt.textContent=`${playerName(p)}${p.code?` · ${p.code}`:''}`; select.appendChild(opt); }); if(current&&players.some(p=>p.id===current))select.value=current; if(!$('paymentDate').value)$('paymentDate').value=todayLocal(); }

function newIdempotencyKey(){ if(globalThis.crypto?.randomUUID)return `pay:${ctx.organization_id}:${crypto.randomUUID()}`; return `pay:${ctx.organization_id}:${Date.now()}:${Math.random().toString(36).slice(2)}`; }
async function postPayment(ev){ ev.preventDefault(); setPaymentMessage(); const btn=$('paymentSubmit'); const playerId=$('paymentPlayer').value; const amount=Number($('paymentAmount').value); const paymentDate=$('paymentDate').value; if(!playerId||!Number.isFinite(amount)||amount<=0||!paymentDate){ setPaymentMessage('Completa jugador, monto y fecha.'); return; } if(!pendingPaymentKey)pendingPaymentKey=newIdempotencyKey(); btn.disabled=true; btn.textContent='Registrando…'; try{ const paymentId=await rpc('v2_post_payment',{organization_id:ctx.organization_id,player_id:playerId,amount,payment_date:paymentDate,method:$('paymentMethod').value,reference:$('paymentReference').value.trim()||null,concept:'Mensualidad',payer_type:$('paymentPayerType').value,payer_name:$('paymentPayerName').value.trim()||null,idempotency_key:pendingPaymentKey}); pendingPaymentKey=null; const paidPlayer=players.find(p=>p.id===playerId); setPaymentMessage(`Pago registrado${paidPlayer?` para ${playerName(paidPlayer)}`:''}. ID ${String(paymentId).slice(0,8)}…`,'success'); $('paymentAmount').value=''; $('paymentReference').value=''; $('paymentPayerName').value=''; const {data:userData}=await supabase.auth.getUser(); await loadDashboard(userData.user); if(drawerPlayer?.id===playerId)await openPlayerDrawer(playerId); }catch(e){ setPaymentMessage(friendlyError(e)); }finally{ btn.disabled=false; btn.textContent='Registrar pago'; } }

const moduleLabels={players:'Jugadores',billing:'Cobranza',accounting:'Contabilidad',academies:'Academias',attendance:'Asistencia',programs:'Programas',commerce:'Tienda',prospects:'Prospectos',scouting:'Scouting',sponsors:'Patrocinadores',equipment:'Utilería',calendar:'Calendario',users:'Usuarios',admin:'Administración',qa:'QA'};
function renderModules(rows){ const list=$('modulesList'); list.innerHTML=''; rows.forEach(m=>{ const x=document.createElement('span'); x.className='module'; x.textContent=moduleLabels[m.module_code]||m.module_code; list.appendChild(x); }); if(!rows.length){ const x=document.createElement('span'); x.className='module'; x.textContent='Sin módulos disponibles'; list.appendChild(x); } }
function playerName(p){ return [p.first_name,p.last_name].filter(Boolean).join(' ').trim(); }
function renderPlayers(rows){ const body=$('playersBody'); body.innerHTML=''; $('playersEmpty').classList.toggle('hidden',rows.length>0); rows.forEach(p=>{ const tr=document.createElement('tr'); tr.className='player-row'; tr.tabIndex=0; tr.dataset.playerId=p.id; [p.code||'—',playerName(p)||'Sin nombre',p.category||'Sin categoría',p.base_monthly_fee==null?'Por configurar':money.format(Number(p.base_monthly_fee))].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.appendChild(td);}); const td=document.createElement('td'), badge=document.createElement('span'); const review=Boolean(p.needs_review||p.billing_status==='review'); badge.className=`status ${review?'review':'active'}`; badge.textContent=review?'Revisar':'Activo'; td.appendChild(badge); tr.appendChild(td); tr.addEventListener('click',()=>openPlayerDrawer(p.id)); tr.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openPlayerDrawer(p.id);}}); body.appendChild(tr); }); }
function filterPlayers(){ const q=$('playerSearch').value.trim().toLocaleLowerCase('es-MX'); renderPlayers(!q?players:players.filter(p=>`${p.code||''} ${playerName(p)} ${p.category||''}`.toLocaleLowerCase('es-MX').includes(q))); }

function formatPeriod(v){ if(!v)return 'Sin periodo'; const [y,m]=v.slice(0,7).split('-'); const names=['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic']; return `${names[Number(m)-1]} ${y}`; }
function renderLedgerList(el,rows,type){ el.innerHTML=''; if(!rows?.length){ el.innerHTML='<div class="ledger-empty">Sin movimientos.</div>'; return; } rows.forEach(r=>{ const item=document.createElement('div'); item.className='ledger-item'; const title=type==='charge'?`${formatPeriod(r.period)} · ${r.type==='monthly_fee'?'Mensualidad':r.type}`:`${r.date||''} · ${r.method||'Pago'}`; const detail=type==='charge'?`${money.format(Number(r.allocated||0))} aplicado · saldo ${money.format(Number(r.balance||0))}`:`${money.format(Number(r.allocated||0))} aplicado${Number(r.credit||0)>0?` · ${money.format(Number(r.credit))} a favor`:''}`; item.innerHTML=`<div><strong>${title}</strong><small>${detail}</small></div><b>${money.format(Number(r.amount||0))}</b>`; el.appendChild(item); }); }
function renderBenefits(rows=[]){ const el=$('drawerBenefits'); el.innerHTML=''; if(!rows.length){ el.innerHTML='<div class="ledger-empty">Sin beneficios registrados.</div>'; return; } const names={scholarship_full:'Beca completa',scholarship_partial:'Beca parcial',sibling_discount:'Hermanos Tanner',sponsor_funded:'Apoyo patrocinado'}; rows.forEach(r=>{ const item=document.createElement('div'); item.className='ledger-item'; const state=r.active&&(r.endsOn==null||r.endsOn>=todayLocal())?'Activo':'Histórico'; const detail=[r.legacyLabel,r.fundingSourceName,r.startsOn?`desde ${r.startsOn}`:null,r.endsOn?`hasta ${r.endsOn}`:null].filter(Boolean).join(' · '); let amount='Info'; if(r.calculationType==='full_waiver')amount='100%'; else if(r.fixedAmount!=null)amount=money.format(Number(r.fixedAmount)); else if(r.percentage!=null)amount=`${Number(r.percentage)}%`; else if(r.overrideAmount!=null)amount=money.format(Number(r.overrideAmount)); item.innerHTML=`<div><strong>${names[r.type]||r.type} · ${state}</strong><small>${detail||r.notes||'Sin detalle adicional'}</small></div><b>${amount}</b>`; el.appendChild(item); }); }
async function openPlayerDrawer(playerId){ setLifecycleMessage(); const account=await rpc('v2_player_account',{organization_id:ctx.organization_id,player_id:playerId}); if(!account?.player)throw new Error('Player not found'); drawerPlayer=account.player; $('drawerPlayerName').textContent=[drawerPlayer.firstName,drawerPlayer.lastName].filter(Boolean).join(' '); $('drawerMeta').textContent=`${drawerPlayer.code||'Sin código'} · ${drawerPlayer.status==='active'?'Activo':drawerPlayer.status==='withdrawn'?'Baja':'Inactivo'}`; $('drawerFee').textContent=drawerPlayer.baseMonthlyFee==null?'Por configurar':money.format(Number(drawerPlayer.baseMonthlyFee)); const total=(account.charges||[]).reduce((s,c)=>s+Number(c.balance||0),0); $('drawerBalance').textContent=money.format(total); renderBenefits(account.benefits||[]); renderLedgerList($('drawerCharges'),account.charges||[],'charge'); renderLedgerList($('drawerPayments'),account.payments||[],'payment'); const playersModule=moduleRows.find(m=>m.module_code==='players'); const canWrite=Boolean(playersModule?.enabled&&playersModule?.can_write); $('playerLifecycle').classList.toggle('hidden',!canWrite); $('withdrawControls').classList.toggle('hidden',drawerPlayer.status!=='active'); $('reactivateControls').classList.toggle('hidden',drawerPlayer.status!=='withdrawn'); $('withdrawDate').value=todayLocal(); $('reactivateDate').value=todayLocal(); $('drawerBackdrop').classList.remove('hidden'); $('playerDrawer').classList.remove('hidden'); $('playerDrawer').setAttribute('aria-hidden','false'); }
function closePlayerDrawer(){ drawerPlayer=null; $('drawerBackdrop').classList.add('hidden'); $('playerDrawer').classList.add('hidden'); $('playerDrawer').setAttribute('aria-hidden','true'); }
async function withdrawCurrentPlayer(){ if(!drawerPlayer)return; const reason=$('withdrawReason').value.trim(), date=$('withdrawDate').value; if(!reason){setLifecycleMessage('Escribe el motivo de la baja.');return;} if(!confirm(`¿Dar de baja a ${[drawerPlayer.firstName,drawerPlayer.lastName].filter(Boolean).join(' ')}? La deuda histórica se conservará.`))return; const btn=$('withdrawPlayer'); btn.disabled=true; try{ await rpc('v2_withdraw_player',{organization_id:ctx.organization_id,player_id:drawerPlayer.id,withdrawn_at:date,reason}); setLifecycleMessage('Baja registrada correctamente. El historial financiero se conservó.','success'); const {data:userData}=await supabase.auth.getUser(); await loadDashboard(userData.user); closePlayerDrawer(); }catch(e){setLifecycleMessage(friendlyError(e));}finally{btn.disabled=false;} }
async function reactivateCurrentPlayer(){ if(!drawerPlayer)return; const date=$('reactivateDate').value; if(!confirm(`¿Reactivar a ${[drawerPlayer.firstName,drawerPlayer.lastName].filter(Boolean).join(' ')} desde ${date}?`))return; const btn=$('reactivatePlayer'); btn.disabled=true; try{ await rpc('v2_reactivate_player',{organization_id:ctx.organization_id,player_id:drawerPlayer.id,reactivated_at:date}); setLifecycleMessage('Tanner reactivado correctamente.','success'); const {data:userData}=await supabase.auth.getUser(); await loadDashboard(userData.user); closePlayerDrawer(); }catch(e){setLifecycleMessage(friendlyError(e));}finally{btn.disabled=false;} }

async function signOut(){ await supabase.auth.signOut(); ctx=null; players=[]; moduleRows=[]; pendingPaymentKey=null; closePlayerDrawer(); switchAuthMode('signin'); showView('authView'); }
$('signInTab')?.addEventListener('click',()=>switchAuthMode('signin'));
$('signUpTab')?.addEventListener('click',()=>switchAuthMode('signup'));
$('authForm')?.addEventListener('submit',handleAuthSubmit);
$('resendConfirmation')?.addEventListener('click',resendConfirmation);
$('signOut')?.addEventListener('click',signOut);
$('pendingSignOut')?.addEventListener('click',signOut);
$('refreshAccess')?.addEventListener('click',loadAuthenticatedApp);
$('playerSearch')?.addEventListener('input',filterPlayers);
$('paymentForm')?.addEventListener('submit',postPayment);
$('closeDrawer')?.addEventListener('click',closePlayerDrawer);
$('drawerBackdrop')?.addEventListener('click',closePlayerDrawer);
$('withdrawPlayer')?.addEventListener('click',withdrawCurrentPlayer);
$('reactivatePlayer')?.addEventListener('click',reactivateCurrentPlayer);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('playerDrawer')?.classList.contains('hidden'))closePlayerDrawer();});

const {data:initial}=await supabase.auth.getSession();
if(initial?.session){ try{ await loadAuthenticatedApp(); }catch(e){ console.error(e); $('pendingText').textContent=friendlyError(e); showView('pendingView'); } } else { switchAuthMode('signin'); showView('authView'); }
