import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://pacnegivzgxpanphrnwp.supabase.co','sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);let ctx=null,orders=[],current=null,canWrite=false;const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'});
const labels={draft:'Borrador',pending_payment:'Pendiente pago',partial_payment:'Pago parcial',paid:'Pagado',in_production:'En producción',ready:'Listo',delivered:'Entregado',cancelled:'Cancelado',refunded:'Reembolsado'};
// Pago parcial y Pagado ya no se seleccionan a mano: los determina el backend según pagos registrados.
const transitions={draft:['pending_payment','cancelled'],pending_payment:['cancelled'],partial_payment:['cancelled','refunded'],paid:['in_production','ready','refunded'],in_production:['ready','refunded'],ready:['delivered','refunded'],delivered:['refunded'],cancelled:['cancelled'],refunded:['refunded']};
function show(id){['loadingView','deniedView','view'].forEach(v=>$(v)?.classList.toggle('hidden',v!==id));}
function msg(t='',type='error'){const e=$('statusMessage');e.textContent=t;e.dataset.type=type;e.classList.toggle('hidden',!t);}
function payMsg(t='',type='error'){const e=$('paymentMessage');e.textContent=t;e.dataset.type=type;e.classList.toggle('hidden',!t);}
async function rpc(n,p={}){const {data,error}=await supabase.rpc(n,p);if(error)throw error;return data;}
function fmt(v){return v?new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';}
function fmtDate(v){return v?new Intl.DateTimeFormat('es-MX',{dateStyle:'medium'}).format(new Date(`${v}T12:00:00`)):'—';}
function readinessText(r){const miss=Array.isArray(r?.missing)?r.missing:[];return r?.ok?'Listo para producción':miss.length?miss.join(' · '):'Pendiente de validar';}
async function boot(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/v2';return;}const rows=await rpc('v2_my_context');if(!rows?.length){$('deniedText').textContent='Sin organización.';show('deniedView');return;}ctx=rows[0];const mods=await rpc('v2_my_modules',{organization_id:ctx.organization_id});const mod=mods.find(m=>m.module_code==='commerce');if(!mod?.enabled||!mod?.can_read){$('deniedText').textContent='Tu rol no tiene acceso a Tienda/Pedidos.';show('deniedView');return;}canWrite=!!mod.can_write;$('orgName').textContent=ctx.organization_name;$('roleBadge').textContent=ctx.is_owner?'Propietario':ctx.role;await load();show('view');}
async function load(){orders=await rpc('v2_orders',{organization_id:ctx.organization_id,status_filter:$('statusFilter').value||null});render();renderKpis();}
function renderKpis(){$('kpiPending').textContent=orders.filter(o=>['pending_payment','partial_payment'].includes(o.status)).length;$('kpiPaid').textContent=orders.filter(o=>o.status==='paid').length;$('kpiProduction').textContent=orders.filter(o=>o.status==='in_production').length;$('kpiReady').textContent=orders.filter(o=>o.status==='ready').length;}
function render(){const list=$('orderList');list.innerHTML='';$('empty').classList.toggle('hidden',orders.length>0);orders.forEach(o=>{const b=document.createElement('button');b.type='button';b.className='order-row';b.innerHTML=`<div><strong>${o.folio}</strong><span>${o.customer_name} · ${fmt(o.created_at)}</span></div><div class="order-right"><b>${money.format(Number(o.total||0))}</b><span class="order-status ${o.status}">${labels[o.status]||o.status}</span></div>`;b.addEventListener('click',()=>openOrder(o));list.appendChild(b);});}
function renderPayments(d){const paid=Number(current?.paidAmount||0),balance=Number(current?.balance||0);$('orderPaid').textContent=money.format(paid);$('orderBalance').textContent=money.format(balance);const hist=$('paymentList');hist.innerHTML='';const rows=current?.payments||[];$('paymentEmpty').classList.toggle('hidden',rows.length>0);rows.forEach(p=>{const row=document.createElement('article');row.className='payment-row';row.innerHTML=`<div><strong>${money.format(Number(p.amount||0))}</strong><span>${fmtDate(p.paymentDate)} · ${p.method||'otro'}${p.reference?` · ${p.reference}`:''}</span></div><span class="payment-status ${p.status}">${p.status==='posted'?'Cobrado':p.status}</span>`;hist.appendChild(row);});const open=['pending_payment','partial_payment'].includes(d.status)&&balance>0;$('paymentForm').classList.toggle('hidden',!open||!canWrite);if(open){$('paymentAmount').value=balance.toFixed(2);$('paymentAmount').max=balance.toFixed(2);$('paymentDate').value=new Date().toISOString().slice(0,10);$('paymentPayer').value=d.customer_name||'';}payMsg();}
function renderReadiness(){const r=current?.readiness||{};const box=$('readinessBox');box.dataset.ready=r.ok?'true':'false';$('readinessTitle').textContent=r.ok?'Listo para producción':'Aún no está listo';$('readinessText').textContent=readinessText(r);$('readinessPayment').textContent=`Pago ${Number(r.paidPercent||0).toFixed(0)}% · requerido ${Number(r.effectivePaymentRequirementPercent||100).toFixed(0)}%`;}
function renderStateActions(d){const s=$('nextStatus');s.innerHTML='';const opts=transitions[d.status]||[];opts.forEach(v=>{const op=document.createElement('option');op.value=v;op.textContent=labels[v]||v;s.appendChild(op);});const hasAction=opts.some(v=>v!==d.status);$('statusActions').classList.toggle('hidden',!hasAction);$('saveStatus').disabled=!canWrite||!hasAction;}
async function openOrder(o){current=await rpc('v2_order_detail',{organization_id:ctx.organization_id,order_id:o.id});const d=current.order;$('orderFolio').textContent=d.folio;$('orderMeta').textContent=`${fmt(d.created_at)} · ${d.source||'interno'}`;$('orderTotal').textContent=money.format(Number(d.total||0));$('orderStatusLabel').textContent=labels[d.status]||d.status;$('customerName').textContent=d.customer_name||'Sin nombre';$('customerContact').textContent=[d.customer_phone,d.customer_email].filter(Boolean).join(' · ')||'Sin contacto';const items=$('itemList');items.innerHTML='';(current.items||[]).forEach(i=>{const a=i.attributes||{};const detail=[a.talla||a.size,a.nombrePers||a.personalizationName,a.numero||a.number].filter(Boolean).join(' · ');const row=document.createElement('article');row.className='item-row';row.innerHTML=`<div><strong>${i.description}</strong><span>${i.quantity} × ${money.format(Number(i.unitPrice||0))}${detail?` · ${detail}`:''}</span></div><b>${money.format(Number(i.quantity||0)*Number(i.unitPrice||0))}</b>`;items.appendChild(row);});renderPayments(d);renderReadiness();renderStateActions(d);msg();$('backdrop').classList.remove('hidden');$('drawer').classList.remove('hidden');}
function close(){current=null;$('backdrop').classList.add('hidden');$('drawer').classList.add('hidden');msg();payMsg();}
async function refreshCurrent(orderId){await load();const o=orders.find(x=>x.id===orderId);if(o)await openOrder(o);else close();}
async function postPayment(){if(!current||!canWrite)return;const d=current.order;const amount=Number($('paymentAmount').value||0),balance=Number(current.balance||0);if(!Number.isFinite(amount)||amount<=0){payMsg('Captura un monto mayor a cero.');return;}if(amount>balance+0.005){payMsg(`El pago excede el saldo de ${money.format(balance)}.`);return;}const btn=$('savePayment');btn.disabled=true;payMsg();try{await rpc('v2_post_order_payment',{organization_id:ctx.organization_id,order_id:d.id,amount,payment_date:$('paymentDate').value||new Date().toISOString().slice(0,10),method:$('paymentMethod').value||'other',reference:$('paymentReference').value.trim()||null,payer_name:$('paymentPayer').value.trim()||d.customer_name||null,idempotency_key:`order-${d.id}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`});await refreshCurrent(d.id);payMsg('Pago registrado y estado actualizado.','success');}catch(e){payMsg(e.message||'No se pudo registrar el pago.');}finally{btn.disabled=!canWrite;}}
async function saveStatus(){if(!current||!canWrite)return;const btn=$('saveStatus'),id=current.order.id;btn.disabled=true;try{await rpc('v2_update_order_status',{organization_id:ctx.organization_id,order_id:id,new_status:$('nextStatus').value});await refreshCurrent(id);msg('Estado actualizado.','success');}catch(e){msg(e.message||'No se pudo actualizar.');}finally{btn.disabled=!canWrite;}}
$('statusFilter').addEventListener('change',load);$('closeDrawer').addEventListener('click',close);$('backdrop').addEventListener('click',close);$('saveStatus').addEventListener('click',saveStatus);$('savePayment').addEventListener('click',postPayment);boot().catch(e=>{$('deniedText').textContent=e.message;show('deniedView');});