import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://pacnegivzgxpanphrnwp.supabase.co','sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);let ctx=null,orders=[],current=null,canWrite=false,metricsRun=0;const details=new Map();const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:2});const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={draft:'Borrador',pending_payment:'Pendiente pago',partial_payment:'Pago parcial',paid:'Pagado',in_production:'En producción',ready:'Listo',delivered:'Entregado',cancelled:'Cancelado',refunded:'Reembolsado'};
const payerLabels={guardian:'Familia / tutor',sponsor:'Patrocinador',player:'Jugador',organization:'Club',other:'Otro'};
const transitions={draft:['pending_payment','cancelled'],pending_payment:['cancelled'],partial_payment:['cancelled','refunded'],paid:['in_production','ready','refunded'],in_production:['ready','refunded'],ready:['delivered','refunded'],delivered:['refunded'],cancelled:['cancelled'],refunded:['refunded']};
function show(id){['loadingView','deniedView','view'].forEach(v=>$(v)?.classList.toggle('hidden',v!==id));}
function msg(t='',type='error'){const e=$('statusMessage');e.textContent=t;e.dataset.type=type;e.classList.toggle('hidden',!t);}function payMsg(t='',type='error'){const e=$('paymentMessage');e.textContent=t;e.dataset.type=type;e.classList.toggle('hidden',!t);}
async function rpc(n,p={}){const {data,error}=await supabase.rpc(n,p);if(error)throw error;return data;}function fmt(v){return v?new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';}function fmtDate(v){return v?new Intl.DateTimeFormat('es-MX',{dateStyle:'medium'}).format(new Date(`${v}T12:00:00`)):'—';}
function readinessText(r){const miss=Array.isArray(r?.missing)?r.missing:[];return r?.ok?'Listo para producción':miss.length?miss.join(' · '):'Pendiente de validar';}
function vigente(o){return !['cancelled','refunded'].includes(o.status);}
async function boot(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/v2';return;}const rows=await rpc('v2_my_context');if(!rows?.length){$('deniedText').textContent='Sin organización.';show('deniedView');return;}ctx=rows[0];const mods=await rpc('v2_my_modules',{organization_id:ctx.organization_id});const mod=mods.find(m=>m.module_code==='commerce');if(!mod?.enabled||!mod?.can_read){$('deniedText').textContent='Tu rol no tiene acceso a Tienda/Pedidos.';show('deniedView');return;}canWrite=!!mod.can_write;$('orgName').textContent=ctx.organization_name;$('roleBadge').textContent=ctx.is_owner?'Propietario':ctx.role;await load();show('view');}
async function load(){orders=await rpc('v2_orders',{organization_id:ctx.organization_id,status_filter:null})||[];render();renderKpis();loadBusinessMetrics();}
function filteredOrders(){const status=$('statusFilter').value,q=$('orderSearch').value.trim().toLocaleLowerCase('es-MX');return orders.filter(o=>(!status||o.status===status)&&(!q||`${o.folio||''} ${o.customer_name||''} ${o.customer_phone||''} ${o.customer_email||''}`.toLocaleLowerCase('es-MX').includes(q)));}
function renderKpis(){const rows=orders.filter(vigente);$('kpiOrders').textContent=rows.length;$('kpiPending').textContent=rows.filter(o=>['pending_payment','partial_payment'].includes(o.status)).length;$('kpiProduction').textContent=rows.filter(o=>o.status==='in_production').length;$('kpiReady').textContent=rows.filter(o=>o.status==='ready').length;}
function render(){const rows=filteredOrders(),list=$('orderList');list.innerHTML='';$('empty').classList.toggle('hidden',rows.length>0);rows.forEach(o=>{const d=details.get(o.id),balance=d?Number(d.balance||0):null,b=document.createElement('button');b.type='button';b.dataset.orderId=o.id;b.className='order-row';b.innerHTML=`<div><strong>${esc(o.folio)}</strong><span>${esc(o.customer_name)} · ${fmt(o.created_at)}</span><small>${Number(o.item_count||0)} pieza(s)${balance!=null&&balance>0?` · saldo ${money.format(balance)}`:''}</small></div><div class="order-right"><b>${money.format(Number(o.total||0))}</b><span class="order-status ${esc(o.status)}">${labels[o.status]||esc(o.status)}</span></div>`;b.addEventListener('click',()=>openOrder(o));list.appendChild(b);});}
async function fetchDetail(order){try{const d=await rpc('v2_order_detail',{organization_id:ctx.organization_id,order_id:order.id});details.set(order.id,d);return d;}catch{return null;}}
async function loadBusinessMetrics(){const run=++metricsRun,rows=orders.filter(vigente);$('metricsStatus').textContent='Calculando…';for(let i=0;i<rows.length;i+=8){const batch=rows.slice(i,i+8).filter(o=>!details.has(o.id));if(batch.length)await Promise.all(batch.map(fetchDetail));if(run!==metricsRun)return;}if(run!==metricsRun)return;renderBusinessMetrics(rows);render();}
function renderBusinessMetrics(rows){let sales=0,collected=0,receivable=0,cost=0,knownSales=0,profit=0,complete=0,resolved=0;rows.forEach(o=>{sales+=Number(o.total||0);const d=details.get(o.id);if(!d)return;resolved++;collected+=Number(d.paidAmount||0);receivable+=Math.max(0,Number(d.balance||0));if(d.costComplete){complete++;cost+=Number(d.costTotal||0);knownSales+=Number(d.order?.total??o.total??0);profit+=Number(d.grossProfitExpected||0);}});$('bizSales').textContent=money.format(sales);$('bizCollected').textContent=money.format(collected);$('bizReceivable').textContent=money.format(receivable);$('bizCost').textContent=complete?money.format(cost):'Pendiente';$('bizProfit').textContent=complete?money.format(profit):'Pendiente';$('bizProfit').dataset.state=profit<0?'negative':'normal';$('bizMargin').textContent=complete&&knownSales>0?`${(profit/knownSales*100).toFixed(0)}%`:'—';$('costCoverage').textContent=`${complete}/${rows.length} pedido(s) con costo completo`;const incomplete=rows.length-complete,failed=rows.length-resolved;$('metricsStatus').textContent=failed?'Lectura parcial':incomplete?`${incomplete} sin costo completo`:'Costos completos';$('metricsStatus').dataset.state=failed?'attention':incomplete?'attention':'ok';}
function renderProfitability(){const cost=current?.costComplete?Number(current.costTotal||0):null,profit=current?.costComplete?Number(current.grossProfitExpected||0):null;$('orderCost').textContent=cost==null?'Pendiente':money.format(cost);$('orderProfit').textContent=profit==null?'Pendiente':money.format(profit);$('orderProfit').dataset.state=profit!=null&&profit<0?'negative':'normal';}
function renderPayments(d){const paid=Number(current?.paidAmount||0),balance=Number(current?.balance||0);$('orderPaid').textContent=money.format(paid);$('orderBalance').textContent=money.format(balance);const hist=$('paymentList');hist.innerHTML='';const rows=current?.payments||[];$('paymentEmpty').classList.toggle('hidden',rows.length>0);rows.forEach(p=>{const who=[payerLabels[p.payerType]||p.payerType,p.payerName].filter(Boolean).join(' · ');const row=document.createElement('article');row.className='payment-row';row.innerHTML=`<div><strong>${money.format(Number(p.amount||0))}</strong><span>${fmtDate(p.paymentDate)} · ${esc(p.method||'otro')}${p.reference?` · ${esc(p.reference)}`:''}</span><small>${esc(who||'Pagador no especificado')}</small></div><span class="payment-status ${esc(p.status)}">${p.status==='posted'?'Cobrado':esc(p.status)}</span>`;hist.appendChild(row);});const open=['pending_payment','partial_payment'].includes(d.status)&&balance>0;$('paymentForm').classList.toggle('hidden',!open||!canWrite);if(open){$('paymentAmount').value=balance.toFixed(2);$('paymentAmount').max=balance.toFixed(2);$('paymentDate').value=new Date().toISOString().slice(0,10);$('paymentPayerType').value='guardian';$('paymentPayer').value=d.customer_name||'';}payMsg();}
function renderReadiness(){const r=current?.readiness||{},box=$('readinessBox');box.dataset.ready=r.ok?'true':'false';$('readinessTitle').textContent=r.ok?'Listo para producción':'Aún no está listo';$('readinessText').textContent=readinessText(r);$('readinessPayment').textContent=`Pago ${Number(r.paidPercent||0).toFixed(0)}% · requerido ${Number(r.effectivePaymentRequirementPercent||100).toFixed(0)}%`;}
function renderStateActions(d){const s=$('nextStatus');s.innerHTML='';const opts=transitions[d.status]||[];opts.forEach(v=>{const op=document.createElement('option');op.value=v;op.textContent=labels[v]||v;s.appendChild(op);});const hasAction=opts.some(v=>v!==d.status);$('statusActions').classList.toggle('hidden',!hasAction);$('saveStatus').disabled=!canWrite||!hasAction;}
function itemEditor(i,d){const a=i.attributes||{},editable=canWrite&&['draft','pending_payment','partial_payment','paid'].includes(d.status),bundle=a.bundleName?`<small class="bundle-tag">${esc(a.bundleName)} · ${esc(a.bundleTier||'')}</small>`:'',detail=[a.talla||a.size,a.nombrePers||a.personalizationName,a.numero||a.number].filter(Boolean).join(' · ');return `<article class="item-row ${editable?'editable':''}" data-item-id="${esc(i.id)}"><div class="item-summary"><div><strong>${esc(i.description)}</strong>${bundle}<span>${i.quantity} × ${money.format(Number(i.unitPrice||0))}${i.unitCost!=null?` · costo ${money.format(Number(i.unitCost))}`:''}${detail?` · ${esc(detail)}`:''}</span></div><b>${money.format(Number(i.quantity||0)*Number(i.unitPrice||0))}</b></div>${editable?`<div class="item-editor"><label>Talla / medida<input class="item-size" value="${esc(a.talla||a.size||'')}" maxlength="40"></label><label>Nombre<input class="item-name" value="${esc(a.nombrePers||a.personalizationName||'')}" maxlength="80" placeholder="Si aplica"></label><label>Número<input class="item-number" value="${esc(a.numero||a.number||'')}" maxlength="4" inputmode="numeric" placeholder="Si aplica"></label><label>Observación<input class="item-note" value="${esc(a.obs||'')}" maxlength="200"></label><button class="secondary save-item" type="button">Guardar pieza</button></div>`:''}</article>`;}
async function openOrder(o){current=await rpc('v2_order_detail',{organization_id:ctx.organization_id,order_id:o.id});details.set(o.id,current);const d=current.order;$('orderFolio').textContent=d.folio;$('orderMeta').textContent=`${fmt(d.created_at)} · ${d.source||'interno'}`;$('orderTotal').textContent=money.format(Number(d.total||0));$('orderStatusLabel').textContent=labels[d.status]||d.status;$('customerName').textContent=d.customer_name||'Sin nombre';$('customerContact').textContent=[d.customer_phone,d.customer_email].filter(Boolean).join(' · ')||'Sin contacto';const items=$('itemList');items.innerHTML=(current.items||[]).map(i=>itemEditor(i,d)).join('');items.querySelectorAll('.save-item').forEach(b=>b.addEventListener('click',()=>saveItem(b.closest('.item-row'))));renderProfitability();renderPayments(d);renderReadiness();renderStateActions(d);renderBusinessMetrics(orders.filter(vigente));render();msg();$('backdrop').classList.remove('hidden');$('drawer').classList.remove('hidden');}
function close(){current=null;$('backdrop').classList.add('hidden');$('drawer').classList.add('hidden');msg();payMsg();}async function refreshCurrent(orderId){details.delete(orderId);await load();const o=orders.find(x=>x.id===orderId);if(o)await openOrder(o);else close();}
async function saveItem(row){if(!current||!canWrite||!row)return;const orderId=current.order.id,btn=row.querySelector('.save-item');btn.disabled=true;try{await rpc('v2_update_order_item_fulfillment',{organization_id:ctx.organization_id,order_item_id:row.dataset.itemId,size:row.querySelector('.item-size').value.trim()||null,personalization_name:row.querySelector('.item-name').value.trim()||null,number:row.querySelector('.item-number').value.trim()||null,notes:row.querySelector('.item-note').value.trim()||null});await refreshCurrent(orderId);msg('Datos de pieza actualizados y readiness recalculado.','success');}catch(e){msg(e.message||'No se pudo actualizar la pieza.');btn.disabled=false;}}
async function postPayment(){if(!current||!canWrite)return;const d=current.order,amount=Number($('paymentAmount').value||0),balance=Number(current.balance||0),payerType=$('paymentPayerType').value,payerName=$('paymentPayer').value.trim();if(!Number.isFinite(amount)||amount<=0){payMsg('Captura un monto mayor a cero.');return;}if(amount>balance+0.005){payMsg(`El pago excede el saldo de ${money.format(balance)}.`);return;}if(payerType==='sponsor'&&!payerName){payMsg('Indica el nombre del patrocinador.');return;}const btn=$('savePayment');btn.disabled=true;payMsg();try{await rpc('v2_post_order_payment_attributed',{organization_id:ctx.organization_id,order_id:d.id,amount,payment_date:$('paymentDate').value||new Date().toISOString().slice(0,10),method:$('paymentMethod').value||'other',reference:$('paymentReference').value.trim()||null,payer_type:payerType,payer_name:payerName||d.customer_name||null,idempotency_key:`order-${d.id}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`});await refreshCurrent(d.id);payMsg('Pago registrado con pagador y estado actualizado.','success');}catch(e){payMsg(e.message||'No se pudo registrar el pago.');}finally{btn.disabled=!canWrite;}}
async function saveStatus(){if(!current||!canWrite)return;const btn=$('saveStatus'),id=current.order.id;btn.disabled=true;try{await rpc('v2_update_order_status',{organization_id:ctx.organization_id,order_id:id,new_status:$('nextStatus').value});await refreshCurrent(id);msg('Estado actualizado.','success');}catch(e){msg(e.message||'No se pudo actualizar.');}finally{btn.disabled=!canWrite;}}
$('paymentPayerType').addEventListener('change',()=>{if($('paymentPayerType').value==='guardian'&&current)$('paymentPayer').value=current.order.customer_name||'';});$('statusFilter').addEventListener('change',render);$('orderSearch').addEventListener('input',render);$('closeDrawer').addEventListener('click',close);$('backdrop').addEventListener('click',close);$('saveStatus').addEventListener('click',saveStatus);$('savePayment').addEventListener('click',postPayment);boot().catch(e=>{$('deniedText').textContent=e.message;show('deniedView');});