import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://pacnegivzgxpanphrnwp.supabase.co','sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',{auth:{persistSession:true,autoRefreshToken:true}});const $=id=>document.getElementById(id);let ctx=null,orders=[],current=null,canWrite=false;const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'});
const labels={draft:'Borrador',pending_payment:'Pendiente pago',partial_payment:'Pago parcial',paid:'Pagado',in_production:'En producción',ready:'Listo',delivered:'Entregado',cancelled:'Cancelado',refunded:'Reembolsado'};
const transitions={draft:['pending_payment','cancelled'],pending_payment:['partial_payment','paid','cancelled'],partial_payment:['paid','cancelled','refunded'],paid:['in_production','ready','refunded'],in_production:['ready','refunded'],ready:['delivered','refunded'],delivered:['refunded'],cancelled:['cancelled'],refunded:['refunded']};
function show(id){['loadingView','deniedView','view'].forEach(v=>$(v)?.classList.toggle('hidden',v!==id));}function msg(t='',type='error'){const e=$('statusMessage');e.textContent=t;e.dataset.type=type;e.classList.toggle('hidden',!t);}async function rpc(n,p={}){const {data,error}=await supabase.rpc(n,p);if(error)throw error;return data;}function fmt(v){return v?new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';}
async function boot(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/v2';return;}const rows=await rpc('v2_my_context');if(!rows?.length){$('deniedText').textContent='Sin organización.';show('deniedView');return;}ctx=rows[0];const mods=await rpc('v2_my_modules',{organization_id:ctx.organization_id});const mod=mods.find(m=>m.module_code==='commerce');if(!mod?.enabled||!mod?.can_read){$('deniedText').textContent='Tu rol no tiene acceso a Tienda/Pedidos.';show('deniedView');return;}canWrite=!!mod.can_write;$('orgName').textContent=ctx.organization_name;$('roleBadge').textContent=ctx.is_owner?'Propietario':ctx.role;await load();show('view');}
async function load(){orders=await rpc('v2_orders',{organization_id:ctx.organization_id,status_filter:$('statusFilter').value||null});render();renderKpis();}function renderKpis(){$('kpiPending').textContent=orders.filter(o=>o.status==='pending_payment').length;$('kpiPaid').textContent=orders.filter(o=>o.status==='paid').length;$('kpiProduction').textContent=orders.filter(o=>o.status==='in_production').length;$('kpiReady').textContent=orders.filter(o=>o.status==='ready').length;}
function render(){const list=$('orderList');list.innerHTML='';$('empty').classList.toggle('hidden',orders.length>0);orders.forEach(o=>{const b=document.createElement('button');b.type='button';b.className='order-row';b.innerHTML=`<div><strong>${o.folio}</strong><span>${o.customer_name} · ${fmt(o.created_at)}</span></div><div class="order-right"><b>${money.format(Number(o.total||0))}</b><span class="order-status ${o.status}">${labels[o.status]||o.status}</span></div>`;b.addEventListener('click',()=>openOrder(o));list.appendChild(b);});}
async function openOrder(o){current=await rpc('v2_order_detail',{organization_id:ctx.organization_id,order_id:o.id});const d=current.order;$('orderFolio').textContent=d.folio;$('orderMeta').textContent=`${fmt(d.created_at)} · ${d.source||'interno'}`;$('orderTotal').textContent=money.format(Number(d.total||0));$('orderStatusLabel').textContent=labels[d.status]||d.status;$('customerName').textContent=d.customer_name||'Sin nombre';$('customerContact').textContent=[d.customer_phone,d.customer_email].filter(Boolean).join(' · ')||'Sin contacto';const items=$('itemList');items.innerHTML='';(current.items||[]).forEach(i=>{const row=document.createElement('article');row.className='item-row';row.innerHTML=`<div><strong>${i.description}</strong><span>${i.quantity} × ${money.format(Number(i.unitPrice||0))}</span></div><b>${money.format(Number(i.quantity||0)*Number(i.unitPrice||0))}</b>`;items.appendChild(row);});const s=$('nextStatus');s.innerHTML='';(transitions[d.status]||[d.status]).forEach(v=>{const op=document.createElement('option');op.value=v;op.textContent=labels[v]||v;s.appendChild(op);});$('saveStatus').disabled=!canWrite;msg();$('backdrop').classList.remove('hidden');$('drawer').classList.remove('hidden');}
function close(){current=null;$('backdrop').classList.add('hidden');$('drawer').classList.add('hidden');msg();}async function saveStatus(){if(!current||!canWrite)return;const btn=$('saveStatus');btn.disabled=true;try{await rpc('v2_update_order_status',{organization_id:ctx.organization_id,order_id:current.order.id,new_status:$('nextStatus').value});msg('Estado actualizado.','success');await load();close();}catch(e){msg(e.message||'No se pudo actualizar.');}finally{btn.disabled=!canWrite;}}
$('statusFilter').addEventListener('change',load);$('closeDrawer').addEventListener('click',close);$('backdrop').addEventListener('click',close);$('saveStatus').addEventListener('click',saveStatus);boot().catch(e=>{$('deniedText').textContent=e.message;show('deniedView');});