import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://pacnegivzgxpanphrnwp.supabase.co','sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);let ctx=null,canWrite=false,calendarItems=[],players=[],items=[],filter='all',selectedDay='';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=v=>String(v).padStart(2,'0'),dayKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const nameOf=p=>[p.first_name,p.last_name].filter(Boolean).join(' ')||'Tanner';
const initials=p=>nameOf(p).split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
function show(id){['loadingView','deniedView','view'].forEach(v=>$(v)?.classList.toggle('hidden',v!==id));}
function msg(id,t='',type='error'){const e=$(id);if(!e)return;e.textContent=t;e.dataset.type=type;e.classList.toggle('hidden',!t);}
async function rpc(n,p={}){const {data,error}=await supabase.rpc(n,p);if(error)throw error;return data;}
function monthValue(d=new Date()){return `${d.getFullYear()}-${pad(d.getMonth()+1)}`;}
function monthBounds(){const [y,m]=$('month').value.split('-').map(Number);return {year:y,month:m,from:new Date(y,m-1,1),to:new Date(y,m,1)};}
function localIso(v){return v?new Date(v).toISOString():null;}
function friendly(e){const t=String(e?.message||e||'Error');const map={'Not authorized':'No tienes permiso para usar Calendario.','Event title required':'Escribe el título del evento.','Event date required':'Selecciona fecha y hora.','Invalid event type':'Tipo de evento inválido.','Invalid event status':'Estatus inválido.'};return map[t]||t;}
function birthdayDate(birth,year){const parts=String(birth||'').slice(0,10).split('-').map(Number);if(parts.length<3)return null;const d=new Date(year,parts[1]-1,parts[2],12);if(d.getMonth()!==parts[1]-1)d.setDate(0);return d;}
function birthdayItemsForMonth(){const {year,month}=monthBounds();return players.filter(p=>p.birth_date).map(p=>{const d=birthdayDate(p.birth_date,year);if(!d||d.getMonth()!==month-1)return null;const age=Math.max(0,year-Number(String(p.birth_date).slice(0,4)));return {id:`birthday-${p.id}-${year}`,source:'birthday',startsAt:d.toISOString(),allDay:true,title:`Cumpleaños de ${nameOf(p)}`,detail:`${p.category||'Tanner'} · Cumple ${age} años`,player:p};}).filter(Boolean);}
function nextBirthday(p){const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate());let next=birthdayDate(p.birth_date,now.getFullYear());if(next<today)next=birthdayDate(p.birth_date,now.getFullYear()+1);return {player:p,date:next,days:Math.round((next-today)/86400000)};}
async function boot(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/';return;}const rows=await rpc('v2_my_context');if(!rows?.length){$('deniedText').textContent='Tu cuenta no está vinculada a un club.';show('deniedView');return;}ctx=rows[0];const mods=await rpc('v2_my_modules',{organization_id:ctx.organization_id});const mod=mods.find(m=>m.module_code==='calendar');if(!mod?.enabled||!mod?.can_read){$('deniedText').textContent='Tu rol no tiene acceso al calendario.';show('deniedView');return;}canWrite=!!mod.can_write;$('orgName').textContent=ctx.organization_name||'Tannery City FC';$('roleBadge').textContent=ctx.is_owner?'Presidencia':ctx.role;$('eventPanel').classList.toggle('hidden',!canWrite);$('month').value=monthValue();players=await rpc('v2_players',{organization_id:ctx.organization_id,status_filter:'active'})||[];await load();show('view');}
async function load(){const {from,to}=monthBounds();calendarItems=await rpc('v2_calendar',{organization_id:ctx.organization_id,from_at:from.toISOString(),to_at:to.toISOString()});calendarItems=Array.isArray(calendarItems)?calendarItems:[];items=[...calendarItems,...birthdayItemsForMonth()].sort((a,b)=>new Date(a.startsAt)-new Date(b.startsAt));selectedDay='';render();}
function itemMeta(source){return ({session:{label:'Entrenamiento',icon:'tos-icon-ball'},match:{label:'Partido',icon:'tos-icon-trophy'},program:{label:'Programa',icon:'tos-icon-target'},event:{label:'Evento',icon:'tos-icon-pin'},birthday:{label:'Cumpleaños',icon:'tos-icon-cake'}})[source]||{label:'Actividad',icon:'tos-icon-calendar'};}
function visibleItems(){return items.filter(x=>(filter==='all'||x.source===filter||(filter==='event'&&x.source==='program'))&&(!selectedDay||dayKey(new Date(x.startsAt))===selectedDay));}
function render(){const {from}=monthBounds();$('monthTitle').textContent=from.toLocaleDateString('es-MX',{month:'long',year:'numeric'});renderSummary();renderSpotlight();renderMonthGrid();renderAgenda();}
function renderSummary(){const counts={birthday:0,session:0,match:0,event:0,program:0};items.forEach(x=>{if(x.source in counts)counts[x.source]++;});$('kpiBirthdays').textContent=counts.birthday;$('kpiSessions').textContent=counts.session;$('kpiMatches').textContent=counts.match;$('kpiEvents').textContent=counts.event+counts.program;}
function renderSpotlight(){const upcoming=players.filter(p=>p.birth_date).map(nextBirthday).sort((a,b)=>a.days-b.days).slice(0,6),today=upcoming.filter(x=>x.days===0),lead=today[0]||upcoming[0];$('birthdayLead').innerHTML=lead?`<div class="birthday-avatar">${esc(initials(lead.player))}</div><div><span>${lead.days===0?'Cumpleaños de hoy':lead.days===1?'Mañana':'Próximo cumpleaños'}</span><strong>${esc(nameOf(lead.player))}</strong><small>${esc(lead.player.category||'Tanner')}${lead.days>1?` · En ${lead.days} días`:''}</small></div>`:'<div><strong>Completa las fechas de nacimiento</strong><small>Así podremos avisarte a quién felicitar.</small></div>';$('birthdayActions').classList.toggle('hidden',!lead);if(lead){$('openPlayer').href=`/v2/jugadores/?player=${encodeURIComponent(lead.player.id)}`;$('copyGreeting').dataset.name=nameOf(lead.player);}$('upcomingBirthdays').innerHTML=upcoming.slice(today.length?1:0).map(x=>`<a href="/v2/jugadores/?player=${encodeURIComponent(x.player.id)}"><span class="mini-avatar">${esc(initials(x.player))}</span><span><strong>${esc(nameOf(x.player))}</strong><small>${x.days===0?'Hoy':x.days===1?'Mañana':x.date.toLocaleDateString('es-MX',{day:'numeric',month:'short'})}</small></span></a>`).join('');}
function renderMonthGrid(){const {year,month}=monthBounds(),first=new Date(year,month-1,1),days=new Date(year,month,0).getDate(),offset=(first.getDay()+6)%7,todayKey=dayKey(new Date()),box=$('monthGrid');box.innerHTML='';['L','M','M','J','V','S','D'].forEach(x=>{const h=document.createElement('span');h.className='weekday';h.textContent=x;box.appendChild(h);});for(let i=0;i<offset;i++){const blank=document.createElement('span');blank.className='day blank';box.appendChild(blank);}for(let n=1;n<=days;n++){const d=new Date(year,month-1,n),key=dayKey(d),dayItems=items.filter(x=>dayKey(new Date(x.startsAt))===key),button=document.createElement('button');button.type='button';button.className=`day${key===todayKey?' today':''}${key===selectedDay?' selected':''}`;button.setAttribute('aria-label',`${n} de ${first.toLocaleDateString('es-MX',{month:'long'})}, ${dayItems.length} actividades`);button.innerHTML=`<b>${n}</b><span class="day-dots">${[...new Set(dayItems.map(x=>x.source))].slice(0,4).map(s=>`<i class="dot-${esc(s)}"></i>`).join('')}</span>`;button.onclick=()=>{selectedDay=selectedDay===key?'':key;renderMonthGrid();renderAgenda();};box.appendChild(button);}}
function renderAgenda(){const rows=visibleItems(),box=$('agendaList');box.innerHTML='';$('empty').classList.toggle('hidden',rows.length>0);$('agendaTitle').textContent=selectedDay?new Date(`${selectedDay}T12:00:00`).toLocaleDateString('es-MX',{weekday:'long',day:'numeric',month:'long'}):'Agenda del mes';let last='';rows.forEach(x=>{const d=new Date(x.startsAt),key=d.toLocaleDateString('es-MX',{weekday:'long',day:'numeric',month:'short'});if(key!==last){const h=document.createElement('div');h.className='day-heading';h.textContent=key;box.appendChild(h);last=key;}const meta=itemMeta(x.source),row=document.createElement(x.player?'a':'article');row.className=`agenda-card source-${x.source}`;if(x.player)row.href=`/v2/jugadores/?player=${encodeURIComponent(x.player.id)}`;const when=x.allDay?'Todo el día':d.toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'});row.innerHTML=`<div class="agenda-icon"><span class="tos-icon ${meta.icon}" aria-hidden="true"></span></div><div class="agenda-main"><strong>${esc(x.title||'Actividad')}</strong><span>${esc(when)}${x.location?` · ${esc(x.location)}`:''}</span>${x.detail?`<small>${esc(x.detail)}</small>`:''}</div><span class="source-chip">${esc(meta.label)}</span>`;box.appendChild(row);});}
async function saveEvent(e){e.preventDefault();msg('eventMessage');const btn=$('saveEvent');btn.disabled=true;try{await rpc('v2_upsert_club_event',{organization_id:ctx.organization_id,event_id:null,title:$('eventTitle').value.trim(),starts_at:localIso($('eventDate').value),event_type:$('eventType').value,location:$('eventLocation').value.trim()||null,status:$('eventStatus').value,rival:$('eventRival').value.trim()||null,jersey:$('eventJersey').value.trim()||null,notes:$('eventNotes').value.trim()||null});e.target.reset();await load();msg('eventMessage','Evento guardado.','success');}catch(err){msg('eventMessage',friendly(err));}finally{btn.disabled=!canWrite;}}
function shiftMonth(delta){const [y,m]=$('month').value.split('-').map(Number);$('month').value=monthValue(new Date(y,m-1+delta,1));load();}
$('eventForm')?.addEventListener('submit',saveEvent);$('month')?.addEventListener('change',load);$('prevMonth')?.addEventListener('click',()=>shiftMonth(-1));$('nextMonth')?.addEventListener('click',()=>shiftMonth(1));$('todayButton')?.addEventListener('click',()=>{$('month').value=monthValue();load();});document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;selectedDay='';document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderMonthGrid();renderAgenda();}));$('copyGreeting')?.addEventListener('click',async e=>{const name=e.currentTarget.dataset.name||'Tanner',text=`Feliz cumpleaños, ${name}. Todo Tannery City te desea un gran día.`;await navigator.clipboard.writeText(text);e.currentTarget.textContent='Mensaje copiado';setTimeout(()=>e.currentTarget.textContent='Copiar felicitación',1800);});boot().catch(e=>{$('deniedText').textContent=friendly(e);show('deniedView');});
