import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://pacnegivzgxpanphrnwp.supabase.co','sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);let ctx=null,canWrite=false,items=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function show(id){['loadingView','deniedView','view'].forEach(v=>$(v)?.classList.toggle('hidden',v!==id));}
function msg(id,t='',type='error'){const e=$(id);if(!e)return;e.textContent=t;e.dataset.type=type;e.classList.toggle('hidden',!t);}
async function rpc(n,p={}){const {data,error}=await supabase.rpc(n,p);if(error)throw error;return data;}
function monthValue(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;}
function monthBounds(){const [y,m]=$('month').value.split('-').map(Number);return {from:new Date(y,m-1,1,0,0,0),to:new Date(y,m,1,0,0,0)};}
function localIso(v){return v?new Date(v).toISOString():null;}
function friendly(e){const t=String(e?.message||e||'Error');const map={'Not authorized':'No tienes permiso para usar Calendario.','Event title required':'Escribe el título del evento.','Event date required':'Selecciona fecha y hora.','Invalid event type':'Tipo de evento inválido.','Invalid event status':'Estatus inválido.'};return map[t]||t;}
async function boot(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/';return;}const rows=await rpc('v2_my_context');if(!rows?.length){$('deniedText').textContent='Sin organización.';show('deniedView');return;}ctx=rows[0];const mods=await rpc('v2_my_modules',{organization_id:ctx.organization_id});const mod=mods.find(m=>m.module_code==='calendar');if(!mod?.enabled||!mod?.can_read){$('deniedText').textContent='Tu rol no tiene acceso a Calendario.';show('deniedView');return;}canWrite=!!mod.can_write;$('orgName').textContent=ctx.organization_name||'Tannery City FC';$('roleBadge').textContent=ctx.is_owner?'Presidencia':ctx.role;$('eventPanel').classList.toggle('hidden',!canWrite);$('month').value=monthValue();await load();show('view');}
async function load(){const {from,to}=monthBounds();items=await rpc('v2_calendar',{organization_id:ctx.organization_id,from_at:from.toISOString(),to_at:to.toISOString()});items=Array.isArray(items)?items:[];render();}
function render(){const {from}=monthBounds();$('monthTitle').textContent=from.toLocaleDateString('es-MX',{month:'long',year:'numeric'});$('kpiSessions').textContent=items.filter(x=>x.source==='session').length;$('kpiMatches').textContent=items.filter(x=>x.source==='match').length;$('kpiPrograms').textContent=items.filter(x=>x.source==='program').length;$('kpiEvents').textContent=items.filter(x=>x.source==='event').length;const box=$('agendaList');box.innerHTML='';$('empty').classList.toggle('hidden',items.length>0);let last='';items.forEach(x=>{const d=new Date(x.startsAt),key=d.toLocaleDateString('es-MX',{weekday:'long',day:'numeric',month:'short'});if(key!==last){const h=document.createElement('div');h.className='day-heading';h.textContent=key;box.appendChild(h);last=key;}const row=document.createElement('article');row.className=`agenda-card source-${['session','match','program','event'].includes(x.source)?x.source:'event'}`;const when=x.allDay?'Todo el día':d.toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'}),icon=({session:'⚽',match:'🏆',program:'🎯',event:'📌'})[x.source]||'•',sourceLabel=({session:'Entrenamiento',match:'Partido',program:'Programa',event:'Evento'})[x.source]||'Actividad';row.innerHTML=`<div class="agenda-icon">${icon}</div><div class="agenda-main"><strong>${esc(x.title||'Actividad')}</strong><span>${esc(when)}${x.location?` · ${esc(x.location)}`:''}</span>${x.detail?`<small>${esc(x.detail)}</small>`:''}</div><span class="source-chip">${esc(sourceLabel)}</span>`;box.appendChild(row);});}
async function saveEvent(e){e.preventDefault();msg('eventMessage');const btn=$('saveEvent');btn.disabled=true;try{await rpc('v2_upsert_club_event',{organization_id:ctx.organization_id,event_id:null,title:$('eventTitle').value.trim(),starts_at:localIso($('eventDate').value),event_type:$('eventType').value,location:$('eventLocation').value.trim()||null,status:$('eventStatus').value,rival:$('eventRival').value.trim()||null,jersey:$('eventJersey').value.trim()||null,notes:$('eventNotes').value.trim()||null});e.target.reset();await load();msg('eventMessage','Evento guardado.','success');}catch(err){msg('eventMessage',friendly(err));}finally{btn.disabled=!canWrite;}}
function shiftMonth(delta){const [y,m]=$('month').value.split('-').map(Number);$('month').value=monthValue(new Date(y,m-1+delta,1));load();}
$('eventForm')?.addEventListener('submit',saveEvent);$('month')?.addEventListener('change',load);$('prevMonth')?.addEventListener('click',()=>shiftMonth(-1));$('nextMonth')?.addEventListener('click',()=>shiftMonth(1));boot().catch(e=>{$('deniedText').textContent=friendly(e);show('deniedView');});
