import {bootstrapProtectedShell,rpc,$,setShellHealth} from '/v2/shell.js';
const boot=await bootstrapProtectedShell({active:'admin',title:'Auditoría'});if(!boot)throw new Error('No access');
const org=boot.ctx.organization_id;let rows=[];
const escCsv=v=>`"${String(v??'').replace(/"/g,'""')}"`;
const fmt=v=>v?new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';
function fillSelect(id,values){const s=$(id),current=s.value;[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es-MX')).forEach(v=>{if([...s.options].some(o=>o.value===v))return;const o=document.createElement('option');o.value=v;o.textContent=v;s.appendChild(o);});s.value=current;}
function render(){const body=$('auditRows');body.innerHTML='';$('auditCount').textContent=`${rows.length} evento${rows.length===1?'':'s'}`;$('auditEmpty').classList.toggle('hidden',rows.length>0);rows.forEach(r=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${fmt(r.occurred_at)}</td><td><strong>${r.event_type||'—'}</strong></td><td>${r.aggregate_type||'—'}${r.aggregate_id?`<small>${r.aggregate_id}</small>`:''}</td><td>${r.actor_label||'Sistema'}</td><td>${r.actor_role||'—'}</td><td>${r.request_id||'—'}</td>`;body.appendChild(tr);});fillSelect('eventFilter',rows.map(r=>r.event_type));fillSelect('aggregateFilter',rows.map(r=>r.aggregate_type));setShellHealth({state:'ok',label:'Trazabilidad activa'});}
async function load(){const from=$('fromFilter').value?`${$('fromFilter').value}T00:00:00`:null,to=$('toFilter').value?`${$('toFilter').value}T23:59:59.999`:null;rows=await rpc('v2_audit_events',{organization_id:org,event_type_filter:$('eventFilter').value||null,aggregate_type_filter:$('aggregateFilter').value||null,from_at:from,to_at:to,result_limit:300});render();}
function exportCsv(){if(!rows.length)return;const header=['Fecha','Evento','Entidad','ID','Actor','Rol','Referencia'],lines=[header.map(escCsv).join(',')];rows.forEach(r=>lines.push([r.occurred_at,r.event_type,r.aggregate_type,r.aggregate_id,r.actor_label,r.actor_role,r.request_id].map(escCsv).join(',')));const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`tanneros-auditoria-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
$('refreshAudit').addEventListener('click',load);$('eventFilter').addEventListener('change',load);$('aggregateFilter').addEventListener('change',load);$('exportAudit').addEventListener('click',exportCsv);await load();