import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://pacnegivzgxpanphrnwp.supabase.co','sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);let ctx=null,canWrite=false,expenses=[];const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:2});
function show(id){['loadingView','deniedView','view'].forEach(v=>$(v)?.classList.toggle('hidden',v!==id));}
function msg(id,t='',type='error'){const e=$(id);if(!e)return;e.textContent=t;e.dataset.type=type;e.classList.toggle('hidden',!t);}
async function rpc(n,p={}){const {data,error}=await supabase.rpc(n,p);if(error)throw error;return data;}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function monthValue(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;}
function periodDate(){return `${$('period').value||monthValue()}-01`;}
function idem(){return globalThis.crypto?.randomUUID?`expense:${ctx.organization_id}:${crypto.randomUUID()}`:`expense:${ctx.organization_id}:${Date.now()}:${Math.random()}`;}
function friendly(e){const t=String(e?.message||e||'Error');const map={'Not authorized':'No tienes permiso para registrar este movimiento.','Expense amount must be greater than zero':'El monto debe ser mayor a cero.','Expense concept required':'Escribe el concepto del egreso.','Void reason required':'Escribe el motivo de anulación.','Expense not found':'No encontramos ese egreso.','Expense already void':'Ese egreso ya está anulado.'};return map[t]||t;}
async function boot(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/v2';return;}const rows=await rpc('v2_my_context');if(!rows?.length){$('deniedText').textContent='Sin organización.';show('deniedView');return;}ctx=rows[0];const mods=await rpc('v2_my_modules',{organization_id:ctx.organization_id});const mod=mods.find(m=>m.module_code==='accounting');if(!mod?.enabled||!mod?.can_read){$('deniedText').textContent='Tu rol no tiene acceso a Contabilidad.';show('deniedView');return;}canWrite=!!mod.can_write;$('orgName').textContent=ctx.organization_name||'Tannery City FC';$('roleBadge').textContent=ctx.is_owner?'Propietario':ctx.role;$('date').value=today();$('period').value=monthValue();$('saveExpense').disabled=!canWrite;await load();show('view');}
async function load(){expenses=await rpc('v2_expenses',{organization_id:ctx.organization_id,period:periodDate()});expenses=Array.isArray(expenses)?expenses:[];render();}
function render(){const posted=expenses.filter(x=>x.status==='posted'),voided=expenses.filter(x=>x.status==='void');const total=posted.reduce((s,x)=>s+Number(x.amount||0),0);const byCat={};posted.forEach(x=>byCat[x.category||'Sin categoría']=(byCat[x.category||'Sin categoría']||0)+Number(x.amount||0));const top=Object.entries(byCat).sort((a,b)=>b[1]-a[1])[0];$('kpiTotal').textContent=money.format(total);$('kpiCount').textContent=posted.length;$('kpiVoided').textContent=voided.length;$('kpiCategory').textContent=top?top[0]:'—';const box=$('expenseList');box.innerHTML='';$('empty').classList.toggle('hidden',expenses.length>0);expenses.forEach(x=>{const row=document.createElement('article');row.className=`expense-card ${x.status==='void'?'voided':''}`;row.innerHTML=`<div><div class="expense-title"><strong>${x.concept||x.category||'Egreso'}</strong><span class="status-chip">${x.status==='void'?'Anulado':'Publicado'}</span></div><span>${x.expense_date||''} · ${x.category||'Sin categoría'} · ${x.method||'Sin método'}</span>${x.reference?`<small>Ref: ${x.reference}</small>`:''}${x.status==='void'&&x.void_reason?`<small>Motivo: ${x.void_reason}</small>`:''}</div><div class="expense-side"><b>${money.format(Number(x.amount||0))}</b>${canWrite&&x.status==='posted'?`<button class="secondary mini void-expense" data-id="${x.id}" type="button">Anular</button>`:''}</div>`;box.appendChild(row);});box.querySelectorAll('.void-expense').forEach(b=>b.addEventListener('click',()=>voidExpense(b.dataset.id)));}
async function saveExpense(e){e.preventDefault();msg('expenseMessage');const amount=Number($('amount').value);if(!Number.isFinite(amount)||amount<=0){msg('expenseMessage','El monto debe ser mayor a cero.');return;}const btn=$('saveExpense');btn.disabled=true;try{await rpc('v2_post_expense',{organization_id:ctx.organization_id,amount,expense_date:$('date').value,category:$('category').value,method:$('method').value,reference:$('reference').value.trim()||null,concept:$('concept').value.trim(),metadata:{source:'v2_accounting_console'},idempotency_key:idem()});e.target.reset();$('date').value=today();$('category').value='Proveedor';$('method').value='Efectivo';await load();msg('expenseMessage','Egreso registrado.','success');}catch(err){msg('expenseMessage',friendly(err));}finally{btn.disabled=!canWrite;}}
async function voidExpense(id){const reason=prompt('Motivo de anulación:');if(reason===null)return;if(!reason.trim())return;try{await rpc('v2_void_expense',{organization_id:ctx.organization_id,expense_id:id,reason:reason.trim()});await load();}catch(err){alert(friendly(err));}}
$('expenseForm').addEventListener('submit',saveExpense);$('refresh').addEventListener('click',load);$('period').addEventListener('change',load);boot().catch(e=>{$('deniedText').textContent=friendly(e);show('deniedView');});