import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://pacnegivzgxpanphrnwp.supabase.co','sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);let ctx=null,canWrite=false,isPresidency=false,expenses=[],billingPlayers=[],receivables=[],adjustments=[];const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:2});const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function show(id){['loadingView','deniedView','view'].forEach(v=>$(v)?.classList.toggle('hidden',v!==id));}function msg(id,t='',type='error'){const e=$(id);if(!e)return;e.textContent=t;e.dataset.type=type;e.classList.toggle('hidden',!t);}async function rpc(n,p={}){const {data,error}=await supabase.rpc(n,p);if(error)throw error;return data;}function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}function monthValue(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;}function periodDate(){return `${$('period').value||monthValue()}-01`;}function idem(prefix='expense'){return globalThis.crypto?.randomUUID?`${prefix}:${ctx.organization_id}:${crypto.randomUUID()}`:`${prefix}:${ctx.organization_id}:${Date.now()}:${Math.random()}`;}
function friendly(e){const t=String(e?.message||e||'Error');const map={'Not authorized':'No tienes permiso para registrar este movimiento.','Expense amount must be greater than zero':'El monto debe ser mayor a cero.','Expense concept required':'Escribe el concepto del egreso.','Void reason required':'Escribe el motivo de anulación.','Only Presidencia can authorize debt adjustments':'Solo Presidencia puede autorizar un ajuste de deuda.','Accounting permission required':'Se requiere permiso de Contabilidad para aplicar el ajuste.','Adjustment exceeds outstanding balance':'El ajuste supera el saldo pendiente.','Authorized amount now exceeds outstanding balance':'El saldo cambió y ya es menor al monto autorizado.','Financial configuration requires Presidencia or Contabilidad':'Solo Presidencia o Contabilidad pueden configurar financiamiento.'};return map[t]||t;}
async function boot(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/v2';return;}const rows=await rpc('v2_my_context');if(!rows?.length){$('deniedText').textContent='Sin organización.';show('deniedView');return;}ctx=rows[0];const mods=await rpc('v2_my_modules',{organization_id:ctx.organization_id}),mod=mods.find(m=>m.module_code==='accounting');if(!mod?.enabled||!mod?.can_read){$('deniedText').textContent='Tu rol no tiene acceso a Contabilidad.';show('deniedView');return;}canWrite=!!mod.can_write;isPresidency=ctx.role==='Presidencia';$('orgName').textContent=ctx.organization_name||'Tannery City FC';$('roleBadge').textContent=ctx.is_owner?'Propietario':ctx.role;$('date').value=today();$('period').value=monthValue();$('fundingStart').value=today();$('saveExpense').disabled=!canWrite;$('saveFunding').disabled=!canWrite;$('authorizeAdjustment').classList.toggle('hidden',!isPresidency);await loadAll();show('view');}
async function loadAll(){const tasks=[rpc('v2_expenses',{organization_id:ctx.organization_id,period:periodDate()}),rpc('v2_billing_players',{organization_id:ctx.organization_id}),rpc('v2_open_receivables',{organization_id:ctx.organization_id}),rpc('v2_adjustment_authorizations',{organization_id:ctx.organization_id,status_filter:null})];const [e,p,r,a]=await Promise.all(tasks);expenses=Array.isArray(e)?e:[];billingPlayers=Array.isArray(p)?p:[];receivables=Array.isArray(r)?r:[];adjustments=Array.isArray(a)?a:[];renderAccountingOverview();renderExpenses();renderFunding();renderReceivables();renderAdjustments();}
async function loadExpenses(){expenses=await rpc('v2_expenses',{organization_id:ctx.organization_id,period:periodDate()})||[];renderExpenses();}
function renderExpenses(){const posted=expenses.filter(x=>x.status==='posted'),voided=expenses.filter(x=>x.status==='void'),total=posted.reduce((s,x)=>s+Number(x.amount||0),0),byCat={};posted.forEach(x=>byCat[x.category||'Sin categoría']=(byCat[x.category||'Sin categoría']||0)+Number(x.amount||0));const top=Object.entries(byCat).sort((a,b)=>b[1]-a[1])[0];$('kpiTotal').textContent=money.format(total);$('kpiCount').textContent=posted.length;$('kpiVoided').textContent=voided.length;$('kpiCategory').textContent=top?top[0]:'—';const box=$('expenseList');box.innerHTML='';$('empty').classList.toggle('hidden',expenses.length>0);expenses.forEach(x=>{const linked=x.metadata?.productionBatchId||x.production_batch_id;const row=document.createElement('article');row.className=`expense-card ${x.status==='void'?'voided':''}`;row.innerHTML=`<div><div class="expense-title"><strong>${esc(x.concept||x.category||'Egreso')}</strong><span class="status-chip">${x.status==='void'?'Anulado':'Publicado'}</span></div><span>${esc(x.expense_date||'')} · ${esc(x.category||'Sin categoría')} · ${esc(x.method||'Sin método')}</span>${x.reference?`<small>Ref: ${esc(x.reference)}</small>`:''}${linked?`<small>Ligado a corte de producción</small>`:''}${x.status==='void'&&x.void_reason?`<small>Motivo: ${esc(x.void_reason)}</small>`:''}</div><div class="expense-side"><b>${money.format(Number(x.amount||0))}</b>${canWrite&&x.status==='posted'?`<button class="secondary mini void-expense" data-id="${x.id}" type="button">Anular</button>`:''}</div>`;box.appendChild(row);});box.querySelectorAll('.void-expense').forEach(b=>b.addEventListener('click',()=>voidExpense(b.dataset.id)));}
function renderFunding(){const s=$('fundingPlayer'),selected=s.value;s.innerHTML='<option value="">Selecciona Tanner</option>';billingPlayers.forEach(p=>{const o=document.createElement('option');o.value=p.player_id;o.textContent=`${p.player_name} · ${money.format(Number(p.base_monthly_fee||0))}${p.sponsor_source?` · ${p.sponsor_source}`:''}`;s.appendChild(o);});if(selected&&billingPlayers.some(p=>p.player_id===selected))s.value=selected;const list=$('fundingList');list.innerHTML='';const rows=billingPlayers.filter(p=>p.sponsor_benefit_id);$('fundingEmpty').classList.toggle('hidden',rows.length>0);rows.forEach(p=>{const configured=!!p.sponsor_configured_at,unit=p.sponsor_mode==='percentage'?`${Number(p.sponsor_value||0)}%`:p.sponsor_value!=null?money.format(Number(p.sponsor_value)):'Sin definir';const card=document.createElement('button');card.type='button';card.className=`funding-card ${configured?'configured':'needs-config'}`;card.innerHTML=`<div><strong>${esc(p.player_name)}</strong><span>${esc(p.sponsor_source||'Patrocinador')} · ${configured?`cubre ${unit}`:'apoyo pendiente de configurar'}</span></div><b>${money.format(Number(p.base_monthly_fee||0))}</b>`;card.onclick=()=>{$('fundingPlayer').value=p.player_id;$('fundingPlayer').dispatchEvent(new Event('change',{bubbles:true}));};list.appendChild(card);});}
function fillFundingForm(){const p=billingPlayers.find(x=>x.player_id===$('fundingPlayer').value);if(!p)return;$('fundingMonthlyTotal').value=Number(p.base_monthly_fee||0).toFixed(2);$('fundingSource').value=p.sponsor_source||'Curtibrother';$('fundingMode').value=['fixed_amount','percentage'].includes(p.sponsor_mode)?p.sponsor_mode:'fixed_amount';$('fundingValue').value=p.sponsor_value==null?'':Number(p.sponsor_value);$('fundingStart').value=today();$('fundingEnd').value='';$('fundingNotes').value='';updateFundingHint();}
function updateFundingHint(){const total=Number($('fundingMonthlyTotal').value||0),value=Number($('fundingValue').value||0),mode=$('fundingMode').value,sponsor=mode==='percentage'?total*Math.min(100,Math.max(0,value))/100:value,family=Math.max(0,total-sponsor);$('fundingHint').textContent=`Patrocinador: ${money.format(Math.max(0,sponsor))} · Familia: ${money.format(family)} · Total: ${money.format(total)}`;}
async function saveFunding(e){e.preventDefault();msg('fundingMessage');const p=billingPlayers.find(x=>x.player_id===$('fundingPlayer').value);if(!p){msg('fundingMessage','Selecciona un Tanner.');return;}const total=Number($('fundingMonthlyTotal').value),value=Number($('fundingValue').value);if(!Number.isFinite(total)||total<0||!Number.isFinite(value)||value<0){msg('fundingMessage','Revisa total mensual y cobertura del patrocinador.');return;}const btn=$('saveFunding');btn.disabled=true;try{await rpc('v2_configure_sponsor_funding',{organization_id:ctx.organization_id,player_id:p.player_id,benefit_id:p.sponsor_benefit_id||null,funding_source_name:$('fundingSource').value.trim(),monthly_total:total,funding_mode:$('fundingMode').value,sponsor_value:value,starts_on:$('fundingStart').value||today(),ends_on:$('fundingEnd').value||null,notes:$('fundingNotes').value.trim()||null});billingPlayers=await rpc('v2_billing_players',{organization_id:ctx.organization_id})||[];renderFunding();$('fundingPlayer').value=p.player_id;fillFundingForm();msg('fundingMessage','Financiamiento configurado. Los próximos cargos separarán patrocinador y familia.','success');}catch(err){msg('fundingMessage',friendly(err));}finally{btn.disabled=!canWrite;}}
function renderReceivables(){const s=$('waiverCharge'),selected=s.value;s.innerHTML='<option value="">Selecciona cargo pendiente</option>';receivables.forEach(r=>{const o=document.createElement('option');o.value=r.charge_id;o.textContent=`${r.player_name||'Sin Tanner'} · ${r.concept} · saldo ${money.format(Number(r.balance_due||0))}${r.payer_type==='sponsor'?` · ${r.payer_name||'Patrocinador'}`:''}`;s.appendChild(o);});if(selected&&receivables.some(r=>r.charge_id===selected))s.value=selected;}
function fillAdjustment(){const r=receivables.find(x=>x.charge_id===$('waiverCharge').value);if(r){$('waiverAmount').value=Number(r.balance_due||0).toFixed(2);$('waiverBalance').textContent=`Saldo actual: ${money.format(Number(r.balance_due||0))}`;}else{$('waiverAmount').value='';$('waiverBalance').textContent='';}}
async function authorizeAdjustment(e){e.preventDefault();if(!isPresidency)return;msg('waiverMessage');const r=receivables.find(x=>x.charge_id===$('waiverCharge').value),amount=Number($('waiverAmount').value),reason=$('waiverReason').value.trim();if(!r||!Number.isFinite(amount)||amount<=0||!reason){msg('waiverMessage','Selecciona cargo, monto y escribe el motivo.');return;}const btn=$('authorizeAdjustment');btn.disabled=true;try{await rpc('v2_authorize_charge_adjustment',{organization_id:ctx.organization_id,charge_id:r.charge_id,adjustment_type:$('waiverType').value,amount,reason,idempotency_key:idem('adjustment-auth')});$('waiverReason').value='';await refreshFinancialQueues();msg('waiverMessage','Ajuste autorizado por Presidencia. Contabilidad ya puede aplicarlo.','success');}catch(err){msg('waiverMessage',friendly(err));}finally{btn.disabled=false;}}
async function refreshFinancialQueues(){[receivables,adjustments]=await Promise.all([rpc('v2_open_receivables',{organization_id:ctx.organization_id}),rpc('v2_adjustment_authorizations',{organization_id:ctx.organization_id,status_filter:null})]);renderReceivables();renderAdjustments();}
function renderAdjustments(){const box=$('waiverQueue');box.innerHTML='';$('waiverQueueEmpty').classList.toggle('hidden',adjustments.length>0);adjustments.forEach(a=>{const card=document.createElement('article');card.className=`waiver-card ${a.status}`;card.innerHTML=`<div><strong>${esc(a.player_name||'Sin Tanner')} · ${money.format(Number(a.amount||0))}</strong><span>${esc(a.charge_concept||'Cargo')} · ${esc(a.adjustment_type)} · ${esc(a.status)}</span><small>${esc(a.reason)} · autorizado ${new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(new Date(a.authorized_at))}</small></div><div class="waiver-actions"></div>`;const acts=card.querySelector('.waiver-actions');if(a.status==='approved'&&canWrite){const apply=document.createElement('button');apply.className='primary mini';apply.type='button';apply.textContent='Aplicar';apply.onclick=()=>postAdjustment(a.id);acts.appendChild(apply);}if(a.status==='approved'&&isPresidency){const revoke=document.createElement('button');revoke.className='secondary mini';revoke.type='button';revoke.textContent='Revocar';revoke.onclick=()=>revokeAdjustment(a.id);acts.appendChild(revoke);}box.appendChild(card);});}
async function postAdjustment(id){if(!confirm('¿Aplicar este ajuste autorizado? El cargo original se conserva.'))return;try{await rpc('v2_post_authorized_adjustment',{organization_id:ctx.organization_id,authorization_id:id});await refreshFinancialQueues();}catch(err){alert(friendly(err));}}
async function revokeAdjustment(id){const reason=prompt('Motivo de revocación:');if(!reason?.trim())return;try{await rpc('v2_revoke_charge_adjustment_authorization',{organization_id:ctx.organization_id,authorization_id:id,reason:reason.trim()});await refreshFinancialQueues();}catch(err){alert(friendly(err));}}
async function saveExpense(e){e.preventDefault();msg('expenseMessage');const amount=Number($('amount').value);if(!Number.isFinite(amount)||amount<=0){msg('expenseMessage','El monto debe ser mayor a cero.');return;}const btn=$('saveExpense');btn.disabled=true;try{await rpc('v2_post_expense',{organization_id:ctx.organization_id,amount,expense_date:$('date').value,category:$('category').value,method:$('method').value,reference:$('reference').value.trim()||null,concept:$('concept').value.trim(),metadata:{source:'v2_accounting_console'},idempotency_key:idem()});e.target.reset();$('date').value=today();$('category').value='Proveedor';$('method').value='Efectivo';await loadExpenses();msg('expenseMessage','Egreso registrado.','success');}catch(err){msg('expenseMessage',friendly(err));}finally{btn.disabled=!canWrite;}}
async function voidExpense(id){const reason=prompt('Motivo de anulación:');if(reason===null||!reason.trim())return;try{await rpc('v2_void_expense',{organization_id:ctx.organization_id,expense_id:id,reason:reason.trim()});await loadExpenses();}catch(err){alert(friendly(err));}}
$('expenseForm').addEventListener('submit',saveExpense);$('fundingForm').addEventListener('submit',saveFunding);$('fundingPlayer').addEventListener('change',fillFundingForm);['fundingMonthlyTotal','fundingMode','fundingValue'].forEach(id=>$(id).addEventListener('input',updateFundingHint));$('waiverForm').addEventListener('submit',authorizeAdjustment);$('waiverCharge').addEventListener('change',fillAdjustment);$('refresh').addEventListener('click',loadExpenses);$('period').addEventListener('change',loadExpenses);boot().catch(e=>{$('deniedText').textContent=friendly(e);show('deniedView');});

async function renderAccountingOverview(){
  const box=$('accountingOverview');if(!box)return;
  let ov;try{ov=await rpc('v2_accounting_overview',{p_organization_id:ctx.organization_id});}catch(e){return;}
  if(!ov)return;
  const m=v=>money.format(Number(v||0));
  const cb=ov.clubBalance||{},mo=ov.month||{},q=ov.quality||{},be=ov.breakEven||{};
  const rec=Number(q.recurrent||0),ext=Number(q.extraordinary||0),qt=rec+ext,recPct=qt?Math.round(rec/qt*100):0;
  const P=(title,inner,sub)=>`<section style="background:#fff;border:1px solid #e4ebe9;border-radius:18px;padding:18px;margin-bottom:14px"><div style="margin-bottom:12px"><strong style="font-size:16px;color:#0b1418">${title}</strong>${sub?`<div style="font-size:12px;color:#8a969b">${sub}</div>`:''}</div>${inner}</section>`;
  const card=(l,v,c)=>`<div style="flex:1;min-width:150px;background:#fff;border:1px solid #e4ebe9;border-radius:16px;padding:16px"><div style="font-size:11px;font-weight:800;text-transform:uppercase;letter-spacing:.04em;color:#68737a">${l}</div><div style="font-size:24px;font-weight:900;color:${c||'#0b1418'};margin-top:4px">${v}</div></div>`;
  const trend=ov.trend||[],maxT=Math.max(1,...trend.map(t=>Math.max(Number(t.income||0),Number(t.expense||0))));
  const trendBars=trend.map(t=>{const ih=Math.round(Number(t.income||0)/maxT*60),eh=Math.round(Number(t.expense||0)/maxT*60);return `<div style="flex:1;display:flex;flex-direction:column;align-items:center;gap:4px"><div style="display:flex;gap:2px;align-items:flex-end;height:62px"><div style="width:11px;height:${ih}px;background:#087d8e;border-radius:3px 3px 0 0"></div><div style="width:11px;height:${eh}px;background:#d9a441;border-radius:3px 3px 0 0"></div></div><span style="font-size:9px;color:#8a969b">${(t.month||'').slice(5)}</span></div>`;}).join('');
  const catList=(arr,c)=>`<div style="display:flex;flex-direction:column;gap:7px">${(arr||[]).slice(0,8).map(x=>`<div style="display:flex;justify-content:space-between;font-size:13.5px"><span style="color:#40595f">${esc(x.category)} <span style="color:#9aa4a8;font-size:11px">(${x.count})</span></span><b style="color:${c}">${m(x.amount)}</b></div>`).join('')||'<span style="color:#9aa4a8;font-size:13px">Sin movimientos este mes</span>'}</div>`;
  const pnl=ov.pnlBySource||[],pnlTot=pnl.reduce((s,x)=>s+Number(x.amount||0),0);
  const pnlRows=pnl.map(x=>{const pct=pnlTot?Math.round(Number(x.amount)/pnlTot*100):0;return `<div style="margin-bottom:9px"><div style="display:flex;justify-content:space-between;font-size:13px"><span>${esc(x.source)}</span><b style="color:#087d8e">${m(x.amount)} <span style="color:#9aa4a8;font-weight:600">${pct}%</span></b></div><div style="height:6px;background:#eef1ee;border-radius:3px;margin-top:3px"><div style="height:6px;width:${pct}%;background:#c6ac5c;border-radius:3px"></div></div></div>`;}).join('');
  const meth=(cb.byMethod||[]).map(x=>`<tr><td style="padding:8px 4px;font-weight:700">${esc(x.method)}</td><td style="padding:8px 4px;text-align:right;color:#159c4c">${m(x.in)}</td><td style="padding:8px 4px;text-align:right;color:#d23829">${Number(x.out)?m(x.out):'—'}</td><td style="padding:8px 4px;text-align:right;font-weight:800">${m(x.balance)}</td></tr>`).join('');
  box.innerHTML=
    P('Saldo del club',`<div style="font-size:30px;font-weight:900;color:#159c4c">${m(cb.total)}</div><div style="font-size:12px;color:#8a969b;margin-top:2px">Histórico · ${m(cb.income)} entradas − ${m(cb.expense)} salidas</div>`)
    +`<div style="display:flex;gap:10px;margin-bottom:14px;flex-wrap:wrap">${card('Ingresos del mes',m(mo.income),'#159c4c')}${card('Egresos del mes',m(mo.expense),'#d23829')}${card('Resultado del mes',m(mo.result),Number(mo.result)>=0?'#159c4c':'#d23829')}</div>`
    +P('Calidad del ingreso',`<div style="height:10px;border-radius:5px;overflow:hidden;background:#c6ac5c;display:flex;margin-bottom:10px"><div style="width:${recPct}%;background:#087d8e"></div></div><div style="display:flex;justify-content:space-between;font-size:13px;flex-wrap:wrap;gap:6px"><span><b style="color:#087d8e">Recurrente</b> ${m(rec)} (${recPct}%)</span><span><b style="color:#a9791b">Extraordinario</b> ${m(ext)} (${100-recPct}%)</span></div><p style="font-size:12px;color:#8a969b;margin:8px 0 0">Entre más alto el recurrente (mensualidades y academias), más estable el club.</p>`,'Recurrente vs extraordinario · este mes')
    +P('Punto de equilibrio',`<div style="display:flex;gap:14px;flex-wrap:wrap;align-items:center"><div><div style="font-size:11px;font-weight:800;text-transform:uppercase;color:#68737a">Costo fijo mensual</div><div style="font-size:22px;font-weight:900;color:#0b1418">${m(be.fixedMonthly)}</div></div><div style="font-size:20px;color:#cbd3d0">vs</div><div><div style="font-size:11px;font-weight:800;text-transform:uppercase;color:#68737a">Ingreso recurrente</div><div style="font-size:22px;font-weight:900;color:#087d8e">${m(be.recurrentMonth)}</div></div><div style="margin-left:auto;padding:8px 14px;border-radius:12px;font-weight:800;font-size:13px;background:${be.covered?'#e7f5ec':'#fdeceb'};color:${be.covered?'#159c4c':'#d23829'}">${be.covered?'Cubierto':'No cubierto'}</div></div><p style="font-size:12px;color:#8a969b;margin:10px 0 0">Necesitas ${m(be.fixedMonthly)} al mes en ingresos recurrentes para cubrir nómina, renta y servicios.</p>`,'¿Cubres tus costos fijos con lo recurrente?')
    +P('Tendencia · 6 meses',`<div style="display:flex;gap:6px;align-items:flex-end">${trendBars}</div><div style="display:flex;gap:16px;margin-top:8px;font-size:11px;color:#68737a"><span><i style="display:inline-block;width:9px;height:9px;background:#087d8e;border-radius:2px"></i> Ingresos</span><span><i style="display:inline-block;width:9px;height:9px;background:#d9a441;border-radius:2px"></i> Egresos</span></div>`)
    +`<div style="display:flex;gap:14px;flex-wrap:wrap"><div style="flex:1;min-width:250px">${P('Ingresos por categoría',catList(ov.incomeByCategory,'#159c4c'))}</div><div style="flex:1;min-width:250px">${P('Egresos por categoría',catList(ov.expenseByCategory,'#d23829'))}</div></div>`
    +P('Saldo por método',`<table style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr style="color:#8a969b;font-size:10px;text-transform:uppercase"><th style="text-align:left;padding:4px">Método</th><th style="text-align:right;padding:4px">Entró</th><th style="text-align:right;padding:4px">Salió</th><th style="text-align:right;padding:4px">Saldo</th></tr></thead><tbody>${meth}</tbody></table>`,'Histórico · todos los métodos')
    +P('P&L por fuente',pnlRows,'De dónde viene el dinero · histórico');
}
