import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const supabase=createClient('https://pacnegivzgxpanphrnwp.supabase.co','sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',{auth:{persistSession:true,autoRefreshToken:true}});
const PHOTO_BUCKET='tanneros-prospect-photos';
const $=id=>document.getElementById(id);
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0});
const shortDate=new Intl.DateTimeFormat('es-MX',{day:'numeric',month:'short'});
const longDate=new Intl.DateTimeFormat('es-MX',{day:'numeric',month:'short',year:'numeric'});
const statusLabels={draft:'Borrador',published:'Publicado',active:'Activo',completed:'Terminado',cancelled:'Cancelado',archived:'Archivado'};
const enrollmentLabels={registered:'Registrado',confirmed:'Confirmado',waitlisted:'Lista de espera',completed:'Completado',cancelled:'Cancelado'};
const paymentLabels={pending:'Pendiente',partial:'Parcial',paid:'Pagado',waived:'Sin costo',refunded:'Reembolsado'};
const attendanceLabels={present:'Presente',late:'Retardo',absent:'Ausente'};
const currentStatuses=new Set(['published','active']);
const closedStatuses=new Set(['completed','cancelled','archived']);
let ctx=null,programs=[],enrollments=[],attendance=[],payments=[];
let currentProgram=null,currentEnrollment=null,currentPaymentEnrollment=null;
let canWrite=false,canMoneyRead=false,canCollect=false,canSensitive=false;
let stage='current',participantFilter='all',wizardStep=1;
const photoUrls=new Map();

function show(id){['loadingView','deniedView','view'].forEach(v=>$(v)?.classList.toggle('hidden',v!==id));}
function safe(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function message(id,text='',type='error'){const e=$(id);if(!e)return;e.textContent=text;e.dataset.type=type;e.classList.toggle('hidden',!text);}
async function rpc(name,params={}){const {data,error}=await supabase.rpc(name,params);if(error)throw error;return data;}
function asNum(v){if(v==null||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null;}
function asInt(v){const n=asNum(v);return n==null?null:Math.trunc(n);}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function localDate(v){if(!v)return null;const d=new Date(`${String(v).slice(0,10)}T12:00:00`);return Number.isNaN(d.getTime())?null:d;}
function dateFmt(v,short=false){const d=localDate(v);return d?(short?shortDate:longDate).format(d):'—';}
function age(birth){const b=localDate(birth);if(!b)return null;const n=new Date();let a=n.getFullYear()-b.getFullYear();const m=n.getMonth()-b.getMonth();if(m<0||(m===0&&n.getDate()<b.getDate()))a--;return a;}
function slugify(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,120);}
function scheduleText(p){const s=p?.schedule;if(Array.isArray(s)){const first=s.find(Boolean);if(typeof first==='string')return first;if(first?.label)return first.label;}return '';}
function participantName(e){return [e?.firstName,e?.lastName].filter(Boolean).join(' ').trim()||'Participante';}
function activeEnrollments(programId){return enrollments.filter(e=>e.programId===programId&&!['cancelled'].includes(e.status));}
function attendanceFor(enrollmentId,date=$('attendanceDate')?.value||today()){return attendance.find(a=>a.enrollmentId===enrollmentId&&String(a.attendanceDate||'').slice(0,10)===date);}
function expectedFee(p){if(Number(p?.fee)>0)return Number(p.fee);if(Number(p?.feeWeekly)>0&&Number(p?.weeks)>0)return Number(p.feeWeekly)*Number(p.weeks);return 0;}
function publicUrl(p=currentProgram){return p?`${location.origin}/programas/?program=${encodeURIComponent(p.slug)}`:`${location.origin}/programas/`;}
function isPublic(p){return Boolean(p?.publicRegistrationEnabled)&&['published','active'].includes(p.status);}
function paymentDue(e){return ['pending','partial'].includes(e.paymentStatus);}
function nextProgram(){return programs.filter(p=>!closedStatuses.has(p.status)&&p.startsOn&&p.startsOn>=today()).sort((a,b)=>String(a.startsOn).localeCompare(String(b.startsOn)))[0]||null;}
function toast(text){let el=document.getElementById('programToast');if(!el){el=document.createElement('div');el.id='programToast';el.style.cssText='position:fixed;left:50%;bottom:24px;transform:translateX(-50%);z-index:220;background:#07191e;color:#fff;padding:11px 15px;border-radius:12px;font:800 12px Inter,system-ui;box-shadow:0 12px 32px rgba(0,0,0,.25)';document.body.appendChild(el);}el.textContent=text;el.classList.remove('hidden');clearTimeout(el._timer);el._timer=setTimeout(()=>el.classList.add('hidden'),2300);}
async function copyText(text,success='Link copiado'){try{await navigator.clipboard.writeText(text);toast(success);}catch{prompt('Copia el enlace:',text);}}

async function boot(){
  const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/';return;}
  const rows=await rpc('v2_my_context');if(!rows?.length){$('deniedText').textContent='Tu cuenta no está vinculada a una organización.';show('deniedView');return;}
  ctx=rows[0];const modules=await rpc('v2_my_modules',{organization_id:ctx.organization_id});const mod=modules.find(m=>m.module_code==='programs');
  if(!mod?.enabled||!mod?.can_read){$('deniedText').textContent='Tu rol no tiene acceso a Programas y Eventos.';show('deniedView');return;}
  canWrite=Boolean(mod.can_write);$('orgName').textContent=ctx.organization_name||'Tannery City FC';$('roleBadge').textContent=ctx.is_owner?'Presidencia':(ctx.role||'Miembro');$('newProgram').classList.toggle('hidden',!canWrite);
  $('attendanceDate').value=today();$('paymentDate').value=today();$('quickBirthDate').max=today();
  await load();show('view');
}

async function load(){
  const currentId=currentProgram?.id||null;const data=await rpc('v2_program_admin',{organization_id:ctx.organization_id});
  programs=Array.isArray(data?.programs)?data.programs:[];enrollments=Array.isArray(data?.enrollments)?data.enrollments:[];attendance=Array.isArray(data?.attendance)?data.attendance:[];payments=Array.isArray(data?.payments)?data.payments:[];
  const caps=data?.capabilities||{};canMoneyRead=Boolean(caps.canMoneyRead);canCollect=Boolean(caps.canCollect);canSensitive=Boolean(caps.canSensitive??canWrite);
  $('paymentsTabButton').classList.toggle('hidden',!canMoneyRead);renderDashboard();
  if(currentId){currentProgram=programs.find(p=>p.id===currentId)||null;if(currentProgram)renderOperation();}
}

function stageRows(value=stage){
  const t=today();return programs.filter(p=>{
    if(value==='all')return true;
    if(value==='draft')return p.status==='draft';
    if(value==='completed')return closedStatuses.has(p.status);
    if(value==='upcoming')return currentStatuses.has(p.status)&&p.startsOn&&p.startsOn>=t;
    return currentStatuses.has(p.status);
  });
}
function searchedRows(){const q=$('programSearch').value.trim().toLocaleLowerCase('es-MX');return stageRows().filter(p=>!q||[p.name,p.programType,p.categoryLabel,p.location,p.description].filter(Boolean).join(' ').toLocaleLowerCase('es-MX').includes(q));}
function renderDashboard(){renderKpis();renderStageCounts();renderPrograms();}
function renderKpis(){
  const active=programs.filter(p=>currentStatuses.has(p.status));const activeIds=new Set(active.map(p=>p.id));const people=enrollments.filter(e=>activeIds.has(e.programId)&&e.status!=='cancelled');const attention=people.filter(e=>e.status==='registered'||paymentDue(e));
  $('kpiCurrent').textContent=active.length;$('kpiEnrollments').textContent=people.length;$('kpiAttention').textContent=attention.length;
  $('kpiAttentionHint').textContent=attention.length?'pagos o confirmación':'operación al corriente';
  if(canMoneyRead){$('kpiFourthLabel').textContent='Ingresos de eventos';$('kpiFourth').textContent=money.format(active.reduce((sum,p)=>sum+Number(p.paidTotal||0),0));$('kpiFourthHint').textContent='cobros vinculados';}
  else{const next=nextProgram();$('kpiFourthLabel').textContent='Próximo evento';$('kpiFourth').textContent=next?dateFmt(next.startsOn,true):'—';$('kpiFourthHint').textContent=next?.name||'sin fecha programada';}
}
function renderStageCounts(){
  $('countCurrent').textContent=stageRows('current').length;$('countUpcoming').textContent=stageRows('upcoming').length;$('countDraft').textContent=stageRows('draft').length;$('countCompleted').textContent=stageRows('completed').length;$('countAll').textContent=programs.length;
}
function renderPrograms(){
  const rows=searchedRows(),box=$('programList');box.innerHTML='';$('empty').classList.toggle('hidden',rows.length>0);
  const titles={current:['EN OPERACIÓN','Lo que está pasando'],upcoming:['PRÓXIMOS','Lo que viene'],draft:['BORRADORES','Eventos por preparar'],completed:['HISTORIAL','Eventos terminados'],all:['TODOS','Programas y eventos']};[$('boardEyebrow').textContent,$('boardTitle').textContent]=titles[stage]||titles.current;
  rows.forEach(p=>{
    const people=activeEnrollments(p.id);const capacity=Number(p.capacity||0);const percent=capacity?Math.min(100,Math.round(people.length/capacity*100)):0;const due=Number(p.pendingPaymentCount??people.filter(paymentDue).length);const paidCount=Number(p.paidEnrollmentCount??people.filter(e=>['paid','waived'].includes(e.paymentStatus)).length);
    const card=document.createElement('article');card.className='program-card';card.innerHTML=`
      <div class="program-card-head"><div><span class="program-kind">${safe(p.programType||'Evento')}</span><h3>${safe(p.name)}</h3></div><span class="status-badge ${safe(p.status)}">${safe(statusLabels[p.status]||p.status)}</span></div>
      <div class="program-meta"><span><span class="tos-icon tos-icon-calendar" aria-hidden="true"></span>${safe(p.startsOn?dateFmt(p.startsOn):'Sin fecha')}</span><span><span class="tos-icon tos-icon-pin" aria-hidden="true"></span>${safe(p.location||'Sede por definir')}</span>${p.categoryLabel?`<span><span class="tos-icon tos-icon-ball" aria-hidden="true"></span>${safe(p.categoryLabel)}</span>`:''}</div>
      <div class="capacity-row"><div class="capacity-copy"><span>Cupo</span><strong>${people.length}${capacity?` / ${capacity}`:' · sin límite'}</strong></div><div class="progress-track"><i style="width:${capacity?percent:(people.length?100:0)}%"></i></div></div>
      <div class="program-numbers"><div class="program-number"><span>Registrados</span><strong>${people.length}</strong><small>${Number(p.confirmedCount||people.filter(e=>e.status==='confirmed').length)} confirmados</small></div><div class="program-number"><span>${canMoneyRead?'Pagados':'Listos'}</span><strong>${paidCount}</strong><small>${due} por cobrar</small></div><div class="program-number"><span>${canMoneyRead?'Ingreso':'Asistieron'}</span><strong>${canMoneyRead?money.format(Number(p.paidTotal||0)):Number(p.attendedCount||0)}</strong><small>${isPublic(p)?'<span class="public-indicator">link abierto</span>':'registro cerrado'}</small></div></div>
      <div class="program-card-actions"><button class="primary" data-open-program="${safe(p.id)}" type="button">Ver operación</button><button class="secondary mini" data-card-copy="${safe(p.id)}" type="button" ${isPublic(p)?'':'disabled'}>Copiar link</button></div>`;
    card.querySelector('[data-open-program]').addEventListener('click',()=>openProgram(p.id));card.querySelector('[data-card-copy]').addEventListener('click',()=>copyText(publicUrl(p)));box.appendChild(card);
  });
}

function openDrawer(){$('backdrop').classList.remove('hidden');$('drawer').classList.remove('hidden');$('drawer').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}
function closeDrawer(){currentProgram=null;$('backdrop').classList.add('hidden');$('drawer').classList.add('hidden');$('drawer').setAttribute('aria-hidden','true');document.body.style.overflow='';closeEnrollment();closeQuickParticipant();closePayment();message('programMessage');}
function setTab(name){
  if(name==='payments'&&!canMoneyRead)name='participants';
  document.querySelectorAll('.operation-pane').forEach(el=>el.classList.toggle('hidden',el.id!==`${name}Tab`));document.querySelectorAll('.operation-tab').forEach(el=>el.classList.toggle('active',el.dataset.tab===name));
  if(name==='participants')renderParticipants();if(name==='attendance')renderAttendance();if(name==='payments')renderPayments();if(name==='config')showWizardStep(wizardStep);
}
function openProgram(id){const p=programs.find(x=>x.id===id);if(!p)return;currentProgram=p;populateProgram(p);$('operationActions').classList.remove('hidden');$('operationTabs').classList.remove('hidden');$('editProgram').classList.toggle('hidden',!canWrite);$('addParticipant').classList.toggle('hidden',!canWrite);setTab('summary');renderOperation();openDrawer();}
function renderOperation(){
  const p=currentProgram;if(!p)return;$('drawerEyebrow').textContent=(p.programType||'EVENTO').toUpperCase();$('drawerTitle').textContent=p.name;$('drawerMeta').textContent=[p.startsOn?dateFmt(p.startsOn):null,p.location,p.categoryLabel].filter(Boolean).join(' · ')||'Configura la ficha del evento';$('drawerStatus').textContent=statusLabels[p.status]||p.status;$('drawerStatus').className=`status-badge ${p.status}`;$('drawerStatus').classList.remove('hidden');
  $('copyProgramLink').disabled=!isPublic(p);$('shareProgramWhatsapp').disabled=!isPublic(p);$('tabParticipantCount').textContent=activeEnrollments(p.id).length;renderSummary();renderParticipants();renderAttendance();if(canMoneyRead)renderPayments();loadVisiblePhotos();
}
function renderSummary(){
  const p=currentProgram,people=activeEnrollments(p.id),confirmed=people.filter(e=>e.status==='confirmed').length,due=people.filter(paymentDue).length,present=people.filter(e=>['present','late'].includes(attendanceFor(e.id)?.status)).length;const capacity=Number(p.capacity||0);
  const metrics=[['Participantes',people.length,capacity?`${Math.max(0,capacity-people.length)} lugares libres`:'sin límite'],['Confirmados',confirmed,`${people.filter(e=>e.status==='registered').length} por confirmar`],['Asistencia',present,`en ${dateFmt($('attendanceDate').value,true)}`],canMoneyRead?['Cobrado',money.format(Number(p.paidTotal||0)),due?`${due} pendientes`:'al corriente']:['Pago listo',people.filter(e=>['paid','waived'].includes(e.paymentStatus)).length,due?`${due} pendientes`:'al corriente']];
  $('operationMetrics').innerHTML=metrics.map(([label,value,hint])=>`<article class="operation-metric"><span>${safe(label)}</span><strong>${safe(value)}</strong><small>${safe(hint)}</small></article>`).join('');
  const facts=[['Fecha',p.startsOn?`${dateFmt(p.startsOn)}${p.endsOn&&p.endsOn!==p.startsOn?` – ${dateFmt(p.endsOn)}`:''}`:'Por definir'],['Horario',scheduleText(p)||'Por definir'],['Lugar',p.location||'Por definir'],['Categoría',p.categoryLabel||'Abierta'],['Edades',p.ageMin!=null||p.ageMax!=null?`${p.ageMin??'—'} a ${p.ageMax??'—'} años`:'Sin restricción'],['Cuota',expectedFee(p)?money.format(expectedFee(p)):'Gratuito']];$('programFacts').innerHTML=facts.map(([k,v])=>`<div class="fact-item"><span>${safe(k)}</span><strong>${safe(v)}</strong></div>`).join('');
  let title='Prepara el registro',text='Publica el evento y comparte su enlace para comenzar a recibir participantes.',buttons=`<button class="primary mini" data-summary-action="config" type="button">Terminar configuración</button>`;
  if(isPublic(p)&&!people.length){title='Comparte el evento';text='El registro está abierto. Copia el link y envíalo a las familias o a tu campaña.';buttons='<button class="primary mini" data-summary-action="copy" type="button">Copiar link</button><button class="secondary mini" data-summary-action="share" type="button">WhatsApp</button>';}
  if(people.length&&new Date(`${p.startsOn||today()}T23:59:59`)>=new Date()){title=due?'Confirma registros y pagos':'Prepara el check-in';text=due?`${due} participante${due===1?'':'s'} todavía requiere${due===1?'':'n'} atención de cobro.`:'La lista está lista. El día del evento pasa asistencia desde el teléfono.';buttons=`<button class="primary mini" data-summary-action="${due&&canMoneyRead?'payments':'attendance'}" type="button">${due&&canMoneyRead?'Revisar pagos':'Pasar asistencia'}</button>`;}
  if(closedStatuses.has(p.status)){title='Consulta el historial';text='El evento está cerrado. Conservamos participantes, pagos y asistencia para trazabilidad.';buttons='<button class="secondary mini" data-summary-action="participants" type="button">Ver participantes</button>';}
  $('nextActionTitle').textContent=title;$('nextActionText').textContent=text;$('nextActionButtons').innerHTML=buttons;$('nextActionButtons').querySelectorAll('[data-summary-action]').forEach(b=>b.addEventListener('click',()=>handleSummaryAction(b.dataset.summaryAction)));
  const att=people.filter(e=>e.status==='registered'||paymentDue(e)).slice(0,5);$('attentionList').innerHTML=att.length?att.map(e=>`<button class="attention-row" data-attention-id="${safe(e.id)}" type="button"><div><strong>${safe(participantName(e))}</strong><small>${safe(e.status==='registered'?'Falta confirmar':`Pago ${paymentLabels[e.paymentStatus]||'pendiente'}`)}</small></div><span>Revisar</span></button>`).join(''):'<div class="attention-empty">No hay pendientes operativos en este evento.</div>';$('attentionList').querySelectorAll('[data-attention-id]').forEach(b=>b.addEventListener('click',()=>openEnrollment(b.dataset.attentionId)));
}
function handleSummaryAction(action){if(action==='copy')return copyText(publicUrl());if(action==='share')return shareWhatsapp();if(action==='config'){wizardStep=1;return setTab('config');}setTab(action);}

function participantRows(){
  if(!currentProgram)return[];const q=$('participantSearch').value.trim().toLocaleLowerCase('es-MX');return activeEnrollments(currentProgram.id).filter(e=>{
    if(q&&!`${participantName(e)} ${e.phone||''}`.toLocaleLowerCase('es-MX').includes(q))return false;const att=attendanceFor(e.id);
    if(participantFilter==='attention')return e.status==='registered'||paymentDue(e);if(participantFilter==='paid')return ['paid','waived'].includes(e.paymentStatus);if(participantFilter==='present')return ['present','late'].includes(att?.status);return true;
  });
}
function avatarHtml(e){const initials=participantName(e).split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();const path=e.metadata?.photoPath;return `<div class="participant-avatar">${path&&canSensitive?`<img data-photo-path="${safe(path)}" alt="Foto de ${safe(participantName(e))}">`:safe(initials)}</div>`;}
function renderParticipants(){
  if(!currentProgram)return;const rows=participantRows(),box=$('enrollmentList');box.innerHTML='';$('enrollmentEmpty').classList.toggle('hidden',rows.length>0);rows.forEach(e=>{const a=age(e.birthDate),att=attendanceFor(e.id),paymentClass=['paid','waived'].includes(e.paymentStatus)?'paid':paymentDue(e)?'due':'';const row=document.createElement('button');row.type='button';row.className='enrollment-row';row.innerHTML=`${avatarHtml(e)}<div class="participant-main"><strong>${safe(participantName(e))}</strong><span>${safe([a!=null?`${a} años`:null,e.metadata?.position,e.metadata?.bibNumber?`#${e.metadata.bibNumber}`:null].filter(Boolean).join(' · ')||'Perfil por completar')}</span><small>${safe(e.phone||e.email||'Sin contacto')}</small></div><div class="participant-state"><span>${safe(enrollmentLabels[e.status]||e.status)}</span><span class="${paymentClass}">${safe(att?attendanceLabels[att.status]:(paymentLabels[e.paymentStatus]||e.paymentStatus))}</span></div>`;row.addEventListener('click',()=>openEnrollment(e.id));box.appendChild(row);});loadVisiblePhotos();
}
async function signedPhoto(path){if(photoUrls.has(path))return photoUrls.get(path);const {data,error}=await supabase.storage.from(PHOTO_BUCKET).createSignedUrl(path,900);if(error)throw error;photoUrls.set(path,data.signedUrl);return data.signedUrl;}
async function loadVisiblePhotos(){document.querySelectorAll('img[data-photo-path]:not([data-loaded])').forEach(async img=>{img.dataset.loaded='1';try{img.src=await signedPhoto(img.dataset.photoPath);}catch{img.remove();}});}
function openEnrollment(id){
  const e=enrollments.find(x=>x.id===id);if(!e)return;currentEnrollment=e;const meta=e.metadata||{},a=age(e.birthDate),att=attendanceFor(e.id);$('enrollmentName').textContent=participantName(e);$('enrollmentSubtitle').textContent=[enrollmentLabels[e.status]||e.status,att?attendanceLabels[att.status]:null].filter(Boolean).join(' · ');$('enrollmentStatus').value=e.status;$('enrollmentNote').value='';$('enrollmentStatus').disabled=!canWrite;$('enrollmentNote').disabled=!canWrite;$('saveEnrollment').classList.toggle('hidden',!canWrite);
  const photo=meta.photoPath&&canSensitive?`<img data-photo-path="${safe(meta.photoPath)}" alt="Foto de ${safe(participantName(e))}">`:'<span class="tos-icon tos-icon-user" aria-hidden="true"></span>';
  const profile=[['Nacimiento',e.birthDate?dateFmt(e.birthDate):'—'],['Edad',a==null?'—':`${a} años`],['Posición',meta.position||'—'],['Pierna',meta.dominantFoot||'—'],['Residencia',meta.residence||'—'],['Equipo actual',meta.currentTeam||'—']];$('enrollmentProfile').innerHTML=`<div class="profile-hero"><div class="profile-photo">${photo}</div><div class="profile-copy">${profile.map(([k,v])=>`<div><span>${safe(k)}</span><strong>${safe(v)}</strong></div>`).join('')}</div></div>`;
  const facts=[['Tutor',meta.guardianName],['WhatsApp',e.phone],['Correo',e.email],['Emergencia',meta.emergencyContact],['Tel. emergencia',meta.emergencyPhone],['Información médica',meta.medicalSummary],['Experiencia',meta.experience],['Registro',e.createdAt?new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(new Date(e.createdAt)):null],canMoneyRead?['Pagado',money.format(Number(e.paidAmount||0))]:null,canMoneyRead?['Saldo',money.format(Number(e.balance||0))]:null].filter(Boolean).filter(([,v])=>v!=null&&String(v).trim()!=='');$('enrollmentFacts').innerHTML=facts.map(([k,v])=>`<div><span>${safe(k)}</span><strong>${safe(v)}</strong></div>`).join('');
  const digits=String(e.phone||'').replace(/\D/g,'');$('enrollmentWhatsapp').classList.toggle('hidden',!digits);$('enrollmentWhatsapp').href=digits?`https://wa.me/${digits}?text=${encodeURIComponent(`Hola, te escribimos de Tannery City sobre ${currentProgram.name}.`)}`:'#';message('enrollmentMessage');$('enrollmentBackdrop').classList.remove('hidden');$('enrollmentModal').classList.remove('hidden');$('enrollmentModal').setAttribute('aria-hidden','false');loadVisiblePhotos();
}
function closeEnrollment(){currentEnrollment=null;$('enrollmentBackdrop').classList.add('hidden');$('enrollmentModal').classList.add('hidden');$('enrollmentModal').setAttribute('aria-hidden','true');message('enrollmentMessage');}
async function saveEnrollment(){if(!currentEnrollment||!canWrite)return;const btn=$('saveEnrollment');btn.disabled=true;try{await rpc('v2_update_program_enrollment_status',{organization_id:ctx.organization_id,enrollment_id:currentEnrollment.id,status:$('enrollmentStatus').value,notes:$('enrollmentNote').value.trim()||null});await load();closeEnrollment();toast('Participante actualizado');}catch(e){message('enrollmentMessage',e.message||'No se pudo actualizar.');}finally{btn.disabled=false;}}

function renderAttendance(){
  if(!currentProgram)return;const rows=activeEnrollments(currentProgram.id),date=$('attendanceDate').value||today(),box=$('attendanceList');box.innerHTML='';$('attendanceEmpty').classList.toggle('hidden',rows.length>0);const present=rows.filter(e=>['present','late'].includes(attendanceFor(e.id,date)?.status)).length;$('attendanceProgress').textContent=`${present} de ${rows.length} presentes`;$('attendanceProgressBar').style.width=rows.length?`${Math.round(present/rows.length*100)}%`:'0%';
  rows.forEach(e=>{const att=attendanceFor(e.id,date),row=document.createElement('article');row.className='attendance-row';row.innerHTML=`<div class="attendance-person"><strong>${safe(participantName(e))}</strong><span>${safe([e.metadata?.bibNumber?`#${e.metadata.bibNumber}`:null,e.metadata?.position,e.paymentStatus&&paymentLabels[e.paymentStatus]].filter(Boolean).join(' · '))}</span></div><div class="attendance-actions">${[['present','Presente'],['late','Retardo'],['absent','Ausente']].map(([v,l])=>`<button class="attendance-mark ${att?.status===v?'active':''}" data-status="${v}" data-enrollment="${safe(e.id)}" type="button" ${canWrite?'':'disabled'}>${l}</button>`).join('')}</div>`;row.querySelectorAll('.attendance-mark').forEach(b=>b.addEventListener('click',()=>markAttendance(e.id,b.dataset.status===att?.status?null:b.dataset.status)));box.appendChild(row);});
}
async function markAttendance(enrollmentId,status){if(!canWrite)return;try{await rpc('v2_mark_program_attendance',{organization_id:ctx.organization_id,enrollment_id:enrollmentId,attendance_date:$('attendanceDate').value||today(),status,bib_number:null,notes:null});await load();renderAttendance();toast(status?attendanceLabels[status]:'Marca retirada');}catch(e){toast(e.message||'No se pudo registrar la asistencia');}}

function renderPayments(){
  if(!currentProgram||!canMoneyRead)return;const p=currentProgram,rows=activeEnrollments(p.id),box=$('paymentList');const expected=rows.reduce((s,e)=>s+Number(e.expectedAmount??expectedFee(p)),0),paid=Number(p.paidTotal||rows.reduce((s,e)=>s+Number(e.paidAmount||0),0)),pending=Math.max(0,Number(p.pendingTotal??(expected-paid)));$('paymentsSummary').innerHTML=`<article><span>Esperado</span><strong>${money.format(expected)}</strong></article><article><span>Cobrado</span><strong>${money.format(paid)}</strong></article><article><span>Pendiente</span><strong>${money.format(pending)}</strong></article>`;box.innerHTML='';$('paymentEmpty').classList.toggle('hidden',rows.length>0);
  rows.forEach(e=>{const balance=Number(e.balance||0),paidAmount=Number(e.paidAmount||0),row=document.createElement('article');row.className='payment-row';row.innerHTML=`<div class="participant-main"><strong>${safe(participantName(e))}</strong><span>${safe(paymentLabels[e.paymentStatus]||e.paymentStatus)}</span></div><div class="payment-amounts"><strong>${money.format(paidAmount)} pagado</strong><small>${money.format(balance)} pendiente</small></div>${canCollect&&balance>0?`<button class="collect-button" data-collect="${safe(e.id)}" type="button">Cobrar</button>`:`<span class="payment-status-only ${safe(e.paymentStatus)}">${safe(paymentLabels[e.paymentStatus]||e.paymentStatus)}</span>`}`;row.querySelector('[data-collect]')?.addEventListener('click',()=>openPayment(e.id));box.appendChild(row);});
}
function openPayment(id){const e=enrollments.find(x=>x.id===id);if(!e||!canCollect)return;currentPaymentEnrollment=e;$('paymentParticipantName').textContent=participantName(e);$('paymentBalance').textContent=`Saldo pendiente: ${money.format(Number(e.balance||0))}`;$('paymentAmount').value=Number(e.balance||0)>0?Number(e.balance):'';$('paymentDate').value=today();$('paymentReference').value='';message('paymentMessage');$('paymentBackdrop').classList.remove('hidden');$('paymentModal').classList.remove('hidden');$('paymentModal').setAttribute('aria-hidden','false');}
function closePayment(){currentPaymentEnrollment=null;$('paymentBackdrop').classList.add('hidden');$('paymentModal').classList.add('hidden');$('paymentModal').setAttribute('aria-hidden','true');message('paymentMessage');}
async function savePayment(e){e.preventDefault();if(!currentPaymentEnrollment||!canCollect)return;const btn=$('savePayment');btn.disabled=true;try{await rpc('v2_post_program_payment',{organization_id:ctx.organization_id,enrollment_id:currentPaymentEnrollment.id,amount:asNum($('paymentAmount').value),payment_date:$('paymentDate').value,method:$('paymentMethod').value,reference:$('paymentReference').value.trim()||null,idempotency_key:crypto.randomUUID()});await load();closePayment();setTab('payments');toast('Pago registrado y vinculado');}catch(err){message('paymentMessage',err.message||'No se pudo registrar el pago.');}finally{btn.disabled=false;}}

function openQuickParticipant(){if(!currentProgram||!canWrite)return;$('quickParticipantForm').reset();$('quickBirthDate').max=today();message('quickParticipantMessage');$('quickParticipantBackdrop').classList.remove('hidden');$('quickParticipantModal').classList.remove('hidden');$('quickParticipantModal').setAttribute('aria-hidden','false');setTimeout(()=>$('quickFirstName').focus(),40);}
function closeQuickParticipant(){$('quickParticipantBackdrop').classList.add('hidden');$('quickParticipantModal').classList.add('hidden');$('quickParticipantModal').setAttribute('aria-hidden','true');message('quickParticipantMessage');}
async function saveQuickParticipant(e){e.preventDefault();if(!currentProgram||!canWrite)return;const btn=$('saveQuickParticipant');btn.disabled=true;try{const first=$('quickFirstName').value.trim();if(first.length<2)throw new Error('Escribe el nombre del participante.');await rpc('v2_create_program_enrollment',{organization_id:ctx.organization_id,program_id:currentProgram.id,first_name:first,last_name:$('quickLastName').value.trim()||null,phone:$('quickPhone').value.trim()||null,birth_date:$('quickBirthDate').value||null,metadata:{position:$('quickPosition').value.trim()||null,bibNumber:$('quickBib').value.trim()||null,source:'staff_walk_in'}});await load();closeQuickParticipant();setTab('participants');toast('Participante agregado');}catch(err){message('quickParticipantMessage',err.message||'No se pudo agregar.');}finally{btn.disabled=false;}}

function clearProgram(){
  currentProgram=null;['programName','programSlug','categoryLabel','programLocation','startsOn','endsOn','ageMin','ageMax','capacity','fee','feeWeekly','weeks','scheduleLabel','programDescription'].forEach(id=>$(id).value='');$('programType').value='Visoría';$('paymentMode').value='free';$('programStatus').value='draft';$('publicEnabled').checked=false;wizardStep=1;selectType('Visoría');selectPaymentMode('free');$('drawerEyebrow').textContent='NUEVO EVENTO';$('drawerTitle').textContent='Crear programa o evento';$('drawerMeta').textContent='Cuatro decisiones para dejarlo listo';$('drawerStatus').classList.add('hidden');$('operationActions').classList.add('hidden');$('operationTabs').classList.add('hidden');document.querySelectorAll('.operation-pane').forEach(el=>el.classList.toggle('hidden',el.id!=='configTab'));setProgramDisabled(!canWrite);showWizardStep(1);message('programMessage');openDrawer();
}
function populateProgram(p){
  $('programName').value=p.name||'';$('programSlug').value=p.slug||'';$('categoryLabel').value=p.categoryLabel||'';$('programLocation').value=p.location||'';$('startsOn').value=p.startsOn||'';$('endsOn').value=p.endsOn||'';$('ageMin').value=p.ageMin??'';$('ageMax').value=p.ageMax??'';$('capacity').value=p.capacity??'';$('fee').value=p.fee??'';$('feeWeekly').value=p.feeWeekly??'';$('weeks').value=p.weeks??'';$('scheduleLabel').value=scheduleText(p);$('programStatus').value=p.status||'draft';$('publicEnabled').checked=Boolean(p.publicRegistrationEnabled);$('programDescription').value=p.description||'';selectType(p.programType||'Evento');selectPaymentMode(Number(p.feeWeekly)>0?'weekly':Number(p.fee)>0?'single':'free');setProgramDisabled(!canWrite);wizardStep=1;updatePreview();
}
function setProgramDisabled(disabled){['programName','programSlug','categoryLabel','programLocation','startsOn','endsOn','ageMin','ageMax','capacity','fee','feeWeekly','weeks','scheduleLabel','programStatus','publicEnabled','programDescription','saveProgram','wizardNext'].forEach(id=>$(id).disabled=disabled);document.querySelectorAll('.type-card,.payment-mode').forEach(b=>b.disabled=disabled);}
function selectType(type){$('programType').value=type;document.querySelectorAll('.type-card').forEach(b=>b.classList.toggle('active',b.dataset.type===type));updatePreview();}
function selectPaymentMode(mode){$('paymentMode').value=mode;document.querySelectorAll('.payment-mode').forEach(b=>b.classList.toggle('active',b.dataset.paymentMode===mode));$('singleFeeFields').classList.toggle('hidden',mode!=='single');$('weeklyFeeFields').classList.toggle('hidden',mode!=='weekly');if(mode==='free'){$('fee').value='';$('feeWeekly').value='';$('weeks').value='';}updatePreview();}
function validateWizardStep(step){
  if(step===2){if($('programName').value.trim().length<2)throw new Error('Escribe el nombre del evento.');if($('startsOn').value&&$('endsOn').value&&$('endsOn').value<$('startsOn').value)throw new Error('La fecha final no puede ser anterior al inicio.');if(asInt($('ageMin').value)!=null&&asInt($('ageMax').value)!=null&&asInt($('ageMax').value)<asInt($('ageMin').value))throw new Error('Revisa el rango de edades.');}
  if(step===3){const mode=$('paymentMode').value;if(mode==='single'&&!(asNum($('fee').value)>0))throw new Error('Escribe la cuota del evento.');if(mode==='weekly'&&(!(asNum($('feeWeekly').value)>0)||!(asInt($('weeks').value)>0)))throw new Error('Escribe cuota semanal y semanas.');}
}
function showWizardStep(step){wizardStep=Math.max(1,Math.min(4,step));document.querySelectorAll('.form-step').forEach(s=>s.classList.toggle('hidden',Number(s.dataset.step)!==wizardStep));document.querySelectorAll('#wizardSteps span').forEach((s,i)=>s.classList.toggle('active',i<wizardStep));$('wizardBar').style.width=`${wizardStep*25}%`;$('wizardBack').classList.toggle('hidden',wizardStep===1);$('wizardNext').classList.toggle('hidden',wizardStep===4);$('saveProgram').classList.toggle('hidden',wizardStep!==4);$('wizardHeader').querySelector('.eyebrow').textContent=currentProgram?'EDITAR EVENTO':'CREAR EVENTO';$('wizardHeader').querySelector('h3').textContent=currentProgram?'Actualiza la operación sin perder trazabilidad':'Configúralo en cuatro decisiones';if(wizardStep===4){if(!$('programSlug').value.trim())$('programSlug').value=slugify($('programName').value);updatePreview();}}
function wizardNext(){try{validateWizardStep(wizardStep);message('programMessage');showWizardStep(wizardStep+1);}catch(e){message('programMessage',e.message);}}
function updatePreview(){if(!$('previewProgramName'))return;const name=$('programName').value.trim()||`Nueva ${$('programType').value.toLowerCase()}`;$('previewProgramName').textContent=name;$('previewProgramMeta').textContent=[$('categoryLabel').value.trim(),$('startsOn').value?dateFmt($('startsOn').value):null,$('programLocation').value.trim()].filter(Boolean).join(' · ')||'Completa la información para publicar.';const mode=$('paymentMode').value;$('previewProgramFee').textContent=mode==='single'&&asNum($('fee').value)?money.format(asNum($('fee').value)):mode==='weekly'&&asNum($('feeWeekly').value)?`${money.format(asNum($('feeWeekly').value))}/sem`:'Gratis';}
async function saveProgram(e){
  e.preventDefault();if(!canWrite)return;const btn=$('saveProgram');btn.disabled=true;message('programMessage');try{validateWizardStep(2);validateWizardStep(3);const name=$('programName').value.trim(),slug=$('programSlug').value.trim()||slugify(name),mode=$('paymentMode').value,schedule=$('scheduleLabel').value.trim();if(slug.length<2)throw new Error('Escribe un nombre válido para el enlace.');const id=await rpc('v2_upsert_program',{organization_id:ctx.organization_id,program_id:currentProgram?.id||null,slug,name,program_type:$('programType').value,category_label:$('categoryLabel').value.trim()||null,description:$('programDescription').value.trim()||null,starts_on:$('startsOn').value||null,ends_on:$('endsOn').value||null,schedule:schedule?[{label:schedule}]:[],location:$('programLocation').value.trim()||null,capacity:asInt($('capacity').value),fee:mode==='single'?asNum($('fee').value):null,fee_weekly:mode==='weekly'?asNum($('feeWeekly').value):null,weeks:mode==='weekly'?asInt($('weeks').value):null,age_min:asInt($('ageMin').value),age_max:asInt($('ageMax').value),status:$('programStatus').value,public_registration_enabled:$('publicEnabled').checked});await load();openProgram(id);toast('Evento guardado');}catch(err){message('programMessage',err.message||'No se pudo guardar el evento.');}finally{btn.disabled=false;}}

function shareWhatsapp(){if(!currentProgram||!isPublic(currentProgram))return;const text=`${currentProgram.name}\n${currentProgram.startsOn?dateFmt(currentProgram.startsOn):''}${currentProgram.location?` · ${currentProgram.location}`:''}\nRegistro: ${publicUrl(currentProgram)}`;window.open(`https://wa.me/?text=${encodeURIComponent(text)}`,'_blank','noopener');}

$('newProgram').addEventListener('click',clearProgram);$('closeDrawer').addEventListener('click',closeDrawer);$('backdrop').addEventListener('click',closeDrawer);$('copyProgramLink').addEventListener('click',()=>copyText(publicUrl()));$('shareProgramWhatsapp').addEventListener('click',shareWhatsapp);$('editProgram').addEventListener('click',()=>{wizardStep=1;setTab('config');});
document.querySelectorAll('.stage-chip').forEach(b=>b.addEventListener('click',()=>{stage=b.dataset.stage;document.querySelectorAll('.stage-chip').forEach(x=>x.classList.toggle('active',x===b));renderPrograms();}));$('programSearch').addEventListener('input',renderPrograms);
document.querySelectorAll('.operation-tab').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab)));document.querySelectorAll('[data-open-tab]').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.openTab)));
$('participantSearch').addEventListener('input',renderParticipants);document.querySelectorAll('.mini-chip').forEach(b=>b.addEventListener('click',()=>{participantFilter=b.dataset.participantFilter;document.querySelectorAll('.mini-chip').forEach(x=>x.classList.toggle('active',x===b));renderParticipants();}));
$('attendanceDate').addEventListener('change',()=>{renderAttendance();renderParticipants();renderSummary();});$('addParticipant').addEventListener('click',openQuickParticipant);$('closeQuickParticipant').addEventListener('click',closeQuickParticipant);$('quickParticipantBackdrop').addEventListener('click',closeQuickParticipant);$('quickParticipantForm').addEventListener('submit',saveQuickParticipant);
$('closeEnrollment').addEventListener('click',closeEnrollment);$('enrollmentBackdrop').addEventListener('click',closeEnrollment);$('saveEnrollment').addEventListener('click',saveEnrollment);
$('closePayment').addEventListener('click',closePayment);$('paymentBackdrop').addEventListener('click',closePayment);$('paymentForm').addEventListener('submit',savePayment);
document.querySelectorAll('.type-card').forEach(b=>b.addEventListener('click',()=>selectType(b.dataset.type)));document.querySelectorAll('.payment-mode').forEach(b=>b.addEventListener('click',()=>selectPaymentMode(b.dataset.paymentMode)));$('wizardNext').addEventListener('click',wizardNext);$('wizardBack').addEventListener('click',()=>showWizardStep(wizardStep-1));$('programForm').addEventListener('submit',saveProgram);
['programName','categoryLabel','programLocation','startsOn','fee','feeWeekly'].forEach(id=>$(id).addEventListener('input',updatePreview));$('programName').addEventListener('blur',()=>{if(!currentProgram&&!$('programSlug').value.trim())$('programSlug').value=slugify($('programName').value);});$('programStatus').addEventListener('change',()=>{if(!['published','active'].includes($('programStatus').value))$('publicEnabled').checked=false;});
document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;if(!$('paymentModal').classList.contains('hidden'))closePayment();else if(!$('quickParticipantModal').classList.contains('hidden'))closeQuickParticipant();else if(!$('enrollmentModal').classList.contains('hidden'))closeEnrollment();else if(!$('drawer').classList.contains('hidden'))closeDrawer();});

boot().catch(e=>{$('deniedText').textContent=e.message||'No fue posible abrir Programas y Eventos.';show('deniedView');});
