import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const supabase=createClient('https://pacnegivzgxpanphrnwp.supabase.co','sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'});
let ctx=null,programs=[],enrollments=[],currentProgram=null,currentEnrollment=null,canWrite=false;
const currentStatuses=new Set(['draft','published','active']);
const statusLabels={draft:'Borrador',published:'Publicado',active:'Activo',completed:'Completado',cancelled:'Cancelado',archived:'Archivado'};
const enrollmentLabels={registered:'Registrado',confirmed:'Confirmado',waitlisted:'Lista de espera',completed:'Completado',cancelled:'Cancelado'};
const paymentLabels={pending:'Pago pendiente',partial:'Pago parcial',paid:'Pagado',waived:'Condonado',refunded:'Reembolsado'};
function show(id){['loadingView','deniedView','view'].forEach(v=>$(v)?.classList.toggle('hidden',v!==id));}
function message(id,text='',type='error'){const e=$(id);if(!e)return;e.textContent=text;e.dataset.type=type;e.classList.toggle('hidden',!text);}
async function rpc(name,params={}){const {data,error}=await supabase.rpc(name,params);if(error)throw error;return data;}
function safe(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function asNum(v){if(v==null||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null;}
function asInt(v){const n=asNum(v);return n==null?null:Math.trunc(n);}
function dateFmt(v){return v?new Intl.DateTimeFormat('es-MX',{dateStyle:'medium'}).format(new Date(`${v}T12:00:00`)):'—';}
function slugify(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,120);}
function scheduleText(p){const s=p?.schedule;if(Array.isArray(s)){const first=s.find(Boolean);if(typeof first==='string')return first;if(first?.label)return first.label;}return '';}
function age(birth){if(!birth)return null;const b=new Date(`${birth}T12:00:00`),n=new Date();let a=n.getFullYear()-b.getFullYear();const m=n.getMonth()-b.getMonth();if(m<0||(m===0&&n.getDate()<b.getDate()))a--;return a;}

async function boot(){
  const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/v2';return;}
  const rows=await rpc('v2_my_context');if(!rows?.length){$('deniedText').textContent='Tu cuenta no está vinculada a una organización.';show('deniedView');return;}
  ctx=rows[0];const modules=await rpc('v2_my_modules',{organization_id:ctx.organization_id});const mod=modules.find(m=>m.module_code==='programs');
  if(!mod?.enabled||!mod?.can_read){$('deniedText').textContent='Tu rol no tiene acceso a Programas.';show('deniedView');return;}
  canWrite=Boolean(mod.can_write);$('orgName').textContent=ctx.organization_name||'Tannery City FC';$('roleBadge').textContent=ctx.is_owner?'Propietario':(ctx.role||'Miembro');$('newProgram').classList.toggle('hidden',!canWrite);await load();show('view');
}

async function load(){const data=await rpc('v2_program_admin',{organization_id:ctx.organization_id});programs=Array.isArray(data?.programs)?data.programs:[];enrollments=Array.isArray(data?.enrollments)?data.enrollments:[];renderKpis();renderPrograms();}
function renderKpis(){
  $('kpiCurrent').textContent=programs.filter(p=>currentStatuses.has(p.status)).length;
  $('kpiPublic').textContent=programs.filter(p=>p.publicRegistrationEnabled&&['published','active'].includes(p.status)).length;
  $('kpiEnrollments').textContent=enrollments.filter(e=>['registered','confirmed'].includes(e.status)).length;
  $('kpiWaitlist').textContent=enrollments.filter(e=>e.status==='waitlisted').length;
}
function filteredPrograms(){const status=$('programStatusFilter').value,q=$('programSearch').value.trim().toLocaleLowerCase('es-MX');return programs.filter(p=>{if(status==='current'&&!currentStatuses.has(p.status))return false;if(status&&status!=='current'&&p.status!==status)return false;if(!q)return true;return [p.name,p.slug,p.programType,p.categoryLabel,p.location,p.description].filter(Boolean).join(' ').toLocaleLowerCase('es-MX').includes(q);});}
function renderPrograms(){const rows=filteredPrograms(),box=$('programList');box.innerHTML='';$('empty').classList.toggle('hidden',rows.length>0);rows.forEach(p=>{const cap=p.capacity==null?'Sin límite':`${Number(p.registeredCount||0)}/${p.capacity}`;const card=document.createElement('button');card.type='button';card.className='program-row';card.innerHTML=`<div class="program-main"><div class="title-line"><strong>${safe(p.name)}</strong>${p.publicRegistrationEnabled?'<span class="public-pill">Público</span>':''}</div><span>${safe([p.categoryLabel,p.location].filter(Boolean).join(' · ')||p.programType||'Programa')}</span><small>${safe(p.startsOn?`${dateFmt(p.startsOn)}${p.endsOn?` → ${dateFmt(p.endsOn)}`:''}`:'Sin fechas')}</small></div><div class="program-side"><span class="status ${safe(p.status)}">${safe(statusLabels[p.status]||p.status)}</span><b>${safe(cap)}</b><small>${Number(p.waitlistedCount||0)} espera</small></div>`;card.addEventListener('click',()=>openProgram(p.id));box.appendChild(card);});}

function openDrawer(){$('backdrop').classList.remove('hidden');$('drawer').classList.remove('hidden');$('drawer').setAttribute('aria-hidden','false');}
function closeDrawer(){currentProgram=null;$('backdrop').classList.add('hidden');$('drawer').classList.add('hidden');$('drawer').setAttribute('aria-hidden','true');message('programMessage');closeEnrollment();}
function setDisabled(disabled){['programName','programSlug','programType','categoryLabel','programLocation','startsOn','endsOn','ageMin','ageMax','capacity','fee','feeWeekly','weeks','scheduleLabel','programStatus','publicEnabled','programDescription','saveProgram'].forEach(id=>$(id).disabled=disabled);}
function clearProgram(){currentProgram=null;$('drawerEyebrow').textContent='NUEVO PROGRAMA';$('drawerTitle').textContent='Crear programa';$('drawerMeta').textContent='Configura primero el programa; los cobros automáticos no se generan aquí.';['programName','programSlug','programType','categoryLabel','programLocation','startsOn','endsOn','ageMin','ageMax','capacity','fee','feeWeekly','weeks','scheduleLabel','programDescription'].forEach(id=>$(id).value='');$('programType').value='program';$('programStatus').value='draft';$('publicEnabled').checked=false;$('enrollmentSection').classList.add('hidden');setDisabled(!canWrite);message('programMessage');openDrawer();}
function openProgram(id){const p=programs.find(x=>x.id===id);if(!p)return;currentProgram=p;$('drawerEyebrow').textContent='PROGRAMA';$('drawerTitle').textContent=p.name;$('drawerMeta').textContent=`${statusLabels[p.status]||p.status} · ${p.slug}`;$('programName').value=p.name||'';$('programSlug').value=p.slug||'';$('programType').value=p.programType||'program';$('categoryLabel').value=p.categoryLabel||'';$('programLocation').value=p.location||'';$('startsOn').value=p.startsOn||'';$('endsOn').value=p.endsOn||'';$('ageMin').value=p.ageMin??'';$('ageMax').value=p.ageMax??'';$('capacity').value=p.capacity??'';$('fee').value=p.fee??'';$('feeWeekly').value=p.feeWeekly??'';$('weeks').value=p.weeks??'';$('scheduleLabel').value=scheduleText(p);$('programStatus').value=p.status||'draft';$('publicEnabled').checked=Boolean(p.publicRegistrationEnabled);$('programDescription').value=p.description||'';setDisabled(!canWrite);$('enrollmentSection').classList.remove('hidden');renderEnrollments(p);message('programMessage');openDrawer();}
function renderEnrollments(p){const rows=enrollments.filter(e=>e.programId===p.id);const active=rows.filter(e=>['registered','confirmed'].includes(e.status)).length;$('capacityBadge').textContent=p.capacity==null?`${active} activos · sin límite`:`${active}/${p.capacity} lugares`;$('enrollmentList').innerHTML='';$('enrollmentEmpty').classList.toggle('hidden',rows.length>0);rows.forEach(e=>{const r=document.createElement('button');r.type='button';r.className='enrollment-row';r.innerHTML=`<div><strong>${safe([e.firstName,e.lastName].filter(Boolean).join(' '))}</strong><span>${safe([e.phone,e.email].filter(Boolean).join(' · ')||'Sin contacto')}</span><small>${safe(dateFmt(String(e.createdAt||'').slice(0,10)))}</small></div><div><span class="enrollment-status ${safe(e.status)}">${safe(enrollmentLabels[e.status]||e.status)}</span><small>${safe(paymentLabels[e.paymentStatus]||e.paymentStatus)}</small></div>`;r.addEventListener('click',()=>openEnrollment(e.id));$('enrollmentList').appendChild(r);});}

async function saveProgram(){if(!canWrite)return;const name=$('programName').value.trim(),slug=$('programSlug').value.trim()||slugify(name);if(name.length<2){message('programMessage','Escribe el nombre del programa.');return;}if(slug.length<2){message('programMessage','Escribe un slug válido.');return;}const btn=$('saveProgram');btn.disabled=true;message('programMessage');try{const schedule=$('scheduleLabel').value.trim();const id=await rpc('v2_upsert_program',{organization_id:ctx.organization_id,program_id:currentProgram?.id||null,slug,name,program_type:$('programType').value.trim()||'program',category_label:$('categoryLabel').value.trim()||null,description:$('programDescription').value.trim()||null,starts_on:$('startsOn').value||null,ends_on:$('endsOn').value||null,schedule:schedule?[{label:schedule}]:[],location:$('programLocation').value.trim()||null,capacity:asInt($('capacity').value),fee:asNum($('fee').value),fee_weekly:asNum($('feeWeekly').value),weeks:asInt($('weeks').value),age_min:asInt($('ageMin').value),age_max:asInt($('ageMax').value),status:$('programStatus').value,public_registration_enabled:$('publicEnabled').checked});await load();openProgram(id);message('programMessage','Programa guardado.','success');}catch(e){message('programMessage',e.message||'No se pudo guardar el programa.');}finally{btn.disabled=!canWrite;}}

function openEnrollment(id){const e=enrollments.find(x=>x.id===id);if(!e)return;currentEnrollment=e;$('enrollmentName').textContent=[e.firstName,e.lastName].filter(Boolean).join(' ');$('enrollmentStatus').value=e.status;$('enrollmentNote').value='';$('enrollmentStatus').disabled=!canWrite;$('enrollmentNote').disabled=!canWrite;$('saveEnrollment').disabled=!canWrite;const a=age(e.birthDate);const facts=[['Teléfono',e.phone],['Correo',e.email],['Edad',a==null?null:`${a} años`],['Pago',paymentLabels[e.paymentStatus]||e.paymentStatus],['Registro',new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(new Date(e.createdAt))],['Vínculo Tanner',e.playerId?'Sí':'No']].filter(([,v])=>v!=null&&String(v).trim()!=='');$('enrollmentFacts').innerHTML=facts.map(([k,v])=>`<div><span>${safe(k)}</span><strong>${safe(v)}</strong></div>`).join('');message('enrollmentMessage');$('enrollmentBackdrop').classList.remove('hidden');$('enrollmentModal').classList.remove('hidden');$('enrollmentModal').setAttribute('aria-hidden','false');}
function closeEnrollment(){currentEnrollment=null;$('enrollmentBackdrop')?.classList.add('hidden');$('enrollmentModal')?.classList.add('hidden');$('enrollmentModal')?.setAttribute('aria-hidden','true');message('enrollmentMessage');}
async function saveEnrollment(){if(!currentEnrollment||!canWrite)return;const btn=$('saveEnrollment');btn.disabled=true;message('enrollmentMessage');try{await rpc('v2_update_program_enrollment_status',{organization_id:ctx.organization_id,enrollment_id:currentEnrollment.id,status:$('enrollmentStatus').value,notes:$('enrollmentNote').value.trim()||null});const pid=currentEnrollment.programId;await load();closeEnrollment();openProgram(pid);message('programMessage','Estado del participante actualizado.','success');}catch(e){message('enrollmentMessage',e.message||'No se pudo actualizar.');}finally{btn.disabled=!canWrite;}}

$('newProgram').addEventListener('click',clearProgram);$('programName').addEventListener('blur',()=>{if(!currentProgram&&!$('programSlug').value.trim())$('programSlug').value=slugify($('programName').value);});$('programStatus').addEventListener('change',()=>{if(!['published','active'].includes($('programStatus').value))$('publicEnabled').checked=false;});$('programStatusFilter').addEventListener('change',renderPrograms);$('programSearch').addEventListener('input',renderPrograms);$('closeDrawer').addEventListener('click',closeDrawer);$('backdrop').addEventListener('click',closeDrawer);$('saveProgram').addEventListener('click',saveProgram);$('closeEnrollment').addEventListener('click',closeEnrollment);$('enrollmentBackdrop').addEventListener('click',closeEnrollment);$('saveEnrollment').addEventListener('click',saveEnrollment);
boot().catch(e=>{$('deniedText').textContent=e.message||'No fue posible abrir Programas.';show('deniedView');});