import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://pacnegivzgxpanphrnwp.supabase.co','sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);let ctx=null,items=[],assignments=[],canWrite=false;const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function show(id){['loadingView','deniedView','view'].forEach(v=>$(v)?.classList.toggle('hidden',v!==id));}function msg(id,text='',type='error'){const e=$(id);if(!e)return;e.textContent=text;e.dataset.type=type;e.classList.toggle('hidden',!text);}async function rpc(name,params={}){const {data,error}=await supabase.rpc(name,params);if(error)throw error;return data;}function fmtDate(v){if(!v)return '—';return new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));}
async function boot(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/';return;}const rows=await rpc('v2_my_context');if(!rows?.length){$('deniedText').textContent='Tu cuenta no está vinculada a un club.';show('deniedView');return;}ctx=rows[0];const mods=await rpc('v2_my_modules',{organization_id:ctx.organization_id});const mod=mods.find(m=>m.module_code==='equipment');if(!mod?.enabled||!mod?.can_read){$('deniedText').textContent='Tu rol no tiene acceso a Utilería.';show('deniedView');return;}canWrite=!!mod.can_write;$('orgName').textContent=ctx.organization_name||'Tannery City FC';$('roleBadge').textContent=ctx.is_owner?'Presidencia':ctx.role;$('saveItem').disabled=!canWrite;$('saveAssignment').disabled=!canWrite;await load();show('view');}
async function load(){[items,assignments]=await Promise.all([rpc('v2_equipment_items',{organization_id:ctx.organization_id}),rpc('v2_equipment_assignments',{organization_id:ctx.organization_id,active_only:true})]);items=Array.isArray(items)?items:[];assignments=Array.isArray(assignments)?assignments:[];renderKpis();renderItems();renderAssignSelect();renderAssignments();}
function renderKpis(){$('kpiItems').textContent=items.length;$('kpiUnits').textContent=items.reduce((s,i)=>s+Number(i.quantity||0),0);$('kpiAssigned').textContent=items.reduce((s,i)=>s+Number(i.assigned_quantity||0),0);$('kpiLow').textContent=items.filter(i=>i.needs_reorder).length;}
function renderItems(){const body=$('itemsBody');body.innerHTML='';$('itemsEmpty').classList.toggle('hidden',items.length>0);items.forEach(i=>{const tr=document.createElement('tr'),state=i.needs_reorder?'Reponer':Number(i.available_quantity||0)===0?'Sin disponible':'OK',meta=[i.category,i.location,i.unit_cost!=null?money.format(Number(i.unit_cost)):null].filter(Boolean).map(esc).join(' · ');tr.innerHTML=`<td><strong>${esc(i.name||'Artículo')}</strong><small>${meta}</small></td><td>${Number(i.quantity||0)}</td><td>${Number(i.assigned_quantity||0)}</td><td><strong>${Number(i.available_quantity||0)}</strong></td><td><span class="stock-state ${i.needs_reorder?'low':state==='Sin disponible'?'empty-stock':'ok'}">${esc(state)}</span></td>`;body.appendChild(tr);});}
function renderAssignSelect(){const s=$('assignItem'),current=s.value;s.innerHTML='<option value="">Selecciona</option>';items.filter(i=>i.status==='active'&&Number(i.available_quantity||0)>0).forEach(i=>{const o=document.createElement('option');o.value=i.id;o.textContent=`${i.name||'Artículo'} · ${Number(i.available_quantity||0)} disponibles`;s.appendChild(o);});if(current&&items.some(i=>i.id===current&&Number(i.available_quantity||0)>0))s.value=current;}
function renderAssignments(){const box=$('assignmentList');box.innerHTML='';$('assignmentsEmpty').classList.toggle('hidden',assignments.length>0);assignments.forEach(a=>{const card=document.createElement('article');card.className='assignment-card';card.innerHTML=`<div><strong>${esc(a.item_name||'Artículo')}</strong><span>${esc(a.recipient_name||'Sin destinatario')} · ${Number(a.quantity||0)} unidad${Number(a.quantity)===1?'':'es'} · ${esc(fmtDate(a.assigned_at))}</span>${a.notes?`<small>${esc(a.notes)}</small>`:''}</div>${canWrite?'<button class="secondary mini" type="button">Registrar devolución</button>':''}`;card.querySelector('button')?.addEventListener('click',()=>returnAssignment(a));box.appendChild(card);});}
async function saveItem(e){e.preventDefault();msg('itemMessage');const btn=$('saveItem');btn.disabled=true;try{await rpc('v2_upsert_equipment_item',{organization_id:ctx.organization_id,item_id:null,sku:$('itemSku').value.trim()||null,name:$('itemName').value.trim(),category:$('itemCategory').value.trim()||null,quantity:Number($('itemQuantity').value||0),min_stock:Number($('itemMinStock').value||0),unit_cost:$('itemCost').value===''?null:Number($('itemCost').value),location:$('itemLocation').value.trim()||null,status:'active',notes:$('itemNotes').value.trim()||null});msg('itemMessage','Artículo guardado.','success');e.target.reset();$('itemQuantity').value='0';$('itemMinStock').value='0';await load();}catch(err){msg('itemMessage',err.message||'No se pudo guardar.');}finally{btn.disabled=!canWrite;}}
async function saveAssignment(e){e.preventDefault();msg('assignMessage');const btn=$('saveAssignment');btn.disabled=true;try{await rpc('v2_assign_equipment',{organization_id:ctx.organization_id,item_id:$('assignItem').value,assigned_to_user_id:null,assigned_to_label:$('assignLabel').value.trim(),quantity:Number($('assignQuantity').value||0),notes:$('assignNotes').value.trim()||null});msg('assignMessage','Material asignado.','success');e.target.reset();$('assignQuantity').value='1';await load();}catch(err){const map={'Not enough equipment available':'No hay suficiente material disponible.','Assignment recipient required':'Escribe quién recibe el material.'};msg('assignMessage',map[err.message]||err.message||'No se pudo asignar.');}finally{btn.disabled=!canWrite;}}
async function returnAssignment(a){if(!canWrite)return;if(!confirm(`¿Registrar devolución de ${Number(a.quantity||0)} × ${String(a.item_name||'artículo')} por ${String(a.recipient_name||'destinatario')}?`))return;try{await rpc('v2_return_equipment',{organization_id:ctx.organization_id,assignment_id:a.id,notes:'Devolución registrada desde TannerOS'});await load();}catch(err){alert(err.message||'No se pudo registrar la devolución.');}}
$('itemForm')?.addEventListener('submit',saveItem);$('assignForm')?.addEventListener('submit',saveAssignment);$('refresh')?.addEventListener('click',load);boot().catch(e=>{$('deniedText').textContent=e.message||'No pudimos abrir Utilería.';show('deniedView');});
