import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://pacnegivzgxpanphrnwp.supabase.co','sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);let ctx=null,canWrite=false,sponsors=[],agreements=[],assets=[];const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0});
function show(id){['loadingView','deniedView','view'].forEach(v=>$(v)?.classList.toggle('hidden',v!==id));}
function msg(id,t='',type='error'){const e=$(id);if(!e)return;e.textContent=t;e.dataset.type=type;e.classList.toggle('hidden',!t);}
async function rpc(n,p={}){const {data,error}=await supabase.rpc(n,p);if(error)throw error;return data;}
function toIso(v){return v?new Date(v).toISOString():null;}
function toLocalInput(v){if(!v)return'';const d=new Date(v);const pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;}
function lines(id){return $(id).value.split('\n').map(x=>x.trim()).filter(Boolean);}
function arrLines(v){return Array.isArray(v)?v.join('\n'):'';}
function sponsorById(id){return sponsors.find(s=>s.id===id);}
function statusLabel(s){return ({prospect:'Prospecto',negotiation:'Negociación',active:'Activo',archived:'Archivado'})[s]||s;}
function agreementStatusLabel(s){return ({draft:'Borrador',active:'Activo',completed:'Completado'})[s]||s;}
function friendly(err){const t=String(err?.message||err||'Error');const map={'Invalid sponsor phone':'El teléfono no tiene un formato válido. Usa 10 dígitos de México o formato internacional.','Invalid sponsor status':'Estatus de patrocinador inválido.','Potential value cannot be negative':'El valor potencial no puede ser negativo.','Agreement end cannot precede start':'La fecha fin no puede ser anterior al inicio.','Agreement value cannot be negative':'El valor del convenio no puede ser negativo.','Invalid agreement status':'Estatus de convenio inválido.','Not authorized':'No tienes permiso para realizar esta operación.'};return map[t]||t;}
async function boot(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/v2';return;}const rows=await rpc('v2_my_context');if(!rows?.length){$('deniedText').textContent='Sin organización.';show('deniedView');return;}ctx=rows[0];const mods=await rpc('v2_my_modules',{organization_id:ctx.organization_id});const mod=mods.find(m=>m.module_code==='sponsors');if(!mod?.enabled||!mod?.can_read){$('deniedText').textContent='Tu rol no tiene acceso a Patrocinadores.';show('deniedView');return;}canWrite=!!mod.can_write;$('orgName').textContent=ctx.organization_name||'Tannery City FC';$('roleBadge').textContent=ctx.is_owner?'Propietario':ctx.role;[$('saveSponsor'),$('saveAgreement')].forEach(b=>b.disabled=!canWrite);await load();show('view');}
async function load(){const data=await rpc('v2_sponsor_admin',{organization_id:ctx.organization_id});sponsors=Array.isArray(data?.sponsors)?data.sponsors:[];agreements=Array.isArray(data?.agreements)?data.agreements:[];assets=Array.isArray(data?.assets)?data.assets:[];render();}
function render(){const active=sponsors.filter(s=>s.status==='active').length,neg=sponsors.filter(s=>s.status==='negotiation').length,activeAgr=agreements.filter(a=>a.status==='active').length,potential=sponsors.reduce((a,s)=>a+Number(s.potentialValue||0),0);$('kpiActive').textContent=active;$('kpiNegotiation').textContent=neg;$('kpiAgreements').textContent=activeAgr;$('kpiPotential').textContent=money.format(potential);renderSponsorSelect();renderSponsors();renderAgreements();}
function renderSponsorSelect(){const sel=$('agreementSponsor'),current=sel.value;sel.innerHTML='<option value="">Selecciona</option>';sponsors.filter(s=>s.status!=='archived').sort((a,b)=>a.name.localeCompare(b.name,'es-MX')).forEach(s=>{const o=document.createElement('option');o.value=s.id;o.textContent=s.name;sel.appendChild(o);});if(current&&sponsors.some(s=>s.id===current))sel.value=current;}
function renderSponsors(){const box=$('sponsorList');box.innerHTML='';$('empty').classList.toggle('hidden',sponsors.length>0);sponsors.forEach(s=>{const due=s.nextActionAt?new Date(s.nextActionAt).toLocaleDateString('es-MX'):'Sin próxima fecha';const card=document.createElement('article');card.className='sponsor-card';card.innerHTML=`<div class="sponsor-main"><div class="sponsor-title"><strong>${s.name}</strong><span class="status-chip ${s.status}">${statusLabel(s.status)}</span></div><span>${[s.tier,s.stage,s.contactName].filter(Boolean).join(' · ')||'Sin datos comerciales'}</span>${s.nextAction?`<small>Próximo: ${s.nextAction} · ${due}</small>`:''}${s.phone||s.email?`<small>${[s.phone,s.email].filter(Boolean).join(' · ')}</small>`:''}</div><div class="sponsor-side"><b>${s.potentialValue!=null?money.format(Number(s.potentialValue)):'—'}</b><small>${Number(s.activeAgreementCount||0)} convenio(s) activo(s)</small>${canWrite?`<button class="secondary mini edit-sponsor" type="button" data-id="${s.id}">Editar</button>`:''}</div>`;box.appendChild(card);});box.querySelectorAll('.edit-sponsor').forEach(b=>b.addEventListener('click',()=>editSponsor(b.dataset.id)));}
function renderAgreements(){const box=$('agreementList');box.innerHTML='';$('agreementsEmpty').classList.toggle('hidden',agreements.length>0);agreements.forEach(a=>{const s=sponsorById(a.sponsorId);const card=document.createElement('article');card.className='agreement-card';const range=[a.startsOn,a.endsOn].filter(Boolean).join(' → ')||'Sin vigencia';card.innerHTML=`<div><strong>${s?.name||'Patrocinador'}</strong><span>${agreementStatusLabel(a.status)} · ${range}</span><small>${Array.isArray(a.deliverables)&&a.deliverables.length?`${a.deliverables.length} entregable(s)`: 'Sin entregables capturados'}${Array.isArray(a.benefitsReceived)&&a.benefitsReceived.length?` · ${a.benefitsReceived.length} derecho(s)`:''}</small></div><div class="agreement-side"><b>${a.monetaryValue!=null?money.format(Number(a.monetaryValue)):'—'}</b>${canWrite?`<button class="secondary mini edit-agreement" type="button" data-id="${a.id}">Editar</button>`:''}</div>`;box.appendChild(card);});box.querySelectorAll('.edit-agreement').forEach(b=>b.addEventListener('click',()=>editAgreement(b.dataset.id)));}
function resetSponsorForm(){const f=$('sponsorForm');f.reset();$('sponsorId').value='';$('sponsorStatus').value='prospect';$('sponsorFormTitle').textContent='Nuevo patrocinador';$('saveSponsor').textContent='Guardar patrocinador';$('cancelSponsorEdit').classList.add('hidden');msg('sponsorMessage');}
function editSponsor(id){const s=sponsorById(id);if(!s)return;$('sponsorId').value=s.id;$('sponsorName').value=s.name||'';$('sponsorStatus').value=s.status||'prospect';$('sponsorTier').value=s.tier||'';$('sponsorType').value=s.sponsorType||'';$('sponsorContact').value=s.contactName||'';$('sponsorPhone').value=s.phone||'';$('sponsorEmail').value=s.email||'';$('sponsorPotential').value=s.potentialValue??'';$('sponsorStage').value=s.stage||'';$('sponsorRelationship').value=s.relationshipType||'';$('sponsorNextAction').value=s.nextAction||'';$('sponsorNextDate').value=toLocalInput(s.nextActionAt);$('sponsorNotes').value=s.notes||'';$('sponsorFormTitle').textContent='Editar patrocinador';$('saveSponsor').textContent='Guardar cambios';$('cancelSponsorEdit').classList.remove('hidden');$('sponsorForm').scrollIntoView({behavior:'smooth',block:'start'});}
function resetAgreementForm(){const f=$('agreementForm');f.reset();$('agreementId').value='';$('agreementStatus').value='draft';$('agreementFormTitle').textContent='Nuevo acuerdo';$('saveAgreement').textContent='Guardar acuerdo';$('cancelAgreementEdit').classList.add('hidden');renderSponsorSelect();msg('agreementMessage');}
function editAgreement(id){const a=agreements.find(x=>x.id===id);if(!a)return;$('agreementId').value=a.id;$('agreementSponsor').value=a.sponsorId||'';$('agreementStart').value=a.startsOn||'';$('agreementEnd').value=a.endsOn||'';$('agreementValue').value=a.monetaryValue??'';$('agreementStatus').value=a.status||'draft';$('agreementBenefits').value=arrLines(a.benefitsReceived);$('agreementDeliverables').value=arrLines(a.deliverables);$('agreementNotes').value=a.notes||'';$('agreementFormTitle').textContent='Editar acuerdo';$('saveAgreement').textContent='Guardar cambios';$('cancelAgreementEdit').classList.remove('hidden');$('agreementForm').scrollIntoView({behavior:'smooth',block:'start'});}
async function saveSponsor(e){e.preventDefault();msg('sponsorMessage');const btn=$('saveSponsor');btn.disabled=true;try{await rpc('v2_upsert_sponsor_admin',{organization_id:ctx.organization_id,sponsor_id:$('sponsorId').value||null,name:$('sponsorName').value.trim(),sponsor_type:$('sponsorType').value.trim()||null,contact_name:$('sponsorContact').value.trim()||null,phone:$('sponsorPhone').value.trim()||null,email:$('sponsorEmail').value.trim()||null,status:$('sponsorStatus').value,tier:$('sponsorTier').value.trim()||null,relationship_type:$('sponsorRelationship').value.trim()||null,stage:$('sponsorStage').value.trim()||null,potential_value:$('sponsorPotential').value===''?null:Number($('sponsorPotential').value),next_action:$('sponsorNextAction').value.trim()||null,next_action_at:toIso($('sponsorNextDate').value),notes:$('sponsorNotes').value.trim()||null});resetSponsorForm();await load();msg('sponsorMessage','Patrocinador guardado.','success');}catch(err){msg('sponsorMessage',friendly(err));}finally{btn.disabled=!canWrite;}}
async function saveAgreement(e){e.preventDefault();msg('agreementMessage');const btn=$('saveAgreement');btn.disabled=true;try{await rpc('v2_upsert_sponsor_agreement_admin',{organization_id:ctx.organization_id,agreement_id:$('agreementId').value||null,sponsor_id:$('agreementSponsor').value,starts_on:$('agreementStart').value||null,ends_on:$('agreementEnd').value||null,monetary_value:$('agreementValue').value===''?null:Number($('agreementValue').value),benefits_received:lines('agreementBenefits'),deliverables:lines('agreementDeliverables'),status:$('agreementStatus').value,notes:$('agreementNotes').value.trim()||null});resetAgreementForm();await load();msg('agreementMessage','Convenio guardado.','success');}catch(err){msg('agreementMessage',friendly(err));}finally{btn.disabled=!canWrite;}}
$('sponsorForm').addEventListener('submit',saveSponsor);$('agreementForm').addEventListener('submit',saveAgreement);$('cancelSponsorEdit').addEventListener('click',resetSponsorForm);$('cancelAgreementEdit').addEventListener('click',resetAgreementForm);$('refresh').addEventListener('click',load);boot().catch(e=>{$('deniedText').textContent=friendly(e)||'No pudimos abrir Patrocinadores.';show('deniedView');});