import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://pacnegivzgxpanphrnwp.supabase.co','sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);let ctx=null,categories=[],sessions=[],currentSession=null,currentRoster=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function show(id){['loadingView','deniedView','attendanceView'].forEach(v=>$(v)?.classList.toggle('hidden',v!==id));}
function msg(id,text='',type='error'){const el=$(id);if(!el)return;el.textContent=text;el.dataset.type=type;el.classList.toggle('hidden',!text);}
async function rpc(name,params={}){const {data,error}=await supabase.rpc(name,params);if(error)throw error;return data;}
function isoLocalDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function localTime(){const d=new Date();return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;}
function fmtDateTime(v){if(!v)return '—';return new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));}
async function boot(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/';return;}const rows=await rpc('v2_my_context');if(!rows?.length){$('deniedText').textContent='Tu cuenta no está vinculada a un club.';show('deniedView');return;}ctx=rows[0];const mods=await rpc('v2_my_modules',{organization_id:ctx.organization_id});const attendance=mods?.find(m=>m.module_code==='attendance');if(!attendance?.enabled||!attendance?.can_read){$('deniedText').textContent='Tu rol no tiene acceso al módulo de Asistencia.';show('deniedView');return;}ctx.canWrite=Boolean(attendance.can_write);$('orgName').textContent=ctx.organization_name||'Tannery City FC';$('roleBadge').textContent=ctx.is_owner?'Presidencia':ctx.role;$('sessionForm').classList.toggle('read-only',!ctx.canWrite);$('createSession').disabled=!ctx.canWrite;await Promise.all([loadCategories(),loadSessions()]);show('attendanceView');}
async function loadCategories(){categories=await rpc('v2_attendance_categories',{organization_id:ctx.organization_id})||[];const sel=$('sessionCategory');sel.innerHTML='<option value="">Selecciona categoría</option>';const cards=$('categoryCards');cards.innerHTML='';for(const c of categories){const o=document.createElement('option');o.value=c.category_id;o.textContent=`${c.name||'Categoría'} · ${Number(c.active_players||0)}`;sel.appendChild(o);const a=document.createElement('article');a.className='category-card';const strong=document.createElement('strong');strong.textContent=c.name||'Categoría';const span=document.createElement('span');span.textContent=`${Number(c.active_players||0)} Tanners`;a.append(strong,span);cards.appendChild(a);}if(!$('sessionDate').value)$('sessionDate').value=isoLocalDate();if(!$('sessionTime').value)$('sessionTime').value=localTime();}
async function loadSessions(){sessions=await rpc('v2_attendance_sessions',{organization_id:ctx.organization_id,from_at:null,to_at:null})||[];const list=$('sessionsList');list.innerHTML='';$('sessionsEmpty').classList.toggle('hidden',sessions.length>0);for(const s of sessions){const row=document.createElement('button');row.className='session-row';row.type='button';const main=document.createElement('div'),strong=document.createElement('strong'),span=document.createElement('span'),stats=document.createElement('div'),count=document.createElement('b'),label=document.createElement('span');strong.textContent=s.title||s.category_name||'Sesión';span.textContent=`${fmtDateTime(s.starts_at)} · ${s.category_name||'Sin categoría'}`;main.append(strong,span);stats.className='session-stats';count.textContent=Number(s.present_count||0);label.textContent='presentes';stats.append(count,label);row.append(main,stats);row.addEventListener('click',()=>openRoster(s));list.appendChild(row);}}
async function createSession(ev){ev.preventDefault();msg('sessionMessage');if(!ctx.canWrite)return;const date=$('sessionDate').value,time=$('sessionTime').value;if(!$('sessionCategory').value||!date||!time){msg('sessionMessage','Completa categoría, fecha y hora.');return;}const starts=new Date(`${date}T${time}:00`),duration=Number($('sessionDuration').value||90),ends=new Date(starts.getTime()+duration*60000),btn=$('createSession');btn.disabled=true;try{const id=await rpc('v2_create_attendance_session',{organization_id:ctx.organization_id,category_id:$('sessionCategory').value,starts_at:starts.toISOString(),ends_at:ends.toISOString(),title:$('sessionTitle').value.trim()||null,location:$('sessionLocation').value.trim()||null,notes:null});msg('sessionMessage','Sesión creada.','success');await loadSessions();const s=sessions.find(x=>x.session_id===id)||sessions[0];if(s)await openRoster(s);}catch(e){msg('sessionMessage',e.message||'No se pudo crear la sesión.');}finally{btn.disabled=!ctx.canWrite;}}
async function openRoster(s){currentSession=s;currentRoster=await rpc('v2_attendance_roster',{organization_id:ctx.organization_id,session_id:s.session_id})||[];$('rosterTitle').textContent=s.title||s.category_name||'Sesión';$('rosterMeta').textContent=`${fmtDateTime(s.starts_at)} · ${s.category_name||'Sin categoría'}`;renderRoster();$('rosterBackdrop').classList.remove('hidden');$('rosterDrawer').classList.remove('hidden');$('rosterDrawer').setAttribute('aria-hidden','false');}
function renderRoster(){const list=$('rosterList');list.innerHTML='';for(const p of currentRoster){const row=document.createElement('article');row.className='roster-row';const selected=p.attendance_status||'';row.innerHTML=`<div class="roster-person"><strong>${esc(p.player_name||'Tanner')}</strong><span>${esc(p.player_code||'')}</span></div><div class="attendance-buttons"><button type="button" data-s="present" class="${selected==='present'?'active':''}">Presente</button><button type="button" data-s="late" class="${selected==='late'?'active':''}">Tarde</button><button type="button" data-s="excused" class="${selected==='excused'?'active':''}">Justificado</button><button type="button" data-s="absent" class="${selected==='absent'?'active':''}">Ausente</button></div>`;row.querySelectorAll('[data-s]').forEach(b=>{b.disabled=!ctx.canWrite;b.addEventListener('click',()=>{p.attendance_status=b.dataset.s;renderRoster();});});list.appendChild(row);}$('saveAttendance').disabled=!ctx.canWrite;}
function closeRoster(){currentSession=null;currentRoster=[];$('rosterBackdrop').classList.add('hidden');$('rosterDrawer').classList.add('hidden');$('rosterDrawer').setAttribute('aria-hidden','true');msg('rosterMessage');}
async function saveAttendance(){msg('rosterMessage');const marked=currentRoster.filter(p=>p.attendance_status);if(!marked.length){msg('rosterMessage','Marca al menos un Tanner.');return;}const btn=$('saveAttendance');btn.disabled=true;try{const payload=marked.map(p=>({player_id:p.player_id,status:p.attendance_status,punctuality:p.attendance_status==='late'?'late':null,notes:null}));const count=await rpc('v2_save_attendance',{organization_id:ctx.organization_id,session_id:currentSession.session_id,records:payload});msg('rosterMessage',`${count} registros guardados.`,'success');currentRoster=await rpc('v2_attendance_roster',{organization_id:ctx.organization_id,session_id:currentSession.session_id})||[];renderRoster();await loadSessions();}catch(e){msg('rosterMessage',e.message||'No se pudo guardar.');}finally{btn.disabled=!ctx.canWrite;}}
$('sessionForm')?.addEventListener('submit',createSession);$('refreshSessions')?.addEventListener('click',loadSessions);$('closeRoster')?.addEventListener('click',closeRoster);$('rosterBackdrop')?.addEventListener('click',closeRoster);$('allPresent')?.addEventListener('click',()=>{if(!ctx.canWrite)return;currentRoster.forEach(p=>p.attendance_status='present');renderRoster();});$('clearMarks')?.addEventListener('click',()=>{if(!ctx.canWrite)return;currentRoster.forEach(p=>p.attendance_status=null);renderRoster();});$('saveAttendance')?.addEventListener('click',saveAttendance);$('signOut')?.addEventListener('click',async()=>{await supabase.auth.signOut();location.href='/';});boot().catch(e=>{$('deniedText').textContent=e.message||'No pudimos abrir Asistencia.';show('deniedView');});
