import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://pacnegivzgxpanphrnwp.supabase.co','sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',{auth:{persistSession:true,autoRefreshToken:true}});const $=id=>document.getElementById(id);let ctx=null,matches=[],current=null,canWrite=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function show(id){['loadingView','deniedView','view'].forEach(v=>$(v)?.classList.toggle('hidden',v!==id));}function msg(t='',type='error'){const e=$('rosterMessage');e.textContent=t;e.dataset.type=type;e.classList.toggle('hidden',!t);}async function rpc(n,p={}){const {data,error}=await supabase.rpc(n,p);if(error)throw error;return data;}
function isoDate(d){return d.toISOString().slice(0,10);}function friendly(e){const t=String(e?.message||e||'Error');const map={'Not authorized':'No tienes permiso para Convocatoria.','Only scheduled matches can change callups':'La convocatoria ya está cerrada porque el partido no está programado.','Player is outside match category':'Ese Tanner no pertenece a la categoría del partido.','Player is not active':'Ese Tanner ya no está activo.'};return map[t]||t;}
async function boot(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/v2';return;}const rows=await rpc('v2_my_context');if(!rows?.length){$('deniedText').textContent='Sin organización.';show('deniedView');return;}ctx=rows[0];const mods=await rpc('v2_my_modules',{organization_id:ctx.organization_id}),mod=mods.find(m=>m.module_code==='callups');if(!mod?.enabled||!mod?.can_read){$('deniedText').textContent='Tu rol no tiene acceso a Convocatoria.';show('deniedView');return;}canWrite=!!mod.can_write;$('orgName').textContent=ctx.organization_name||'Tannery City FC';$('roleBadge').textContent=ctx.is_owner?'Propietario':ctx.role;await loadMatches();show('view');}
async function loadMatches(){const from=new Date();from.setDate(from.getDate()-7);const to=new Date();to.setMonth(to.getMonth()+4);matches=await rpc('v2_matches',{organization_id:ctx.organization_id,from_date:isoDate(from),to_date:isoDate(to)})||[];matches=matches.filter(m=>m.status==='scheduled').sort((a,b)=>String(a.date).localeCompare(String(b.date)));renderMatches();}
function renderMatches(){const box=$('matchList');box.innerHTML='';$('matchEmpty').classList.toggle('hidden',matches.length>0);matches.forEach(m=>{const b=document.createElement('button');b.type='button';b.className=`callup-match ${current?.match?.id===m.id?'selected':''}`;b.innerHTML=`<strong>${esc(m.date||'Sin fecha')} · vs ${esc(m.opponent||'Rival')}</strong><span>${esc([m.category,m.tournament,m.phase,m.location].filter(Boolean).join(' · '))}</span>`;b.onclick=()=>openMatch(m.id);box.appendChild(b);});}
async function openMatch(id){msg();current=await rpc('v2_callup_roster',{organization_id:ctx.organization_id,match_id:id});$('rosterEmpty').classList.add('hidden');$('rosterView').classList.remove('hidden');$('matchTitle').textContent=`vs ${current.match.opponent||'Rival'}`;$('matchMeta').textContent=[current.match.date,current.match.category,current.match.tournament,current.match.phase,current.match.location].filter(Boolean).join(' · ');renderMatches();renderRoster();}
function filteredRoster(){const q=$('rosterSearch').value.trim().toLocaleLowerCase('es-MX');return (current?.roster||[]).filter(p=>!q||`${p.code||''} ${p.name||''} ${p.position||''} ${p.jerseyNumber||''}`.toLocaleLowerCase('es-MX').includes(q));}
function renderRoster(){if(!current)return;const all=current.roster||[],selected=all.filter(p=>p.selected).length;$('selectedCount').textContent=selected;$('eligibleCount').textContent=all.length;const box=$('rosterList');box.innerHTML='';filteredRoster().forEach(p=>{const row=document.createElement('article');row.className=`roster-row ${p.selected?'selected':''}`;row.innerHTML=`<label><input class="callup-check" type="checkbox" ${p.selected?'checked':''} ${canWrite?'':'disabled'}><span><strong>${p.jerseyNumber?`#${esc(p.jerseyNumber)} · `:''}${esc(p.name)}</strong><small>${esc([p.code,p.position,p.category].filter(Boolean).join(' · '))}</small></span></label><input class="callup-note" maxlength="200" placeholder="Nota opcional" value="${esc(p.notes||'')}" ${canWrite?'':'disabled'}>`;const check=row.querySelector('.callup-check'),note=row.querySelector('.callup-note');check.onchange=()=>save(p.playerId,check.checked,note.value);note.onchange=()=>save(p.playerId,check.checked,note.value);box.appendChild(row);});}
async function save(playerId,selected,notes){if(!current||!canWrite)return;msg();try{await rpc('v2_set_callup',{organization_id:ctx.organization_id,match_id:current.match.id,player_id:playerId,selected,notes:notes.trim()||null});current=await rpc('v2_callup_roster',{organization_id:ctx.organization_id,match_id:current.match.id});renderRoster();msg('Convocatoria actualizada.','success');}catch(e){msg(friendly(e));await openMatch(current.match.id);}}
async function bulk(selected){if(!current||!canWrite)return;const targets=(current.roster||[]).filter(p=>p.selected!==selected);for(const p of targets){await rpc('v2_set_callup',{organization_id:ctx.organization_id,match_id:current.match.id,player_id:p.playerId,selected,notes:p.notes||null});}current=await rpc('v2_callup_roster',{organization_id:ctx.organization_id,match_id:current.match.id});renderRoster();msg(selected?'Roster completo convocado.':'Convocatoria limpiada.','success');}
$('rosterSearch').addEventListener('input',renderRoster);$('selectAll').addEventListener('click',()=>bulk(true).catch(e=>msg(friendly(e))));$('clearAll').addEventListener('click',()=>bulk(false).catch(e=>msg(friendly(e))));boot().catch(e=>{$('deniedText').textContent=friendly(e);show('deniedView');});