import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://pacnegivzgxpanphrnwp.supabase.co','sb_publishable_XG-mi_NVeit5BSco9t9AaQ_pk8CU0QG',{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);let ctx=null,players=[],matches=[],playerSports=null,canPlayersWrite=false,canCalendarWrite=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function show(id){['loadingView','deniedView','view'].forEach(v=>$(v)?.classList.toggle('hidden',v!==id));}
function msg(id,t='',type='error'){const e=$(id);if(!e)return;e.textContent=t;e.dataset.type=type;e.classList.toggle('hidden',!t);}
async function rpc(n,p={}){const {data,error}=await supabase.rpc(n,p);if(error)throw error;return data;}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function playerName(p){return [p.first_name,p.last_name].filter(Boolean).join(' ').trim()||p.code||'Tanner';}
function friendly(e){const t=String(e?.message||e||'Error');const map={'Not authorized':'No tienes permiso para esta operación.','Match date required':'Selecciona la fecha del partido.','Opponent required':'Escribe el rival.','Goals cannot be negative':'Los goles no pueden ser negativos.','Match stats cannot be negative':'Las estadísticas no pueden ser negativas.','Unattended player cannot have match performance':'Si el Tanner no asistió, no puede registrar minutos, titularidad, goles, tarjetas o atajadas.','Evaluation date required':'Selecciona la fecha de evaluación.','Evaluation score out of range':'Las evaluaciones deben estar entre 0 y 10.','Goalkeeper score out of range':'Las evaluaciones de portero deben estar entre 0 y 10.','Note text required':'Escribe la nota del Tanner.','Player not found':'No encontramos ese Tanner.','Match not found':'No encontramos ese partido.'};return map[t]||t;}
function fillPlayerSelect(id){const s=$(id),current=s.value;s.innerHTML='<option value="">Selecciona un Tanner</option>';[...players].sort((a,b)=>playerName(a).localeCompare(playerName(b),'es-MX')).forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=`${playerName(p)}${p.category?` · ${p.category}`:''}`;s.appendChild(o);});if(current&&players.some(p=>p.id===current))s.value=current;}
function fillMatchSelect(){const s=$('statMatch'),current=s.value;s.innerHTML='<option value="">Selecciona</option>';matches.forEach(m=>{const o=document.createElement('option');o.value=m.id;o.textContent=`${m.date||'Sin fecha'} · ${m.opponent||'Rival'}${m.category?` · ${m.category}`:''}`;s.appendChild(o);});if(current&&matches.some(m=>m.id===current))s.value=current;}
async function boot(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/v2';return;}const rows=await rpc('v2_my_context');if(!rows?.length){$('deniedText').textContent='Sin organización.';show('deniedView');return;}ctx=rows[0];const mods=await rpc('v2_my_modules',{organization_id:ctx.organization_id});const playersMod=mods.find(m=>m.module_code==='players'),calendarMod=mods.find(m=>m.module_code==='calendar');if(!playersMod?.enabled||!playersMod?.can_read){$('deniedText').textContent='Tu rol no tiene acceso al historial deportivo de jugadores.';show('deniedView');return;}canPlayersWrite=!!playersMod.can_write;canCalendarWrite=!!calendarMod?.enabled&&!!calendarMod?.can_write;$('orgName').textContent=ctx.organization_name||'Tannery City FC';$('roleBadge').textContent=ctx.is_owner?'Propietario':ctx.role;$('matchPanel').classList.toggle('hidden',!canCalendarWrite);$('statPanel').classList.toggle('hidden',!canCalendarWrite);$('evaluationPanel').classList.toggle('hidden',!canPlayersWrite);$('notePanel').classList.toggle('hidden',!canPlayersWrite);$('matchDate').value=today();$('evalDate').value=today();$('noteDate').value=today();await loadBase();show('view');}
async function loadBase(){const [p,m]=await Promise.all([rpc('v2_players',{organization_id:ctx.organization_id,status_filter:'active'}),rpc('v2_matches',{organization_id:ctx.organization_id,from_date:null,to_date:null})]);players=Array.isArray(p)?p:[];matches=Array.isArray(m)?m:[];['playerSelect','statPlayer','evalPlayer','notePlayer'].forEach(fillPlayerSelect);fillMatchSelect();renderMatches();const current=$('playerSelect').value;if(current)await loadPlayerSports(current);}
function renderMatches(){const box=$('matchList');box.innerHTML='';$('matchEmpty').classList.toggle('hidden',matches.length>0);matches.forEach(m=>{const row=document.createElement('article');row.className='match-card';const score=(m.goalsFor!=null||m.goalsAgainst!=null)?`${m.goalsFor??'–'} - ${m.goalsAgainst??'–'}`:(m.result||'—');row.innerHTML=`<div><strong>${esc(m.opponent||'Rival')}</strong><span>${esc(m.date||'Sin fecha')}${m.category?` · ${esc(m.category)}`:''}${m.tournament?` · ${esc(m.tournament)}`:''}</span><small>${esc([m.phase,m.location].filter(Boolean).join(' · '))}</small></div><div class="match-side"><b>${esc(score)}</b><small>${Number(m.statsCount||0)} registro(s)</small>${canCalendarWrite?`<button class="secondary mini use-match" type="button" data-id="${esc(m.id)}">Capturar stats</button>`:''}</div>`;box.appendChild(row);});box.querySelectorAll('.use-match').forEach(b=>b.addEventListener('click',()=>{$('statMatch').value=b.dataset.id;$('statPanel').scrollIntoView({behavior:'smooth',block:'start'});}));}
async function loadPlayerSports(playerId){if(!playerId){playerSports=null;renderPlayerSports();return;}playerSports=await rpc('v2_player_sports',{organization_id:ctx.organization_id,player_id:playerId});renderPlayerSports();}
function renderPlayerSports(){const s=playerSports?.summary||{};$('kpiPlayed').textContent=playerSports?Number(s.played||0):'—';$('kpiMinutes').textContent=playerSports?Number(s.minutes||0):'—';$('kpiGoals').textContent=playerSports?Number(s.goals||0):'—';$('kpiAssists').textContent=playerSports?Number(s.assists||0):'—';$('kpiCards').textContent=playerSports?`${Number(s.yellow||0)}A · ${Number(s.red||0)}R`:'—';$('kpiSaves').textContent=playerSports?Number(s.saves||0):'—';renderHistory('recentMatches',playerSports?.recentMatches||[],'match');renderHistory('evaluationHistory',playerSports?.evaluations||[],'evaluation');renderHistory('noteHistory',playerSports?.notes||[],'note');}
function renderHistory(id,rows,type){const box=$(id);box.innerHTML='';if(!rows.length){box.innerHTML='<div class="mini-empty">Sin registros.</div>';return;}rows.slice(0,12).forEach(r=>{const el=document.createElement('article');el.className='history-card';if(type==='match'){const tags=[r.starter?'Titular':'',r.goals?`${r.goals} gol(es)`:null,r.assists?`${r.assists} asistencia(s)`:null].filter(Boolean).join(' · ');el.innerHTML=`<strong>${esc(r.date||'')} · ${esc(r.opponent||'Rival')}</strong><span>${r.attended?`${Number(r.minutes||0)} min`:'No jugó'}${tags?` · ${esc(tags)}`:''}</span>`;}else if(type==='evaluation'){const vals=Object.entries(r.scores||{}).filter(([k,v])=>k!=='goalkeeper'&&typeof v==='number').map(([k,v])=>`${k}: ${v}`).join(' · ');el.innerHTML=`<strong>${esc(r.date||'')} ${r.period?`· ${esc(r.period)}`:''}</strong><span>${esc(vals||'Evaluación registrada')}</span>${r.sportsObjective?`<small>Objetivo: ${esc(r.sportsObjective)}</small>`:''}`;}else{el.innerHTML=`<strong>${esc(r.date||'')} ${r.context?`· ${esc(r.context)}`:''}</strong><span>${esc(r.text||'')}</span><small>${esc(r.author||'')}</small>`;}box.appendChild(el);});}
async function saveMatch(e){e.preventDefault();msg('matchMessage');const btn=$('saveMatch');btn.disabled=true;try{await rpc('v2_upsert_match',{organization_id:ctx.organization_id,match_id:null,match_date:$('matchDate').value,category:$('matchCategory').value.trim()||null,opponent:$('matchOpponent').value.trim(),tournament:$('matchTournament').value.trim()||null,phase:$('matchPhase').value.trim()||null,location:$('matchLocation').value.trim()||null,result:$('matchResult').value.trim()||null,goals_for:$('goalsFor').value===''?null:Number($('goalsFor').value),goals_against:$('goalsAgainst').value===''?null:Number($('goalsAgainst').value),status:$('matchStatus').value,notes:$('matchNotes').value.trim()||null});e.target.reset();$('matchDate').value=today();$('matchStatus').value='scheduled';await loadBase();msg('matchMessage','Partido guardado.','success');}catch(err){msg('matchMessage',friendly(err));}finally{btn.disabled=!canCalendarWrite;}}
function zeroPerformanceIfAbsent(){if($('attended').checked)return;$('starter').checked=false;$('cleanSheet').checked=false;['minutes','statGoals','statAssists','yellow','red','saves'].forEach(id=>$(id).value='0');}
async function saveStat(e){e.preventDefault();msg('statMessage');zeroPerformanceIfAbsent();const btn=$('saveStat');btn.disabled=true;try{const playerId=$('statPlayer').value;await rpc('v2_upsert_match_stat',{organization_id:ctx.organization_id,match_id:$('statMatch').value,player_id:playerId,attended:$('attended').checked,starter:$('starter').checked,minutes:Number($('minutes').value||0),goals:Number($('statGoals').value||0),assists:Number($('statAssists').value||0),yellow:Number($('yellow').value||0),red:Number($('red').value||0),saves:Number($('saves').value||0),clean_sheet:$('cleanSheet').checked,notes:$('statNotes').value.trim()||null});await loadBase();if($('playerSelect').value===playerId)await loadPlayerSports(playerId);msg('statMessage','Rendimiento guardado. Repetir este Tanner/partido actualiza el registro.','success');}catch(err){msg('statMessage',friendly(err));}finally{btn.disabled=!canCalendarWrite;}}
function score(id){return $(id).value===''?null:Number($(id).value);}
async function saveEvaluation(e){e.preventDefault();msg('evalMessage');const btn=$('saveEvaluation');btn.disabled=true;try{const playerId=$('evalPlayer').value;const scores={tecnica:score('tec'),inteligencia:score('intel'),intensidad:score('intensity'),mentalidad:score('mental'),valores:score('values'),goalkeeper:{manos:score('gkHands'),colocacion:score('gkPosition'),aereo:score('gkAir'),pies:score('gkFeet'),mando:score('gkCommand')}};await rpc('v2_upsert_player_evaluation',{organization_id:ctx.organization_id,evaluation_id:null,player_id:playerId,period:$('evalPeriod').value.trim()||null,evaluated_on:$('evalDate').value,scores,sports_objective:$('sportsObjective').value.trim()||null,formative_objective:$('formativeObjective').value.trim()||null,notes:$('evalNotes').value.trim()||null});e.target.reset();$('evalDate').value=today();if($('playerSelect').value===playerId)await loadPlayerSports(playerId);msg('evalMessage','Evaluación guardada.','success');}catch(err){msg('evalMessage',friendly(err));}finally{btn.disabled=!canPlayersWrite;}}
async function saveNote(e){e.preventDefault();msg('noteMessage');const btn=$('saveNote');btn.disabled=true;try{const playerId=$('notePlayer').value;await rpc('v2_upsert_player_note',{organization_id:ctx.organization_id,note_id:null,player_id:playerId,note_date:$('noteDate').value,context:$('noteContext').value.trim()||null,note_text:$('noteText').value.trim()});e.target.reset();$('noteDate').value=today();if($('playerSelect').value===playerId)await loadPlayerSports(playerId);msg('noteMessage','Nota guardada.','success');}catch(err){msg('noteMessage',friendly(err));}finally{btn.disabled=!canPlayersWrite;}}
$('playerSelect').addEventListener('change',e=>loadPlayerSports(e.target.value));$('matchForm').addEventListener('submit',saveMatch);$('statForm').addEventListener('submit',saveStat);$('attended').addEventListener('change',zeroPerformanceIfAbsent);$('evaluationForm').addEventListener('submit',saveEvaluation);$('noteForm').addEventListener('submit',saveNote);$('refresh').addEventListener('click',loadBase);boot().catch(e=>{$('deniedText').textContent=friendly(e);show('deniedView');});