-- Centro Tanner: catálogo completo de políticas (1-133) del Contexto Maestro
-- entregado por Presidencia (Centro_Tanner_Contexto_Maestro_v1.0.docx).
-- Contenido oficial verbatim; solo se calculó categoría, slug y una
-- respuesta corta (primeras oraciones del texto oficial, sin agregar
-- información nueva). Las políticas 134-141 del documento son
-- instrucciones para el agente/implementación, no reglas del club, así
-- que no se publican. La política 142 (Pagos y servicios no acumulables)
-- ya estaba cargada en la migración de seed inicial.

insert into app.policies (
  organization_id, policy_code, slug, title, category, scope, short_answer,
  official_content, keywords, status, requires_acceptance, effective_date, published_at
)
select o.id, v.policy_code, v.slug, v.title, v.category, v.scope, v.short_answer,
  v.official_content, v.keywords, 'published', false, date '2026-09-09', timestamptz '2026-09-09 19:07:52+00'
from public.organizations o
cross join (values
($$TC-001$$, $$inscripcion$$, $$Inscripción$$, $$inscripcion$$, $$tannery_city$$, $$Costo de inscripción Tannery City: $800 MXN. Se paga al ingresar por primera vez y no existe reinscripción anual mientras el jugador permanezca activo.$$, $$Costo de inscripción Tannery City: $800 MXN. Se paga al ingresar por primera vez y no existe reinscripción anual mientras el jugador permanezca activo. En el cambio formal Baby Tanners → Tanners se paga una nueva inscripción correspondiente a la nueva etapa. Si un jugador se da de baja y quiere regresar, debe cubrir adeudos pendientes y pagar nuevamente la inscripción vigente, salvo acuerdo especial autorizado por Presidencia. Con 2 meses consecutivos sin asistir y sin acuerdo autorizado, podrá considerarse dado de baja.$$, array[$$inscripción$$]),
($$TC-002$$, $$baja-voluntaria$$, $$Baja voluntaria$$, $$inscripcion$$, $$tannery_city$$, $$La familia deberá comunicar la baja a Administración o Área Deportiva. Se recomienda avisar mínimo 1–2 semanas antes y aproximadamente 1 mes antes si existe torneo o compromiso deportivo importante.$$, $$La familia deberá comunicar la baja a Administración o Área Deportiva. Se recomienda avisar mínimo 1–2 semanas antes y aproximadamente 1 mes antes si existe torneo o compromiso deportivo importante. No existen devoluciones por mensualidades ya pagadas; el jugador puede continuar durante el periodo cubierto.$$, array[$$baja$$,$$voluntaria$$]),
($$TC-003$$, $$mensualidades$$, $$Mensualidades$$, $$mensualidades$$, $$tannery_city$$, $$Tanners: $800 MXN mensuales. Baby Tanners 1 día por semana: $400 MXN mensuales. Baby Tanners 2 días por semana: $550 MXN mensuales.$$, $$Tanners: $800 MXN mensuales. Baby Tanners 1 día por semana: $400 MXN mensuales. Baby Tanners 2 días por semana: $550 MXN mensuales.$$, array[$$mensualidades$$]),
($$TC-004$$, $$fecha-de-pago-y-recargos$$, $$Fecha de pago y recargos$$, $$mensualidades$$, $$tannery_city$$, $$La mensualidad debe pagarse a más tardar el día 5. Desde el día 6 se agrega un recargo único de $100 MXN a esa mensualidad.$$, $$La mensualidad debe pagarse a más tardar el día 5. Desde el día 6 se agrega un recargo único de $100 MXN a esa mensualidad. El mismo adeudo no genera $100 adicionales cada mes. Ejemplo Tanners: $800 + $100 = $900. Al iniciar el siguiente mes se agrega la nueva mensualidad correspondiente.$$, array[$$fecha$$,$$pago$$,$$recargos$$]),
($$TC-005$$, $$adeudos$$, $$Adeudos$$, $$mensualidades$$, $$tannery_city$$, $$Primer mes vencido: seguimiento de Administración. Segundo mes: contacto directo con la familia.$$, $$Primer mes vencido: seguimiento de Administración. Segundo mes: contacto directo con la familia. Primera semana del tercer mes: el jugador puede tener suspensión temporal de entrenamientos y actividades hasta liquidar o establecer acuerdo autorizado por Dirección/Presidencia. El adeudo no desaparece por darse de baja. Para reingreso: liquidar adeudo + nueva inscripción, salvo acuerdo de Presidencia.$$, array[$$adeudos$$]),
($$TC-006$$, $$devoluciones$$, $$Devoluciones$$, $$mensualidades$$, $$tannery_city$$, $$Inscripciones, mensualidades y cuotas ya pagadas generalmente no son reembolsables. Solo podrán revisarse errores de cobro atribuibles al club y casos extraordinarios autorizados por Presidencia.$$, $$Inscripciones, mensualidades y cuotas ya pagadas generalmente no son reembolsables. Solo podrán revisarse errores de cobro atribuibles al club y casos extraordinarios autorizados por Presidencia.$$, array[$$devoluciones$$]),
($$TC-007$$, $$prorrateo$$, $$Prorrateo$$, $$mensualidades$$, $$tannery_city$$, $$Cuando un jugador ingresa a mitad de mes se calcula prorrateo por semanas usando base administrativa de 4 semanas por mes.$$, $$Cuando un jugador ingresa a mitad de mes se calcula prorrateo por semanas usando base administrativa de 4 semanas por mes. Ejemplo Tanners: $800 ÷ 4 = $200 por semana.$$, array[$$prorrateo$$]),
($$TC-008$$, $$vacaciones$$, $$Vacaciones$$, $$mensualidades$$, $$tannery_city$$, $$Para garantizar el lugar dentro del equipo el jugador debe mantener activa su mensualidad.$$, $$Para garantizar el lugar dentro del equipo el jugador debe mantener activa su mensualidad. Una familia con tarifa ordinaria completa puede solicitar Apoyo por Vacaciones: máximo 1 vez por año, mensualidad reducida al 50% durante el mes autorizado y sujeto a autorización de Dirección/Administración. Al pagar el 50% conserva su lugar. Jugadores con beca, Curtibrother, beneficio familiar, convenio o tarifa especial deben revisar el apoyo directamente con Administración.$$, array[$$vacaciones$$]),
($$TC-009$$, $$beneficio-familiar-hermanos-tanners$$, $$Beneficio familiar hermanos Tanners$$, $$becas$$, $$tannery_city$$, $$Nombre oficial: Beneficio Familiar Hermanos Tanners; no llamarlo beca. Solo aplica a hermanos del mismo núcleo familiar, no a primos, amigos o familia extendida.$$, $$Nombre oficial: Beneficio Familiar Hermanos Tanners; no llamarlo beca. Solo aplica a hermanos del mismo núcleo familiar, no a primos, amigos o familia extendida. Tarifas: 1 Tanner $800; 2 hermanos Tanners $1,500 total; 3 hermanos Tanners $2,000 total; 2 Baby Tanners $1,000 total; 1 Tanner + 1 Baby Tanner $1,200 total. Si un hermano se da de baja, el precio se actualiza al siguiente mes. No inventar combinaciones no definidas: consultar Administración/Presidencia.$$, array[$$beneficio$$,$$familiar$$,$$hermanos$$,$$tanners$$]),
($$TC-010$$, $$becas$$, $$Becas$$, $$becas$$, $$tannery_city$$, $$Tipos: parcial, total, Curtibrother y Beneficio Familiar Hermanos Tanners (este último no es beca deportiva).$$, $$Tipos: parcial, total, Curtibrother y Beneficio Familiar Hermanos Tanners (este último no es beca deportiva). Puede solicitarse evaluación después de 3 meses en el club. Se consideran talento, potencial, asistencia, disciplina, actitud, liderazgo, compromiso familiar, competencias, situación económica, comportamiento y desarrollo. Presidencia determina porcentaje. Primera asignación: 3 meses; renovaciones: hasta 6 meses sujetas a evaluación. Asistencia recomendada: 90%. La beca cubre únicamente el porcentaje autorizado de mensualidad y no incluye automáticamente inscripción, uniformes, arbitrajes, torneos, viajes, transporte, servicios externos o productos. Puede perderse por inasistencia, indisciplina, incumplimiento, falta de compromiso, faltas graves o conducta contraria a valores Tanner. Una falta grave puede causar pérdida inmediata. El ajuste económico normalmente aplica a partir del siguiente mes. Decisión final: Presidencia.$$, array[$$becas$$]),
($$TC-011$$, $$curtibrother$$, $$Curtibrother$$, $$becas$$, $$tannery_city$$, $$Programa distinto a una beca ordinaria. Un tercero, empresa o persona puede financiar el desarrollo de un Tanner.$$, $$Programa distinto a una beca ordinaria. Un tercero, empresa o persona puede financiar el desarrollo de un Tanner. Puede incluir beneficios acordados de reconocimiento, marketing, exposición, activaciones y relación con el club. Sus condiciones se rigen por el programa Curtibrother vigente.$$, array[$$curtibrother$$]),
($$TC-012$$, $$que-incluye-la-mensualidad$$, $$Qué incluye la mensualidad$$, $$mensualidades$$, $$tannery_city$$, $$Entrenamientos programados de la categoría, uso de cancha durante sesiones, entrenadores/cuerpo técnico, material deportivo ordinario, planeación, metodología Tannery City y seguimiento deportivo ordinario.$$, $$Entrenamientos programados de la categoría, uso de cancha durante sesiones, entrenadores/cuerpo técnico, material deportivo ordinario, planeación, metodología Tannery City y seguimiento deportivo ordinario.$$, array[$$qué$$,$$incluye$$,$$mensualidad$$]),
($$TC-013$$, $$que-no-incluye-la-mensualidad$$, $$Qué no incluye la mensualidad$$, $$mensualidades$$, $$tannery_city$$, $$No incluye automáticamente inscripción, uniformes, academia especializada de porteros, arbitrajes, amistosos con costos extraordinarios, cuotas de torneos, competencias extraordinarias, viajes, transporte, hospedaje, peajes, sesiones privadas, fisioterapia, servicios externos o productos de tienda.$$, $$No incluye automáticamente inscripción, uniformes, academia especializada de porteros, arbitrajes, amistosos con costos extraordinarios, cuotas de torneos, competencias extraordinarias, viajes, transporte, hospedaje, peajes, sesiones privadas, fisioterapia, servicios externos o productos de tienda.$$, array[$$qué$$,$$incluye$$,$$mensualidad$$]),
($$TC-014$$, $$asistencia$$, $$Asistencia$$, $$asistencia$$, $$tannery_city$$, $$Objetivo mínimo jugador ordinario: 80%. Jugador con beca: 90%. Las ausencias deben notificarse previamente cuando sea posible.$$, $$Objetivo mínimo jugador ordinario: 80%. Jugador con beca: 90%. Las ausencias deben notificarse previamente cuando sea posible. Pueden justificarse por enfermedad, lesión, compromiso escolar, emergencia familiar o viaje avisado. Una ausencia justificada puede evitar sanción disciplinaria, pero sigue contando estadísticamente como ausencia.$$, array[$$asistencia$$]),
($$TC-015$$, $$retardos$$, $$Retardos$$, $$asistencia$$, $$tannery_city$$, $$Los retardos recurrentes primero se revisan con la familia. Si continúan, Área Deportiva puede determinar medidas internas según categoría y situación.$$, $$Los retardos recurrentes primero se revisan con la familia. Si continúan, Área Deportiva puede determinar medidas internas según categoría y situación. Pueden afectar titularidad, decisiones deportivas, minutos y participación competitiva.$$, array[$$retardos$$]),
($$TC-016$$, $$semana-muestra$$, $$Semana muestra$$, $$inscripcion$$, $$tannery_city$$, $$Solo puede usarse una vez por jugador. Tanners: 3 entrenamientos. Baby Tanners: 2 entrenamientos. Durante la semana muestra se usa la indumentaria indicada por el club si aún no existe uniforme oficial.$$, $$Solo puede usarse una vez por jugador. Tanners: 3 entrenamientos. Baby Tanners: 2 entrenamientos. Durante la semana muestra se usa la indumentaria indicada por el club si aún no existe uniforme oficial.$$, array[$$semana$$,$$muestra$$]),
($$TC-017$$, $$baby-tanners$$, $$Baby Tanners$$, $$baby_tanners$$, $$tannery_city$$, $$Edad mínima: 3 años cumplidos. Padre/madre/tutor debe permanecer en Tannery City Park durante la sesión.$$, $$Edad mínima: 3 años cumplidos. Padre/madre/tutor debe permanecer en Tannery City Park durante la sesión. Transición aproximada hacia Tanners alrededor de los 6 años según edad, evaluación deportiva, madurez y adaptación. Área Deportiva puede decidir permanencia temporal en Baby Tanners.$$, array[$$baby$$,$$tanners$$]),
($$TC-018$$, $$documentacion-obligatoria$$, $$Documentación obligatoria$$, $$jugadores$$, $$tannery_city$$, $$CURP, acta de nacimiento, comprobante de estudios, foto actual, datos de contacto, contactos de emergencia, información médica relevante, alergias/condiciones y certificado médico deportivo anual.$$, $$CURP, acta de nacimiento, comprobante de estudios, foto actual, datos de contacto, contactos de emergencia, información médica relevante, alergias/condiciones y certificado médico deportivo anual. Falta de documentación puede impedir inscripción a torneos, trámites o procesos administrativos.$$, array[$$documentación$$,$$obligatoria$$]),
($$TC-019$$, $$actualizacion-de-datos$$, $$Actualización de datos$$, $$familias$$, $$tannery_city$$, $$La familia debe actualizar cambios de domicilio, escuela, teléfono, tutor, contacto de emergencia, alergias, condición médica e información relevante.$$, $$La familia debe actualizar cambios de domicilio, escuela, teléfono, tutor, contacto de emergencia, alergias, condición médica e información relevante. Información falsa puede generar aclaración, amonestación, suspensión o revisión de permanencia según gravedad.$$, array[$$actualización$$,$$datos$$]),
($$TC-020$$, $$informacion-medica-en-tanner-os$$, $$Información médica en Tanner OS$$, $$salud$$, $$tannery_city$$, $$Entrenadores autorizados solo podrán consultar información necesaria para atención y operación deportiva: nombre, apellidos, fecha de nacimiento, categoría, posición, pierna dominante, escuela, tipo de sangre, alergias, condiciones, contacto de emergencia y estado documental.$$, $$Entrenadores autorizados solo podrán consultar información necesaria para atención y operación deportiva: nombre, apellidos, fecha de nacimiento, categoría, posición, pierna dominante, escuela, tipo de sangre, alergias, condiciones, contacto de emergencia y estado documental.$$, array[$$información$$,$$médica$$,$$tanner$$]),
($$TC-021$$, $$certificado-medico$$, $$Certificado médico$$, $$salud$$, $$tannery_city$$, $$Obligatorio una vez al año. El club puede pedir información adicional ante lesión importante, condición médica, regreso deportivo o necesidad especial.$$, $$Obligatorio una vez al año. El club puede pedir información adicional ante lesión importante, condición médica, regreso deportivo o necesidad especial.$$, array[$$certificado$$,$$médico$$]),
($$TC-022$$, $$lesiones$$, $$Lesiones$$, $$salud$$, $$tannery_city$$, $$Puede solicitarse congelamiento de mensualidad cuando una lesión impida entrenar por 1 mes completo o más.$$, $$Puede solicitarse congelamiento de mensualidad cuando una lesión impida entrenar por 1 mes completo o más. Requiere constancia médica. Aplica sobre meses posteriores completos y no genera devolución retroactiva por semanas ya transcurridas.$$, array[$$lesiones$$]),
($$TC-023$$, $$emergencia-medica$$, $$Emergencia médica$$, $$salud$$, $$tannery_city$$, $$Ante lesión: evaluar, retirar al jugador si es necesario, contactar tutor, seguir instrucciones y, ante emergencia real, solicitar atención médica inmediata.$$, $$Ante lesión: evaluar, retirar al jugador si es necesario, contactar tutor, seguir instrucciones y, ante emergencia real, solicitar atención médica inmediata. La seguridad del menor tiene prioridad mientras se intenta contactar a la familia.$$, array[$$emergencia$$,$$médica$$]),
($$TC-024$$, $$golpes-en-la-cabeza$$, $$Golpes en la cabeza$$, $$salud$$, $$tannery_city$$, $$Ante golpe significativo: retirar al jugador, no permitir regreso inmediato, observar síntomas, contactar tutor y solicitar atención médica cuando corresponda.$$, $$Ante golpe significativo: retirar al jugador, no permitir regreso inmediato, observar síntomas, contactar tutor y solicitar atención médica cuando corresponda.$$, array[$$golpes$$,$$cabeza$$]),
($$TC-025$$, $$enfermedad$$, $$Enfermedad$$, $$salud$$, $$tannery_city$$, $$Si hay síntomas evidentes de enfermedad o riesgo de contagio, el staff puede pedir que el jugador no participe y solicitar al tutor retirarlo.$$, $$Si hay síntomas evidentes de enfermedad o riesgo de contagio, el staff puede pedir que el jugador no participe y solicitar al tutor retirarlo.$$, array[$$enfermedad$$]),
($$TC-026$$, $$medicamentos$$, $$Medicamentos$$, $$salud$$, $$tannery_city$$, $$Preferentemente administrados por padre, madre o tutor. El personal solo puede intervenir con autorización e instrucción previa y clara.$$, $$Preferentemente administrados por padre, madre o tutor. El personal solo puede intervenir con autorización e instrucción previa y clara.$$, array[$$medicamentos$$]),
($$TC-027$$, $$responsabilidad-del-tutor$$, $$Responsabilidad del tutor$$, $$familias$$, $$tannery_city$$, $$Durante actividades, el tutor debe permanecer localizable. Si otra persona quedará a cargo, debe notificarse previamente.$$, $$Durante actividades, el tutor debe permanecer localizable. Si otra persona quedará a cargo, debe notificarse previamente.$$, array[$$responsabilidad$$,$$tutor$$]),
($$TC-028$$, $$entrega-y-salida-de-menores$$, $$Entrega y salida de menores$$, $$seguridad$$, $$tannery_city$$, $$Solo tutores registrados o adultos previamente autorizados pueden recoger al jugador. Si llega alguien distinto, confirmar con el tutor antes de entregar.$$, $$Solo tutores registrados o adultos previamente autorizados pueden recoger al jugador. Si llega alguien distinto, confirmar con el tutor antes de entregar. El jugador solo puede retirarse solo con autorización expresa del tutor.$$, array[$$entrega$$,$$salida$$,$$menores$$]),
($$TC-029$$, $$recogida-tardia$$, $$Recogida tardía$$, $$seguridad$$, $$tannery_city$$, $$Tolerancia recomendada máxima: 30 minutos. La familia debe recoger puntualmente. Mientras no se entregue a adulto autorizado, el club continuará procurando resguardo y contactará responsables.$$, $$Tolerancia recomendada máxima: 30 minutos. La familia debe recoger puntualmente. Mientras no se entregue a adulto autorizado, el club continuará procurando resguardo y contactará responsables. Reincidencias pueden generar medidas administrativas.$$, array[$$recogida$$,$$tardía$$]),
($$TC-030$$, $$partidos-amistosos-en-dia-de-entrenamiento$$, $$Partidos amistosos en día de entrenamiento$$, $$entrenamientos$$, $$tannery_city$$, $$Cuando sustituyan entrenamiento normal, la participación es opcional. Opción A: participar y cubrir conceptos correspondientes.$$, $$Cuando sustituyan entrenamiento normal, la participación es opcional. Opción A: participar y cubrir conceptos correspondientes. Opción B: entrenamiento alternativo. Para entrenamiento alternativo: avisar mínimo 48 h antes, tener mensualidad ordinaria completa y cuenta al corriente. Becas/convenios/tarifas especiales se revisan con Administración. El club procurará anunciar amistosos con al menos 24 h de anticipación cuando sea posible.$$, array[$$partidos$$,$$amistosos$$,$$día$$,$$entrenamiento$$]),
($$TC-031$$, $$torneos$$, $$Torneos$$, $$partidos$$, $$tannery_city$$, $$Participación opcional antes de confirmar inscripción. Una vez que la familia confirma, registra al jugador y acepta costos, se genera compromiso con la competencia.$$, $$Participación opcional antes de confirmar inscripción. Una vez que la familia confirma, registra al jugador y acepta costos, se genera compromiso con la competencia. Cuotas pagadas generalmente no son reembolsables si después se retiran. Excepciones por enfermedad, lesión o emergencia familiar pueden revisarse.$$, array[$$torneos$$]),
($$TC-032$$, $$costos-de-torneos$$, $$Costos de torneos$$, $$partidos$$, $$tannery_city$$, $$La cuota puede incluir inscripción, arbitrajes, operación y gastos relacionados. Dirección Deportiva y Administración determinan costo total y distribución entre participantes.$$, $$La cuota puede incluir inscripción, arbitrajes, operación y gastos relacionados. Dirección Deportiva y Administración determinan costo total y distribución entre participantes.$$, array[$$costos$$,$$torneos$$]),
($$TC-033$$, $$cancelacion-de-torneo$$, $$Cancelación de torneo$$, $$partidos$$, $$tannery_city$$, $$Si el organizador cancela, devolución depende del dinero efectivamente recuperado y de gastos no recuperables ya realizados.$$, $$Si el organizador cancela, devolución depende del dinero efectivamente recuperado y de gastos no recuperables ya realizados.$$, array[$$cancelación$$,$$torneo$$]),
($$TC-034$$, $$numero-minimo-para-torneo$$, $$Número mínimo para torneo$$, $$partidos$$, $$tannery_city$$, $$No hay un número universal. Dirección Deportiva lo determina según categoría, formato, competencia y necesidades deportivas.$$, $$No hay un número universal. Dirección Deportiva lo determina según categoría, formato, competencia y necesidades deportivas.$$, array[$$número$$,$$mínimo$$,$$torneo$$]),
($$TC-035$$, $$arbitrajes$$, $$Arbitrajes$$, $$partidos$$, $$tannery_city$$, $$Costo ordinario de referencia: $50 por jugador. Si hay baja participación puede ajustarse, por ejemplo a $70, según costos reales.$$, $$Costo ordinario de referencia: $50 por jugador. Si hay baja participación puede ajustarse, por ejemplo a $70, según costos reales. Paquete: 4 arbitrajes por $200, solo para partidos del torneo regular correspondiente; no incluye amistosos, otros torneos ni competencias adicionales. Un quinto partido puede cobrarse aparte. Normalmente se registran/cobran después del partido. Si un jugador participa y queda saldo pendiente: entrenador reporta → Administración registra → familia liquida.$$, array[$$arbitrajes$$]),
($$TC-036$$, $$participacion-y-minutos$$, $$Participación y minutos$$, $$partidos$$, $$tannery_city$$, $$Pagar torneo, arbitraje o mensualidad no garantiza titularidad, posición ni cantidad específica de minutos.$$, $$Pagar torneo, arbitraje o mensualidad no garantiza titularidad, posición ni cantidad específica de minutos. La intención es que convocados tengan participación. Las decisiones corresponden al Área Deportiva.$$, array[$$participación$$,$$minutos$$]),
($$TC-037$$, $$categorias$$, $$Categorías$$, $$jugadores$$, $$tannery_city$$, $$Un jugador puede ser invitado temporalmente a una categoría superior. No implica ascenso permanente, futuras convocatorias ni minutos garantizados.$$, $$Un jugador puede ser invitado temporalmente a una categoría superior. No implica ascenso permanente, futuras convocatorias ni minutos garantizados. Cambio permanente: Dirección Deportiva.$$, array[$$categorías$$]),
($$TC-038$$, $$otros-clubes$$, $$Otros clubes$$, $$jugadores$$, $$tannery_city$$, $$Un Tanner no debe participar simultáneamente con otra academia o club sin autorización. Sí puede representar a su escuela.$$, $$Un Tanner no debe participar simultáneamente con otra academia o club sin autorización. Sí puede representar a su escuela. Casos especiales con otro club: Dirección Deportiva / Presidencia.$$, array[$$otros$$,$$clubes$$]),
($$TC-039$$, $$convocatorias$$, $$Convocatorias$$, $$partidos$$, $$tannery_city$$, $$Pueden considerar asistencia, disciplina, puntualidad, compromiso, desempeño y necesidades deportivas.$$, $$Pueden considerar asistencia, disciplina, puntualidad, compromiso, desempeño y necesidades deportivas. Familias deben avisar si el jugador no puede asistir.$$, array[$$convocatorias$$]),
($$TC-040$$, $$llegada-a-partidos$$, $$Llegada a partidos$$, $$partidos$$, $$tannery_city$$, $$Jugadores deben presentarse aproximadamente 20 minutos antes. Llegar tarde puede afectar titularidad, minutos o participación según criterio deportivo.$$, $$Jugadores deben presentarse aproximadamente 20 minutos antes. Llegar tarde puede afectar titularidad, minutos o participación según criterio deportivo.$$, array[$$llegada$$,$$partidos$$])
) as v(policy_code, slug, title, category, scope, short_answer, official_content, keywords)
where o.public_key='1850TC1850'
  and not exists (select 1 from app.policies p where p.organization_id=o.id and p.slug=v.slug);

insert into app.policies (
  organization_id, policy_code, slug, title, category, scope, short_answer,
  official_content, keywords, status, requires_acceptance, effective_date, published_at
)
select o.id, v.policy_code, v.slug, v.title, v.category, v.scope, v.short_answer,
  v.official_content, v.keywords, 'published', false, date '2026-09-09', timestamptz '2026-09-09 19:07:52+00'
from public.organizations o
cross join (values
($$TC-041$$, $$regla-de-24-horas$$, $$Regla de 24 horas$$, $$conducta$$, $$tannery_city$$, $$Después de un partido se solicita esperar al menos 24 horas antes de presentar inconformidades sobre minutos, titularidad, posición o decisiones tácticas/técnicas.$$, $$Después de un partido se solicita esperar al menos 24 horas antes de presentar inconformidades sobre minutos, titularidad, posición o decisiones tácticas/técnicas. No aplica a seguridad, salud, agresiones o emergencias.$$, array[$$regla$$,$$horas$$]),
($$TC-042$$, $$evaluaciones-deportivas$$, $$Evaluaciones deportivas$$, $$jugadores$$, $$tannery_city$$, $$Padres pueden solicitar evaluación. Tannery City busca realizar evaluaciones trimestrales. Información individual privada; acceso a jugador, padre/tutor, staff autorizado, Dirección y Presidencia.$$, $$Padres pueden solicitar evaluación. Tannery City busca realizar evaluaciones trimestrales. Información individual privada; acceso a jugador, padre/tutor, staff autorizado, Dirección y Presidencia.$$, array[$$evaluaciones$$,$$deportivas$$]),
($$TC-043$$, $$clima$$, $$Clima$$, $$entrenamientos$$, $$tannery_city$$, $$Ante tormenta eléctrica se suspende actividad. Con lluvia, el club procurará informar aproximadamente 40 minutos antes si continúa o se suspende.$$, $$Ante tormenta eléctrica se suspende actividad. Con lluvia, el club procurará informar aproximadamente 40 minutos antes si continúa o se suspende. Si comienza durante la sesión, entrenador puede suspender. Cancelación por clima no genera automáticamente reposición. Si la cancelación es atribuible al club, Dirección evalúa reposición.$$, array[$$clima$$]),
($$TC-044$$, $$entrenamiento-con-pocos-jugadores$$, $$Entrenamiento con pocos jugadores$$, $$entrenamientos$$, $$tannery_city$$, $$Mínimo para impartir sesión: 1 jugador. Mientras la sesión esté oficialmente programada, el club entrenará al jugador presente.$$, $$Mínimo para impartir sesión: 1 jugador. Mientras la sesión esté oficialmente programada, el club entrenará al jugador presente.$$, array[$$entrenamiento$$,$$pocos$$,$$jugadores$$]),
($$TC-045$$, $$dias-festivos$$, $$Días festivos$$, $$entrenamientos$$, $$tannery_city$$, $$El club puede consultar disponibilidad mediante encuesta. Las encuestas son consultivas; decisión final corresponde al club.$$, $$El club puede consultar disponibilidad mediante encuesta. Las encuestas son consultivas; decisión final corresponde al club.$$, array[$$días$$,$$festivos$$]),
($$TC-046$$, $$calzado$$, $$Calzado$$, $$uniformes$$, $$tannery_city$$, $$Prohibidos tachones. Permitidos multitachos / calzado deportivo autorizado.$$, $$Prohibidos tachones. Permitidos multitachos / calzado deportivo autorizado.$$, array[$$calzado$$]),
($$TC-047$$, $$espinilleras$$, $$Espinilleras$$, $$uniformes$$, $$tannery_city$$, $$No obligatorias en entrenamiento ordinario; pueden utilizarse. En competencia se sigue también el reglamento correspondiente.$$, $$No obligatorias en entrenamiento ordinario; pueden utilizarse. En competencia se sigue también el reglamento correspondiente.$$, array[$$espinilleras$$]),
($$TC-048$$, $$hidratacion$$, $$Hidratación$$, $$entrenamientos$$, $$tannery_city$$, $$Cada jugador debe llevar agua o hidratación propia.$$, $$Cada jugador debe llevar agua o hidratación propia.$$, array[$$hidratación$$]),
($$TC-049$$, $$uniformes$$, $$Uniformes$$, $$uniformes$$, $$tannery_city$$, $$Tannery City maneja 4 jerseys oficiales en rotación. Cada 6 meses se renuevan 2 de los 4 diseños y los otros 2 siguen vigentes; en el siguiente ciclo se renueva la pareja restante.$$, $$Tannery City maneja 4 jerseys oficiales en rotación. Cada 6 meses se renuevan 2 de los 4 diseños y los otros 2 siguen vigentes; en el siguiente ciclo se renueva la pareja restante. El jugador debe contar con los uniformes designados para su ciclo. Si ya tiene un modelo vigente y en buenas condiciones, no necesita duplicado.$$, array[$$uniformes$$]),
($$TC-050$$, $$short-y-medias$$, $$Short y medias$$, $$uniformes$$, $$tannery_city$$, $$Estándar Tanner: short negro y medias blancas. Podrán renovarse cuando corresponda.$$, $$Estándar Tanner: short negro y medias blancas. Podrán renovarse cuando corresponda.$$, array[$$short$$,$$medias$$]),
($$TC-051$$, $$porteros$$, $$Porteros$$, $$uniformes$$, $$tannery_city$$, $$Cada portero debe contar con mínimo 2 uniformes de distinto color para diferenciarse según uniforme del equipo y competencia.$$, $$Cada portero debe contar con mínimo 2 uniformes de distinto color para diferenciarse según uniforme del equipo y competencia.$$, array[$$porteros$$]),
($$TC-052$$, $$olvido-de-uniforme$$, $$Olvido de uniforme$$, $$uniformes$$, $$tannery_city$$, $$Puede entrenar con playera negra, short negro y medias blancas. Primera incidencia: recordatorio. Reincidencia: puede generar amonestación/formación disciplinaria.$$, $$Puede entrenar con playera negra, short negro y medias blancas. Primera incidencia: recordatorio. Reincidencia: puede generar amonestación/formación disciplinaria. En becados, incumplimiento reiterado puede influir en renovación.$$, array[$$olvido$$,$$uniforme$$]),
($$TC-053$$, $$garantia-cambios-de-uniforme$$, $$Garantía / cambios de uniforme$$, $$uniformes$$, $$tannery_city$$, $$Primeros 3 días después de entrega: reportar anomalías a Tannery City. Posteriormente y hasta aproximadamente 30 días: seguimiento conforme garantía del proveedor.$$, $$Primeros 3 días después de entrega: reportar anomalías a Tannery City. Posteriormente y hasta aproximadamente 30 días: seguimiento conforme garantía del proveedor. No aplica automáticamente a mal uso, lavado incorrecto, modificaciones o desgaste normal.$$, array[$$garantía$$,$$cambios$$,$$uniforme$$]),
($$TC-054$$, $$objetos-personales$$, $$Objetos personales$$, $$seguridad$$, $$tannery_city$$, $$Tannery City no se responsabiliza por objetos personales no entregados formalmente a resguardo, como celular, dinero, reloj, chamarra o accesorios.$$, $$Tannery City no se responsabiliza por objetos personales no entregados formalmente a resguardo, como celular, dinero, reloj, chamarra o accesorios.$$, array[$$objetos$$,$$personales$$]),
($$TC-055$$, $$celulares$$, $$Celulares$$, $$conducta$$, $$tannery_city$$, $$Jugadores no deben usar celular durante entrenamiento salvo emergencia. Entrenador no confisca el dispositivo; puede pedir guardarlo y reportar reincidencias.$$, $$Jugadores no deben usar celular durante entrenamiento salvo emergencia. Entrenador no confisca el dispositivo; puede pedir guardarlo y reportar reincidencias.$$, array[$$celulares$$]),
($$TC-056$$, $$joyeria$$, $$Joyería$$, $$seguridad$$, $$tannery_city$$, $$Durante entrenamiento y partido no usar elementos que representen riesgo: cadenas, relojes, aretes o accesorios peligrosos.$$, $$Durante entrenamiento y partido no usar elementos que representen riesgo: cadenas, relojes, aretes o accesorios peligrosos.$$, array[$$joyería$$]),
($$TC-057$$, $$danos$$, $$Daños$$, $$conducta$$, $$tannery_city$$, $$Daño intencional o negligente a instalaciones, baños, mobiliario, material o propiedad del club puede ser cobrado a la persona/familia responsable.$$, $$Daño intencional o negligente a instalaciones, baños, mobiliario, material o propiedad del club puede ser cobrado a la persona/familia responsable.$$, array[$$daños$$]),
($$TC-058$$, $$material-deportivo$$, $$Material deportivo$$, $$entrenamientos$$, $$tannery_city$$, $$Fuera del entrenamiento no se presta material sin autorización. Después de sesión, quienes sigan jugando deben usar su propio balón.$$, $$Fuera del entrenamiento no se presta material sin autorización. Después de sesión, quienes sigan jugando deben usar su propio balón. Si un balón del club sale fuera debe recuperarse; cuando sea necesario, el menor lo hace acompañado por su tutor. Pérdida por incumplimiento puede generar responsabilidad de reposición.$$, array[$$material$$,$$deportivo$$]),
($$TC-059$$, $$uso-de-cancha-despues-de-entrenar$$, $$Uso de cancha después de entrenar$$, $$tannery_city_park$$, $$tannery_city$$, $$Puede permitirse permanecer jugando con disponibilidad y autorización. Referencia: hasta aproximadamente 19:00 hrs, sujeto a operación TCP.$$, $$Puede permitirse permanecer jugando con disponibilidad y autorización. Referencia: hasta aproximadamente 19:00 hrs, sujeto a operación TCP. Cuando la cancha se necesite, pueden ser canalizados a La Lechuguilla u otra zona disponible.$$, array[$$uso$$,$$cancha$$,$$después$$,$$entrenar$$]),
($$TC-060$$, $$conducta-de-jugadores$$, $$Conducta de jugadores$$, $$conducta$$, $$tannery_city$$, $$Principios: respeto, disciplina, esfuerzo, honestidad, responsabilidad y trabajo en equipo.$$, $$Principios: respeto, disciplina, esfuerzo, honestidad, responsabilidad y trabajo en equipo.$$, array[$$conducta$$,$$jugadores$$]),
($$TC-061$$, $$bullying-y-discriminacion$$, $$Bullying y discriminación$$, $$conducta$$, $$tannery_city$$, $$Política de cero tolerancia. Se atienden inmediatamente bullying, discriminación, intimidación, agresión y hostigamiento.$$, $$Política de cero tolerancia. Se atienden inmediatamente bullying, discriminación, intimidación, agresión y hostigamiento.$$, array[$$bullying$$,$$discriminación$$]),
($$TC-062$$, $$groserias-entre-jugadores$$, $$Groserías entre jugadores$$, $$conducta$$, $$tannery_city$$, $$Primera respuesta: corrección formativa. Reincidencias o gravedad: medidas deportivas/administrativas.$$, $$Primera respuesta: corrección formativa. Reincidencias o gravedad: medidas deportivas/administrativas.$$, array[$$groserías$$,$$jugadores$$]),
($$TC-063$$, $$agresion-fisica-entre-jugadores$$, $$Agresión física entre jugadores$$, $$conducta$$, $$tannery_city$$, $$Ruta: separación inmediata; revisión Área Deportiva; escuchar involucrados; comunicar con familias; seguimiento; sanción según gravedad.$$, $$Ruta: separación inmediata; revisión Área Deportiva; escuchar involucrados; comunicar con familias; seguimiento; sanción según gravedad.$$, array[$$agresión$$,$$física$$,$$jugadores$$]),
($$TC-064$$, $$padres-y-decisiones-tecnicas$$, $$Padres y decisiones técnicas$$, $$familias$$, $$tannery_city$$, $$Padres no pueden dar instrucciones técnicas desde fuera, elegir posición, exigir titularidad o minutos, ni sustituir decisiones del entrenador.$$, $$Padres no pueden dar instrucciones técnicas desde fuera, elegir posición, exigir titularidad o minutos, ni sustituir decisiones del entrenador. Decisiones deportivas corresponden al Área Deportiva. Interferencia reiterada puede generar amonestación o restricción.$$, array[$$padres$$,$$decisiones$$,$$técnicas$$]),
($$TC-065$$, $$acceso-a-cancha$$, $$Acceso a cancha$$, $$seguridad$$, $$tannery_city$$, $$Padres/familiares no pueden entrar a cancha sin autorización. Si un adulto entra después de indicación de no hacerlo, puede recibir amonestación.$$, $$Padres/familiares no pueden entrar a cancha sin autorización. Si un adulto entra después de indicación de no hacerlo, puede recibir amonestación.$$, array[$$acceso$$,$$cancha$$]),
($$TC-066$$, $$banca-y-zonas-restringidas$$, $$Banca y zonas restringidas$$, $$seguridad$$, $$tannery_city$$, $$Banca: jugadores convocados, entrenadores y staff autorizado. No padres, hermanos o acompañantes. Si un adulto se niega a retirarse: llamada de atención, reporte y revisión disciplinaria.$$, $$Banca: jugadores convocados, entrenadores y staff autorizado. No padres, hermanos o acompañantes. Si un adulto se niega a retirarse: llamada de atención, reporte y revisión disciplinaria.$$, array[$$banca$$,$$zonas$$,$$restringidas$$]),
($$TC-067$$, $$restriccion-a-un-adulto$$, $$Restricción a un adulto$$, $$conducta$$, $$tannery_city$$, $$Tannery City puede restringir temporalmente el acceso de padre, familiar o acompañante sin que esto signifique automáticamente baja del jugador.$$, $$Tannery City puede restringir temporalmente el acceso de padre, familiar o acompañante sin que esto signifique automáticamente baja del jugador.$$, array[$$restricción$$,$$adulto$$]),
($$TC-068$$, $$conducta-fuera-de-tcp$$, $$Conducta fuera de TCP$$, $$conducta$$, $$tannery_city$$, $$El Reglamento Tanner aplica cuando se representa al club en partidos de visita, torneos, viajes, eventos y convivencias oficiales, y cuando el jugador usa uniforme oficial en representación del club.$$, $$El Reglamento Tanner aplica cuando se representa al club en partidos de visita, torneos, viajes, eventos y convivencias oficiales, y cuando el jugador usa uniforme oficial en representación del club.$$, array[$$conducta$$,$$fuera$$,$$tcp$$]),
($$TC-069$$, $$arbitros-y-rivales$$, $$Árbitros y rivales$$, $$conducta$$, $$tannery_city$$, $$Familias no deben confrontar directamente árbitros, rivales, jugadores rivales o entrenadores rivales.$$, $$Familias no deben confrontar directamente árbitros, rivales, jugadores rivales o entrenadores rivales. Inconformidades se canalizan por staff del club.$$, array[$$árbitros$$,$$rivales$$]),
($$TC-070$$, $$tarjetas-y-sanciones-de-liga$$, $$Tarjetas y sanciones de liga$$, $$conducta$$, $$tannery_city$$, $$Una sanción externa puede generar medida interna Tannery City si la conducta lo amerita. Multas económicas se revisan caso por caso según reglamento, responsable y circunstancia.$$, $$Una sanción externa puede generar medida interna Tannery City si la conducta lo amerita. Multas económicas se revisan caso por caso según reglamento, responsable y circunstancia.$$, array[$$tarjetas$$,$$sanciones$$,$$liga$$]),
($$TC-071$$, $$sistema-de-amonestaciones$$, $$Sistema de amonestaciones$$, $$conducta$$, $$tannery_city$$, $$Primera: acta administrativa + seguimiento. Segunda: acta + reunión con Dirección + posible restricción temporal.$$, $$Primera: acta administrativa + seguimiento. Segunda: acta + reunión con Dirección + posible restricción temporal. Tercera: revisión de permanencia del jugador y/o familia.$$, array[$$sistema$$,$$amonestaciones$$]),
($$TC-072$$, $$faltas-graves$$, $$Faltas graves$$, $$conducta$$, $$tannery_city$$, $$Una conducta grave puede saltarse el sistema progresivo. Ejemplos: agresión física grave, amenazas, riesgo para menores, violencia, drogas, armas, conducta peligrosa y hostigamiento severo.$$, $$Una conducta grave puede saltarse el sistema progresivo. Ejemplos: agresión física grave, amenazas, riesgo para menores, violencia, drogas, armas, conducta peligrosa y hostigamiento severo. Presidencia puede ordenar restricción, suspensión o expulsión.$$, array[$$faltas$$,$$graves$$]),
($$TC-073$$, $$sanciones-entre-padre-y-jugador$$, $$Sanciones entre padre y jugador$$, $$conducta$$, $$tannery_city$$, $$Sanción al padre no sanciona automáticamente al hijo. Sanción al jugador no sanciona automáticamente al padre, salvo seguridad, operación o protección del menor.$$, $$Sanción al padre no sanciona automáticamente al hijo. Sanción al jugador no sanciona automáticamente al padre, salvo seguridad, operación o protección del menor.$$, array[$$sanciones$$,$$padre$$,$$jugador$$]),
($$TC-074$$, $$permanencia$$, $$Permanencia$$, $$conducta$$, $$tannery_city$$, $$El club puede revisar, restringir o terminar permanencia de cualquier persona por conducta grave que afecte seguridad, integridad, convivencia, operación, reputación o valores.$$, $$El club puede revisar, restringir o terminar permanencia de cualquier persona por conducta grave que afecte seguridad, integridad, convivencia, operación, reputación o valores.$$, array[$$permanencia$$]),
($$TC-075$$, $$expulsion$$, $$Expulsión$$, $$conducta$$, $$tannery_city$$, $$Decisión final inicial: Presidencia. La persona puede presentar 1 solicitud de reconsideración. Presidencia revisa antecedentes, evidencia y argumentos; la resolución posterior es definitiva dentro del club.$$, $$Decisión final inicial: Presidencia. La persona puede presentar 1 solicitud de reconsideración. Presidencia revisa antecedentes, evidencia y argumentos; la resolución posterior es definitiva dentro del club.$$, array[$$expulsión$$]),
($$TC-076$$, $$conflictos-entre-ninos$$, $$Conflictos entre niños$$, $$conducta$$, $$tannery_city$$, $$Ruta: informar al entrenador/Área Deportiva; Área Deportiva escucha y media; si continúa o requiere más atención, Dirección interviene; cuando corresponda, reunión con padres/tutores.$$, $$Ruta: informar al entrenador/Área Deportiva; Área Deportiva escucha y media; si continúa o requiere más atención, Dirección interviene; cuando corresponda, reunión con padres/tutores. Adultos no deben resolver físicamente conflictos entre menores por cuenta propia.$$, array[$$conflictos$$,$$niños$$]),
($$TC-077$$, $$conducta-de-padres$$, $$Conducta de padres$$, $$conducta$$, $$tannery_city$$, $$Prohibido sujetar físicamente a un jugador ajeno, amenazar, intimidar, disciplinar directamente a un menor ajeno, promover peleas o confrontar violentamente.$$, $$Prohibido sujetar físicamente a un jugador ajeno, amenazar, intimidar, disciplinar directamente a un menor ajeno, promover peleas o confrontar violentamente. Toda preocupación debe canalizarse al club.$$, array[$$conducta$$,$$padres$$]),
($$TC-078$$, $$actas-administrativas$$, $$Actas administrativas$$, $$conducta$$, $$tannery_city$$, $$Se usan para documentar incidentes, incumplimientos, hechos relevantes, acuerdos y sanciones. Conservar durante permanencia y el periodo administrativo/disciplinario necesario para seguimiento.$$, $$Se usan para documentar incidentes, incumplimientos, hechos relevantes, acuerdos y sanciones. Conservar durante permanencia y el periodo administrativo/disciplinario necesario para seguimiento.$$, array[$$actas$$,$$administrativas$$]),
($$TC-079$$, $$delegado-de-padres$$, $$Delegado de padres$$, $$familias$$, $$tannery_city$$, $$Cada categoría puede nombrar 1 Delegado de Padres como enlace, comunicación, organización e inquietudes generales.$$, $$Cada categoría puede nombrar 1 Delegado de Padres como enlace, comunicación, organización e inquietudes generales. No tiene acceso automático a actas, expedientes, datos médicos, sanciones individuales o información privada.$$, array[$$delegado$$,$$padres$$]),
($$TC-080$$, $$canales-oficiales$$, $$Canales oficiales$$, $$familias$$, $$tannery_city$$, $$WhatsApp oficial de Tannery City, grupo oficial de Administración, grupo/subgrupo oficial de categoría, Tanner OS y contacto directo con entrenador para asuntos deportivos.$$, $$WhatsApp oficial de Tannery City, grupo oficial de Administración, grupo/subgrupo oficial de categoría, Tanner OS y contacto directo con entrenador para asuntos deportivos.$$, array[$$canales$$,$$oficiales$$])
) as v(policy_code, slug, title, category, scope, short_answer, official_content, keywords)
where o.public_key='1850TC1850'
  and not exists (select 1 from app.policies p where p.organization_id=o.id and p.slug=v.slug);

insert into app.policies (
  organization_id, policy_code, slug, title, category, scope, short_answer,
  official_content, keywords, status, requires_acceptance, effective_date, published_at
)
select o.id, v.policy_code, v.slug, v.title, v.category, v.scope, v.short_answer,
  v.official_content, v.keywords, 'published', false, date '2026-09-09', timestamptz '2026-09-09 19:07:52+00'
from public.organizations o
cross join (values
($$TC-081$$, $$grupos-sociales-no-oficiales$$, $$Grupos sociales no oficiales$$, $$familias$$, $$tannery_city$$, $$Grupos creados por padres no son canales oficiales. Tannery City no administra, supervisa permanentemente ni responde por su contenido.$$, $$Grupos creados por padres no son canales oficiales. Tannery City no administra, supervisa permanentemente ni responde por su contenido. Si existe evidencia de amenazas, hostigamiento, discriminación, agresiones o conducta contraria al Código Tanner, el club puede revisar y actuar. No sancionar solo por opiniones o inconformidades legítimas.$$, array[$$grupos$$,$$sociales$$,$$oficiales$$]),
($$TC-082$$, $$avisos-oficiales$$, $$Avisos oficiales$$, $$familias$$, $$tannery_city$$, $$Un aviso publicado mediante canal oficial se considera comunicado. Cada familia es responsable de mantenerse atenta.$$, $$Un aviso publicado mediante canal oficial se considera comunicado. Cada familia es responsable de mantenerse atenta.$$, array[$$avisos$$,$$oficiales$$]),
($$TC-083$$, $$horario-administrativo$$, $$Horario administrativo$$, $$familias$$, $$tannery_city$$, $$Lunes a viernes: 10:00–14:00 y 16:00–19:00 hrs. Objetivo de respuesta: máximo 24 horas hábiles.$$, $$Lunes a viernes: 10:00–14:00 y 16:00–19:00 hrs. Objetivo de respuesta: máximo 24 horas hábiles.$$, array[$$horario$$,$$administrativo$$]),
($$TC-084$$, $$encuestas$$, $$Encuestas$$, $$familias$$, $$tannery_city$$, $$Las encuestas a familias son consultivas. Decisión final deportiva/operativa corresponde a Dirección, Área Deportiva o Presidencia según el tema.$$, $$Las encuestas a familias son consultivas. Decisión final deportiva/operativa corresponde a Dirección, Área Deportiva o Presidencia según el tema.$$, array[$$encuestas$$]),
($$TC-085$$, $$reporte-de-incidentes$$, $$Reporte de incidentes$$, $$seguridad$$, $$tannery_city$$, $$Canal: WhatsApp oficial de Tannery City. No se requiere módulo independiente de denuncias en Tanner OS.$$, $$Canal: WhatsApp oficial de Tannery City. No se requiere módulo independiente de denuncias en Tanner OS. Objetivo: conservar evidencia, fecha y seguimiento.$$, array[$$reporte$$,$$incidentes$$]),
($$TC-086$$, $$foto-interna$$, $$Foto interna$$, $$privacidad$$, $$tannery_city$$, $$Foto del jugador obligatoria para identificación y operación interna.$$, $$Foto del jugador obligatoria para identificación y operación interna.$$, array[$$foto$$,$$interna$$]),
($$TC-087$$, $$uso-de-imagen$$, $$Uso de imagen$$, $$privacidad$$, $$tannery_city$$, $$Marketing/publicidad es opcional. Tutor debe aceptar o negar expresamente. Negarse no afecta derecho a entrenar.$$, $$Marketing/publicidad es opcional. Tutor debe aceptar o negar expresamente. Negarse no afecta derecho a entrenar.$$, array[$$uso$$,$$imagen$$]),
($$TC-088$$, $$fotos-videos-del-staff$$, $$Fotos y videos del staff$$, $$privacidad$$, $$tannery_city$$, $$Entrenadores pueden tomar material con fines deportivos legítimos. Debe respetar autorizaciones, transferirse a almacenamiento oficial y no conservarse innecesariamente en dispositivos personales.$$, $$Entrenadores pueden tomar material con fines deportivos legítimos. Debe respetar autorizaciones, transferirse a almacenamiento oficial y no conservarse innecesariamente en dispositivos personales. Publicación en cuentas personales solo con autorización vigente de imagen.$$, array[$$fotos$$,$$videos$$,$$staff$$]),
($$TC-089$$, $$fotos-y-videos-de-familias$$, $$Fotos y videos de familias$$, $$privacidad$$, $$tannery_city$$, $$Se permiten para uso personal procurando respetar privacidad, imagen de otros menores e instrucciones del club.$$, $$Se permiten para uso personal procurando respetar privacidad, imagen de otros menores e instrucciones del club.$$, array[$$fotos$$,$$videos$$,$$familias$$]),
($$TC-090$$, $$drones-y-streaming$$, $$Drones y streaming$$, $$privacidad$$, $$tannery_city$$, $$Drones solo con autorización previa. Transmisiones/streaming por terceros requieren autorización.$$, $$Drones solo con autorización previa. Transmisiones/streaming por terceros requieren autorización.$$, array[$$drones$$,$$streaming$$]),
($$TC-091$$, $$uso-de-marca$$, $$Uso de marca$$, $$privacidad$$, $$tannery_city$$, $$No utilizar sin autorización nombre Tannery City, Tannery City Park, escudo, logos, diseños, identidad, jerseys o elementos gráficos para eventos, productos, negocios, patrocinios, campañas, torneos o ventas.$$, $$No utilizar sin autorización nombre Tannery City, Tannery City Park, escudo, logos, diseños, identidad, jerseys o elementos gráficos para eventos, productos, negocios, patrocinios, campañas, torneos o ventas.$$, array[$$uso$$,$$marca$$]),
($$TC-092$$, $$patrocinios$$, $$Patrocinios$$, $$conducta$$, $$tannery_city$$, $$Ninguna familia, jugador, entrenador o tercero puede representar a Tannery City ante una empresa o negociar patrocinio sin autorización.$$, $$Ninguna familia, jugador, entrenador o tercero puede representar a Tannery City ante una empresa o negociar patrocinio sin autorización.$$, array[$$patrocinios$$]),
($$TC-093$$, $$colectas-dinero$$, $$Colectas / dinero$$, $$conducta$$, $$tannery_city$$, $$No solicitar dinero, cooperaciones o colectas usando grupos/nombre Tanner sin autorización.$$, $$No solicitar dinero, cooperaciones o colectas usando grupos/nombre Tanner sin autorización.$$, array[$$colectas$$,$$dinero$$]),
($$TC-094$$, $$ventas-rifas$$, $$Ventas / rifas$$, $$tannery_city_park$$, $$tannery_city$$, $$Pueden existir con aviso previo a Administración. No pueden competir directamente con tienda TCP, comercializar alcohol sin autorización ni presentarse como actividad oficial Tanner sin permiso.$$, $$Pueden existir con aviso previo a Administración. No pueden competir directamente con tienda TCP, comercializar alcohol sin autorización ni presentarse como actividad oficial Tanner sin permiso.$$, array[$$ventas$$,$$rifas$$]),
($$TC-095$$, $$cumpleanos$$, $$Cumpleaños$$, $$tannery_city_park$$, $$tannery_city$$, $$Permitidos convivios sencillos en área social si no interfieren con entrenamiento, no invaden cancha y respetan operación TCP.$$, $$Permitidos convivios sencillos en área social si no interfieren con entrenamiento, no invaden cancha y respetan operación TCP.$$, array[$$cumpleaños$$]),
($$TC-096$$, $$alcohol$$, $$Alcohol$$, $$tannery_city_park$$, $$tannery_city$$, $$Prohibido en cancha, área deportiva y actividades deportivas infantiles. En área social habilitada, consumo solo ahí conforme reglas TCP.$$, $$Prohibido en cancha, área deportiva y actividades deportivas infantiles. En área social habilitada, consumo solo ahí conforme reglas TCP.$$, array[$$alcohol$$]),
($$TC-097$$, $$tabaco$$, $$Tabaco$$, $$tannery_city_park$$, $$tannery_city$$, $$Prohibido en área deportiva/cancha. Solo en área permitida/social según reglas TCP.$$, $$Prohibido en área deportiva/cancha. Solo en área permitida/social según reglas TCP.$$, array[$$tabaco$$]),
($$TC-098$$, $$vapeo$$, $$Vapeo$$, $$tannery_city_park$$, $$tannery_city$$, $$Permitido fuera de cancha; nunca debe interferir con actividades de menores.$$, $$Permitido fuera de cancha; nunca debe interferir con actividades de menores.$$, array[$$vapeo$$]),
($$TC-099$$, $$comida$$, $$Comida$$, $$tannery_city_park$$, $$tannery_city$$, $$No consumir dentro de cancha. Usar área social o zonas permitidas.$$, $$No consumir dentro de cancha. Usar área social o zonas permitidas.$$, array[$$comida$$]),
($$TC-100$$, $$mascotas$$, $$Mascotas$$, $$tannery_city_park$$, $$tannery_city$$, $$Pueden ingresar con autorización previa.$$, $$Pueden ingresar con autorización previa.$$, array[$$mascotas$$]),
($$TC-101$$, $$bicicletas-patines$$, $$Bicicletas / patines$$, $$tannery_city_park$$, $$tannery_city$$, $$No dentro de cancha. Solo en zonas autorizadas, estacionamiento/alrededores cuando sea seguro.$$, $$No dentro de cancha. Solo en zonas autorizadas, estacionamiento/alrededores cuando sea seguro.$$, array[$$bicicletas$$,$$patines$$]),
($$TC-102$$, $$hermanos-menores-acompanantes$$, $$Hermanos / menores acompañantes$$, $$seguridad$$, $$tannery_city$$, $$Son responsabilidad total de su padre/tutor. No deben ingresar a cancha sin autorización.$$, $$Son responsabilidad total de su padre/tutor. No deben ingresar a cancha sin autorización.$$, array[$$hermanos$$,$$menores$$,$$acompañantes$$]),
($$TC-103$$, $$objetos-prohibidos$$, $$Objetos prohibidos$$, $$seguridad$$, $$tannery_city$$, $$Prohibidos drogas, armas, objetos peligrosos, pirotecnia, bengalas y elementos que pongan en riesgo la seguridad.$$, $$Prohibidos drogas, armas, objetos peligrosos, pirotecnia, bengalas y elementos que pongan en riesgo la seguridad.$$, array[$$objetos$$,$$prohibidos$$]),
($$TC-104$$, $$velocidad-tcp$$, $$Velocidad TCP$$, $$tannery_city_park$$, $$tannery_city$$, $$Velocidad máxima dentro de instalaciones: 10 km/h.$$, $$Velocidad máxima dentro de instalaciones: 10 km/h.$$, array[$$velocidad$$,$$tcp$$]),
($$TC-105$$, $$gafete-de-estacionamiento$$, $$Gafete de estacionamiento$$, $$estacionamiento$$, $$tannery_city$$, $$Costo $100 MXN, vigencia 1 año natural. Evita cobro ordinario de estacionamiento Tanner durante vigencia conforme condiciones.$$, $$Costo $100 MXN, vigencia 1 año natural. Evita cobro ordinario de estacionamiento Tanner durante vigencia conforme condiciones. Sin gafete: auto $20, moto $10. Máximo 2 gafetes por familia. Reposición $100. No se puede prestar a terceros. Uso indebido puede cancelar beneficio.$$, array[$$gafete$$,$$estacionamiento$$]),
($$TC-106$$, $$banos$$, $$Baños$$, $$tannery_city_park$$, $$tannery_city$$, $$Disponibles para usuarios de TCP. Daños identificados: responsable cubre reparación/reposición.$$, $$Disponibles para usuarios de TCP. Daños identificados: responsable cubre reparación/reposición.$$, array[$$baños$$]),
($$TC-107$$, $$bodega$$, $$Bodega$$, $$tannery_city_park$$, $$tannery_city$$, $$Acceso exclusivo a personal autorizado. Jugadores/familias no ingresan sin autorización.$$, $$Acceso exclusivo a personal autorizado. Jugadores/familias no ingresan sin autorización.$$, array[$$bodega$$]),
($$TC-108$$, $$bocinas-musica$$, $$Bocinas / música$$, $$tannery_city_park$$, $$tannery_city$$, $$Solo con autorización previa.$$, $$Solo con autorización previa.$$, array[$$bocinas$$,$$música$$]),
($$TC-109$$, $$staff-tanner$$, $$Staff Tanner$$, $$conducta$$, $$tannery_city$$, $$Todo entrenador debe firmar Código de Conducta Tanner, presentar identificación, entregar documentación requerida, entregar carta/constancia de antecedentes solicitada dentro de los primeros 30 días y cumplir periodo de prueba de 3 meses.$$, $$Todo entrenador debe firmar Código de Conducta Tanner, presentar identificación, entregar documentación requerida, entregar carta/constancia de antecedentes solicitada dentro de los primeros 30 días y cumplir periodo de prueba de 3 meses.$$, array[$$staff$$,$$tanner$$]),
($$TC-110$$, $$perfil-del-entrenador$$, $$Perfil del entrenador$$, $$conducta$$, $$tannery_city$$, $$Preferentemente Licenciatura en Educación Física/deporte/área relacionada, experiencia relevante, certificaciones reconocidas y experiencia deportiva suficiente.$$, $$Preferentemente Licenciatura en Educación Física/deporte/área relacionada, experiencia relevante, certificaciones reconocidas y experiencia deportiva suficiente. Evaluación final: Presidencia/Dirección Deportiva.$$, array[$$perfil$$,$$entrenador$$]),
($$TC-111$$, $$contratacion-y-baja-de-staff$$, $$Contratación y baja de staff$$, $$conducta$$, $$tannery_city$$, $$Autoridad: Presidencia.$$, $$Autoridad: Presidencia.$$, array[$$contratación$$,$$baja$$,$$staff$$]),
($$TC-112$$, $$entrenador-a-solas-con-menor$$, $$Entrenador a solas con menor$$, $$seguridad$$, $$tannery_city$$, $$Evitar estar a solas con un menor en espacios privados/cerrados. Interacciones uno a uno preferentemente visibles e interrumpibles.$$, $$Evitar estar a solas con un menor en espacios privados/cerrados. Interacciones uno a uno preferentemente visibles e interrumpibles.$$, array[$$entrenador$$,$$solas$$,$$menor$$]),
($$TC-113$$, $$banos-y-cambio-de-ropa$$, $$Baños y cambio de ropa$$, $$seguridad$$, $$tannery_city$$, $$Cambios de ropa corresponden a padres/tutores. Entrenadores pueden acompañar hasta acceso de baño cuando sea necesario.$$, $$Cambios de ropa corresponden a padres/tutores. Entrenadores pueden acompañar hasta acceso de baño cuando sea necesario. Evitar asistencia privada innecesaria.$$, array[$$baños$$,$$cambio$$,$$ropa$$]),
($$TC-114$$, $$contacto-fisico$$, $$Contacto físico$$, $$seguridad$$, $$tannery_city$$, $$Contacto deportivo apropiado permitido cuando sea breve, respetuoso, visible, adecuado a la edad y aceptado por el menor.$$, $$Contacto deportivo apropiado permitido cuando sea breve, respetuoso, visible, adecuado a la edad y aceptado por el menor. Ejemplos: celebración, consuelo, corrección deportiva apropiada. No contacto forzado, íntimo, secreto, prolongado o incómodo.$$, array[$$contacto$$,$$físico$$]),
($$TC-115$$, $$castigo-fisico$$, $$Castigo físico$$, $$seguridad$$, $$tannery_city$$, $$No utilizar ejercicio como castigo o humillación. Consecuencias deben ser formativas/deportivas.$$, $$No utilizar ejercicio como castigo o humillación. Consecuencias deben ser formativas/deportivas.$$, array[$$castigo$$,$$físico$$]),
($$TC-116$$, $$lenguaje-de-entrenadores$$, $$Lenguaje de entrenadores$$, $$conducta$$, $$tannery_city$$, $$No usar groserías dirigidas a jugadores. Prohibido humillar, ridiculizar o degradar públicamente.$$, $$No usar groserías dirigidas a jugadores. Prohibido humillar, ridiculizar o degradar públicamente.$$, array[$$lenguaje$$,$$entrenadores$$]),
($$TC-117$$, $$quejas-contra-entrenadores$$, $$Quejas contra entrenadores$$, $$conducta$$, $$tannery_city$$, $$Ruta: recepción; revisión Área Deportiva; investigación; Presidencia cuando corresponda. Continuidad durante investigación depende de gravedad, riesgo y hechos.$$, $$Ruta: recepción; revisión Área Deportiva; investigación; Presidencia cuando corresponda. Continuidad durante investigación depende de gravedad, riesgo y hechos.$$, array[$$quejas$$,$$contra$$,$$entrenadores$$]),
($$TC-118$$, $$invitados-auxiliares$$, $$Invitados / auxiliares$$, $$seguridad$$, $$tannery_city$$, $$Entrenador no puede llevar asistentes/invitados a trabajar con menores sin autorización.$$, $$Entrenador no puede llevar asistentes/invitados a trabajar con menores sin autorización.$$, array[$$invitados$$,$$auxiliares$$]),
($$TC-119$$, $$cambio-cancelacion-de-sesion$$, $$Cambio o cancelación de sesión$$, $$entrenamientos$$, $$tannery_city$$, $$Entrenador no modifica horarios ni cancela unilateralmente. Debe autorizar Área Deportiva.$$, $$Entrenador no modifica horarios ni cancela unilateralmente. Debe autorizar Área Deportiva.$$, array[$$cambio$$,$$cancelación$$,$$sesión$$]),
($$TC-120$$, $$ausencia-del-entrenador$$, $$Ausencia del entrenador$$, $$entrenamientos$$, $$tannery_city$$, $$Dirección Deportiva organiza sustitución/cobertura.$$, $$Dirección Deportiva organiza sustitución/cobertura.$$, array[$$ausencia$$,$$entrenador$$])
) as v(policy_code, slug, title, category, scope, short_answer, official_content, keywords)
where o.public_key='1850TC1850'
  and not exists (select 1 from app.policies p where p.organization_id=o.id and p.slug=v.slug);

insert into app.policies (
  organization_id, policy_code, slug, title, category, scope, short_answer,
  official_content, keywords, status, requires_acceptance, effective_date, published_at
)
select o.id, v.policy_code, v.slug, v.title, v.category, v.scope, v.short_answer,
  v.official_content, v.keywords, 'published', false, date '2026-09-09', timestamptz '2026-09-09 19:07:52+00'
from public.organizations o
cross join (values
($$TC-121$$, $$sanciones-del-entrenador-a-jugador$$, $$Sanciones del entrenador a jugador$$, $$conducta$$, $$tannery_city$$, $$Puede retirar al jugador de la sesión actual por indisciplina cuando sea necesario y reportar inmediatamente a Dirección Deportiva / Presidencia si corresponde.$$, $$Puede retirar al jugador de la sesión actual por indisciplina cuando sea necesario y reportar inmediatamente a Dirección Deportiva / Presidencia si corresponde. Suspender sesiones posteriores: solo Dirección Deportiva.$$, array[$$sanciones$$,$$entrenador$$,$$jugador$$]),
($$TC-122$$, $$multas-de-entrenadores$$, $$Multas de entrenadores$$, $$conducta$$, $$tannery_city$$, $$Profesores no pueden cobrar multas disciplinarias directamente.$$, $$Profesores no pueden cobrar multas disciplinarias directamente.$$, array[$$multas$$,$$entrenadores$$]),
($$TC-123$$, $$regalos-propinas$$, $$Regalos / propinas$$, $$conducta$$, $$tannery_city$$, $$Staff no debe aceptar dinero, propinas o beneficios de familias. Especialmente prohibido cualquier beneficio ligado a minutos, titularidad, convocatoria, categoría, becas o decisiones deportivas.$$, $$Staff no debe aceptar dinero, propinas o beneficios de familias. Especialmente prohibido cualquier beneficio ligado a minutos, titularidad, convocatoria, categoría, becas o decisiones deportivas.$$, array[$$regalos$$,$$propinas$$]),
($$TC-124$$, $$relaciones-personales-comerciales$$, $$Relaciones personales o comerciales$$, $$conducta$$, $$tannery_city$$, $$Entrenadores pueden tener relaciones personales o comerciales legítimas con familias, pero nunca deben influir en decisiones deportivas ni crear conflicto de interés.$$, $$Entrenadores pueden tener relaciones personales o comerciales legítimas con familias, pero nunca deben influir en decisiones deportivas ni crear conflicto de interés.$$, array[$$relaciones$$,$$personales$$,$$comerciales$$]),
($$TC-125$$, $$invitaciones-sociales$$, $$Invitaciones sociales$$, $$conducta$$, $$tannery_city$$, $$Entrenadores pueden aceptar invitaciones familiares/sociales; no deben influir en decisiones deportivas.$$, $$Entrenadores pueden aceptar invitaciones familiares/sociales; no deben influir en decisiones deportivas.$$, array[$$invitaciones$$,$$sociales$$]),
($$TC-126$$, $$sesiones-privadas$$, $$Sesiones privadas$$, $$entrenamientos$$, $$tannery_city$$, $$Una familia puede contratar sesión privada con un entrenador solo con conocimiento del Área Deportiva, autorización correspondiente y separación clara del programa ordinario.$$, $$Una familia puede contratar sesión privada con un entrenador solo con conocimiento del Área Deportiva, autorización correspondiente y separación clara del programa ordinario.$$, array[$$sesiones$$,$$privadas$$]),
($$TC-127$$, $$transporte-de-jugadores$$, $$Transporte de jugadores$$, $$seguridad$$, $$tannery_city$$, $$Entrenador puede transportar a un menor solo con autorización expresa del padre/tutor y conocimiento del club.$$, $$Entrenador puede transportar a un menor solo con autorización expresa del padre/tutor y conocimiento del club. Debe quedar documentada.$$, array[$$transporte$$,$$jugadores$$]),
($$TC-128$$, $$whatsapp-entrenador-menor$$, $$WhatsApp entrenador-menor$$, $$seguridad$$, $$tannery_city$$, $$No mantener conversaciones privadas directas con menores. Comunicación mediante padres/tutores y canales oficiales.$$, $$No mantener conversaciones privadas directas con menores. Comunicación mediante padres/tutores y canales oficiales. No grupos privados coach-menores sin tutores.$$, array[$$whatsapp$$,$$entrenador$$,$$menor$$]),
($$TC-129$$, $$sospecha-de-maltrato-revelacion-del-menor$$, $$Sospecha de maltrato / revelación del menor$$, $$seguridad$$, $$tannery_city$$, $$Si un niño reporta violencia, abuso, maltrato, negligencia o situación preocupante, el entrenador no investiga por su cuenta.$$, $$Si un niño reporta violencia, abuso, maltrato, negligencia o situación preocupante, el entrenador no investiga por su cuenta. Ruta: Entrenador → Dirección Deportiva → Presidencia. Documentar lo esencial.$$, array[$$sospecha$$,$$maltrato$$,$$revelación$$,$$menor$$]),
($$TC-130$$, $$proteccion-de-datos$$, $$Protección de datos$$, $$privacidad$$, $$tannery_city$$, $$El registro debe incluir aviso de privacidad, consentimiento y autorización de tratamiento necesaria.$$, $$El registro debe incluir aviso de privacidad, consentimiento y autorización de tratamiento necesaria. Marketing debe tener autorización separada.$$, array[$$protección$$,$$datos$$]),
($$TC-131$$, $$excepciones$$, $$Excepciones$$, $$faq$$, $$tannery_city$$, $$Toda excepción importante al reglamento debe ser autorizada por Presidencia y quedar registrada en Tanner OS, Administración o expediente correspondiente.$$, $$Toda excepción importante al reglamento debe ser autorizada por Presidencia y quedar registrada en Tanner OS, Administración o expediente correspondiente. Evitar acuerdos verbales sin trazabilidad.$$, array[$$excepciones$$]),
($$TC-132$$, $$tannery-city-park$$, $$Tannery City Park$$, $$tannery_city_park$$, $$tannery_city_park$$, $$El Reglamento de TCP es independiente del Reglamento Tannery City. Aplica a instalaciones, torneos TCP, renta de cancha, usuarios externos, espectadores y seguridad del parque.$$, $$El Reglamento de TCP es independiente del Reglamento Tannery City. Aplica a instalaciones, torneos TCP, renta de cancha, usuarios externos, espectadores y seguridad del parque. Familias Tanner en TCP también cumplen sus reglas vigentes.$$, array[$$tannery$$,$$city$$,$$park$$]),
($$TC-133$$, $$reglamento-de-torneos-tcp$$, $$Reglamento de torneos TCP$$, $$tannery_city_park$$, $$torneos_tcp$$, $$Mantener separado del Reglamento Tanner temas como depósitos, defaults, credenciales, alineaciones, talacha, barridas, reglas específicas de juego, desalojo, multas del torneo y pagos de equipos.$$, $$Mantener separado del Reglamento Tanner temas como depósitos, defaults, credenciales, alineaciones, talacha, barridas, reglas específicas de juego, desalojo, multas del torneo y pagos de equipos. No mezclar automáticamente con academia.$$, array[$$reglamento$$,$$torneos$$,$$tcp$$])
) as v(policy_code, slug, title, category, scope, short_answer, official_content, keywords)
where o.public_key='1850TC1850'
  and not exists (select 1 from app.policies p where p.organization_id=o.id and p.slug=v.slug);

