insert into app.policies (
  organization_id, policy_code, slug, title, category, scope, short_answer,
  official_content, keywords, status, requires_acceptance, effective_date, published_at
)
select o.id, v.policy_code, v.slug, v.title, v.category, v.scope, v.short_answer,
  v.official_content, v.keywords, 'published', false, date '2026-09-09', timestamptz '2026-09-09 19:07:52+00'
from public.organizations o
cross join (values
($$TC-041$$, $$regla-de-24-horas$$, $$Regla de 24 horas$$, $$conducta$$, $$tannery_city$$, $$Después de un partido se solicita esperar al menos 24 horas antes de presentar inconformidades sobre minutos, titularidad, posición o decisiones tácticas/técnicas.$$, $$Después de un partido se solicita esperar al menos 24 horas antes de presentar inconformidades sobre minutos, titularidad, posición o decisiones tácticas/técnicas. No aplica a seguridad, salud, agresiones o emergencias.$$, array[$$regla$$,$$horas$$]),
($$TC-042$$, $$evaluaciones-deportivas$$, $$Evaluaciones deportivas$$, $$jugadores$$, $$tannery_city$$, $$Padres pueden solicitar evaluación. Tannery City busca realizar evaluaciones trimestrales. Información individual privada; acceso a jugador, padre/tutor, staff autorizado, Dirección y Presidencia.$$, $$Padres pueden solicitar evaluación. Tannery City busca realizar evaluaciones trimestrales. Información individual privada; acceso a jugador, padre/tutor, staff autorizado, Dirección y Presidencia.$$, array[$$evaluaciones$$,$$deportivas$$]),
($$TC-043$$, $$clima$$, $$Clima$$, $$entrenamientos$$, $$tannery_city$$, $$Ante tormenta eléctrica se suspende actividad. Con lluvia, el club procurará informar aproximadamente 40 minutos antes si continúa o se suspende.$$, $$Ante tormenta eléctrica se suspende actividad. Con lluvia, el club procurará informar aproximadamente 40 minutos antes si continúa o se suspende. Si comienza durante la sesión, entrenador puede suspender. Cancelación por clima no genera automáticamente reposición. Si la cancelación es atribuible al club, Dirección evalúa reposición.$$, array[$$clima$$]),
($$TC-044$$, $$entrenamiento-con-pocos-jugadores$$, $$Entrenamiento con pocos jugadores$$, $$entrenamientos$$, $$tannery_city$$, $$Mínimo para impartir sesión: 1 jugador. Mientras la sesión esté oficialmente programada, el club entrenará al jugador presente.$$, $$Mínimo para impartir sesión: 1 jugador. Mientras la sesión esté oficialmente programada, el club entrenará al jugador presente.$$, array[$$entrenamiento$$,$$pocos$$,$$jugadores$$]),
($$TC-045$$, $$dias-festivos$$, $$Días festivos$$, $$entrenamientos$$, $$tannery_city$$, $$El club puede consultar disponibilidad mediante encuesta. Las encuestas son consultivas; decisión final corresponde al club.$$, $$El club puede consultar disponibilidad mediante encuesta. Las encuestas son consultivas; decisión final corresponde al club.$$, array[$$días$$,$$festivos$$]),
($$TC-046$$, $$calzado$$, $$Calzado$$, $$uniformes$$, $$tannery_city$$, $$Prohibidos tachones. Permitidos multitachos / calzado deportivo autorizado.$$, $$Prohibidos tachones. Permitidos multitachos / calzado deportivo autorizado.$$, array[$$calzado$$]),
($$TC-047$$, $$espinilleras$$, $$Espinilleras$$, $$uniformes$$, $$tannery_city$$, $$No obligatorias en entrenamiento ordinario; pueden utilizarse. En competencia se sigue también el reglamento correspondiente.$$, $$No obligatorias en entrenamiento ordinario; pueden utilizarse. En competencia se sigue también el reglamento correspondiente.$$, array[$$espinilleras$$]),
($$TC-048$$, $$hidratacion$$, $$Hidratación$$, $$entrenamientos$$, $$tannery_city$$, $$Cada jugador debe llevar agua o hidratación propia.$$, $$Cada jugador debe llevar agua o hidratación propia.$$, array[$$hidratación$$]),
($$TC-049$$, $$uniformes$$, $$Uniformes$$, $$uniformes$$, $$tannery_city$$, $$Tannery City maneja 4 jerseys oficiales en rotación. Cada 6 meses se renuevan 2 de los 4 diseños y los otros 2 siguen vigentes; en el siguiente ciclo se renueva la pareja restante.$$, $$Tannery City maneja 4 jerseys oficiales en rotación. Cada 6 meses se renuevan 2 de los 4 diseños y los otros 2 siguen vigentes; en el siguiente ciclo se renueva la pareja restante. El jugador debe contar con los uniformes designados para su ciclo. Si ya tiene un modelo vigente y en buenas condiciones, no necesita duplicado.$$, array[$$uniformes$$]),
($$TC-050$$, $$short-y-medias$$, $$Short y medias$$, $$uniformes$$, $$tannery_city$$, $$Estándar Tanner: short negro y medias blancas. Podrán renovarse cuando corresponda.$$, $$Estándar Tanner: short negro y medias blancas. Podrán renovarse cuando corresponda.$$, array[$$short$$,$$medias$$]),
($$TC-051$$, $$porteros$$, $$Porteros$$, $$uniformes$$, $$tannery_city$$, $$Cada portero debe contar con mínimo 2 uniformes de distinto color para diferenciarse según uniforme del equipo y competencia.$$, $$Cada portero debe contar con mínimo 2 uniformes de distinto color para diferenciarse según uniforme del equipo y competencia.$$, array[$$porteros$$]),
($$TC-052$$, $$olvido-de-uniforme$$, $$Olvido de uniforme$$, $$uniformes$$, $$tannery_city$$, $$Puede entrenar con playera negra, short negro y medias blancas. Primera incidencia: recordatorio. Reincidencia: puede generar amonestación/formación disciplinaria.$$, $$Puede entrenar con playera negra, short negro y medias blancas. Primera incidencia: recordatorio. Reincidencia: puede generar amonestación/formación disciplinaria. En becados, incumplimiento reiterado puede influir en renovación.$$, array[$$olvido$$,$$uniforme$$]),
($$TC-053$$, $$garantia-cambios-de-uniforme$$, $$Garantía / cambios de uniforme$$, $$uniformes$$, $$tannery_city$$, $$Primeros 3 días después de entrega: reportar anomalías a Tannery City. Posteriormente y hasta aproximadamente 30 días: seguimiento conforme garantía del proveedor.$$, $$Primeros 3 días después de entrega: reportar anomalías a Tannery City. Posteriormente y hasta aproximadamente 30 días: seguimiento conforme garantía del proveedor. No aplica automáticamente a mal uso, lavado incorrecto, modificaciones o desgaste normal.$$, array[$$garantía$$,$$cambios$$,$$uniforme$$]),
($$TC-054$$, $$objetos-personales$$, $$Objetos personales$$, $$seguridad$$, $$tannery_city$$, $$Tannery City no se responsabiliza por objetos personales no entregados formalmente a resguardo, como celular, dinero, reloj, chamarra o accesorios.$$, $$Tannery City no se responsabiliza por objetos personales no entregados formalmente a resguardo, como celular, dinero, reloj, chamarra o accesorios.$$, array[$$objetos$$,$$personales$$]),
($$TC-055$$, $$celulares$$, $$Celulares$$, $$conducta$$, $$tannery_city$$, $$Jugadores no deben usar celular durante entrenamiento salvo emergencia. Entrenador no confisca el dispositivo; puede pedir guardarlo y reportar reincidencias.$$, $$Jugadores no deben usar celular durante entrenamiento salvo emergencia. Entrenador no confisca el dispositivo; puede pedir guardarlo y reportar reincidencias.$$, array[$$celulares$$]),
($$TC-056$$, $$joyeria$$, $$Joyería$$, $$seguridad$$, $$tannery_city$$, $$Durante entrenamiento y partido no usar elementos que representen riesgo: cadenas, relojes, aretes o accesorios peligrosos.$$, $$Durante entrenamiento y partido no usar elementos que representen riesgo: cadenas, relojes, aretes o accesorios peligrosos.$$, array[$$joyería$$]),
($$TC-057$$, $$danos$$, $$Daños$$, $$conducta$$, $$tannery_city$$, $$Daño intencional o negligente a instalaciones, baños, mobiliario, material o propiedad del club puede ser cobrado a la persona/familia responsable.$$, $$Daño intencional o negligente a instalaciones, baños, mobiliario, material o propiedad del club puede ser cobrado a la persona/familia responsable.$$, array[$$daños$$]),
($$TC-058$$, $$material-deportivo$$, $$Material deportivo$$, $$entrenamientos$$, $$tannery_city$$, $$Fuera del entrenamiento no se presta material sin autorización. Después de sesión, quienes sigan jugando deben usar su propio balón.$$, $$Fuera del entrenamiento no se presta material sin autorización. Después de sesión, quienes sigan jugando deben usar su propio balón. Si un balón del club sale fuera debe recuperarse; cuando sea necesario, el menor lo hace acompañado por su tutor. Pérdida por incumplimiento puede generar responsabilidad de reposición.$$, array[$$material$$,$$deportivo$$]),
($$TC-059$$, $$uso-de-cancha-despues-de-entrenar$$, $$Uso de cancha después de entrenar$$, $$tannery_city_park$$, $$tannery_city$$, $$Puede permitirse permanecer jugando con disponibilidad y autorización. Referencia: hasta aproximadamente 19:00 hrs, sujeto a operación TCP.$$, $$Puede permitirse permanecer jugando con disponibilidad y autorización. Referencia: hasta aproximadamente 19:00 hrs, sujeto a operación TCP. Cuando la cancha se necesite, pueden ser canalizados a La Lechuguilla u otra zona disponible.$$, array[$$uso$$,$$cancha$$,$$después$$,$$entrenar$$]),
($$TC-060$$, $$conducta-de-jugadores$$, $$Conducta de jugadores$$, $$conducta$$, $$tannery_city$$, $$Principios: respeto, disciplina, esfuerzo, honestidad, responsabilidad y trabajo en equipo.$$, $$Principios: respeto, disciplina, esfuerzo, honestidad, responsabilidad y trabajo en equipo.$$, array[$$conducta$$,$$jugadores$$]),
($$TC-061$$, $$bullying-y-discriminacion$$, $$Bullying y discriminación$$, $$conducta$$, $$tannery_city$$, $$Política de cero tolerancia. Se atienden inmediatamente bullying, discriminación, intimidación, agresión y hostigamiento.$$, $$Política de cero tolerancia. Se atienden inmediatamente bullying, discriminación, intimidación, agresión y hostigamiento.$$, array[$$bullying$$,$$discriminación$$]),
($$TC-062$$, $$groserias-entre-jugadores$$, $$Groserías entre jugadores$$, $$conducta$$, $$tannery_city$$, $$Primera respuesta: corrección formativa. Reincidencias o gravedad: medidas deportivas/administrativas.$$, $$Primera respuesta: corrección formativa. Reincidencias o gravedad: medidas deportivas/administrativas.$$, array[$$groserías$$,$$jugadores$$]),
($$TC-063$$, $$agresion-fisica-entre-jugadores$$, $$Agresión física entre jugadores$$, $$conducta$$, $$tannery_city$$, $$Ruta: separación inmediata; revisión Área Deportiva; escuchar involucrados; comunicar con familias; seguimiento; sanción según gravedad.$$, $$Ruta: separación inmediata; revisión Área Deportiva; escuchar involucrados; comunicar con familias; seguimiento; sanción según gravedad.$$, array[$$agresión$$,$$física$$,$$jugadores$$]),
($$TC-064$$, $$padres-y-decisiones-tecnicas$$, $$Padres y decisiones técnicas$$, $$familias$$, $$tannery_city$$, $$Padres no pueden dar instrucciones técnicas desde fuera, elegir posición, exigir titularidad o minutos, ni sustituir decisiones del entrenador.$$, $$Padres no pueden dar instrucciones técnicas desde fuera, elegir posición, exigir titularidad o minutos, ni sustituir decisiones del entrenador. Decisiones deportivas corresponden al Área Deportiva. Interferencia reiterada puede generar amonestación o restricción.$$, array[$$padres$$,$$decisiones$$,$$técnicas$$]),
($$TC-065$$, $$acceso-a-cancha$$, $$Acceso a cancha$$, $$seguridad$$, $$tannery_city$$, $$Padres/familiares no pueden entrar a cancha sin autorización. Si un adulto entra después de indicación de no hacerlo, puede recibir amonestación.$$, $$Padres/familiares no pueden entrar a cancha sin autorización. Si un adulto entra después de indicación de no hacerlo, puede recibir amonestación.$$, array[$$acceso$$,$$cancha$$]),
($$TC-066$$, $$banca-y-zonas-restringidas$$, $$Banca y zonas restringidas$$, $$seguridad$$, $$tannery_city$$, $$Banca: jugadores convocados, entrenadores y staff autorizado. No padres, hermanos o acompañantes. Si un adulto se niega a retirarse: llamada de atención, reporte y revisión disciplinaria.$$, $$Banca: jugadores convocados, entrenadores y staff autorizado. No padres, hermanos o acompañantes. Si un adulto se niega a retirarse: llamada de atención, reporte y revisión disciplinaria.$$, array[$$banca$$,$$zonas$$,$$restringidas$$]),
($$TC-067$$, $$restriccion-a-un-adulto$$, $$Restricción a un adulto$$, $$conducta$$, $$tannery_city$$, $$Tannery City puede restringir temporalmente el acceso de padre, familiar o acompañante sin que esto signifique automáticamente baja del jugador.$$, $$Tannery City puede restringir temporalmente el acceso de padre, familiar o acompañante sin que esto signifique automáticamente baja del jugador.$$, array[$$restricción$$,$$adulto$$]),
($$TC-068$$, $$conducta-fuera-de-tcp$$, $$Conducta fuera de TCP$$, $$conducta$$, $$tannery_city$$, $$El Reglamento Tanner aplica cuando se representa al club en partidos de visita, torneos, viajes, eventos y convivencias oficiales, y cuando el jugador usa uniforme oficial en representación del club.$$, $$El Reglamento Tanner aplica cuando se representa al club en partidos de visita, torneos, viajes, eventos y convivencias oficiales, y cuando el jugador usa uniforme oficial en representación del club.$$, array[$$conducta$$,$$fuera$$,$$tcp$$]),
($$TC-069$$, $$arbitros-y-rivales$$, $$Árbitros y rivales$$, $$conducta$$, $$tannery_city$$, $$Familias no deben confrontar directamente árbitros, rivales, jugadores rivales o entrenadores rivales.$$, $$Familias no deben confrontar directamente árbitros, rivales, jugadores rivales o entrenadores rivales. Inconformidades se canalizan por staff del club.$$, array[$$árbitros$$,$$rivales$$]),
($$TC-070$$, $$tarjetas-y-sanciones-de-liga$$, $$Tarjetas y sanciones de liga$$, $$conducta$$, $$tannery_city$$, $$Una sanción externa puede generar medida interna Tannery City si la conducta lo amerita. Multas económicas se revisan caso por caso según reglamento, responsable y circunstancia.$$, $$Una sanción externa puede generar medida interna Tannery City si la conducta lo amerita. Multas económicas se revisan caso por caso según reglamento, responsable y circunstancia.$$, array[$$tarjetas$$,$$sanciones$$,$$liga$$]),
($$TC-071$$, $$sistema-de-amonestaciones$$, $$Sistema de amonestaciones$$, $$conducta$$, $$tannery_city$$, $$Primera: acta administrativa + seguimiento. Segunda: acta + reunión con Dirección + posible restricción temporal.$$, $$Primera: acta administrativa + seguimiento. Segunda: acta + reunión con Dirección + posible restricción temporal. Tercera: revisión de permanencia del jugador y/o familia.$$, array[$$sistema$$,$$amonestaciones$$]),
($$TC-072$$, $$faltas-graves$$, $$Faltas graves$$, $$conducta$$, $$tannery_city$$, $$Una conducta grave puede saltarse el sistema progresivo. Ejemplos: agresión física grave, amenazas, riesgo para menores, violencia, drogas, armas, conducta peligrosa y hostigamiento severo.$$, $$Una conducta grave puede saltarse el sistema progresivo. Ejemplos: agresión física grave, amenazas, riesgo para menores, violencia, drogas, armas, conducta peligrosa y hostigamiento severo. Presidencia puede ordenar restricción, suspensión o expulsión.$$, array[$$faltas$$,$$graves$$]),
($$TC-073$$, $$sanciones-entre-padre-y-jugador$$, $$Sanciones entre padre y jugador$$, $$conducta$$, $$tannery_city$$, $$Sanción al padre no sanciona automáticamente al hijo. Sanción al jugador no sanciona automáticamente al padre, salvo seguridad, operación o protección del menor.$$, $$Sanción al padre no sanciona automáticamente al hijo. Sanción al jugador no sanciona automáticamente al padre, salvo seguridad, operación o protección del menor.$$, array[$$sanciones$$,$$padre$$,$$jugador$$]),
($$TC-074$$, $$permanencia$$, $$Permanencia$$, $$conducta$$, $$tannery_city$$, $$El club puede revisar, restringir o terminar permanencia de cualquier persona por conducta grave que afecte seguridad, integridad, convivencia, operación, reputación o valores.$$, $$El club puede revisar, restringir o terminar permanencia de cualquier persona por conducta grave que afecte seguridad, integridad, convivencia, operación, reputación o valores.$$, array[$$permanencia$$]),
($$TC-075$$, $$expulsion$$, $$Expulsión$$, $$conducta$$, $$tannery_city$$, $$Decisión final inicial: Presidencia. La persona puede presentar 1 solicitud de reconsideración. Presidencia revisa antecedentes, evidencia y argumentos; la resolución posterior es definitiva dentro del club.$$, $$Decisión final inicial: Presidencia. La persona puede presentar 1 solicitud de reconsideración. Presidencia revisa antecedentes, evidencia y argumentos; la resolución posterior es definitiva dentro del club.$$, array[$$expulsión$$]),
($$TC-076$$, $$conflictos-entre-ninos$$, $$Conflictos entre niños$$, $$conducta$$, $$tannery_city$$, $$Ruta: informar al entrenador/Área Deportiva; Área Deportiva escucha y media; si continúa o requiere más atención, Dirección interviene; cuando corresponda, reunión con padres/tutores.$$, $$Ruta: informar al entrenador/Área Deportiva; Área Deportiva escucha y media; si continúa o requiere más atención, Dirección interviene; cuando corresponda, reunión con padres/tutores. Adultos no deben resolver físicamente conflictos entre menores por cuenta propia.$$, array[$$conflictos$$,$$niños$$]),
($$TC-077$$, $$conducta-de-padres$$, $$Conducta de padres$$, $$conducta$$, $$tannery_city$$, $$Prohibido sujetar físicamente a un jugador ajeno, amenazar, intimidar, disciplinar directamente a un menor ajeno, promover peleas o confrontar violentamente.$$, $$Prohibido sujetar físicamente a un jugador ajeno, amenazar, intimidar, disciplinar directamente a un menor ajeno, promover peleas o confrontar violentamente. Toda preocupación debe canalizarse al club.$$, array[$$conducta$$,$$padres$$]),
($$TC-078$$, $$actas-administrativas$$, $$Actas administrativas$$, $$conducta$$, $$tannery_city$$, $$Se usan para documentar incidentes, incumplimientos, hechos relevantes, acuerdos y sanciones. Conservar durante permanencia y el periodo administrativo/disciplinario necesario para seguimiento.$$, $$Se usan para documentar incidentes, incumplimientos, hechos relevantes, acuerdos y sanciones. Conservar durante permanencia y el periodo administrativo/disciplinario necesario para seguimiento.$$, array[$$actas$$,$$administrativas$$]),
($$TC-079$$, $$delegado-de-padres$$, $$Delegado de padres$$, $$familias$$, $$tannery_city$$, $$Cada categoría puede nombrar 1 Delegado de Padres como enlace, comunicación, organización e inquietudes generales.$$, $$Cada categoría puede nombrar 1 Delegado de Padres como enlace, comunicación, organización e inquietudes generales. No tiene acceso automático a actas, expedientes, datos médicos, sanciones individuales o información privada.$$, array[$$delegado$$,$$padres$$]),
($$TC-080$$, $$canales-oficiales$$, $$Canales oficiales$$, $$familias$$, $$tannery_city$$, $$WhatsApp oficial de Tannery City, grupo oficial de Administración, grupo/subgrupo oficial de categoría, Tanner OS y contacto directo con entrenador para asuntos deportivos.$$, $$WhatsApp oficial de Tannery City, grupo oficial de Administración, grupo/subgrupo oficial de categoría, Tanner OS y contacto directo con entrenador para asuntos deportivos.$$, array[$$canales$$,$$oficiales$$])
) as v(policy_code, slug, title, category, scope, short_answer, official_content, keywords)
where o.public_key='1850TC1850'
  and not exists (select 1 from app.policies p where p.organization_id=o.id and p.slug=v.slug);
;
