create index if not exists idx_players_source_prospect_id on app.players(source_prospect_id) where source_prospect_id is not null;
create index if not exists idx_player_evaluations_player_id on app.player_evaluations(player_id);
create index if not exists idx_player_notes_player_id on app.player_notes(player_id);
create index if not exists idx_match_player_stats_match_id on app.match_player_stats(match_id);
create index if not exists idx_match_player_stats_player_id on app.match_player_stats(player_id);
create index if not exists idx_matches_season_id on app.matches(season_id) where season_id is not null;
create index if not exists idx_matches_team_id on app.matches(team_id) where team_id is not null;
create index if not exists idx_matches_competition_id on app.matches(competition_id) where competition_id is not null;
create index if not exists idx_matches_venue_id on app.matches(venue_id) where venue_id is not null;
create index if not exists idx_sessions_season_id on app.sessions(season_id) where season_id is not null;
create index if not exists idx_sessions_team_id on app.sessions(team_id) where team_id is not null;
create index if not exists idx_sessions_venue_id on app.sessions(venue_id) where venue_id is not null;
create index if not exists idx_club_events_sponsor_id on app.club_events(sponsor_id) where sponsor_id is not null;
create index if not exists idx_orders_discount_authorized_by on app.orders(discount_authorized_by_user_id) where discount_authorized_by_user_id is not null;
create index if not exists idx_player_benefits_funding_configured_by on app.player_benefits(funding_configured_by_user_id) where funding_configured_by_user_id is not null;
create index if not exists idx_production_batches_created_by on app.production_batches(created_by_user_id) where created_by_user_id is not null;
create index if not exists idx_warranties_created_by on app.warranties(created_by_user_id) where created_by_user_id is not null;
create index if not exists idx_competitions_season_id on app.competitions(season_id) where season_id is not null;
create index if not exists idx_charge_adj_auth_authorized_by on app.charge_adjustment_authorizations(authorized_by_user_id) where authorized_by_user_id is not null;
create index if not exists idx_charge_adj_auth_consumed_by on app.charge_adjustment_authorizations(consumed_by_user_id) where consumed_by_user_id is not null;
create index if not exists idx_charge_adj_auth_revoked_by on app.charge_adjustment_authorizations(revoked_by_user_id) where revoked_by_user_id is not null;
create index if not exists idx_charge_adjustments_authorized_by on app.charge_adjustments(authorized_by_user_id) where authorized_by_user_id is not null;
create index if not exists idx_charge_adjustments_posted_by on app.charge_adjustments(posted_by_user_id) where posted_by_user_id is not null;
create index if not exists idx_charge_adjustments_voided_by on app.charge_adjustments(voided_by_user_id) where voided_by_user_id is not null;
create index if not exists idx_expenses_created_by on app.expenses(created_by_user_id) where created_by_user_id is not null;
create index if not exists idx_expenses_voided_by on app.expenses(voided_by_user_id) where voided_by_user_id is not null;
create index if not exists idx_public_subscriptions_plan_id on public.subscriptions(plan_id);
create index if not exists idx_public_plan_modules_module_code on public.plan_modules(module_code);
create index if not exists idx_public_role_module_permissions_module_code on public.role_module_permissions(module_code);
create index if not exists idx_public_org_module_overrides_module_code on public.organization_module_overrides(module_code);
create index if not exists idx_private_membership_module_overrides_module_code on private.membership_module_overrides(module_code);;
