create index if not exists idx_v2_charge_adj_auth_charge_org on app.charge_adjustment_authorizations(charge_id, organization_id);
create index if not exists idx_v2_charge_adjustments_auth_org on app.charge_adjustments(authorization_id, organization_id) where authorization_id is not null;
create index if not exists idx_v2_charges_academy_enrollment_org on app.charges(academy_enrollment_id, organization_id) where academy_enrollment_id is not null;
create index if not exists idx_v2_charges_player_benefit_org on app.charges(player_benefit_id, organization_id) where player_benefit_id is not null;
create index if not exists idx_v2_expenses_order_org on app.expenses(order_id, organization_id) where order_id is not null;
create index if not exists idx_v2_expenses_batch_org on app.expenses(production_batch_id, organization_id) where production_batch_id is not null;
create index if not exists idx_v2_gk_packages_academy_org on app.goalkeeper_packages(academy_id, organization_id);
create index if not exists idx_v2_gk_packages_player_org on app.goalkeeper_packages(player_id, organization_id);
create index if not exists idx_v2_gk_packages_payment on app.goalkeeper_packages(payment_id) where payment_id is not null;
create index if not exists idx_v2_gk_sessions_academy_org on app.goalkeeper_sessions(academy_id, organization_id);
create index if not exists idx_v2_gk_sessions_player_org on app.goalkeeper_sessions(player_id, organization_id);
create index if not exists idx_v2_gk_sessions_package_org on app.goalkeeper_sessions(package_id, organization_id) where package_id is not null;
create index if not exists idx_v2_gk_sessions_payment on app.goalkeeper_sessions(payment_id) where payment_id is not null;
create index if not exists idx_v2_order_payments_payment on app.order_payments(payment_id);
create index if not exists idx_v2_production_batch_orders_batch_org on app.production_batch_orders(batch_id, organization_id);
create index if not exists idx_v2_production_batch_orders_order_org on app.production_batch_orders(order_id, organization_id);
create index if not exists idx_v2_production_batch_warranties_batch_org on app.production_batch_warranties(batch_id, organization_id);
create index if not exists idx_v2_production_batch_warranties_warranty_org on app.production_batch_warranties(warranty_id, organization_id);
create index if not exists idx_v2_warranties_order_org on app.warranties(order_id, organization_id);
create index if not exists idx_v2_warranties_replacement_batch_org on app.warranties(replacement_batch_id, organization_id) where replacement_batch_id is not null;
create index if not exists idx_v2_warranty_items_warranty_org on app.warranty_items(warranty_id, organization_id);
create index if not exists idx_v2_warranty_items_order_item on app.warranty_items(order_item_id);;
