-- Centro Tanner: catálogo completo de políticas (1-133) del Contexto Maestro
-- entregado por Presidencia. Contenido oficial verbatim; solo se calculó
-- categoría, slug y una respuesta corta (primeras oraciones del texto
-- oficial, sin agregar información nueva). Las políticas 134-141 del
-- documento son instrucciones para el agente/implementación, no reglas
-- del club, así que no se publican. La política 142 (Pagos y servicios
-- no acumulables) ya estaba cargada desde antes.
insert into app.policies (
  organization_id, policy_code, slug, title, category, scope, short_answer,
  official_content, keywords, status, requires_acceptance, effective_date, published_at
)
select o.id, v.policy_code, v.slug, v.title, v.category, v.scope, v.short_answer,
  v.official_content, v.keywords, 'published', false, date '2026-09-09', timestamptz '2026-09-09 19:07:52+00'
from public.organizations o
cross join (values
($$TC-081$$, $$grupos-sociales-no-oficiales$$, $$Grupos sociales no oficiales$$, $$familias$$, $$tannery_city$$, $$Grupos creados por padres no son canales oficiales. Tannery City no administra, supervisa permanentemente ni responde por su contenido.$$, $$Grupos creados por padres no son canales oficiales. Tannery City no administra, supervisa permanentemente ni responde por su contenido. Si existe evidencia de amenazas, hostigamiento, discriminación, agresiones o conducta contraria al Código Tanner, el club puede revisar y actuar. No sancionar solo por opiniones o inconformidades legítimas.$$, array[$$grupos$$,$$sociales$$,$$oficiales$$]),
($$TC-082$$, $$avisos-oficiales$$, $$Avisos oficiales$$, $$familias$$, $$tannery_city$$, $$Un aviso publicado mediante canal oficial se considera comunicado. Cada familia es responsable de mantenerse atenta.$$, $$Un aviso publicado mediante canal oficial se considera comunicado. Cada familia es responsable de mantenerse atenta.$$, array[$$avisos$$,$$oficiales$$]),
($$TC-083$$, $$horario-administrativo$$, $$Horario administrativo$$, $$familias$$, $$tannery_city$$, $$Lunes a viernes: 10:00–14:00 y 16:00–19:00 hrs. Objetivo de respuesta: máximo 24 horas hábiles.$$, $$Lunes a viernes: 10:00–14:00 y 16:00–19:00 hrs. Objetivo de respuesta: máximo 24 horas hábiles.$$, array[$$horario$$,$$administrativo$$]),
($$TC-084$$, $$encuestas$$, $$Encuestas$$, $$familias$$, $$tannery_city$$, $$Las encuestas a familias son consultivas. Decisión final deportiva/operativa corresponde a Dirección, Área Deportiva o Presidencia según el tema.$$, $$Las encuestas a familias son consultivas. Decisión final deportiva/operativa corresponde a Dirección, Área Deportiva o Presidencia según el tema.$$, array[$$encuestas$$]),
($$TC-085$$, $$reporte-de-incidentes$$, $$Reporte de incidentes$$, $$seguridad$$, $$tannery_city$$, $$Canal: WhatsApp oficial de Tannery City. No se requiere módulo independiente de denuncias en Tanner OS.$$, $$Canal: WhatsApp oficial de Tannery City. No se requiere módulo independiente de denuncias en Tanner OS. Objetivo: conservar evidencia, fecha y seguimiento.$$, array[$$reporte$$,$$incidentes$$]),
($$TC-086$$, $$foto-interna$$, $$Foto interna$$, $$privacidad$$, $$tannery_city$$, $$Foto del jugador obligatoria para identificación y operación interna.$$, $$Foto del jugador obligatoria para identificación y operación interna.$$, array[$$foto$$,$$interna$$]),
($$TC-087$$, $$uso-de-imagen$$, $$Uso de imagen$$, $$privacidad$$, $$tannery_city$$, $$Marketing/publicidad es opcional. Tutor debe aceptar o negar expresamente. Negarse no afecta derecho a entrenar.$$, $$Marketing/publicidad es opcional. Tutor debe aceptar o negar expresamente. Negarse no afecta derecho a entrenar.$$, array[$$uso$$,$$imagen$$]),
($$TC-088$$, $$fotos-videos-del-staff$$, $$Fotos y videos del staff$$, $$privacidad$$, $$tannery_city$$, $$Entrenadores pueden tomar material con fines deportivos legítimos. Debe respetar autorizaciones, transferirse a almacenamiento oficial y no conservarse innecesariamente en dispositivos personales.$$, $$Entrenadores pueden tomar material con fines deportivos legítimos. Debe respetar autorizaciones, transferirse a almacenamiento oficial y no conservarse innecesariamente en dispositivos personales. Publicación en cuentas personales solo con autorización vigente de imagen.$$, array[$$fotos$$,$$videos$$,$$staff$$]),
($$TC-089$$, $$fotos-y-videos-de-familias$$, $$Fotos y videos de familias$$, $$privacidad$$, $$tannery_city$$, $$Se permiten para uso personal procurando respetar privacidad, imagen de otros menores e instrucciones del club.$$, $$Se permiten para uso personal procurando respetar privacidad, imagen de otros menores e instrucciones del club.$$, array[$$fotos$$,$$videos$$,$$familias$$]),
($$TC-090$$, $$drones-y-streaming$$, $$Drones y streaming$$, $$privacidad$$, $$tannery_city$$, $$Drones solo con autorización previa. Transmisiones/streaming por terceros requieren autorización.$$, $$Drones solo con autorización previa. Transmisiones/streaming por terceros requieren autorización.$$, array[$$drones$$,$$streaming$$]),
($$TC-091$$, $$uso-de-marca$$, $$Uso de marca$$, $$privacidad$$, $$tannery_city$$, $$No utilizar sin autorización nombre Tannery City, Tannery City Park, escudo, logos, diseños, identidad, jerseys o elementos gráficos para eventos, productos, negocios, patrocinios, campañas, torneos o ventas.$$, $$No utilizar sin autorización nombre Tannery City, Tannery City Park, escudo, logos, diseños, identidad, jerseys o elementos gráficos para eventos, productos, negocios, patrocinios, campañas, torneos o ventas.$$, array[$$uso$$,$$marca$$]),
($$TC-092$$, $$patrocinios$$, $$Patrocinios$$, $$conducta$$, $$tannery_city$$, $$Ninguna familia, jugador, entrenador o tercero puede representar a Tannery City ante una empresa o negociar patrocinio sin autorización.$$, $$Ninguna familia, jugador, entrenador o tercero puede representar a Tannery City ante una empresa o negociar patrocinio sin autorización.$$, array[$$patrocinios$$]),
($$TC-093$$, $$colectas-dinero$$, $$Colectas / dinero$$, $$conducta$$, $$tannery_city$$, $$No solicitar dinero, cooperaciones o colectas usando grupos/nombre Tanner sin autorización.$$, $$No solicitar dinero, cooperaciones o colectas usando grupos/nombre Tanner sin autorización.$$, array[$$colectas$$,$$dinero$$]),
($$TC-094$$, $$ventas-rifas$$, $$Ventas / rifas$$, $$tannery_city_park$$, $$tannery_city$$, $$Pueden existir con aviso previo a Administración. No pueden competir directamente con tienda TCP, comercializar alcohol sin autorización ni presentarse como actividad oficial Tanner sin permiso.$$, $$Pueden existir con aviso previo a Administración. No pueden competir directamente con tienda TCP, comercializar alcohol sin autorización ni presentarse como actividad oficial Tanner sin permiso.$$, array[$$ventas$$,$$rifas$$]),
($$TC-095$$, $$cumpleanos$$, $$Cumpleaños$$, $$tannery_city_park$$, $$tannery_city$$, $$Permitidos convivios sencillos en área social si no interfieren con entrenamiento, no invaden cancha y respetan operación TCP.$$, $$Permitidos convivios sencillos en área social si no interfieren con entrenamiento, no invaden cancha y respetan operación TCP.$$, array[$$cumpleaños$$]),
($$TC-096$$, $$alcohol$$, $$Alcohol$$, $$tannery_city_park$$, $$tannery_city$$, $$Prohibido en cancha, área deportiva y actividades deportivas infantiles. En área social habilitada, consumo solo ahí conforme reglas TCP.$$, $$Prohibido en cancha, área deportiva y actividades deportivas infantiles. En área social habilitada, consumo solo ahí conforme reglas TCP.$$, array[$$alcohol$$]),
($$TC-097$$, $$tabaco$$, $$Tabaco$$, $$tannery_city_park$$, $$tannery_city$$, $$Prohibido en área deportiva/cancha. Solo en área permitida/social según reglas TCP.$$, $$Prohibido en área deportiva/cancha. Solo en área permitida/social según reglas TCP.$$, array[$$tabaco$$]),
($$TC-098$$, $$vapeo$$, $$Vapeo$$, $$tannery_city_park$$, $$tannery_city$$, $$Permitido fuera de cancha; nunca debe interferir con actividades de menores.$$, $$Permitido fuera de cancha; nunca debe interferir con actividades de menores.$$, array[$$vapeo$$]),
($$TC-099$$, $$comida$$, $$Comida$$, $$tannery_city_park$$, $$tannery_city$$, $$No consumir dentro de cancha. Usar área social o zonas permitidas.$$, $$No consumir dentro de cancha. Usar área social o zonas permitidas.$$, array[$$comida$$]),
($$TC-100$$, $$mascotas$$, $$Mascotas$$, $$tannery_city_park$$, $$tannery_city$$, $$Pueden ingresar con autorización previa.$$, $$Pueden ingresar con autorización previa.$$, array[$$mascotas$$]),
($$TC-101$$, $$bicicletas-patines$$, $$Bicicletas / patines$$, $$tannery_city_park$$, $$tannery_city$$, $$No dentro de cancha. Solo en zonas autorizadas, estacionamiento/alrededores cuando sea seguro.$$, $$No dentro de cancha. Solo en zonas autorizadas, estacionamiento/alrededores cuando sea seguro.$$, array[$$bicicletas$$,$$patines$$]),
($$TC-102$$, $$hermanos-menores-acompanantes$$, $$Hermanos / menores acompañantes$$, $$seguridad$$, $$tannery_city$$, $$Son responsabilidad total de su padre/tutor. No deben ingresar a cancha sin autorización.$$, $$Son responsabilidad total de su padre/tutor. No deben ingresar a cancha sin autorización.$$, array[$$hermanos$$,$$menores$$,$$acompañantes$$]),
($$TC-103$$, $$objetos-prohibidos$$, $$Objetos prohibidos$$, $$seguridad$$, $$tannery_city$$, $$Prohibidos drogas, armas, objetos peligrosos, pirotecnia, bengalas y elementos que pongan en riesgo la seguridad.$$, $$Prohibidos drogas, armas, objetos peligrosos, pirotecnia, bengalas y elementos que pongan en riesgo la seguridad.$$, array[$$objetos$$,$$prohibidos$$]),
($$TC-104$$, $$velocidad-tcp$$, $$Velocidad TCP$$, $$tannery_city_park$$, $$tannery_city$$, $$Velocidad máxima dentro de instalaciones: 10 km/h.$$, $$Velocidad máxima dentro de instalaciones: 10 km/h.$$, array[$$velocidad$$,$$tcp$$]),
($$TC-105$$, $$gafete-de-estacionamiento$$, $$Gafete de estacionamiento$$, $$estacionamiento$$, $$tannery_city$$, $$Costo $100 MXN, vigencia 1 año natural. Evita cobro ordinario de estacionamiento Tanner durante vigencia conforme condiciones.$$, $$Costo $100 MXN, vigencia 1 año natural. Evita cobro ordinario de estacionamiento Tanner durante vigencia conforme condiciones. Sin gafete: auto $20, moto $10. Máximo 2 gafetes por familia. Reposición $100. No se puede prestar a terceros. Uso indebido puede cancelar beneficio.$$, array[$$gafete$$,$$estacionamiento$$]),
($$TC-106$$, $$banos$$, $$Baños$$, $$tannery_city_park$$, $$tannery_city$$, $$Disponibles para usuarios de TCP. Daños identificados: responsable cubre reparación/reposición.$$, $$Disponibles para usuarios de TCP. Daños identificados: responsable cubre reparación/reposición.$$, array[$$baños$$]),
($$TC-107$$, $$bodega$$, $$Bodega$$, $$tannery_city_park$$, $$tannery_city$$, $$Acceso exclusivo a personal autorizado. Jugadores/familias no ingresan sin autorización.$$, $$Acceso exclusivo a personal autorizado. Jugadores/familias no ingresan sin autorización.$$, array[$$bodega$$]),
($$TC-108$$, $$bocinas-musica$$, $$Bocinas / música$$, $$tannery_city_park$$, $$tannery_city$$, $$Solo con autorización previa.$$, $$Solo con autorización previa.$$, array[$$bocinas$$,$$música$$]),
($$TC-109$$, $$staff-tanner$$, $$Staff Tanner$$, $$conducta$$, $$tannery_city$$, $$Todo entrenador debe firmar Código de Conducta Tanner, presentar identificación, entregar documentación requerida, entregar carta/constancia de antecedentes solicitada dentro de los primeros 30 días y cumplir periodo de prueba de 3 meses.$$, $$Todo entrenador debe firmar Código de Conducta Tanner, presentar identificación, entregar documentación requerida, entregar carta/constancia de antecedentes solicitada dentro de los primeros 30 días y cumplir periodo de prueba de 3 meses.$$, array[$$staff$$,$$tanner$$]),
($$TC-110$$, $$perfil-del-entrenador$$, $$Perfil del entrenador$$, $$conducta$$, $$tannery_city$$, $$Preferentemente Licenciatura en Educación Física/deporte/área relacionada, experiencia relevante, certificaciones reconocidas y experiencia deportiva suficiente.$$, $$Preferentemente Licenciatura en Educación Física/deporte/área relacionada, experiencia relevante, certificaciones reconocidas y experiencia deportiva suficiente. Evaluación final: Presidencia/Dirección Deportiva.$$, array[$$perfil$$,$$entrenador$$]),
($$TC-111$$, $$contratacion-y-baja-de-staff$$, $$Contratación y baja de staff$$, $$conducta$$, $$tannery_city$$, $$Autoridad: Presidencia.$$, $$Autoridad: Presidencia.$$, array[$$contratación$$,$$baja$$,$$staff$$]),
($$TC-112$$, $$entrenador-a-solas-con-menor$$, $$Entrenador a solas con menor$$, $$seguridad$$, $$tannery_city$$, $$Evitar estar a solas con un menor en espacios privados/cerrados. Interacciones uno a uno preferentemente visibles e interrumpibles.$$, $$Evitar estar a solas con un menor en espacios privados/cerrados. Interacciones uno a uno preferentemente visibles e interrumpibles.$$, array[$$entrenador$$,$$solas$$,$$menor$$]),
($$TC-113$$, $$banos-y-cambio-de-ropa$$, $$Baños y cambio de ropa$$, $$seguridad$$, $$tannery_city$$, $$Cambios de ropa corresponden a padres/tutores. Entrenadores pueden acompañar hasta acceso de baño cuando sea necesario.$$, $$Cambios de ropa corresponden a padres/tutores. Entrenadores pueden acompañar hasta acceso de baño cuando sea necesario. Evitar asistencia privada innecesaria.$$, array[$$baños$$,$$cambio$$,$$ropa$$]),
($$TC-114$$, $$contacto-fisico$$, $$Contacto físico$$, $$seguridad$$, $$tannery_city$$, $$Contacto deportivo apropiado permitido cuando sea breve, respetuoso, visible, adecuado a la edad y aceptado por el menor.$$, $$Contacto deportivo apropiado permitido cuando sea breve, respetuoso, visible, adecuado a la edad y aceptado por el menor. Ejemplos: celebración, consuelo, corrección deportiva apropiada. No contacto forzado, íntimo, secreto, prolongado o incómodo.$$, array[$$contacto$$,$$físico$$]),
($$TC-115$$, $$castigo-fisico$$, $$Castigo físico$$, $$seguridad$$, $$tannery_city$$, $$No utilizar ejercicio como castigo o humillación. Consecuencias deben ser formativas/deportivas.$$, $$No utilizar ejercicio como castigo o humillación. Consecuencias deben ser formativas/deportivas.$$, array[$$castigo$$,$$físico$$]),
($$TC-116$$, $$lenguaje-de-entrenadores$$, $$Lenguaje de entrenadores$$, $$conducta$$, $$tannery_city$$, $$No usar groserías dirigidas a jugadores. Prohibido humillar, ridiculizar o degradar públicamente.$$, $$No usar groserías dirigidas a jugadores. Prohibido humillar, ridiculizar o degradar públicamente.$$, array[$$lenguaje$$,$$entrenadores$$]),
($$TC-117$$, $$quejas-contra-entrenadores$$, $$Quejas contra entrenadores$$, $$conducta$$, $$tannery_city$$, $$Ruta: recepción; revisión Área Deportiva; investigación; Presidencia cuando corresponda. Continuidad durante investigación depende de gravedad, riesgo y hechos.$$, $$Ruta: recepción; revisión Área Deportiva; investigación; Presidencia cuando corresponda. Continuidad durante investigación depende de gravedad, riesgo y hechos.$$, array[$$quejas$$,$$contra$$,$$entrenadores$$]),
($$TC-118$$, $$invitados-auxiliares$$, $$Invitados / auxiliares$$, $$seguridad$$, $$tannery_city$$, $$Entrenador no puede llevar asistentes/invitados a trabajar con menores sin autorización.$$, $$Entrenador no puede llevar asistentes/invitados a trabajar con menores sin autorización.$$, array[$$invitados$$,$$auxiliares$$]),
($$TC-119$$, $$cambio-cancelacion-de-sesion$$, $$Cambio o cancelación de sesión$$, $$entrenamientos$$, $$tannery_city$$, $$Entrenador no modifica horarios ni cancela unilateralmente. Debe autorizar Área Deportiva.$$, $$Entrenador no modifica horarios ni cancela unilateralmente. Debe autorizar Área Deportiva.$$, array[$$cambio$$,$$cancelación$$,$$sesión$$]),
($$TC-120$$, $$ausencia-del-entrenador$$, $$Ausencia del entrenador$$, $$entrenamientos$$, $$tannery_city$$, $$Dirección Deportiva organiza sustitución/cobertura.$$, $$Dirección Deportiva organiza sustitución/cobertura.$$, array[$$ausencia$$,$$entrenador$$])
) as v(policy_code, slug, title, category, scope, short_answer, official_content, keywords)
where o.public_key='1850TC1850'
  and not exists (select 1 from app.policies p where p.organization_id=o.id and p.slug=v.slug);
;
