-- Centro Tanner: catálogo completo de políticas (1-133) del Contexto Maestro
-- entregado por Presidencia. Contenido oficial verbatim; solo se calculó
-- categoría, slug y una respuesta corta (primeras oraciones del texto
-- oficial, sin agregar información nueva). Las políticas 134-141 del
-- documento son instrucciones para el agente/implementación, no reglas
-- del club, así que no se publican. La política 142 (Pagos y servicios
-- no acumulables) ya estaba cargada desde antes.
insert into app.policies (
  organization_id, policy_code, slug, title, category, scope, short_answer,
  official_content, keywords, status, requires_acceptance, effective_date, published_at
)
select o.id, v.policy_code, v.slug, v.title, v.category, v.scope, v.short_answer,
  v.official_content, v.keywords, 'published', false, date '2026-09-09', timestamptz '2026-09-09 19:07:52+00'
from public.organizations o
cross join (values
($$TC-121$$, $$sanciones-del-entrenador-a-jugador$$, $$Sanciones del entrenador a jugador$$, $$conducta$$, $$tannery_city$$, $$Puede retirar al jugador de la sesión actual por indisciplina cuando sea necesario y reportar inmediatamente a Dirección Deportiva / Presidencia si corresponde.$$, $$Puede retirar al jugador de la sesión actual por indisciplina cuando sea necesario y reportar inmediatamente a Dirección Deportiva / Presidencia si corresponde. Suspender sesiones posteriores: solo Dirección Deportiva.$$, array[$$sanciones$$,$$entrenador$$,$$jugador$$]),
($$TC-122$$, $$multas-de-entrenadores$$, $$Multas de entrenadores$$, $$conducta$$, $$tannery_city$$, $$Profesores no pueden cobrar multas disciplinarias directamente.$$, $$Profesores no pueden cobrar multas disciplinarias directamente.$$, array[$$multas$$,$$entrenadores$$]),
($$TC-123$$, $$regalos-propinas$$, $$Regalos / propinas$$, $$conducta$$, $$tannery_city$$, $$Staff no debe aceptar dinero, propinas o beneficios de familias. Especialmente prohibido cualquier beneficio ligado a minutos, titularidad, convocatoria, categoría, becas o decisiones deportivas.$$, $$Staff no debe aceptar dinero, propinas o beneficios de familias. Especialmente prohibido cualquier beneficio ligado a minutos, titularidad, convocatoria, categoría, becas o decisiones deportivas.$$, array[$$regalos$$,$$propinas$$]),
($$TC-124$$, $$relaciones-personales-comerciales$$, $$Relaciones personales o comerciales$$, $$conducta$$, $$tannery_city$$, $$Entrenadores pueden tener relaciones personales o comerciales legítimas con familias, pero nunca deben influir en decisiones deportivas ni crear conflicto de interés.$$, $$Entrenadores pueden tener relaciones personales o comerciales legítimas con familias, pero nunca deben influir en decisiones deportivas ni crear conflicto de interés.$$, array[$$relaciones$$,$$personales$$,$$comerciales$$]),
($$TC-125$$, $$invitaciones-sociales$$, $$Invitaciones sociales$$, $$conducta$$, $$tannery_city$$, $$Entrenadores pueden aceptar invitaciones familiares/sociales; no deben influir en decisiones deportivas.$$, $$Entrenadores pueden aceptar invitaciones familiares/sociales; no deben influir en decisiones deportivas.$$, array[$$invitaciones$$,$$sociales$$]),
($$TC-126$$, $$sesiones-privadas$$, $$Sesiones privadas$$, $$entrenamientos$$, $$tannery_city$$, $$Una familia puede contratar sesión privada con un entrenador solo con conocimiento del Área Deportiva, autorización correspondiente y separación clara del programa ordinario.$$, $$Una familia puede contratar sesión privada con un entrenador solo con conocimiento del Área Deportiva, autorización correspondiente y separación clara del programa ordinario.$$, array[$$sesiones$$,$$privadas$$]),
($$TC-127$$, $$transporte-de-jugadores$$, $$Transporte de jugadores$$, $$seguridad$$, $$tannery_city$$, $$Entrenador puede transportar a un menor solo con autorización expresa del padre/tutor y conocimiento del club.$$, $$Entrenador puede transportar a un menor solo con autorización expresa del padre/tutor y conocimiento del club. Debe quedar documentada.$$, array[$$transporte$$,$$jugadores$$]),
($$TC-128$$, $$whatsapp-entrenador-menor$$, $$WhatsApp entrenador-menor$$, $$seguridad$$, $$tannery_city$$, $$No mantener conversaciones privadas directas con menores. Comunicación mediante padres/tutores y canales oficiales.$$, $$No mantener conversaciones privadas directas con menores. Comunicación mediante padres/tutores y canales oficiales. No grupos privados coach-menores sin tutores.$$, array[$$whatsapp$$,$$entrenador$$,$$menor$$]),
($$TC-129$$, $$sospecha-de-maltrato-revelacion-del-menor$$, $$Sospecha de maltrato / revelación del menor$$, $$seguridad$$, $$tannery_city$$, $$Si un niño reporta violencia, abuso, maltrato, negligencia o situación preocupante, el entrenador no investiga por su cuenta.$$, $$Si un niño reporta violencia, abuso, maltrato, negligencia o situación preocupante, el entrenador no investiga por su cuenta. Ruta: Entrenador → Dirección Deportiva → Presidencia. Documentar lo esencial.$$, array[$$sospecha$$,$$maltrato$$,$$revelación$$,$$menor$$]),
($$TC-130$$, $$proteccion-de-datos$$, $$Protección de datos$$, $$privacidad$$, $$tannery_city$$, $$El registro debe incluir aviso de privacidad, consentimiento y autorización de tratamiento necesaria.$$, $$El registro debe incluir aviso de privacidad, consentimiento y autorización de tratamiento necesaria. Marketing debe tener autorización separada.$$, array[$$protección$$,$$datos$$]),
($$TC-131$$, $$excepciones$$, $$Excepciones$$, $$faq$$, $$tannery_city$$, $$Toda excepción importante al reglamento debe ser autorizada por Presidencia y quedar registrada en Tanner OS, Administración o expediente correspondiente.$$, $$Toda excepción importante al reglamento debe ser autorizada por Presidencia y quedar registrada en Tanner OS, Administración o expediente correspondiente. Evitar acuerdos verbales sin trazabilidad.$$, array[$$excepciones$$]),
($$TC-132$$, $$tannery-city-park$$, $$Tannery City Park$$, $$tannery_city_park$$, $$tannery_city_park$$, $$El Reglamento de TCP es independiente del Reglamento Tannery City. Aplica a instalaciones, torneos TCP, renta de cancha, usuarios externos, espectadores y seguridad del parque.$$, $$El Reglamento de TCP es independiente del Reglamento Tannery City. Aplica a instalaciones, torneos TCP, renta de cancha, usuarios externos, espectadores y seguridad del parque. Familias Tanner en TCP también cumplen sus reglas vigentes.$$, array[$$tannery$$,$$city$$,$$park$$]),
($$TC-133$$, $$reglamento-de-torneos-tcp$$, $$Reglamento de torneos TCP$$, $$tannery_city_park$$, $$torneos_tcp$$, $$Mantener separado del Reglamento Tanner temas como depósitos, defaults, credenciales, alineaciones, talacha, barridas, reglas específicas de juego, desalojo, multas del torneo y pagos de equipos.$$, $$Mantener separado del Reglamento Tanner temas como depósitos, defaults, credenciales, alineaciones, talacha, barridas, reglas específicas de juego, desalojo, multas del torneo y pagos de equipos. No mezclar automáticamente con academia.$$, array[$$reglamento$$,$$torneos$$,$$tcp$$])
) as v(policy_code, slug, title, category, scope, short_answer, official_content, keywords)
where o.public_key='1850TC1850'
  and not exists (select 1 from app.policies p where p.organization_id=o.id and p.slug=v.slug);
;
