-- Centro Tanner: catálogo completo de políticas (1-133) del Contexto Maestro
-- entregado por Presidencia. Contenido oficial verbatim; solo se calculó
-- categoría, slug y una respuesta corta (primeras oraciones del texto
-- oficial, sin agregar información nueva). Las políticas 134-141 del
-- documento son instrucciones para el agente/implementación, no reglas
-- del club, así que no se publican. La política 142 (Pagos y servicios
-- no acumulables) ya estaba cargada desde antes.
insert into app.policies (
  organization_id, policy_code, slug, title, category, scope, short_answer,
  official_content, keywords, status, requires_acceptance, effective_date, published_at
)
select o.id, v.policy_code, v.slug, v.title, v.category, v.scope, v.short_answer,
  v.official_content, v.keywords, 'published', false, date '2026-09-09', timestamptz '2026-09-09 19:07:52+00'
from public.organizations o
cross join (values
($$TC-001$$, $$inscripcion$$, $$Inscripción$$, $$inscripcion$$, $$tannery_city$$, $$Costo de inscripción Tannery City: $800 MXN. Se paga al ingresar por primera vez y no existe reinscripción anual mientras el jugador permanezca activo.$$, $$Costo de inscripción Tannery City: $800 MXN. Se paga al ingresar por primera vez y no existe reinscripción anual mientras el jugador permanezca activo. En el cambio formal Baby Tanners → Tanners se paga una nueva inscripción correspondiente a la nueva etapa. Si un jugador se da de baja y quiere regresar, debe cubrir adeudos pendientes y pagar nuevamente la inscripción vigente, salvo acuerdo especial autorizado por Presidencia. Con 2 meses consecutivos sin asistir y sin acuerdo autorizado, podrá considerarse dado de baja.$$, array[$$inscripción$$]),
($$TC-002$$, $$baja-voluntaria$$, $$Baja voluntaria$$, $$inscripcion$$, $$tannery_city$$, $$La familia deberá comunicar la baja a Administración o Área Deportiva. Se recomienda avisar mínimo 1–2 semanas antes y aproximadamente 1 mes antes si existe torneo o compromiso deportivo importante.$$, $$La familia deberá comunicar la baja a Administración o Área Deportiva. Se recomienda avisar mínimo 1–2 semanas antes y aproximadamente 1 mes antes si existe torneo o compromiso deportivo importante. No existen devoluciones por mensualidades ya pagadas; el jugador puede continuar durante el periodo cubierto.$$, array[$$baja$$,$$voluntaria$$]),
($$TC-003$$, $$mensualidades$$, $$Mensualidades$$, $$mensualidades$$, $$tannery_city$$, $$Tanners: $800 MXN mensuales. Baby Tanners 1 día por semana: $400 MXN mensuales. Baby Tanners 2 días por semana: $550 MXN mensuales.$$, $$Tanners: $800 MXN mensuales. Baby Tanners 1 día por semana: $400 MXN mensuales. Baby Tanners 2 días por semana: $550 MXN mensuales.$$, array[$$mensualidades$$]),
($$TC-004$$, $$fecha-de-pago-y-recargos$$, $$Fecha de pago y recargos$$, $$mensualidades$$, $$tannery_city$$, $$La mensualidad debe pagarse a más tardar el día 5. Desde el día 6 se agrega un recargo único de $100 MXN a esa mensualidad.$$, $$La mensualidad debe pagarse a más tardar el día 5. Desde el día 6 se agrega un recargo único de $100 MXN a esa mensualidad. El mismo adeudo no genera $100 adicionales cada mes. Ejemplo Tanners: $800 + $100 = $900. Al iniciar el siguiente mes se agrega la nueva mensualidad correspondiente.$$, array[$$fecha$$,$$pago$$,$$recargos$$]),
($$TC-005$$, $$adeudos$$, $$Adeudos$$, $$mensualidades$$, $$tannery_city$$, $$Primer mes vencido: seguimiento de Administración. Segundo mes: contacto directo con la familia.$$, $$Primer mes vencido: seguimiento de Administración. Segundo mes: contacto directo con la familia. Primera semana del tercer mes: el jugador puede tener suspensión temporal de entrenamientos y actividades hasta liquidar o establecer acuerdo autorizado por Dirección/Presidencia. El adeudo no desaparece por darse de baja. Para reingreso: liquidar adeudo + nueva inscripción, salvo acuerdo de Presidencia.$$, array[$$adeudos$$]),
($$TC-006$$, $$devoluciones$$, $$Devoluciones$$, $$mensualidades$$, $$tannery_city$$, $$Inscripciones, mensualidades y cuotas ya pagadas generalmente no son reembolsables. Solo podrán revisarse errores de cobro atribuibles al club y casos extraordinarios autorizados por Presidencia.$$, $$Inscripciones, mensualidades y cuotas ya pagadas generalmente no son reembolsables. Solo podrán revisarse errores de cobro atribuibles al club y casos extraordinarios autorizados por Presidencia.$$, array[$$devoluciones$$]),
($$TC-007$$, $$prorrateo$$, $$Prorrateo$$, $$mensualidades$$, $$tannery_city$$, $$Cuando un jugador ingresa a mitad de mes se calcula prorrateo por semanas usando base administrativa de 4 semanas por mes.$$, $$Cuando un jugador ingresa a mitad de mes se calcula prorrateo por semanas usando base administrativa de 4 semanas por mes. Ejemplo Tanners: $800 ÷ 4 = $200 por semana.$$, array[$$prorrateo$$]),
($$TC-008$$, $$vacaciones$$, $$Vacaciones$$, $$mensualidades$$, $$tannery_city$$, $$Para garantizar el lugar dentro del equipo el jugador debe mantener activa su mensualidad.$$, $$Para garantizar el lugar dentro del equipo el jugador debe mantener activa su mensualidad. Una familia con tarifa ordinaria completa puede solicitar Apoyo por Vacaciones: máximo 1 vez por año, mensualidad reducida al 50% durante el mes autorizado y sujeto a autorización de Dirección/Administración. Al pagar el 50% conserva su lugar. Jugadores con beca, Curtibrother, beneficio familiar, convenio o tarifa especial deben revisar el apoyo directamente con Administración.$$, array[$$vacaciones$$]),
($$TC-009$$, $$beneficio-familiar-hermanos-tanners$$, $$Beneficio familiar hermanos Tanners$$, $$becas$$, $$tannery_city$$, $$Nombre oficial: Beneficio Familiar Hermanos Tanners; no llamarlo beca. Solo aplica a hermanos del mismo núcleo familiar, no a primos, amigos o familia extendida.$$, $$Nombre oficial: Beneficio Familiar Hermanos Tanners; no llamarlo beca. Solo aplica a hermanos del mismo núcleo familiar, no a primos, amigos o familia extendida. Tarifas: 1 Tanner $800; 2 hermanos Tanners $1,500 total; 3 hermanos Tanners $2,000 total; 2 Baby Tanners $1,000 total; 1 Tanner + 1 Baby Tanner $1,200 total. Si un hermano se da de baja, el precio se actualiza al siguiente mes. No inventar combinaciones no definidas: consultar Administración/Presidencia.$$, array[$$beneficio$$,$$familiar$$,$$hermanos$$,$$tanners$$]),
($$TC-010$$, $$becas$$, $$Becas$$, $$becas$$, $$tannery_city$$, $$Tipos: parcial, total, Curtibrother y Beneficio Familiar Hermanos Tanners (este último no es beca deportiva).$$, $$Tipos: parcial, total, Curtibrother y Beneficio Familiar Hermanos Tanners (este último no es beca deportiva). Puede solicitarse evaluación después de 3 meses en el club. Se consideran talento, potencial, asistencia, disciplina, actitud, liderazgo, compromiso familiar, competencias, situación económica, comportamiento y desarrollo. Presidencia determina porcentaje. Primera asignación: 3 meses; renovaciones: hasta 6 meses sujetas a evaluación. Asistencia recomendada: 90%. La beca cubre únicamente el porcentaje autorizado de mensualidad y no incluye automáticamente inscripción, uniformes, arbitrajes, torneos, viajes, transporte, servicios externos o productos. Puede perderse por inasistencia, indisciplina, incumplimiento, falta de compromiso, faltas graves o conducta contraria a valores Tanner. Una falta grave puede causar pérdida inmediata. El ajuste económico normalmente aplica a partir del siguiente mes. Decisión final: Presidencia.$$, array[$$becas$$]),
($$TC-011$$, $$curtibrother$$, $$Curtibrother$$, $$becas$$, $$tannery_city$$, $$Programa distinto a una beca ordinaria. Un tercero, empresa o persona puede financiar el desarrollo de un Tanner.$$, $$Programa distinto a una beca ordinaria. Un tercero, empresa o persona puede financiar el desarrollo de un Tanner. Puede incluir beneficios acordados de reconocimiento, marketing, exposición, activaciones y relación con el club. Sus condiciones se rigen por el programa Curtibrother vigente.$$, array[$$curtibrother$$]),
($$TC-012$$, $$que-incluye-la-mensualidad$$, $$Qué incluye la mensualidad$$, $$mensualidades$$, $$tannery_city$$, $$Entrenamientos programados de la categoría, uso de cancha durante sesiones, entrenadores/cuerpo técnico, material deportivo ordinario, planeación, metodología Tannery City y seguimiento deportivo ordinario.$$, $$Entrenamientos programados de la categoría, uso de cancha durante sesiones, entrenadores/cuerpo técnico, material deportivo ordinario, planeación, metodología Tannery City y seguimiento deportivo ordinario.$$, array[$$qué$$,$$incluye$$,$$mensualidad$$]),
($$TC-013$$, $$que-no-incluye-la-mensualidad$$, $$Qué no incluye la mensualidad$$, $$mensualidades$$, $$tannery_city$$, $$No incluye automáticamente inscripción, uniformes, academia especializada de porteros, arbitrajes, amistosos con costos extraordinarios, cuotas de torneos, competencias extraordinarias, viajes, transporte, hospedaje, peajes, sesiones privadas, fisioterapia, servicios externos o productos de tienda.$$, $$No incluye automáticamente inscripción, uniformes, academia especializada de porteros, arbitrajes, amistosos con costos extraordinarios, cuotas de torneos, competencias extraordinarias, viajes, transporte, hospedaje, peajes, sesiones privadas, fisioterapia, servicios externos o productos de tienda.$$, array[$$qué$$,$$incluye$$,$$mensualidad$$]),
($$TC-014$$, $$asistencia$$, $$Asistencia$$, $$asistencia$$, $$tannery_city$$, $$Objetivo mínimo jugador ordinario: 80%. Jugador con beca: 90%. Las ausencias deben notificarse previamente cuando sea posible.$$, $$Objetivo mínimo jugador ordinario: 80%. Jugador con beca: 90%. Las ausencias deben notificarse previamente cuando sea posible. Pueden justificarse por enfermedad, lesión, compromiso escolar, emergencia familiar o viaje avisado. Una ausencia justificada puede evitar sanción disciplinaria, pero sigue contando estadísticamente como ausencia.$$, array[$$asistencia$$]),
($$TC-015$$, $$retardos$$, $$Retardos$$, $$asistencia$$, $$tannery_city$$, $$Los retardos recurrentes primero se revisan con la familia. Si continúan, Área Deportiva puede determinar medidas internas según categoría y situación.$$, $$Los retardos recurrentes primero se revisan con la familia. Si continúan, Área Deportiva puede determinar medidas internas según categoría y situación. Pueden afectar titularidad, decisiones deportivas, minutos y participación competitiva.$$, array[$$retardos$$]),
($$TC-016$$, $$semana-muestra$$, $$Semana muestra$$, $$inscripcion$$, $$tannery_city$$, $$Solo puede usarse una vez por jugador. Tanners: 3 entrenamientos. Baby Tanners: 2 entrenamientos. Durante la semana muestra se usa la indumentaria indicada por el club si aún no existe uniforme oficial.$$, $$Solo puede usarse una vez por jugador. Tanners: 3 entrenamientos. Baby Tanners: 2 entrenamientos. Durante la semana muestra se usa la indumentaria indicada por el club si aún no existe uniforme oficial.$$, array[$$semana$$,$$muestra$$]),
($$TC-017$$, $$baby-tanners$$, $$Baby Tanners$$, $$baby_tanners$$, $$tannery_city$$, $$Edad mínima: 3 años cumplidos. Padre/madre/tutor debe permanecer en Tannery City Park durante la sesión.$$, $$Edad mínima: 3 años cumplidos. Padre/madre/tutor debe permanecer en Tannery City Park durante la sesión. Transición aproximada hacia Tanners alrededor de los 6 años según edad, evaluación deportiva, madurez y adaptación. Área Deportiva puede decidir permanencia temporal en Baby Tanners.$$, array[$$baby$$,$$tanners$$]),
($$TC-018$$, $$documentacion-obligatoria$$, $$Documentación obligatoria$$, $$jugadores$$, $$tannery_city$$, $$CURP, acta de nacimiento, comprobante de estudios, foto actual, datos de contacto, contactos de emergencia, información médica relevante, alergias/condiciones y certificado médico deportivo anual.$$, $$CURP, acta de nacimiento, comprobante de estudios, foto actual, datos de contacto, contactos de emergencia, información médica relevante, alergias/condiciones y certificado médico deportivo anual. Falta de documentación puede impedir inscripción a torneos, trámites o procesos administrativos.$$, array[$$documentación$$,$$obligatoria$$]),
($$TC-019$$, $$actualizacion-de-datos$$, $$Actualización de datos$$, $$familias$$, $$tannery_city$$, $$La familia debe actualizar cambios de domicilio, escuela, teléfono, tutor, contacto de emergencia, alergias, condición médica e información relevante.$$, $$La familia debe actualizar cambios de domicilio, escuela, teléfono, tutor, contacto de emergencia, alergias, condición médica e información relevante. Información falsa puede generar aclaración, amonestación, suspensión o revisión de permanencia según gravedad.$$, array[$$actualización$$,$$datos$$]),
($$TC-020$$, $$informacion-medica-en-tanner-os$$, $$Información médica en Tanner OS$$, $$salud$$, $$tannery_city$$, $$Entrenadores autorizados solo podrán consultar información necesaria para atención y operación deportiva: nombre, apellidos, fecha de nacimiento, categoría, posición, pierna dominante, escuela, tipo de sangre, alergias, condiciones, contacto de emergencia y estado documental.$$, $$Entrenadores autorizados solo podrán consultar información necesaria para atención y operación deportiva: nombre, apellidos, fecha de nacimiento, categoría, posición, pierna dominante, escuela, tipo de sangre, alergias, condiciones, contacto de emergencia y estado documental.$$, array[$$información$$,$$médica$$,$$tanner$$]),
($$TC-021$$, $$certificado-medico$$, $$Certificado médico$$, $$salud$$, $$tannery_city$$, $$Obligatorio una vez al año. El club puede pedir información adicional ante lesión importante, condición médica, regreso deportivo o necesidad especial.$$, $$Obligatorio una vez al año. El club puede pedir información adicional ante lesión importante, condición médica, regreso deportivo o necesidad especial.$$, array[$$certificado$$,$$médico$$]),
($$TC-022$$, $$lesiones$$, $$Lesiones$$, $$salud$$, $$tannery_city$$, $$Puede solicitarse congelamiento de mensualidad cuando una lesión impida entrenar por 1 mes completo o más.$$, $$Puede solicitarse congelamiento de mensualidad cuando una lesión impida entrenar por 1 mes completo o más. Requiere constancia médica. Aplica sobre meses posteriores completos y no genera devolución retroactiva por semanas ya transcurridas.$$, array[$$lesiones$$]),
($$TC-023$$, $$emergencia-medica$$, $$Emergencia médica$$, $$salud$$, $$tannery_city$$, $$Ante lesión: evaluar, retirar al jugador si es necesario, contactar tutor, seguir instrucciones y, ante emergencia real, solicitar atención médica inmediata.$$, $$Ante lesión: evaluar, retirar al jugador si es necesario, contactar tutor, seguir instrucciones y, ante emergencia real, solicitar atención médica inmediata. La seguridad del menor tiene prioridad mientras se intenta contactar a la familia.$$, array[$$emergencia$$,$$médica$$]),
($$TC-024$$, $$golpes-en-la-cabeza$$, $$Golpes en la cabeza$$, $$salud$$, $$tannery_city$$, $$Ante golpe significativo: retirar al jugador, no permitir regreso inmediato, observar síntomas, contactar tutor y solicitar atención médica cuando corresponda.$$, $$Ante golpe significativo: retirar al jugador, no permitir regreso inmediato, observar síntomas, contactar tutor y solicitar atención médica cuando corresponda.$$, array[$$golpes$$,$$cabeza$$]),
($$TC-025$$, $$enfermedad$$, $$Enfermedad$$, $$salud$$, $$tannery_city$$, $$Si hay síntomas evidentes de enfermedad o riesgo de contagio, el staff puede pedir que el jugador no participe y solicitar al tutor retirarlo.$$, $$Si hay síntomas evidentes de enfermedad o riesgo de contagio, el staff puede pedir que el jugador no participe y solicitar al tutor retirarlo.$$, array[$$enfermedad$$]),
($$TC-026$$, $$medicamentos$$, $$Medicamentos$$, $$salud$$, $$tannery_city$$, $$Preferentemente administrados por padre, madre o tutor. El personal solo puede intervenir con autorización e instrucción previa y clara.$$, $$Preferentemente administrados por padre, madre o tutor. El personal solo puede intervenir con autorización e instrucción previa y clara.$$, array[$$medicamentos$$]),
($$TC-027$$, $$responsabilidad-del-tutor$$, $$Responsabilidad del tutor$$, $$familias$$, $$tannery_city$$, $$Durante actividades, el tutor debe permanecer localizable. Si otra persona quedará a cargo, debe notificarse previamente.$$, $$Durante actividades, el tutor debe permanecer localizable. Si otra persona quedará a cargo, debe notificarse previamente.$$, array[$$responsabilidad$$,$$tutor$$]),
($$TC-028$$, $$entrega-y-salida-de-menores$$, $$Entrega y salida de menores$$, $$seguridad$$, $$tannery_city$$, $$Solo tutores registrados o adultos previamente autorizados pueden recoger al jugador. Si llega alguien distinto, confirmar con el tutor antes de entregar.$$, $$Solo tutores registrados o adultos previamente autorizados pueden recoger al jugador. Si llega alguien distinto, confirmar con el tutor antes de entregar. El jugador solo puede retirarse solo con autorización expresa del tutor.$$, array[$$entrega$$,$$salida$$,$$menores$$]),
($$TC-029$$, $$recogida-tardia$$, $$Recogida tardía$$, $$seguridad$$, $$tannery_city$$, $$Tolerancia recomendada máxima: 30 minutos. La familia debe recoger puntualmente. Mientras no se entregue a adulto autorizado, el club continuará procurando resguardo y contactará responsables.$$, $$Tolerancia recomendada máxima: 30 minutos. La familia debe recoger puntualmente. Mientras no se entregue a adulto autorizado, el club continuará procurando resguardo y contactará responsables. Reincidencias pueden generar medidas administrativas.$$, array[$$recogida$$,$$tardía$$]),
($$TC-030$$, $$partidos-amistosos-en-dia-de-entrenamiento$$, $$Partidos amistosos en día de entrenamiento$$, $$entrenamientos$$, $$tannery_city$$, $$Cuando sustituyan entrenamiento normal, la participación es opcional. Opción A: participar y cubrir conceptos correspondientes.$$, $$Cuando sustituyan entrenamiento normal, la participación es opcional. Opción A: participar y cubrir conceptos correspondientes. Opción B: entrenamiento alternativo. Para entrenamiento alternativo: avisar mínimo 48 h antes, tener mensualidad ordinaria completa y cuenta al corriente. Becas/convenios/tarifas especiales se revisan con Administración. El club procurará anunciar amistosos con al menos 24 h de anticipación cuando sea posible.$$, array[$$partidos$$,$$amistosos$$,$$día$$,$$entrenamiento$$]),
($$TC-031$$, $$torneos$$, $$Torneos$$, $$partidos$$, $$tannery_city$$, $$Participación opcional antes de confirmar inscripción. Una vez que la familia confirma, registra al jugador y acepta costos, se genera compromiso con la competencia.$$, $$Participación opcional antes de confirmar inscripción. Una vez que la familia confirma, registra al jugador y acepta costos, se genera compromiso con la competencia. Cuotas pagadas generalmente no son reembolsables si después se retiran. Excepciones por enfermedad, lesión o emergencia familiar pueden revisarse.$$, array[$$torneos$$]),
($$TC-032$$, $$costos-de-torneos$$, $$Costos de torneos$$, $$partidos$$, $$tannery_city$$, $$La cuota puede incluir inscripción, arbitrajes, operación y gastos relacionados. Dirección Deportiva y Administración determinan costo total y distribución entre participantes.$$, $$La cuota puede incluir inscripción, arbitrajes, operación y gastos relacionados. Dirección Deportiva y Administración determinan costo total y distribución entre participantes.$$, array[$$costos$$,$$torneos$$]),
($$TC-033$$, $$cancelacion-de-torneo$$, $$Cancelación de torneo$$, $$partidos$$, $$tannery_city$$, $$Si el organizador cancela, devolución depende del dinero efectivamente recuperado y de gastos no recuperables ya realizados.$$, $$Si el organizador cancela, devolución depende del dinero efectivamente recuperado y de gastos no recuperables ya realizados.$$, array[$$cancelación$$,$$torneo$$]),
($$TC-034$$, $$numero-minimo-para-torneo$$, $$Número mínimo para torneo$$, $$partidos$$, $$tannery_city$$, $$No hay un número universal. Dirección Deportiva lo determina según categoría, formato, competencia y necesidades deportivas.$$, $$No hay un número universal. Dirección Deportiva lo determina según categoría, formato, competencia y necesidades deportivas.$$, array[$$número$$,$$mínimo$$,$$torneo$$]),
($$TC-035$$, $$arbitrajes$$, $$Arbitrajes$$, $$partidos$$, $$tannery_city$$, $$Costo ordinario de referencia: $50 por jugador. Si hay baja participación puede ajustarse, por ejemplo a $70, según costos reales.$$, $$Costo ordinario de referencia: $50 por jugador. Si hay baja participación puede ajustarse, por ejemplo a $70, según costos reales. Paquete: 4 arbitrajes por $200, solo para partidos del torneo regular correspondiente; no incluye amistosos, otros torneos ni competencias adicionales. Un quinto partido puede cobrarse aparte. Normalmente se registran/cobran después del partido. Si un jugador participa y queda saldo pendiente: entrenador reporta → Administración registra → familia liquida.$$, array[$$arbitrajes$$]),
($$TC-036$$, $$participacion-y-minutos$$, $$Participación y minutos$$, $$partidos$$, $$tannery_city$$, $$Pagar torneo, arbitraje o mensualidad no garantiza titularidad, posición ni cantidad específica de minutos.$$, $$Pagar torneo, arbitraje o mensualidad no garantiza titularidad, posición ni cantidad específica de minutos. La intención es que convocados tengan participación. Las decisiones corresponden al Área Deportiva.$$, array[$$participación$$,$$minutos$$]),
($$TC-037$$, $$categorias$$, $$Categorías$$, $$jugadores$$, $$tannery_city$$, $$Un jugador puede ser invitado temporalmente a una categoría superior. No implica ascenso permanente, futuras convocatorias ni minutos garantizados.$$, $$Un jugador puede ser invitado temporalmente a una categoría superior. No implica ascenso permanente, futuras convocatorias ni minutos garantizados. Cambio permanente: Dirección Deportiva.$$, array[$$categorías$$]),
($$TC-038$$, $$otros-clubes$$, $$Otros clubes$$, $$jugadores$$, $$tannery_city$$, $$Un Tanner no debe participar simultáneamente con otra academia o club sin autorización. Sí puede representar a su escuela.$$, $$Un Tanner no debe participar simultáneamente con otra academia o club sin autorización. Sí puede representar a su escuela. Casos especiales con otro club: Dirección Deportiva / Presidencia.$$, array[$$otros$$,$$clubes$$]),
($$TC-039$$, $$convocatorias$$, $$Convocatorias$$, $$partidos$$, $$tannery_city$$, $$Pueden considerar asistencia, disciplina, puntualidad, compromiso, desempeño y necesidades deportivas.$$, $$Pueden considerar asistencia, disciplina, puntualidad, compromiso, desempeño y necesidades deportivas. Familias deben avisar si el jugador no puede asistir.$$, array[$$convocatorias$$]),
($$TC-040$$, $$llegada-a-partidos$$, $$Llegada a partidos$$, $$partidos$$, $$tannery_city$$, $$Jugadores deben presentarse aproximadamente 20 minutos antes. Llegar tarde puede afectar titularidad, minutos o participación según criterio deportivo.$$, $$Jugadores deben presentarse aproximadamente 20 minutos antes. Llegar tarde puede afectar titularidad, minutos o participación según criterio deportivo.$$, array[$$llegada$$,$$partidos$$])
) as v(policy_code, slug, title, category, scope, short_answer, official_content, keywords)
where o.public_key='1850TC1850'
  and not exists (select 1 from app.policies p where p.organization_id=o.id and p.slug=v.slug);
;
